![Hugging Face's logo](https://huggingface.co/front/assets/huggingface_logo-noborder.svg) Hugging Face⟨1⟩
  *  Models ⟨2⟩
  *  Datasets ⟨3⟩
  *  Spaces ⟨4⟩
  *  Buckets new⟨5⟩
  *  Docs ⟨6⟩
  *  Enterprise ⟨7⟩
  * Pricing⟨8⟩
  *     * Website
      *  Tasks⟨9⟩
      *  HuggingChat⟨10⟩
      *  Collections⟨11⟩
      *  Languages⟨12⟩
      *  Organizations⟨13⟩
    * Community
      *  Blog⟨14⟩
      *  Posts⟨15⟩
      *  Daily Papers⟨16⟩
      *  Hardware⟨17⟩
      *  Learn⟨18⟩
      *  Discord⟨19⟩
      *  Forum⟨20⟩
      *  GitHub⟨21⟩
    * Solutions
      *  Team & Enterprise⟨7⟩
      *  Hugging Face PRO⟨22⟩
      *  Enterprise Support⟨23⟩
      *  Inference Providers⟨24⟩
      *  Inference Endpoints⟨25⟩
      *  Storage Buckets⟨5⟩
  * * * *
  * Log In⟨26⟩
  * Sign Up⟨27⟩


#   Datasets:⟨3⟩
* * *
 ![](https://huggingface.co/avatars/a20318492906e6048d345a09a426564b.svg) ⟨28⟩
Jasonstephane⟨28⟩
/
Cube_Top_V2⟨29⟩
like 0
Tasks:  Robotics ⟨30⟩
Modalities:  Tabular ⟨31⟩ Time-series ⟨32⟩ Video ⟨33⟩
Formats:  parquet ⟨34⟩
Size:  1K - 10K ⟨35⟩
Tags:  LeRobot ⟨36⟩
Libraries:  Datasets ⟨37⟩ pandas ⟨38⟩ Polars ⟨39⟩ + 2
License:
apache-2.0
 Dataset card ⟨29⟩ Data Studio ⟨40⟩ Files Files and versions xet ⟨41⟩ Community ⟨42⟩
Dataset Viewer
 Auto-converted to Parquet⟨43⟩ API Embed  Duplicate⟨44⟩ Data Studio
Subset (1)
default · 1.79k rows
default (1.79k rows)
Split (1)
train · 1.79k rows
train (1.79k rows)
Search is not available for this dataset
SQL
Console  
|  action list  |  observation.state list  |  timestamp float32 0 59.6  |  frame_index int64 0 1.79k  |  episode_index int64 0 0  |  index int64 0 1.79k  |  task_index int64 0 0  |  
| --- | --- | --- | --- | --- | --- | --- |  
|  [ -9.478093147277832, -105.29603576660156, 94.62004089355469, 71.4208755493164, 34.78471755981445, 12.699511528015137 ]  |  [ -13.01098918914795, -101.27472686767578, 99.47252655029297, 76.57142639160156, 33.406593322753906, 26.946107864379883 ]  |  0  |  0  |  0  |  0  |  0  |  
|  [ -9.42751407623291, -105.0688705444336, 94.38920593261719, 71.41715240478516, 34.82701873779297, 12.592909812927246 ]  |  [ -13.01098918914795, -101.27472686767578, 99.47252655029297, 76.57142639160156, 33.406593322753906, 26.946107864379883 ]  |  0.033333  |  1  |  0  |  1  |  0  |  
|  [ -7.639105319976807, -103.50381469726562, 96.154541015625, 69.32427215576172, 35.08695602416992, 10.594667434692383 ]  |  [ -12.747252464294434, -101.53845977783203, 99.29669952392578, 76.3956069946289, 33.4945068359375, 26.813039779663086 ]  |  0.066667  |  2  |  0  |  2  |  0  |  
|  [ -8.96743106842041, -104.50028228759766, 94.83446502685547, 70.73133087158203, 35.1318359375, 12.529281616210938 ]  |  [ -11.780220031738281, -102.76923370361328, 98.5934066772461, 75.69230651855469, 33.846153259277344, 25.681968688964844 ]  |  0.1  |  3  |  0  |  3  |  0  |  
|  [ -9.042547225952148, -104.76261901855469, 95.19367980957031, 69.95924377441406, 35.12369918823242, 11.894246101379395 ]  |  [ -10.549450874328613, -103.47252655029297, 98.15384674072266, 74.02198028564453, 34.19780349731445, 23.486360549926758 ]  |  0.133333  |  4  |  0  |  4  |  0  |  
|  [ -9.011909484863281, -104.84247589111328, 94.8193359375, 69.49991607666016, 34.97342300415039, 12.388566970825195 ]  |  [ -9.318681716918945, -103.56044006347656, 98.06593322753906, 72.70330047607422, 34.373626708984375, 20.958084106445312 ]  |  0.166667  |  5  |  0  |  5  |  0  |  
|  [ -8.644789695739746, -105.66035461425781, 95.32704162597656, 69.8536605834961, 34.82200241088867, 11.867902755737305 ]  |  [ -9.230769157409668, -103.56044006347656, 98.06593322753906, 72.0879135131836, 34.46154022216797, 18.36327362060547 ]  |  0.2  |  6  |  0  |  6  |  0  |  
|  [ -7.872145175933838, -101.64105224609375, 95.54286193847656, 67.41903686523438, 35.44871520996094, 10.517276763916016 ]  |  [ -9.494505882263184, -103.73626708984375, 98.06593322753906, 71.56044006347656, 34.46154022216797, 15.901530265808105 ]  |  0.233333  |  7  |  0  |  7  |  0  |  
|  [ -8.02904224395752, -102.60504913330078, 95.02808380126953, 68.46649932861328, 35.484458923339844, 11.112863540649414 ]  |  [ -9.582417488098145, -104.52747344970703, 98.06593322753906, 71.20879364013672, 34.46154022216797, 14.570858001708984 ]  |  0.266667  |  8  |  0  |  8  |  0  |  
|  [ -8.536340713500977, -102.68341827392578, 93.81986999511719, 67.78014373779297, 35.53263854980469, 12.44909954071045 ]  |  [ -9.142857551574707, -104.79120635986328, 98.06593322753906, 70.5934066772461, 34.5494499206543, 13.772455215454102 ]  |  0.3  |  9  |  0  |  9  |  0  |  
|  [ -8.16526985168457, -103.1801528930664, 94.47085571289062, 67.68726348876953, 35.14259719848633, 11.134971618652344 ]  |  [ -8.527472496032715, -104.17582702636719, 98.06593322753906, 69.71428680419922, 34.72527313232422, 12.974051475524902 ]  |  0.333333  |  10  |  0  |  10  |  0  |  
|  [ -7.940916061401367, -100.09929656982422, 93.80174255371094, 66.29374694824219, 35.41748809814453, 11.689032554626465 ]  |  [ -8.263736724853516, -103.56044006347656, 98.06593322753906, 69.36264038085938, 34.901100158691406, 12.77445125579834 ]  |  0.366667  |  11  |  0  |  11  |  0  |  
|  [ -8.216104507446289, -100.26436614990234, 93.02033996582031, 66.29766082763672, 35.39949417114258, 12.244478225708008 ]  |  [ -8.263736724853516, -103.47252655029297, 98.06593322753906, 69.0988998413086, 34.901100158691406, 12.77445125579834 ]  |  0.4  |  12  |  0  |  12  |  0  |  
|  [ -7.482560157775879, -100.31402587890625, 92.95188903808594, 65.95328521728516, 35.098201751708984, 11.680242538452148 ]  |  [ -8.527472496032715, -103.47252655029297, 98.06593322753906, 68.57142639160156, 34.901100158691406, 12.375249862670898 ]  |  0.433333  |  13  |  0  |  13  |  0  |  
|  [ -7.737534046173096, -99.8407211303711, 92.24746704101562, 65.53704833984375, 35.09233093261719, 12.593565940856934 ]  |  [ -8.79120922088623, -102.5054931640625, 97.97801971435547, 68.04395294189453, 34.901100158691406, 12.375249862670898 ]  |  0.466667  |  14  |  0  |  14  |  0  |  
|  [ -8.004790306091309, -100.11763763427734, 91.54241943359375, 65.52240753173828, 34.83380889892578, 13.113520622253418 ]  |  [ -8.615385055541992, -101.45054626464844, 97.71428680419922, 67.6043930053711, 34.901100158691406, 12.242182731628418 ]  |  0.5  |  15  |  0  |  15  |  0  |  
|  [ -8.243513107299805, -97.44664764404297, 89.5099105834961, 64.97554779052734, 34.8923454284668, 13.366124153137207 ]  |  [ -8.263736724853516, -101.18681335449219, 97.36264038085938, 67.25274658203125, 34.901100158691406, 12.242182731628418 ]  |  0.533333  |  16  |  0  |  16  |  0  |  
|  [ -8.293553352355957, -95.67046356201172, 89.52195739746094, 64.73892974853516, 35.3809814453125, 13.220643043518066 ]  |  [ -8, -101.18681335449219, 96.83516693115234, 66.989013671875, 34.901100158691406, 12.3087158203125 ]  |  0.566667  |  17  |  0  |  17  |  0  |  
|  [ -8.161323547363281, -95.00254821777344, 87.69180297851562, 64.26199340820312, 35.006134033203125, 14.382574081420898 ]  |  [ -8, -100.65933990478516, 96.04395294189453, 66.54945373535156, 34.901100158691406, 12.574850082397461 ]  |  0.6  |  18  |  0  |  18  |  0  |  
|  [ -8.788755416870117, -91.67684936523438, 86.00589752197266, 63.58778381347656, 34.71577835083008, 14.601277351379395 ]  |  [ -8.087912559509277, -99.25274658203125, 95.07691955566406, 66.19779968261719, 34.901100158691406, 12.707917213439941 ]  |  0.633333  |  19  |  0  |  19  |  0  |  
|  [ -8.769651412963867, -92.36300659179688, 86.33320617675781, 63.54444885253906, 34.47798538208008, 14.793633460998535 ]  |  [ -8.263736724853516, -97.84615325927734, 94.19779968261719, 65.84615325927734, 34.901100158691406, 13.0405855178833 ]  |  0.666667  |  20  |  0  |  20  |  0  |  
|  [ -9.005334854125977, -91.77653503417969, 85.34461975097656, 63.396759033203125, 34.53122329711914, 15.788101196289062 ]  |  [ -8.439560890197754, -96.26373291015625, 92.87911987304688, 65.31867980957031, 34.901100158691406, 13.50632095336914 ]  |  0.7  |  21  |  0  |  21  |  0  |  
|  [ -9.611136436462402, -86.927734375, 81.32695007324219, 62.571533203125, 34.587982177734375, 16.907119750976562 ]  |  [ -8.527472496032715, -95.56044006347656, 92.0879135131836, 65.05494689941406, 34.901100158691406, 13.905522346496582 ]  |  0.733333  |  22  |  0  |  22  |  0  |  
|  [ -9.693634033203125, -85.87976837158203, 79.44084930419922, 62.161293029785156, 34.10643768310547, 16.84027099609375 ]  |  [ -8.703296661376953, -94.4175796508789, 91.20879364013672, 64.70330047607422, 34.901100158691406, 14.437790870666504 ]  |  0.766667  |  23  |  0  |  23  |  0  |  
|  [ -9.836581230163574, -86.44558715820312, 81.1876220703125, 62.63821792602539, 34.190765380859375, 16.818359375 ]  |  [ -8.879120826721191, -93.0988998413086, 89.97801971435547, 64.35164642333984, 34.901100158691406, 15.169660568237305 ]  |  0.8  |  24  |  0  |  24  |  0  |  
|  [ -10.269793510437012, -81.66175842285156, 77.48117065429688, 62.038978576660156, 34.38639831542969, 17.547758102416992 ]  |  [ -8.967033386230469, -91.34066009521484, 88.21977996826172, 63.912086486816406, 34.901100158691406, 15.635396003723145 ]  |  0.833333  |  25  |  0  |  25  |  0  |  
|  [ -10.975942611694336, -78.87831115722656, 74.79612731933594, 61.79150390625, 34.24228286743164, 18.690528869628906 ]  |  [ -9.142857551574707, -89.5824203491211, 86.63735961914062, 63.736263275146484, 34.901100158691406, 15.968064308166504 ]  |  0.866667  |  26  |  0  |  26  |  0  |  
|  [ -11.136916160583496, -78.99455261230469, 74.7568588256836, 62.12181854248047, 33.996665954589844, 18.631498336791992 ]  |  [ -9.494505882263184, -88, 85.4065933227539, 63.38461685180664, 34.901100158691406, 16.367265701293945 ]  |  0.9  |  27  |  0  |  27  |  0  |  
|  [ -11.665964126586914, -74.51017761230469, 71.82456970214844, 62.10319137573242, 34.03926467895508, 18.669086456298828 ]  |  [ -9.934065818786621, -85.80220031738281, 83.82417297363281, 63.20878982543945, 34.901100158691406, 16.966068267822266 ]  |  0.933333  |  28  |  0  |  28  |  0  |  
|  [ -11.987144470214844, -73.73291015625, 71.37708282470703, 61.582000732421875, 34.55458068847656, 20.17312240600586 ]  |  [ -10.549450874328613, -83.6043930053711, 82.15384674072266, 63.20878982543945, 34.901100158691406, 17.43180274963379 ]  |  0.966667  |  29  |  0  |  29  |  0  |  
|  [ -11.935698509216309, -71.43878173828125, 70.03619384765625, 61.628334045410156, 34.439090728759766, 19.411937713623047 ]  |  [ -11.076923370361328, -81.31867980957031, 80.65933990478516, 63.03296661376953, 34.901100158691406, 17.76447105407715 ]  |  1  |  30  |  0  |  30  |  0  |  
|  [ -12.52990436553955, -69.71041870117188, 69.326171875, 61.41466522216797, 34.59428024291992, 20.689441680908203 ]  |  [ -11.604395866394043, -78.85713958740234, 79.07691955566406, 62.85714340209961, 34.901100158691406, 18.29673957824707 ]  |  1.033333  |  31  |  0  |  31  |  0  |  
|  [ -12.77761173248291, -70.25389099121094, 69.13296508789062, 61.84104537963867, 34.017303466796875, 20.103805541992188 ]  |  [ -11.692307472229004, -76.48351287841797, 77.4945068359375, 62.769229888916016, 34.901100158691406, 18.89554214477539 ]  |  1.066667  |  32  |  0  |  32  |  0  |  
|  [ -13.219104766845703, -64.47843933105469, 65.23039245605469, 61.25669860839844, 34.85767364501953, 20.93497085571289 ]  |  [ -11.692307472229004, -74.37362670898438, 76.17582702636719, 62.593406677246094, 34.901100158691406, 19.361276626586914 ]  |  1.1  |  33  |  0  |  33  |  0  |  
|  [ -13.78997802734375, -63.133880615234375, 64.222412109375, 61.425636291503906, 34.300323486328125, 21.345169067382812 ]  |  [ -11.604395866394043, -72.79120635986328, 75.20879364013672, 62.593406677246094, 34.81318664550781, 19.49434471130371 ]  |  1.133333  |  34  |  0  |  34  |  0  |  
|  [ -13.78519058227539, -63.25554275512695, 63.91082000732422, 61.52845764160156, 34.50209426879883, 21.524986267089844 ]  |  [ -12.131868362426758, -71.82417297363281, 74.24176025390625, 62.593406677246094, 34.81318664550781, 19.693944931030273 ]  |  1.166667  |  35  |  0  |  35  |  0  |  
|  [ -14.83251667022705, -57.42957305908203, 60.97404479980469, 61.36399841308594, 34.681304931640625, 22.545473098754883 ]  |  [ -12.835165023803711, -70.4175796508789, 72.74725341796875, 62.593406677246094, 34.81318664550781, 20.15968132019043 ]  |  1.2  |  36  |  0  |  36  |  0  |  
|  [ -15.061182022094727, -55.8889274597168, 59.15856170654297, 61.70439529418945, 34.332923889160156, 22.636489868164062 ]  |  [ -13.538461685180664, -68.83516693115234, 71.25274658203125, 62.593406677246094, 34.81318664550781, 20.558881759643555 ]  |  1.233333  |  37  |  0  |  37  |  0  |  
|  [ -14.761344909667969, -56.70262145996094, 59.441932678222656, 61.56935119628906, 34.78521728515625, 22.732921600341797 ]  |  [ -13.978021621704102, -66.28571319580078, 69.67032623291016, 62.593406677246094, 34.81318664550781, 21.02461814880371 ]  |  1.266667  |  38  |  0  |  38  |  0  |  
|  [ -15.470211029052734, -53.0496711730957, 56.74568176269531, 61.658172607421875, 34.36785888671875, 23.257801055908203 ]  |  [ -14.329669952392578, -62.5054931640625, 67.82417297363281, 62.593406677246094, 34.81318664550781, 21.556886672973633 ]  |  1.3  |  39  |  0  |  39  |  0  |  
|  [ -15.394386291503906, -51.36273193359375, 56.854530334472656, 61.1722526550293, 35.000328063964844, 23.355764389038086 ]  |  [ -14.417582511901855, -59.9560432434082, 66.32967376708984, 62.593406677246094, 34.81318664550781, 21.823020935058594 ]  |  1.333333  |  40  |  0  |  40  |  0  |  
|  [ -14.972330093383789, -53.79939270019531, 58.227867126464844, 61.764949798583984, 34.8488655090332, 22.857101440429688 ]  |  [ -14.593406677246094, -58.19780349731445, 65.45054626464844, 62.593406677246094, 34.81318664550781, 22.22222137451172 ]  |  1.366667  |  41  |  0  |  41  |  0  |  
|  [ -16.156782150268555, -46.44437789916992, 52.801544189453125, 61.70511245727539, 34.59117126464844, 23.750106811523438 ]  |  [ -14.681318283081055, -56.263736724853516, 64.21977996826172, 62.593406677246094, 34.81318664550781, 22.488357543945312 ]  |  1.4  |  42  |  0  |  42  |  0  |  
|  [ -16.28946304321289, -44.21630096435547, 51.41773986816406, 61.8692626953125, 35.0793571472168, 23.98363494873047 ]  |  [ -14.94505500793457, -54.41758346557617, 63.25274658203125, 62.593406677246094, 34.81318664550781, 22.488357543945312 ]  |  1.433333  |  43  |  0  |  43  |  0  |  
|  [ -16.099164962768555, -42.15027618408203, 51.34088897705078, 61.96089172363281, 35.608802795410156, 24.21784210205078 ]  |  [ -15.032966613769531, -53.27472686767578, 63.07692337036133, 62.593406677246094, 34.81318664550781, 22.754491806030273 ]  |  1.466667  |  44  |  0  |  44  |  0  |  
|  [ -17.16014289855957, -34.781639099121094, 45.71185302734375, 61.65650177001953, 35.8310546875, 25.269315719604492 ]  |  [ -15.296703338623047, -51.516483306884766, 62.373626708984375, 62.593406677246094, 34.81318664550781, 23.087158203125 ]  |  1.5  |  45  |  0  |  45  |  0  |  
|  [ -16.818115234375, -38.79360580444336, 49.15028381347656, 61.62644958496094, 35.98910140991211, 24.34982681274414 ]  |  [ -15.560439109802246, -48.879119873046875, 60.70329666137695, 62.593406677246094, 34.81318664550781, 23.35329246520996 ]  |  1.533333  |  46  |  0  |  46  |  0  |  
|  [ -17.03229522705078, -36.64933395385742, 47.03759002685547, 62.005584716796875, 35.59944152832031, 24.944475173950195 ]  |  [ -15.912087440490723, -45.80219650268555, 58.5054931640625, 62.593406677246094, 34.81318664550781, 23.75249481201172 ]  |  1.566667  |  47  |  0  |  47  |  0  |  
|  [ -17.277435302734375, -35.452938079833984, 46.474769592285156, 62.164703369140625, 35.84186553955078, 25.195838928222656 ]  |  [ -16.263736724853516, -42.46154022216797, 56.0439567565918, 62.593406677246094, 34.81318664550781, 24.151697158813477 ]  |  1.6  |  48  |  0  |  48  |  0  |  
|  [ -17.38939666748047, -31.466672897338867, 43.33732604980469, 62.10210037231445, 35.83786392211914, 24.896652221679688 ]  |  [ -16.791208267211914, -39.56044006347656, 54.021976470947266, 62.593406677246094, 34.81318664550781, 24.28476333618164 ]  |  1.633333  |  49  |  0  |  49  |  0  |  
|  [ -17.368797302246094, -31.194334030151367, 44.150352478027344, 62.256805419921875, 36.14117431640625, 24.827369689941406 ]  |  [ -17.14285659790039, -37.89011001586914, 53.05494689941406, 62.5054931640625, 34.901100158691406, 24.484365463256836 ]  |  1.666667  |  50  |  0  |  50  |  0  |  
|  [ -18.225093841552734, -24.525297164916992, 40.06254577636719, 62.16929626464844, 37.092124938964844, 26.11904525756836 ]  |  [ -17.230770111083984, -36.483516693115234, 52, 62.5054931640625, 34.989009857177734, 24.5508975982666 ]  |  1.7  |  51  |  0  |  51  |  0  |  
|  [ -18.30166244506836, -24.312204360961914, 39.38587951660156, 62.222740173339844, 36.78409957885742, 26.225540161132812 ]  |  [ -17.318681716918945, -34.72527313232422, 50.769229888916016, 62.5054931640625, 35.340660095214844, 24.5508975982666 ]  |  1.733333  |  52  |  0  |  52  |  0  |  
|  [ -18.360136032104492, -19.90204620361328, 37.54949188232422, 62.331478118896484, 37.438751220703125, 26.181987762451172 ]  |  [ -17.318681716918945, -32.61538314819336, 49.4505500793457, 62.5054931640625, 35.69230651855469, 24.750499725341797 ]  |  1.766667  |  53  |  0  |  53  |  0  |  
|  [ -18.37793731689453, -20.87767791748047, 37.46672058105469, 62.14509963989258, 36.95286560058594, 26.46194076538086 ]  |  [ -17.318681716918945, -29.9780216217041, 47.78022003173828, 62.5054931640625, 35.9560432434082, 25.21623420715332 ]  |  1.8  |  54  |  0  |  54  |  0  |  
|  [ -18.581811904907227, -21.35066032409668, 37.64554214477539, 62.38249206542969, 37.114383697509766, 26.219524383544922 ]  |  [ -17.494504928588867, -27.16483497619629, 46.10988998413086, 62.5054931640625, 36.30769348144531, 25.415834426879883 ]  |  1.833333  |  55  |  0  |  55  |  0  |  
|  [ -18.281251907348633, -16.699996948242188, 34.267173767089844, 62.18695831298828, 37.15793991088867, 25.291545867919922 ]  |  [ -17.846153259277344, -24.52747344970703, 44.52747344970703, 62.5054931640625, 36.30769348144531, 25.681968688964844 ]  |  1.866667  |  56  |  0  |  56  |  0  |  
|  [ -18.790687561035156, -15.24559211730957, 33.533042907714844, 62.51256561279297, 37.91160583496094, 26.866825103759766 ]  |  [ -18.285715103149414, -22.681318283081055, 43.736263275146484, 62.5054931640625, 36.30769348144531, 25.748502731323242 ]  |  1.9  |  57  |  0  |  57  |  0  |  
|  [ -18.676593780517578, -11.51824951171875, 32.387752532958984, 62.22843933105469, 38.35557174682617, 26.499847412109375 ]  |  [ -18.549449920654297, -21.626373291015625, 42.85714340209961, 62.5054931640625, 36.30769348144531, 25.681968688964844 ]  |  1.933333  |  58  |  0  |  58  |  0  |  
|  [ -18.606155395507812, -12.928050994873047, 32.30274200439453, 62.60951232910156, 37.75357437133789, 25.962812423706055 ]  |  [ -18.63736343383789, -20.395605087280273, 41.4505500793457, 62.5054931640625, 36.57143020629883, 25.681968688964844 ]  |  1.966667  |  59  |  0  |  59  |  0  |  
|  [ -18.873151779174805, -11.890647888183594, 31.98769760131836, 62.50098419189453, 37.7509651184082, 26.358293533325195 ]  |  [ -18.63736343383789, -18.10988998413086, 39.78022003173828, 62.5054931640625, 37.010990142822266, 25.81503677368164 ]  |  2  |  60  |  0  |  60  |  0  |  
|  [ -18.444721221923828, -11.783102035522461, 31.64026641845703, 62.552818298339844, 38.597320556640625, 25.785541534423828 ]  |  [ -18.63736343383789, -15.472527503967285, 38.46154022216797, 62.5054931640625, 37.098899841308594, 25.81503677368164 ]  |  2.033333  |  61  |  0  |  61  |  0  |  
|  [ -18.48958969116211, -12.179069519042969, 32.298919677734375, 62.68939208984375, 38.854766845703125, 25.87527084350586 ]  |  [ -18.63736343383789, -13.626373291015625, 37.758243560791016, 62.5054931640625, 37.27472686767578, 25.88157081604004 ]  |  2.066667  |  62  |  0  |  62  |  0  |  
|  [ -18.847536087036133, -8.983469009399414, 31.40567398071289, 62.735755920410156, 38.97167205810547, 25.470386505126953 ]  |  [ -18.549449920654297, -12.571428298950195, 37.31867980957031, 62.5054931640625, 37.53845977783203, 25.88157081604004 ]  |  2.1  |  63  |  0  |  63  |  0  |  
|  [ -18.83602523803711, -8.903728485107422, 30.4149169921875, 62.42228317260742, 38.64484405517578, 26.661964416503906 ]  |  [ -18.461538314819336, -12.131868362426758, 37.14285659790039, 62.5054931640625, 37.89011001586914, 25.88157081604004 ]  |  2.133333  |  64  |  0  |  64  |  0  |  
|  [ -18.84581756591797, -7.486137390136719, 28.778331756591797, 62.72969055175781, 39.62351989746094, 25.593955993652344 ]  |  [ -18.373626708984375, -11.516483306884766, 36.70329666137695, 62.5054931640625, 38.153846740722656, 25.88157081604004 ]  |  2.166667  |  65  |  0  |  65  |  0  |  
|  [ -18.637250900268555, -8.006095886230469, 28.845752716064453, 62.638572692871094, 39.326812744140625, 25.920059204101562 ]  |  [ -18.461538314819336, -10.197802543640137, 35.912086486816406, 62.5054931640625, 38.153846740722656, 25.88157081604004 ]  |  2.2  |  66  |  0  |  66  |  0  |  
|  [ -19.016857147216797, -7.003934860229492, 29.17804718017578, 62.65330505371094, 39.69090270996094, 26.128028869628906 ]  |  [ -18.63736343383789, -8.79120922088623, 35.120880126953125, 62.5054931640625, 38.32966995239258, 25.948102951049805 ]  |  2.233333  |  67  |  0  |  67  |  0  |  
|  [ -18.353839874267578, -7.962926864624023, 29.62434196472168, 62.801666259765625, 39.62089538574219, 25.225921630859375 ]  |  [ -18.63736343383789, -8, 34.41758346557617, 62.5054931640625, 38.68132019042969, 25.948102951049805 ]  |  2.266667  |  68  |  0  |  68  |  0  |  
|  [ -18.01609230041504, -6.224590301513672, 27.656723022460938, 62.71275329589844, 40.25373840332031, 24.15420913696289 ]  |  [ -18.63736343383789, -7.648351669311523, 34.153846740722656, 62.5054931640625, 38.85714340209961, 25.948102951049805 ]  |  2.3  |  69  |  0  |  69  |  0  |  
|  [ -18.231182098388672, -5.24116325378418, 27.35483169555664, 62.76760482788086, 40.52376937866211, 24.958322525024414 ]  |  [ -18.63736343383789, -7.208791255950928, 34.06593322753906, 62.5054931640625, 38.94505310058594, 25.948102951049805 ]  |  2.333333  |  70  |  0  |  70  |  0  |  
|  [ -17.967679977416992, -4.69441032409668, 26.846120834350586, 62.55147171020508, 40.328041076660156, 24.483028411865234 ]  |  [ -18.549449920654297, -6.593406677246094, 33.626373291015625, 62.5054931640625, 39.29670333862305, 25.54890251159668 ]  |  2.366667  |  71  |  0  |  71  |  0  |  
|  [ -18.127412796020508, -2.5526199340820312, 25.634450912475586, 62.39582824707031, 41.30609130859375, 24.319133758544922 ]  |  [ -18.285715103149414, -5.714285850524902, 32.92307662963867, 62.5054931640625, 39.47252655029297, 25.415834426879883 ]  |  2.4  |  72  |  0  |  72  |  0  |  
|  [ -18.02835464477539, -2.723194122314453, 26.04054069519043, 62.0954475402832, 41.06544494628906, 24.036455154418945 ]  |  [ -18.19780158996582, -4.835165023803711, 32.131866455078125, 62.5054931640625, 39.64834976196289, 25.349302291870117 ]  |  2.433333  |  73  |  0  |  73  |  0  |  
|  [ -17.76158332824707, -4.217578887939453, 26.486644744873047, 62.381832122802734, 40.743194580078125, 23.810256958007812 ]  |  [ -18.10988998413086, -3.780219793319702, 31.516483306884766, 62.5054931640625, 39.912086486816406, 25.016633987426758 ]  |  2.466667  |  74  |  0  |  74  |  0  |  
|  [ -17.75714683532715, -3.020620346069336, 25.51869010925293, 62.55170440673828, 41.03950119018555, 23.843658447265625 ]  |  [ -18.10988998413086, -2.9010989665985107, 31.076923370361328, 62.5054931640625, 40.17582321166992, 24.6839656829834 ]  |  2.5  |  75  |  0  |  75  |  0  |  
|  [ -17.172870635986328, -3.2205352783203125, 25.519893646240234, 62.669944763183594, 41.675498962402344, 22.840194702148438 ]  |  [ -18.19780158996582, -2.8131868839263916, 30.989011764526367, 62.5054931640625, 40.263736724853516, 24.484365463256836 ]  |  2.533333  |  76  |  0  |  76  |  0  |  
|  [ -16.699710845947266, -2.9738693237304688, 25.21666717529297, 62.84273147583008, 41.76860809326172, 21.923770904541016 ]  |  [ -18.19780158996582, -2.7252748012542725, 30.901098251342773, 62.5054931640625, 40.263736724853516, 24.28476333618164 ]  |  2.566667  |  77  |  0  |  77  |  0  |  
|  [ -16.80767059326172, -2.799854278564453, 25.140594482421875, 62.752140045166016, 41.413291931152344, 21.747949600219727 ]  |  [ -18.285715103149414, -2.461538553237915, 30.72527503967285, 62.5054931640625, 40.35165023803711, 23.885562896728516 ]  |  2.6  |  78  |  0  |  78  |  0  |  
|  [ -16.13658332824707, -2.9834651947021484, 24.645076751708984, 63.078155517578125, 41.766395568847656, 21.469497680664062 ]  |  [ -18.10988998413086, -2.2857143878936768, 30.461538314819336, 62.5054931640625, 40.879119873046875, 23.286760330200195 ]  |  2.633333  |  79  |  0  |  79  |  0  |  
|  [ -15.933910369873047, -2.9663238525390625, 24.05802345275879, 63.32850646972656, 42.07988739013672, 20.586721420288086 ]  |  [ -17.670330047607422, -2.1978023052215576, 30.285715103149414, 62.5054931640625, 40.96703338623047, 22.754491806030273 ]  |  2.666667  |  80  |  0  |  80  |  0  |  
|  [ -15.60969352722168, -3.5846729278564453, 24.002422332763672, 63.50233459472656, 41.894371032714844, 20.046798706054688 ]  |  [ -17.14285659790039, -2.1978023052215576, 29.846153259277344, 62.5054931640625, 41.14285659790039, 22.355289459228516 ]  |  2.7  |  81  |  0  |  81  |  0  |  
|  [ -14.602527618408203, -4.409173965454102, 24.674747467041016, 64.04244995117188, 42.328224182128906, 19.806447982788086 ]  |  [ -16.791208267211914, -2.1098902225494385, 29.406593322753906, 62.5054931640625, 41.31867980957031, 21.889554977416992 ]  |  2.733333  |  82  |  0  |  82  |  0  |  
|  [ -15.594356536865234, -1.0847816467285156, 22.21847915649414, 63.20582580566406, 42.06757736206055, 19.712249755859375 ]  |  [ -16.439559936523438, -2.1098902225494385, 29.05494499206543, 62.5054931640625, 41.31867980957031, 21.290752410888672 ]  |  2.766667  |  83  |  0  |  83  |  0  |  
|  [ -14.74652099609375, -2.4584121704101562, 22.637557983398438, 64.08307647705078, 42.3861083984375, 19.19769287109375 ]  |  [ -16.175825119018555, -2.1098902225494385, 28.879121780395508, 62.769229888916016, 41.31867980957031, 20.825016021728516 ]  |  2.8  |  84  |  0  |  84  |  0  |  
|  [ -14.696173667907715, -1.750509262084961, 22.359352111816406, 63.81990432739258, 42.247215270996094, 19.26598358154297 ]  |  [ -15.912087440490723, -2.0219781398773193, 28.52747344970703, 62.94505310058594, 41.406593322753906, 20.558881759643555 ]  |  2.833333  |  85  |  0  |  85  |  0  |  
|  [ -14.257019996643066, -2.3948593139648438, 23.35088348388672, 63.71564865112305, 42.16064453125, 19.010929107666016 ]  |  [ -15.648351669311523, -1.494505524635315, 27.824174880981445, 63.03296661376953, 41.58241653442383, 20.15968132019043 ]  |  2.866667  |  86  |  0  |  86  |  0  |  
|  [ -13.860841751098633, -4.46009635925293, 23.624530792236328, 64.29276275634766, 42.40518569946289, 17.914581298828125 ]  |  [ -15.472527503967285, -1.2307692766189575, 27.296703338623047, 63.38461685180664, 41.58241653442383, 19.89354705810547 ]  |  2.9  |  87  |  0  |  87  |  0  |  
|  [ -13.972747802734375, -3.038848876953125, 22.689722061157227, 64.22490692138672, 42.58502197265625, 16.9472599029541 ]  |  [ -15.20879077911377, -1.2307692766189575, 27.208791732788086, 63.38461685180664, 41.67033004760742, 19.627412796020508 ]  |  2.933333  |  88  |  0  |  88  |  0  |  
|  [ -13.4229154586792, -3.108797073364258, 22.717512130737305, 64.47089385986328, 42.982688903808594, 18.049070358276367 ]  |  [ -14.94505500793457, -1.2307692766189575, 27.208791732788086, 63.64834976196289, 41.67033004760742, 19.16167640686035 ]  |  2.966667  |  89  |  0  |  89  |  0  |  
|  [ -13.511138916015625, -4.553974151611328, 23.034164428710938, 64.61444091796875, 42.92051696777344, 17.706205368041992 ]  |  [ -14.505494117736816, -1.2307692766189575, 27.208791732788086, 63.82417678833008, 41.67033004760742, 18.429807662963867 ]  |  3  |  90  |  0  |  90  |  0  |  
|  [ -12.880044937133789, -4.22344970703125, 23.036670684814453, 65.39190673828125, 43.118080139160156, 16.63361930847168 ]  |  [ -14.15384578704834, -1.2307692766189575, 27.208791732788086, 64, 41.93406677246094, 18.36327362060547 ]  |  3.033333  |  91  |  0  |  91  |  0  |  
|  [ -12.267854690551758, -7.338642120361328, 24.93421173095703, 65.06350708007812, 42.83951187133789, 16.511898040771484 ]  |  [ -13.89011001586914, -1.2307692766189575, 27.208791732788086, 64.17582702636719, 42.10988998413086, 18.230205535888672 ]  |  3.066667  |  92  |  0  |  92  |  0  |  
|  [ -12.296529769897461, -5.9846343994140625, 23.67212677001953, 65.05001831054688, 42.703407287597656, 17.300899505615234 ]  |  [ -13.714285850524902, -1.2307692766189575, 27.208791732788086, 64.43955993652344, 42.28571319580078, 17.76447105407715 ]  |  3.1  |  93  |  0  |  93  |  0  |  
|  [ -11.847576141357422, -4.872657775878906, 23.570898056030273, 65.73967742919922, 43.07145690917969, 16.102636337280273 ]  |  [ -13.450549125671387, -1.3186813592910767, 27.208791732788086, 64.61538696289062, 42.373626708984375, 17.36526870727539 ]  |  3.133333  |  94  |  0  |  94  |  0  |  
|  [ -11.637090682983398, -3.600343704223633, 21.22979736328125, 65.6029052734375, 43.31121063232422, 16.260883331298828 ]  |  [ -13.186813354492188, -1.4065934419631958, 27.208791732788086, 64.70330047607422, 42.373626708984375, 17.36526870727539 ]  |  3.166667  |  95  |  0  |  95  |  0  |  
|  [ -11.69973373413086, -6.317304611206055, 24.057113647460938, 65.20416259765625, 42.54734420776367, 16.959726333618164 ]  |  [ -12.659340858459473, -1.4065934419631958, 27.208791732788086, 64.87911987304688, 42.373626708984375, 17.232202529907227 ]  |  3.2  |  96  |  0  |  96  |  0  |  
|  [ -11.606691360473633, -6.215803146362305, 23.820358276367188, 65.58934020996094, 43.19108581542969, 15.815810203552246 ]  |  [ -12.395604133605957, -1.4065934419631958, 27.03296661376953, 65.14286041259766, 42.373626708984375, 16.899534225463867 ]  |  3.233333  |  97  |  0  |  97  |  0  |  
|  [ -11.281302452087402, -6.515104293823242, 23.571853637695312, 65.6562728881836, 42.69025421142578, 18.537548065185547 ]  |  [ -12.04395580291748, -1.4065934419631958, 26.505495071411133, 65.14286041259766, 42.373626708984375, 16.899534225463867 ]  |  3.266667  |  98  |  0  |  98  |  0  |  
|  [ -10.998211860656738, -8.032039642333984, 24.847753524780273, 65.96672058105469, 42.607635498046875, 15.813923835754395 ]  |  [ -11.868131637573242, -1.582417607307434, 26.505495071411133, 65.14286041259766, 42.373626708984375, 16.633399963378906 ]  |  3.3  |  99  |  0  |  99  |  0  |  
End of preview. Expand in Data Studio⟨45⟩
* * *
  *  Previous⟨29⟩
  * 1⟨46⟩
  * 2⟨47⟩
  * 3⟨48⟩
  * ...⟨49⟩
  * 18⟨50⟩
  * Next ⟨47⟩


  * Dataset Structure⟨51⟩
  * Citation⟨52⟩


This dataset was created using LeRobot⟨53⟩.
 ![](https://huggingface.co/datasets/huggingface/badges/resolve/main/visualize-this-dataset-xl.svg) ![](https://huggingface.co/datasets/huggingface/badges/resolve/main/visualize-this-dataset-xl-dark.svg) ⟨54⟩
##   ⟨51⟩ Dataset Structure 
meta/info.json⟨55⟩:

```
{
    "codebase_version": "v3.0",
    "fps": 30,
    "features": {
        "action": {
            "dtype": "float32",
            "names": [
                "shoulder_pan.pos",
                "shoulder_lift.pos",
                "elbow_flex.pos",
                "wrist_flex.pos",
                "wrist_roll.pos",
                "gripper.pos"
            ],
            "shape": [
                6
            ]
        },
        "observation.state": {
            "dtype": "float32",
            "names": [
                "shoulder_pan.pos",
                "shoulder_lift.pos",
                "elbow_flex.pos",
                "wrist_flex.pos",
                "wrist_roll.pos",
                "gripper.pos"
            ],
            "shape": [
                6
            ]
        },
        "observation.images.tuy": {
            "dtype": "video",
            "shape": [
                480,
                640,
                3
            ],
            "names": [
                "height",
                "width",
                "channels"
            ],
            "info": {
                "video.height": 480,
                "video.width": 640,
                "video.codec": "av1",
                "video.pix_fmt": "yuv420p",
                "video.is_depth_map": false,
                "video.fps": 30,
                "video.channels": 3,
                "has_audio": false
            }
        },
        "timestamp": {
            "dtype": "float32",
            "shape": [
                1
            ],
            "names": null
        },
        "frame_index": {
            "dtype": "int64",
            "shape": [
                1
            ],
            "names": null
        },
        "episode_index": {
            "dtype": "int64",
            "shape": [
                1
            ],
            "names": null
        },
        "index": {
            "dtype": "int64",
            "shape": [
                1
            ],
            "names": null
        },
        "task_index": {
            "dtype": "int64",
            "shape": [
                1
            ],
            "names": null
        }
    },
    "total_episodes": 1,
    "total_frames": 1789,
    "total_tasks": 1,
    "chunks_size": 1000,
    "data_files_size_in_mb": 100,
    "video_files_size_in_mb": 200,
    "data_path": "data/chunk-{chunk_index:03d}/file-{file_index:03d}.parquet",
    "video_path": "videos/{video_key}/chunk-{chunk_index:03d}/file-{file_index:03d}.mp4",
    "robot_type": "so_follower",
    "splits": {
        "train": "0:1"
    }
}

```

##   ⟨52⟩ Citation 
**BibTeX:**

```
[More Information Needed]

```

Copy to bucket new
Use this dataset 

Downloads last month
    65
License: apache-2.0 Number of rows: 1,789 Total file size: 23.4 MB
##  Collection including Jasonstephane/Cube_Top_V2
#### Cube_top Collection Tested if the camera still works correctly  • 10 items • Updated 19 days ago ⟨56⟩
System theme
Company
TOS⟨57⟩ Privacy⟨58⟩ About⟨59⟩ Careers⟨60⟩ ⟨1⟩
Website
Models⟨2⟩ Datasets⟨3⟩ Spaces⟨4⟩ Pricing⟨8⟩ Docs⟨6⟩
