![Hugging Face's logo](https://huggingface.co/front/assets/huggingface_logo-noborder.svg) Hugging Face⟨1⟩
  *  Models ⟨2⟩
  *  Datasets ⟨3⟩
  *  Spaces ⟨4⟩
  *  Buckets new⟨5⟩
  *  Docs ⟨6⟩
  *  Enterprise ⟨7⟩
  * Pricing⟨8⟩
  *     * Website
      *  Tasks⟨9⟩
      *  HuggingChat⟨10⟩
      *  Collections⟨11⟩
      *  Languages⟨12⟩
      *  Organizations⟨13⟩
    * Community
      *  Blog⟨14⟩
      *  Posts⟨15⟩
      *  Daily Papers⟨16⟩
      *  Hardware⟨17⟩
      *  Learn⟨18⟩
      *  Discord⟨19⟩
      *  Forum⟨20⟩
      *  GitHub⟨21⟩
    * Solutions
      *  Team & Enterprise⟨7⟩
      *  Hugging Face PRO⟨22⟩
      *  Enterprise Support⟨23⟩
      *  Inference Providers⟨24⟩
      *  Inference Endpoints⟨25⟩
      *  Storage Buckets⟨5⟩
  * * * *
  * Log In⟨26⟩
  * Sign Up⟨27⟩


#   Datasets:⟨3⟩
* * *
 ![](https://huggingface.co/avatars/b769e7957fc88d9456b43da3fa018039.svg) ⟨28⟩
asanoQm⟨28⟩
/
so101_xiao_pompom_3⟨29⟩
like 0
Tasks:  Robotics ⟨30⟩
Modalities:  Tabular ⟨31⟩ Time-series ⟨32⟩ Video ⟨33⟩
Formats:  parquet ⟨34⟩
Size:  1K - 10K ⟨35⟩
Tags:  LeRobot ⟨36⟩
Libraries:  Datasets ⟨37⟩ pandas ⟨38⟩ Polars ⟨39⟩ + 2
License:
apache-2.0
 Dataset card ⟨29⟩ Data Studio ⟨40⟩ Files Files and versions xet ⟨41⟩ Community 1 ⟨42⟩
Dataset Viewer
 Auto-converted to Parquet⟨43⟩ API Embed  Duplicate⟨44⟩ Data Studio
Subset (1)
default · 2.17k rows
default (2.17k rows)
Split (1)
train · 2.17k rows
train (2.17k rows)
Search is not available for this dataset
SQL
Console  
|  action list  |  observation.state list  |  timestamp float32 0 24.1  |  frame_index int64 0 724  |  episode_index int64 0 2  |  index int64 0 2.17k  |  task_index int64 0 0  |  
| --- | --- | --- | --- | --- | --- | --- |  
|  [ -2.27606463432312, -60.41322326660156, 100, 3.2863850593566895, 0.5616605877876282, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.7273941040039, 3.217503309249878, 0.7081807255744934, 13.143630981445312 ]  |  0  |  0  |  0  |  0  |  0  |  
|  [ -2.27606463432312, -60.41322326660156, 100, 3.2863850593566895, 0.5616605877876282, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.7273941040039, 3.217503309249878, 0.7081807255744934, 13.143630981445312 ]  |  0.033333  |  1  |  0  |  1  |  0  |  
|  [ -2.27606463432312, -60.41322326660156, 100, 3.2863850593566895, 0.5616605877876282, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.7273941040039, 3.217503309249878, 0.7081807255744934, 13.143630981445312 ]  |  0.066667  |  2  |  0  |  2  |  0  |  
|  [ -2.27606463432312, -60.41322326660156, 100, 3.2863850593566895, 0.5616605877876282, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.81826782226562, 3.217503309249878, 0.7081807255744934, 13.143630981445312 ]  |  0.1  |  3  |  0  |  3  |  0  |  
|  [ -2.27606463432312, -60.41322326660156, 100, 3.2863850593566895, 0.5616605877876282, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.81826782226562, 3.217503309249878, 0.7081807255744934, 13.143630981445312 ]  |  0.133333  |  4  |  0  |  4  |  0  |  
|  [ -2.27606463432312, -60.41322326660156, 100, 3.2863850593566895, 0.5616605877876282, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.81826782226562, 3.217503309249878, 0.7081807255744934, 13.143630981445312 ]  |  0.166667  |  5  |  0  |  5  |  0  |  
|  [ -2.27606463432312, -60.41322326660156, 100, 3.2863850593566895, 0.5616605877876282, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.81826782226562, 3.217503309249878, 0.7081807255744934, 13.143630981445312 ]  |  0.2  |  6  |  0  |  6  |  0  |  
|  [ -2.27606463432312, -60.41322326660156, 100, 3.2863850593566895, 0.5616605877876282, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.81826782226562, 3.217503309249878, 0.7081807255744934, 13.143630981445312 ]  |  0.233333  |  7  |  0  |  7  |  0  |  
|  [ -2.27606463432312, -60.41322326660156, 100, 3.2863850593566895, 0.5616605877876282, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.81826782226562, 3.217503309249878, 0.7081807255744934, 13.143630981445312 ]  |  0.266667  |  8  |  0  |  8  |  0  |  
|  [ -2.27606463432312, -60.41322326660156, 100, 3.2863850593566895, 0.5616605877876282, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.81826782226562, 3.217503309249878, 0.7081807255744934, 13.143630981445312 ]  |  0.3  |  9  |  0  |  9  |  0  |  
|  [ -2.27606463432312, -60.41322326660156, 100, 3.2863850593566895, 0.5616605877876282, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.81826782226562, 3.217503309249878, 0.7081807255744934, 13.143630981445312 ]  |  0.333333  |  10  |  0  |  10  |  0  |  
|  [ -2.27606463432312, -60.41322326660156, 100, 3.2863850593566895, 0.5616605877876282, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.81826782226562, 3.217503309249878, 0.7081807255744934, 13.143630981445312 ]  |  0.366667  |  11  |  0  |  11  |  0  |  
|  [ -2.27606463432312, -60.41322326660156, 100, 3.2863850593566895, 0.5616605877876282, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.81826782226562, 3.217503309249878, 0.7081807255744934, 13.143630981445312 ]  |  0.4  |  12  |  0  |  12  |  0  |  
|  [ -2.27606463432312, -60.41322326660156, 100, 3.2863850593566895, 0.5616605877876282, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.81826782226562, 3.217503309249878, 0.7081807255744934, 13.143630981445312 ]  |  0.433333  |  13  |  0  |  13  |  0  |  
|  [ -2.27606463432312, -60.41322326660156, 100, 3.2863850593566895, 0.5616605877876282, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.81826782226562, 3.217503309249878, 0.7081807255744934, 13.143630981445312 ]  |  0.466667  |  14  |  0  |  14  |  0  |  
|  [ -2.27606463432312, -60.41322326660156, 100, 3.2863850593566895, 0.5616605877876282, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.81826782226562, 3.217503309249878, 0.7081807255744934, 13.143630981445312 ]  |  0.5  |  15  |  0  |  15  |  0  |  
|  [ -2.27606463432312, -60.41322326660156, 100, 3.2863850593566895, 0.5616605877876282, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.81826782226562, 3.217503309249878, 0.7081807255744934, 13.143630981445312 ]  |  0.533333  |  16  |  0  |  16  |  0  |  
|  [ -2.27606463432312, -60.41322326660156, 100, 3.2863850593566895, 0.5616605877876282, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.81826782226562, 3.217503309249878, 0.7081807255744934, 13.143630981445312 ]  |  0.566667  |  17  |  0  |  17  |  0  |  
|  [ -2.27606463432312, -60.41322326660156, 100, 3.2863850593566895, 0.5616605877876282, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.81826782226562, 3.217503309249878, 0.7081807255744934, 13.143630981445312 ]  |  0.6  |  18  |  0  |  18  |  0  |  
|  [ -2.27606463432312, -60.41322326660156, 100, 3.2863850593566895, 0.5616605877876282, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.81826782226562, 3.217503309249878, 0.7081807255744934, 13.143630981445312 ]  |  0.633333  |  19  |  0  |  19  |  0  |  
|  [ -2.27606463432312, -60.41322326660156, 100, 3.2863850593566895, 0.5616605877876282, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.81826782226562, 3.217503309249878, 0.7081807255744934, 13.143630981445312 ]  |  0.666667  |  20  |  0  |  20  |  0  |  
|  [ -2.27606463432312, -60.41322326660156, 100, 3.2863850593566895, 0.5616605877876282, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.81826782226562, 3.217503309249878, 0.7081807255744934, 13.143630981445312 ]  |  0.7  |  21  |  0  |  21  |  0  |  
|  [ -2.27606463432312, -60.41322326660156, 100, 3.2863850593566895, 0.5616605877876282, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.81826782226562, 3.217503309249878, 0.7081807255744934, 13.143630981445312 ]  |  0.733333  |  22  |  0  |  22  |  0  |  
|  [ -2.27606463432312, -60.41322326660156, 100, 3.2863850593566895, 0.5616605877876282, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.81826782226562, 3.217503309249878, 0.7081807255744934, 13.143630981445312 ]  |  0.766667  |  23  |  0  |  23  |  0  |  
|  [ -2.27606463432312, -60.41322326660156, 100, 3.2863850593566895, 0.5616605877876282, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.81826782226562, 3.217503309249878, 0.7081807255744934, 13.143630981445312 ]  |  0.8  |  24  |  0  |  24  |  0  |  
|  [ -2.27606463432312, -60.41322326660156, 100, 3.2863850593566895, 0.5616605877876282, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.81826782226562, 3.217503309249878, 0.7081807255744934, 13.143630981445312 ]  |  0.833333  |  25  |  0  |  25  |  0  |  
|  [ -2.27606463432312, -60.41322326660156, 100, 3.2863850593566895, 0.5616605877876282, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.81826782226562, 3.217503309249878, 0.7081807255744934, 13.143630981445312 ]  |  0.866667  |  26  |  0  |  26  |  0  |  
|  [ -2.27606463432312, -60.41322326660156, 100, 3.2863850593566895, 0.5616605877876282, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.81826782226562, 3.217503309249878, 0.7081807255744934, 13.143630981445312 ]  |  0.9  |  27  |  0  |  27  |  0  |  
|  [ -2.27606463432312, -60.41322326660156, 100, 3.2863850593566895, 0.5616605877876282, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.81826782226562, 3.217503309249878, 0.7081807255744934, 13.143630981445312 ]  |  0.933333  |  28  |  0  |  28  |  0  |  
|  [ -2.27606463432312, -60.41322326660156, 100, 3.2863850593566895, 0.5616605877876282, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.81826782226562, 3.217503309249878, 0.7081807255744934, 13.143630981445312 ]  |  0.966667  |  29  |  0  |  29  |  0  |  
|  [ -2.27606463432312, -60.41322326660156, 100, 3.2863850593566895, 0.5616605877876282, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.81826782226562, 3.217503309249878, 0.7081807255744934, 13.143630981445312 ]  |  1  |  30  |  0  |  30  |  0  |  
|  [ -2.27606463432312, -60.41322326660156, 100, 3.2863850593566895, 0.5616605877876282, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.81826782226562, 3.217503309249878, 0.7081807255744934, 13.143630981445312 ]  |  1.033333  |  31  |  0  |  31  |  0  |  
|  [ -2.27606463432312, -60.41322326660156, 100, 3.2863850593566895, 0.5616605877876282, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.81826782226562, 3.217503309249878, 0.7081807255744934, 13.143630981445312 ]  |  1.066667  |  32  |  0  |  32  |  0  |  
|  [ -2.27606463432312, -60.41322326660156, 100, 3.2863850593566895, 0.5616605877876282, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.81826782226562, 3.217503309249878, 0.7081807255744934, 13.143630981445312 ]  |  1.1  |  33  |  0  |  33  |  0  |  
|  [ -2.27606463432312, -60.41322326660156, 100, 3.2863850593566895, 0.5616605877876282, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.81826782226562, 3.217503309249878, 0.7081807255744934, 13.143630981445312 ]  |  1.133333  |  34  |  0  |  34  |  0  |  
|  [ -2.27606463432312, -60.41322326660156, 100, 3.2863850593566895, 0.5616605877876282, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.81826782226562, 3.217503309249878, 0.7081807255744934, 13.143630981445312 ]  |  1.166667  |  35  |  0  |  35  |  0  |  
|  [ -2.27606463432312, -60.41322326660156, 100, 3.2863850593566895, 0.5616605877876282, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.81826782226562, 3.217503309249878, 0.7081807255744934, 13.143630981445312 ]  |  1.2  |  36  |  0  |  36  |  0  |  
|  [ -2.27606463432312, -60.41322326660156, 100, 3.2863850593566895, 0.5616605877876282, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.81826782226562, 3.217503309249878, 0.7081807255744934, 13.143630981445312 ]  |  1.233333  |  37  |  0  |  37  |  0  |  
|  [ -2.27606463432312, -60.41322326660156, 100, 3.2863850593566895, 0.5616605877876282, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.81826782226562, 3.217503309249878, 0.7081807255744934, 13.143630981445312 ]  |  1.266667  |  38  |  0  |  38  |  0  |  
|  [ -2.27606463432312, -60.41322326660156, 100, 3.2863850593566895, 0.5616605877876282, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.81826782226562, 3.217503309249878, 0.7081807255744934, 13.143630981445312 ]  |  1.3  |  39  |  0  |  39  |  0  |  
|  [ -2.27606463432312, -60.41322326660156, 100, 3.2863850593566895, 0.5616605877876282, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.81826782226562, 3.217503309249878, 0.7081807255744934, 13.143630981445312 ]  |  1.333333  |  40  |  0  |  40  |  0  |  
|  [ -2.27606463432312, -60.41322326660156, 100, 3.2863850593566895, 0.5616605877876282, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.81826782226562, 3.217503309249878, 0.7081807255744934, 13.143630981445312 ]  |  1.366667  |  41  |  0  |  41  |  0  |  
|  [ -2.27606463432312, -60.41322326660156, 100, 3.2863850593566895, 0.5616605877876282, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.81826782226562, 3.217503309249878, 0.7081807255744934, 13.143630981445312 ]  |  1.4  |  42  |  0  |  42  |  0  |  
|  [ -2.27606463432312, -60.41322326660156, 100, 3.2863850593566895, 0.5616605877876282, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.81826782226562, 3.217503309249878, 0.7081807255744934, 13.143630981445312 ]  |  1.433333  |  43  |  0  |  43  |  0  |  
|  [ -2.27606463432312, -60.41322326660156, 100, 3.2863850593566895, 0.5616605877876282, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.81826782226562, 3.217503309249878, 0.7081807255744934, 13.143630981445312 ]  |  1.466667  |  44  |  0  |  44  |  0  |  
|  [ -2.27606463432312, -60.41322326660156, 100, 3.2863850593566895, 0.5616605877876282, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.81826782226562, 3.217503309249878, 0.7081807255744934, 13.143630981445312 ]  |  1.5  |  45  |  0  |  45  |  0  |  
|  [ -2.27606463432312, -60.41322326660156, 100, 3.2863850593566895, 0.5616605877876282, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.81826782226562, 3.217503309249878, 0.7081807255744934, 13.143630981445312 ]  |  1.533333  |  46  |  0  |  46  |  0  |  
|  [ -2.27606463432312, -60.41322326660156, 100, 3.2863850593566895, 0.5616605877876282, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.81826782226562, 3.217503309249878, 0.7081807255744934, 13.143630981445312 ]  |  1.566667  |  47  |  0  |  47  |  0  |  
|  [ -2.27606463432312, -60.41322326660156, 100, 3.2863850593566895, 0.5616605877876282, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.81826782226562, 3.217503309249878, 0.7081807255744934, 13.143630981445312 ]  |  1.6  |  48  |  0  |  48  |  0  |  
|  [ -2.27606463432312, -60.41322326660156, 100, 3.2863850593566895, 0.5616605877876282, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.81826782226562, 3.217503309249878, 0.7081807255744934, 13.143630981445312 ]  |  1.633333  |  49  |  0  |  49  |  0  |  
|  [ -2.27606463432312, -60.41322326660156, 100, 3.2863850593566895, 0.5616605877876282, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.81826782226562, 3.217503309249878, 0.7081807255744934, 13.143630981445312 ]  |  1.666667  |  50  |  0  |  50  |  0  |  
|  [ -2.27606463432312, -60.41322326660156, 100, 3.2863850593566895, 0.5616605877876282, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.81826782226562, 3.217503309249878, 0.7081807255744934, 13.143630981445312 ]  |  1.7  |  51  |  0  |  51  |  0  |  
|  [ -2.27606463432312, -60.41322326660156, 100, 3.2863850593566895, 0.5616605877876282, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.81826782226562, 3.217503309249878, 0.7081807255744934, 13.143630981445312 ]  |  1.733333  |  52  |  0  |  52  |  0  |  
|  [ -2.27606463432312, -60.41322326660156, 100, 3.2863850593566895, 0.5616605877876282, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.81826782226562, 3.217503309249878, 0.7081807255744934, 13.143630981445312 ]  |  1.766667  |  53  |  0  |  53  |  0  |  
|  [ -2.27606463432312, -60.41322326660156, 100, 3.2863850593566895, 0.5616605877876282, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.81826782226562, 3.217503309249878, 0.7081807255744934, 13.143630981445312 ]  |  1.8  |  54  |  0  |  54  |  0  |  
|  [ -2.27606463432312, -60.41322326660156, 100, 3.2863850593566895, 0.5616605877876282, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.81826782226562, 3.217503309249878, 0.7081807255744934, 13.143630981445312 ]  |  1.833333  |  55  |  0  |  55  |  0  |  
|  [ -2.27606463432312, -60.41322326660156, 100, 3.2863850593566895, 0.5616605877876282, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.81826782226562, 3.217503309249878, 0.7081807255744934, 13.143630981445312 ]  |  1.866667  |  56  |  0  |  56  |  0  |  
|  [ -2.27606463432312, -60.41322326660156, 100, 3.2863850593566895, 0.5616605877876282, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.81826782226562, 3.217503309249878, 0.7081807255744934, 13.143630981445312 ]  |  1.9  |  57  |  0  |  57  |  0  |  
|  [ -2.27606463432312, -60.41322326660156, 100, 3.2863850593566895, 0.5616605877876282, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.81826782226562, 3.217503309249878, 0.7081807255744934, 13.143630981445312 ]  |  1.933333  |  58  |  0  |  58  |  0  |  
|  [ -2.27606463432312, -60.41322326660156, 100, 3.2863850593566895, 0.5616605877876282, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.81826782226562, 3.217503309249878, 0.7081807255744934, 13.143630981445312 ]  |  1.966667  |  59  |  0  |  59  |  0  |  
|  [ -2.27606463432312, -60.41322326660156, 100, 3.2863850593566895, 0.5616605877876282, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.81826782226562, 3.217503309249878, 0.7081807255744934, 13.143630981445312 ]  |  2  |  60  |  0  |  60  |  0  |  
|  [ -2.27606463432312, -60.41322326660156, 100, 3.2863850593566895, 0.5616605877876282, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.81826782226562, 3.217503309249878, 0.7081807255744934, 13.143630981445312 ]  |  2.033333  |  61  |  0  |  61  |  0  |  
|  [ -2.27606463432312, -60.41322326660156, 100, 3.2863850593566895, 0.5616605877876282, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.81826782226562, 3.217503309249878, 0.7081807255744934, 13.143630981445312 ]  |  2.066667  |  62  |  0  |  62  |  0  |  
|  [ -2.27606463432312, -60.41322326660156, 100, 3.2863850593566895, 0.5616605877876282, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.81826782226562, 3.217503309249878, 0.7081807255744934, 13.143630981445312 ]  |  2.1  |  63  |  0  |  63  |  0  |  
|  [ -2.27606463432312, -60.41322326660156, 100, 3.2863850593566895, 0.5616605877876282, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.81826782226562, 3.217503309249878, 0.7081807255744934, 13.143630981445312 ]  |  2.133333  |  64  |  0  |  64  |  0  |  
|  [ -2.2026431560516357, -60.41322326660156, 100, 3.2863850593566895, 0.9035409092903137, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.81826782226562, 3.217503309249878, 0.7081807255744934, 13.143630981445312 ]  |  2.166667  |  65  |  0  |  65  |  0  |  
|  [ -2.1292216777801514, -60.41322326660156, 100, 3.201024293899536, 0.9523809552192688, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.81826782226562, 3.217503309249878, 0.7081807255744934, 13.143630981445312 ]  |  2.2  |  66  |  0  |  66  |  0  |  
|  [ -2.1292216777801514, -60.41322326660156, 100, 3.201024293899536, 0.9035409092903137, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.81826782226562, 3.217503309249878, 0.7081807255744934, 13.143630981445312 ]  |  2.233333  |  67  |  0  |  67  |  0  |  
|  [ -2.1292216777801514, -60.41322326660156, 100, 3.115663766860962, 0.7570207715034485, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.81826782226562, 3.217503309249878, 0.7081807255744934, 13.143630981445312 ]  |  2.266667  |  68  |  0  |  68  |  0  |  
|  [ -2.1292216777801514, -60.578514099121094, 99.36160278320312, 2.6888604164123535, 0.6593406796455383, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.81826782226562, 3.217503309249878, 0.7081807255744934, 13.143630981445312 ]  |  2.3  |  69  |  0  |  69  |  0  |  
|  [ -2.422907590866089, -60.578514099121094, 98.17601776123047, 0.5548442006111145, 0.5616605877876282, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.81826782226562, 3.217503309249878, 0.7081807255744934, 13.143630981445312 ]  |  2.333333  |  70  |  0  |  70  |  0  |  
|  [ -2.7900147438049316, -60.49586868286133, 96.71682739257812, -2.4327785968780518, 0.5616605877876282, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.81826782226562, 3.217503309249878, 0.7081807255744934, 13.143630981445312 ]  |  2.366667  |  71  |  0  |  71  |  0  |  
|  [ -2.7900147438049316, -60.49586868286133, 95.44003295898438, -5.761843681335449, 0.5616605877876282, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.63652801513672, 2.9601030349731445, 0.7081807255744934, 13.143630981445312 ]  |  2.4  |  72  |  0  |  72  |  0  |  
|  [ -2.7900147438049316, -60.49586868286133, 94.71044158935547, -9.005548477172852, 0.5616605877876282, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.54566192626953, 1.844701886177063, 0.7081807255744934, 13.143630981445312 ]  |  2.433333  |  73  |  0  |  73  |  0  |  
|  [ -2.7900147438049316, -60.49586868286133, 94.52804565429688, -12.249253273010254, 0.5616605877876282, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.45479583740234, 0.04290004447102547, 0.7081807255744934, 13.143630981445312 ]  |  2.466667  |  74  |  0  |  74  |  0  |  
|  [ -2.863436222076416, -60.49586868286133, 94.6192398071289, -15.919760704040527, 0.5616605877876282, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.27305603027344, -2.273702383041382, 0.7081807255744934, 13.143630981445312 ]  |  2.5  |  75  |  0  |  75  |  0  |  
|  [ -2.863436222076416, -60.49586868286133, 94.98403930664062, -19.590269088745117, 0.5616605877876282, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.18218994140625, -5.019305229187012, 0.7081807255744934, 13.143630981445312 ]  |  2.533333  |  76  |  0  |  76  |  0  |  
|  [ -2.863436222076416, -60.49586868286133, 95.34883880615234, -22.492530822753906, 0.5616605877876282, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.18218994140625, -7.7649078369140625, 0.7081807255744934, 13.143630981445312 ]  |  2.566667  |  77  |  0  |  77  |  0  |  
|  [ -2.863436222076416, -60.49586868286133, 96.07843017578125, -25.394792556762695, 0.5616605877876282, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.18218994140625, -10.9395112991333, 0.7081807255744934, 13.143630981445312 ]  |  2.6  |  78  |  0  |  78  |  0  |  
|  [ -2.863436222076416, -60.49586868286133, 97.08162689208984, -28.040973663330078, 0.5616605877876282, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.18218994140625, -14.028313636779785, 0.7081807255744934, 13.143630981445312 ]  |  2.633333  |  79  |  0  |  79  |  0  |  
|  [ -2.863436222076416, -60.49586868286133, 97.99361419677734, -30.004268646240234, 0.5616605877876282, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.18218994140625, -17.03131675720215, 0.7081807255744934, 13.143630981445312 ]  |  2.666667  |  80  |  0  |  80  |  0  |  
|  [ -2.863436222076416, -60.49586868286133, 99.08800506591797, -31.96756362915039, 0.5616605877876282, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.18218994140625, -20.034320831298828, 0.7081807255744934, 13.143630981445312 ]  |  2.7  |  81  |  0  |  81  |  0  |  
|  [ -2.863436222076416, -60.49586868286133, 100, -33.41869354248047, 0.5616605877876282, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.18218994140625, -22.779922485351562, 0.7081807255744934, 13.143630981445312 ]  |  2.733333  |  82  |  0  |  82  |  0  |  
|  [ -2.863436222076416, -60.49586868286133, 100, -34.01622009277344, 0.5616605877876282, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.54566192626953, -25.353925704956055, 0.7081807255744934, 13.143630981445312 ]  |  2.766667  |  83  |  0  |  83  |  0  |  
|  [ -2.863436222076416, -60.41322326660156, 100, -34.10157775878906, 0.5616605877876282, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.7273941040039, -27.584728240966797, 0.7081807255744934, 13.143630981445312 ]  |  2.8  |  84  |  0  |  84  |  0  |  
|  [ -2.863436222076416, -60.41322326660156, 100, -33.50405502319336, 0.6105006337165833, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.7273941040039, -29.300729751586914, 0.7081807255744934, 13.143630981445312 ]  |  2.833333  |  85  |  0  |  85  |  0  |  
|  [ -2.863436222076416, -60.41322326660156, 100, -32.650447845458984, 0.6105006337165833, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.81826782226562, -30.33032989501953, 0.7081807255744934, 13.143630981445312 ]  |  2.866667  |  86  |  0  |  86  |  0  |  
|  [ -2.863436222076416, -60.41322326660156, 100, -31.62611961364746, 0.6105006337165833, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.81826782226562, -30.930931091308594, 0.7081807255744934, 13.143630981445312 ]  |  2.9  |  87  |  0  |  87  |  0  |  
|  [ -2.863436222076416, -60.41322326660156, 100, -30.43107032775879, 0.6105006337165833, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.81826782226562, -31.10253143310547, 0.7081807255744934, 13.143630981445312 ]  |  2.933333  |  88  |  0  |  88  |  0  |  
|  [ -2.863436222076416, -60.41322326660156, 100, -28.97994041442871, 0.6105006337165833, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.81826782226562, -31.01673126220703, 0.7081807255744934, 13.143630981445312 ]  |  2.966667  |  89  |  0  |  89  |  0  |  
|  [ -2.863436222076416, -60.41322326660156, 100, -27.35808753967285, 0.6105006337165833, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.81826782226562, -30.587730407714844, 0.7081807255744934, 13.143630981445312 ]  |  3  |  90  |  0  |  90  |  0  |  
|  [ -2.863436222076416, -60.41322326660156, 100, -25.821596145629883, 0.6105006337165833, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.81826782226562, -29.815528869628906, 0.7081807255744934, 13.143630981445312 ]  |  3.033333  |  91  |  0  |  91  |  0  |  
|  [ -2.863436222076416, -60.41322326660156, 100, -24.199743270874023, 0.6105006337165833, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.81826782226562, -28.70012855529785, 0.7081807255744934, 13.143630981445312 ]  |  3.066667  |  92  |  0  |  92  |  0  |  
|  [ -2.863436222076416, -60.41322326660156, 100, -22.236448287963867, 0.6105006337165833, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.81826782226562, -27.584728240966797, 0.7081807255744934, 13.143630981445312 ]  |  3.1  |  93  |  0  |  93  |  0  |  
|  [ -2.863436222076416, -60.41322326660156, 100, -20.3585147857666, 0.6105006337165833, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.81826782226562, -26.297725677490234, 0.7081807255744934, 13.143630981445312 ]  |  3.133333  |  94  |  0  |  94  |  0  |  
|  [ -2.863436222076416, -60.41322326660156, 100, -18.224498748779297, 0.6105006337165833, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.81826782226562, -24.753324508666992, 0.7081807255744934, 13.143630981445312 ]  |  3.166667  |  95  |  0  |  95  |  0  |  
|  [ -2.863436222076416, -60.41322326660156, 100, -16.17584228515625, 0.5616605877876282, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.81826782226562, -23.123123168945312, 0.7081807255744934, 13.143630981445312 ]  |  3.2  |  96  |  0  |  96  |  0  |  
|  [ -2.863436222076416, -60.41322326660156, 100, -14.639350891113281, 0.5616605877876282, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.81826782226562, -21.321321487426758, 0.7081807255744934, 13.143630981445312 ]  |  3.233333  |  97  |  0  |  97  |  0  |  
|  [ -2.863436222076416, -60.41322326660156, 100, -13.785744667053223, 0.5616605877876282, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.81826782226562, -19.519519805908203, 0.7081807255744934, 13.143630981445312 ]  |  3.266667  |  98  |  0  |  98  |  0  |  
|  [ -2.863436222076416, -60.41322326660156, 100, -13.358941078186035, 0.5616605877876282, 12.967382431030273 ]  |  [ -2.4551117420196533, -59.46059799194336, 99.81826782226562, -17.63191795349121, 0.7081807255744934, 13.143630981445312 ]  |  3.3  |  99  |  0  |  99  |  0  |  
End of preview. Expand in Data Studio⟨45⟩
* * *
  *  Previous⟨29⟩
  * 1⟨46⟩
  * 2⟨47⟩
  * 3⟨48⟩
  * ...⟨49⟩
  * 22⟨50⟩
  * Next ⟨47⟩


  * Dataset Structure⟨51⟩
  * Citation⟨52⟩


This dataset was created using LeRobot⟨53⟩.
##   ⟨51⟩ Dataset Structure 
meta/info.json⟨54⟩:

```
{
    "codebase_version": "v3.0",
    "robot_type": "so_follower",
    "total_episodes": 3,
    "total_frames": 2173,
    "total_tasks": 1,
    "chunks_size": 1000,
    "data_files_size_in_mb": 100,
    "video_files_size_in_mb": 200,
    "fps": 30,
    "splits": {
        "train": "0:3"
    },
    "data_path": "data/chunk-{chunk_index:03d}/file-{file_index:03d}.parquet",
    "video_path": "videos/{video_key}/chunk-{chunk_index:03d}/file-{file_index:03d}.mp4",
    "features": {
        "action": {
            "dtype": "float32",
            "names": [
                "shoulder_pan.pos",
                "shoulder_lift.pos",
                "elbow_flex.pos",
                "wrist_flex.pos",
                "wrist_roll.pos",
                "gripper.pos"
            ],
            "shape": [
                6
            ]
        },
        "observation.state": {
            "dtype": "float32",
            "names": [
                "shoulder_pan.pos",
                "shoulder_lift.pos",
                "elbow_flex.pos",
                "wrist_flex.pos",
                "wrist_roll.pos",
                "gripper.pos"
            ],
            "shape": [
                6
            ]
        },
        "observation.images.front": {
            "dtype": "video",
            "shape": [
                480,
                640,
                3
            ],
            "names": [
                "height",
                "width",
                "channels"
            ],
            "info": {
                "video.height": 480,
                "video.width": 640,
                "video.codec": "av1",
                "video.pix_fmt": "yuv420p",
                "video.is_depth_map": false,
                "video.fps": 30,
                "video.channels": 3,
                "has_audio": false
            }
        },
        "timestamp": {
            "dtype": "float32",
            "shape": [
                1
            ],
            "names": null
        },
        "frame_index": {
            "dtype": "int64",
            "shape": [
                1
            ],
            "names": null
        },
        "episode_index": {
            "dtype": "int64",
            "shape": [
                1
            ],
            "names": null
        },
        "index": {
            "dtype": "int64",
            "shape": [
                1
            ],
            "names": null
        },
        "task_index": {
            "dtype": "int64",
            "shape": [
                1
            ],
            "names": null
        }
    }
}

```

##   ⟨52⟩ Citation 
**BibTeX:**

```
[More Information Needed]

```

Copy to bucket new
Use this dataset 

Downloads last month
    64
License: apache-2.0 Number of rows: 2,173 Total file size: 2.27 MB
##  Models trained or fine-tuned on asanoQm/so101_xiao_pompom_3
 ![](https://huggingface.co/avatars/b769e7957fc88d9456b43da3fa018039.svg) asanoQm/act_so101_xiao_pompom_3 Robotics • 51.7M • Updated 16 days ago • 38 ⟨55⟩
System theme
Company
TOS⟨56⟩ Privacy⟨57⟩ About⟨58⟩ Careers⟨59⟩ ⟨1⟩
Website
Models⟨2⟩ Datasets⟨3⟩ Spaces⟨4⟩ Pricing⟨8⟩ Docs⟨6⟩
