![Hugging Face's logo](https://huggingface.co/front/assets/huggingface_logo-noborder.svg) Hugging Face⟨1⟩
  *  Models ⟨2⟩
  *  Datasets ⟨3⟩
  *  Spaces ⟨4⟩
  *  Buckets new⟨5⟩
  *  Docs ⟨6⟩
  *  Enterprise ⟨7⟩
  * Pricing⟨8⟩
  *     * Website
      *  Tasks⟨9⟩
      *  HuggingChat⟨10⟩
      *  Collections⟨11⟩
      *  Languages⟨12⟩
      *  Organizations⟨13⟩
    * Community
      *  Blog⟨14⟩
      *  Posts⟨15⟩
      *  Daily Papers⟨16⟩
      *  Hardware⟨17⟩
      *  Learn⟨18⟩
      *  Discord⟨19⟩
      *  Forum⟨20⟩
      *  GitHub⟨21⟩
    * Solutions
      *  Team & Enterprise⟨7⟩
      *  Hugging Face PRO⟨22⟩
      *  Enterprise Support⟨23⟩
      *  Inference Providers⟨24⟩
      *  Inference Endpoints⟨25⟩
      *  Storage Buckets⟨5⟩
  * * * *
  * Log In⟨26⟩
  * Sign Up⟨27⟩


#   Datasets:⟨3⟩
* * *
 ![](https://cdn-avatars.huggingface.co/v1/production/uploads/65bc98383b879593a5a2f5e5/p2ZtoTFN6tW-QkcPJf7YT.jpeg) ⟨28⟩
KangLiao⟨28⟩
/
TartanAir-Absolute-Camera⟨29⟩
like 0
Tasks:  Text-to-3D ⟨30⟩ Image-to-3D ⟨31⟩ Image-Text-to-Image ⟨32⟩ + 1
ArXiv:
arxiv: 2510.08673
Tags:  Camera ⟨33⟩ 3D Vision ⟨34⟩ Spatial AI ⟨35⟩ Physical AI ⟨36⟩ World Model ⟨37⟩ Camera Parameter ⟨38⟩ + 2
 Dataset card ⟨29⟩ Data Studio ⟨39⟩ Files Files and versions xet ⟨40⟩ Community ⟨41⟩
Dataset Preview
API Embed  Duplicate⟨42⟩ Data Studio
Subset (1)
default
default
Split (1)
train
train
The full dataset viewer is not available (click to read why). Only showing a preview of the rows.
Job manager crashed while running this job (missing heartbeats).

```
Error code:   JobManagerCrashedError

```

Need help to make the dataset viewer work? Make sure to review how to configure the dataset viewer⟨43⟩, and open a discussion⟨44⟩ for direct support.  
|  roll float64  |  pitch float64  |  vfov float64  |  k1 float64  |  parse_ok bool  |  
| --- | --- | --- | --- | --- |  
|  0.0046  |  -0.0044  |  0.8664  |  0  |  true  |  
|  0.0044  |  -0.0344  |  0.9846  |  0  |  true  |  
|  0.0104  |  -0.0756  |  1.104  |  0  |  true  |  
|  0.0144  |  -0.1044  |  1.1046  |  0  |  true  |  
|  0.0144  |  -0.1504  |  1.1666  |  0  |  true  |  
|  0.0144  |  -0.1766  |  1.3064  |  0  |  true  |  
|  0.0044  |  -0.2366  |  1.256  |  0  |  true  |  
|  0.0084  |  -0.2804  |  1.2666  |  0  |  true  |  
|  0.0064  |  -0.3044  |  1.2964  |  0  |  true  |  
|  0.0044  |  -0.3604  |  1.2766  |  0  |  true  |  
|  0.0004  |  -0.3904  |  1.288  |  0  |  true  |  
|  -0.0074  |  -0.4244  |  1.286  |  0  |  true  |  
|  -0.0164  |  -0.4546  |  1.276  |  0  |  true  |  
|  -0.0244  |  -0.5044  |  1.2684  |  0  |  true  |  
|  -0.0346  |  -0.5264  |  1.2784  |  0  |  true  |  
|  -0.0448  |  -0.5564  |  1.2764  |  0  |  true  |  
|  -0.0548  |  -0.5704  |  1.2844  |  0  |  true  |  
|  -0.0746  |  -0.6004  |  1.2784  |  0  |  true  |  
|  -0.0944  |  -0.614  |  1.2784  |  0  |  true  |  
|  -0.1044  |  -0.6404  |  1.266  |  0  |  true  |  
|  -0.1204  |  -0.6464  |  1.2864  |  0  |  true  |  
|  -0.1264  |  -0.6454  |  1.3004  |  0  |  true  |  
|  -0.154  |  -0.6464  |  1.3004  |  0  |  true  |  
|  -0.1644  |  -0.654  |  1.2864  |  0  |  true  |  
|  -0.1744  |  -0.6404  |  1.294  |  0  |  true  |  
|  -0.1844  |  -0.6444  |  1.2764  |  0  |  true  |  
|  -0.2004  |  -0.6254  |  1.2984  |  0  |  true  |  
|  -0.2204  |  -0.6204  |  1.286  |  0  |  true  |  
|  -0.2244  |  -0.6004  |  1.286  |  0  |  true  |  
|  -0.2404  |  -0.5944  |  1.2664  |  0  |  true  |  
|  -0.254  |  -0.58  |  1.2544  |  0  |  true  |  
|  -0.2644  |  -0.5844  |  1.246  |  0  |  true  |  
|  -0.2744  |  -0.5484  |  1.2464  |  0  |  true  |  
|  -0.284  |  -0.546  |  1.2546  |  0  |  true  |  
|  -0.2844  |  -0.5264  |  1.2566  |  0  |  true  |  
|  -0.3004  |  -0.5164  |  1.2484  |  0  |  true  |  
|  -0.314  |  -0.5064  |  1.2544  |  0  |  true  |  
|  -0.3204  |  -0.4944  |  1.2406  |  0  |  true  |  
|  -0.3264  |  -0.4846  |  1.246  |  0  |  true  |  
|  -0.3364  |  -0.4946  |  1.2284  |  0  |  true  |  
|  -0.3344  |  -0.4844  |  1.228  |  0  |  true  |  
|  -0.34  |  -0.4844  |  1.2184  |  0  |  true  |  
|  -0.3404  |  -0.4766  |  1.2464  |  0  |  true  |  
|  -0.3404  |  -0.4844  |  1.2464  |  0  |  true  |  
|  -0.3404  |  -0.4844  |  1.244  |  0  |  true  |  
|  -0.34  |  -0.4966  |  1.244  |  0  |  true  |  
|  -0.3444  |  -0.5044  |  1.2286  |  0  |  true  |  
|  -0.336  |  -0.5064  |  1.2444  |  0  |  true  |  
|  -0.34  |  -0.5264  |  1.2406  |  0  |  true  |  
|  -0.3444  |  -0.5444  |  1.216  |  0  |  true  |  
|  -0.3346  |  -0.5464  |  1.2064  |  0  |  true  |  
|  -0.3206  |  -0.5644  |  1.1884  |  0  |  true  |  
|  -0.3144  |  -0.5644  |  1.2084  |  0  |  true  |  
|  -0.3146  |  -0.5904  |  1.2004  |  0  |  true  |  
|  -0.2946  |  -0.6044  |  1.156  |  0  |  true  |  
|  -0.2844  |  -0.64  |  1.1864  |  0  |  true  |  
|  -0.2744  |  -0.6146  |  1.204  |  0  |  true  |  
|  -0.264  |  -0.644  |  1.2664  |  0  |  true  |  
|  -0.244  |  -0.6264  |  1.2406  |  0  |  true  |  
|  -0.2344  |  -0.6444  |  1.248  |  0  |  true  |  
|  -0.2264  |  -0.6644  |  1.228  |  0  |  true  |  
|  -0.1944  |  -0.6546  |  1.2464  |  0  |  true  |  
|  -0.1744  |  -0.6844  |  1.2664  |  0  |  true  |  
|  -0.144  |  -0.688  |  1.2184  |  0  |  true  |  
|  -0.1446  |  -0.6944  |  1.2584  |  0  |  true  |  
|  -0.126  |  -0.7044  |  1.268  |  0  |  true  |  
|  -0.1164  |  -0.716  |  1.266  |  0  |  true  |  
|  -0.084  |  -0.734  |  1.2764  |  0  |  true  |  
|  -0.0764  |  -0.7044  |  1.246  |  0  |  true  |  
|  -0.0444  |  -0.7404  |  1.266  |  0  |  true  |  
|  -0.0348  |  -0.7244  |  1.2584  |  0  |  true  |  
|  0.0044  |  -0.7466  |  1.2764  |  0  |  true  |  
|  0.0264  |  -0.7306  |  1.268  |  0  |  true  |  
|  0.064  |  -0.7468  |  1.2684  |  0  |  true  |  
|  0.0844  |  -0.7468  |  1.256  |  0  |  true  |  
|  0.1044  |  -0.7506  |  1.2666  |  0  |  true  |  
|  0.1284  |  -0.7544  |  1.2764  |  0  |  true  |  
|  0.1544  |  -0.7744  |  1.2746  |  0  |  true  |  
|  0.1644  |  -0.7766  |  1.2664  |  0  |  true  |  
|  0.1944  |  -0.7764  |  1.2684  |  0  |  true  |  
|  0.2184  |  -0.7784  |  1.256  |  0  |  true  |  
|  0.24  |  -0.7768  |  1.2564  |  0  |  true  |  
|  0.274  |  -0.7766  |  1.2466  |  0  |  true  |  
|  0.2904  |  -0.7786  |  1.2404  |  0  |  true  |  
|  0.314  |  -0.774  |  1.2164  |  0  |  true  |  
|  0.3144  |  -0.7546  |  1.2264  |  0  |  true  |  
|  0.3404  |  -0.7764  |  1.266  |  0  |  true  |  
|  0.344  |  -0.7764  |  1.246  |  0  |  true  |  
|  0.3444  |  -0.7746  |  1.2444  |  0  |  true  |  
|  0.3404  |  -0.7784  |  1.2764  |  0  |  true  |  
|  0.3146  |  -0.7784  |  1.2664  |  0  |  true  |  
|  0.3204  |  -0.7784  |  1.2544  |  0  |  true  |  
|  0.3144  |  -0.7744  |  1.226  |  0  |  true  |  
|  0.3264  |  -0.7784  |  1.2364  |  0  |  true  |  
|  0.3444  |  -0.7764  |  1.2064  |  0  |  true  |  
|  0.3284  |  -0.7764  |  1.2584  |  0  |  true  |  
|  0.344  |  -0.7784  |  1.2044  |  0  |  true  |  
|  0.334  |  -0.7784  |  1.2084  |  0  |  true  |  
|  0.34  |  -0.7784  |  1.2064  |  0  |  true  |  
|  0.3264  |  -0.7746  |  1.244  |  0  |  true  |  
End of preview. 
  * Format⟨45⟩
  * Camera Parameter Distributions⟨46⟩
    * Dataset Download⟨47⟩
    * Caption Pipeline⟨48⟩
    * Citation⟨49⟩


#   ⟨50⟩ TartanAir-Absolute-Camera 
![camera map collage](https://huggingface.co/datasets/KangLiao/TartanAir-Absolute-Camera/resolve/main/analysis/TartanAir-Absolute-Camera.png)⟨51⟩
Per-frame **camera parameter** annotations for the **TartanAir** dataset (**18 environments scenes** ; **306,616** valid per-frame annotations), captioned by the **Puffin-World**⟨52⟩ model. More captioned datasets are provided in our **Puffin-16M**⟨53⟩ website.
The collage above visualizes the camera maps on sample images — each pair shows the **up field** (green arrows: the projected gravity-up direction) and the **latitude field** (colored contours: angle above/below the horizon).
##   ⟨45⟩ Format 
**One`.zip` per environment** — `<environment>.zip` (e.g. `abandonedfactory.zip`), 18 environments; each archive holds all its Easy/Hard trajectories.
Each zip unpacks to the original per-frame layout:

```
Easy/P000/000000_camera.json
Hard/P001/000012_camera.json
...

```

Each JSON holds the predicted monocular camera parameters:  
| field  | meaning  | unit  |  
| --- | --- | --- |  
| `roll`  | camera roll  | radians  |  
| `pitch`  | camera pitch  | radians  |  
| `vfov`  | vertical field of view  | radians  |  
| `k1`  | radial distortion coefficient  | –  |  
| `parse_ok`  | whether the model output parsed within valid ranges  | bool  |  
Example:

```
{"roll": -0.0014, "pitch": -0.0764, "vfov": 1.2465, "k1": 0.0, "parse_ok": true}

```

##   ⟨46⟩ Camera Parameter Distributions 
Histograms of the predicted roll / pitch / vertical-FoV over all frames (proportion of valid samples per 10° bin; `parse_ok=False` samples excluded).
![tartanair camera stats](https://huggingface.co/datasets/KangLiao/TartanAir-Absolute-Camera/resolve/main/analysis/tartanair_camera_stats.png)⟨54⟩  
| split  | roll μ / med / σ  | pitch μ / med / σ  | FoV μ / med / σ  |  
| --- | --- | --- | --- |  
| all (307K frames)  | -0.1° / -0.1° / 15.1°  | -5.3° / -4.4° / 23.8°  | 68.9° / 71.4° / 7.3°  |  
**Reading the distributions**
  * **Roll** is spread around 0° (σ ≈ 15.1°) — captures are shot close to level.
  * **Pitch** carries a slight downward bias (median ≈ -4.4°, mean ≈ -5.3°) with σ ≈ 7–24° spread.
  * **FoV** concentrates around **64–79°** (median ≈ 71.4°).


If you'd like a dataset with a more diverse and uniform distribution of camera parameters, please refer to our Puffin-4M⟨55⟩ and Puffin-16M⟨56⟩ datasets.
###   ⟨47⟩ Dataset Download 
You can download the entire dataset using the following command:

```
hf download KangLiao/TartanAir-Absolute-Camera --repo-type dataset

```

###   ⟨48⟩ Caption Pipeline 
Beyond this captioned dataset, we also release **a complete captioning pipeline** for annotating camera parameters for arbitrary datasets, analyzing camera parameter distributions, and visualizing the corresponding camera maps. The pipeline is available in our GitHub repository⟨52⟩.
###   ⟨49⟩ Citation 
If you find the captioned dataset useful for your research or applications, please cite our paper using the following BibTeX:

```
  @article{liao2025puffin,
    title={Thinking with Camera: A Unified Multimodal Model for Camera-Centric Understanding and Generation},
    author={Liao, Kang and Wu, Size and Wu, Zhonghua and Jin, Linyi and Wang, Chao and Wang, Yikai and Wang, Fei and Li, Wei and Loy, Chen Change},
    journal={arXiv preprint arXiv:2510.08673},
    year={2025}
  }

```

Copy to bucket new 

Downloads last month
    172
Total file size: 75.9 MB
##  Paper for KangLiao/TartanAir-Absolute-Camera
#### Thinking with Camera: A Unified Multimodal Model for Camera-Centric Understanding and Generation Paper • 2510.08673 • Published Oct 9, 2025 • 128 ⟨57⟩
System theme
Company
TOS⟨58⟩ Privacy⟨59⟩ About⟨60⟩ Careers⟨61⟩ ⟨1⟩
Website
Models⟨2⟩ Datasets⟨3⟩ Spaces⟨4⟩ Pricing⟨8⟩ Docs⟨6⟩
The table displays a preview with only the first rows.
