![Hugging Face's logo](https://huggingface.co/front/assets/huggingface_logo-noborder.svg) Hugging Face⟨1⟩
  *  Models ⟨2⟩
  *  Datasets ⟨3⟩
  *  Spaces ⟨4⟩
  *  Buckets new⟨5⟩
  *  Docs ⟨6⟩
  *  Enterprise ⟨7⟩
  * Pricing⟨8⟩
  *     * Website
      *  Tasks⟨9⟩
      *  HuggingChat⟨10⟩
      *  Collections⟨11⟩
      *  Languages⟨12⟩
      *  Organizations⟨13⟩
    * Community
      *  Blog⟨14⟩
      *  Posts⟨15⟩
      *  Daily Papers⟨16⟩
      *  Hardware⟨17⟩
      *  Learn⟨18⟩
      *  Discord⟨19⟩
      *  Forum⟨20⟩
      *  GitHub⟨21⟩
    * Solutions
      *  Team & Enterprise⟨7⟩
      *  Hugging Face PRO⟨22⟩
      *  Enterprise Support⟨23⟩
      *  Inference Providers⟨24⟩
      *  Inference Endpoints⟨25⟩
      *  Storage Buckets⟨5⟩
  * * * *
  * Log In⟨26⟩
  * Sign Up⟨27⟩


#   Datasets:⟨3⟩
* * *
 ![](https://huggingface.co/avatars/a20318492906e6048d345a09a426564b.svg) ⟨28⟩
Jasonstephane⟨28⟩
/
Cube_bottom_V5⟨29⟩
like 0
Tasks:  Robotics ⟨30⟩
Modalities:  Tabular ⟨31⟩ Time-series ⟨32⟩ Video ⟨33⟩
Formats:  parquet ⟨34⟩
Size:  1K - 10K ⟨35⟩
Tags:  LeRobot ⟨36⟩
Libraries:  Datasets ⟨37⟩ pandas ⟨38⟩ Polars ⟨39⟩ + 2
License:
apache-2.0
 Dataset card ⟨29⟩ Data Studio ⟨40⟩ Files Files and versions xet ⟨41⟩ Community ⟨42⟩
Dataset Viewer
 Auto-converted to Parquet⟨43⟩ API Embed  Duplicate⟨44⟩ Data Studio
Subset (1)
default · 1.79k rows
default (1.79k rows)
Split (1)
train · 1.79k rows
train (1.79k rows)
Search is not available for this dataset
SQL
Console  
|  action list  |  observation.state list  |  timestamp float32 0 59.6  |  frame_index int64 0 1.79k  |  episode_index int64 0 0  |  index int64 0 1.79k  |  task_index int64 0 0  |  
| --- | --- | --- | --- | --- | --- | --- |  
|  [ -6.314262390136719, -111.83497619628906, 100.928955078125, 70.39307403564453, 22.171714782714844, 1.9685287475585938 ]  |  [ -9.406593322753906, -105.67032623291016, 98.5054931640625, 73.67032623291016, 24.879121780395508, 18.695941925048828 ]  |  0  |  0  |  0  |  0  |  0  |  
|  [ -6.489499568939209, -112.00668334960938, 101.31645202636719, 70.44252014160156, 22.082883834838867, 1.9499702453613281 ]  |  [ -9.406593322753906, -105.67032623291016, 98.5054931640625, 73.67032623291016, 24.879121780395508, 18.695941925048828 ]  |  0.033333  |  1  |  0  |  1  |  0  |  
|  [ -4.13963508605957, -110.19424438476562, 100.85394287109375, 67.80766296386719, 23.648090362548828, 2.121938705444336 ]  |  [ -8.79120922088623, -105.75823974609375, 98.4175796508789, 73.14286041259766, 24.175825119018555, 18.230205535888672 ]  |  0.066667  |  2  |  0  |  2  |  0  |  
|  [ -6.700455665588379, -112.0625, 101.9540023803711, 70.00383758544922, 22.120460510253906, 1.9047861099243164 ]  |  [ -7.824175834655762, -106.10989379882812, 97.80220031738281, 72.43955993652344, 23.560440063476562, 16.433799743652344 ]  |  0.1  |  3  |  0  |  3  |  0  |  
|  [ -5.968741416931152, -112.75811767578125, 102.44700622558594, 69.55227661132812, 22.688312530517578, 1.921797752380371 ]  |  [ -6.94505500793457, -106.46154022216797, 97.62637329101562, 71.9120864868164, 23.296703338623047, 14.038589477539062 ]  |  0.133333  |  4  |  0  |  4  |  0  |  
|  [ -5.115377426147461, -112.4854736328125, 102.16329956054688, 68.85206604003906, 22.859195709228516, 1.9489564895629883 ]  |  [ -6.681318759918213, -106.63735961914062, 97.62637329101562, 71.38461303710938, 23.296703338623047, 11.443778991699219 ]  |  0.166667  |  5  |  0  |  5  |  0  |  
|  [ -5.581307411193848, -112.12322998046875, 102.33576965332031, 68.69412994384766, 22.677772521972656, 1.8112754821777344 ]  |  [ -6.681318759918213, -106.63735961914062, 97.62637329101562, 71.12088012695312, 23.120878219604492, 8.848968505859375 ]  |  0.2  |  6  |  0  |  6  |  0  |  
|  [ -5.012994766235352, -110.92134094238281, 101.90742492675781, 68.09567260742188, 23.621910095214844, 1.8765029907226562 ]  |  [ -6.681318759918213, -106.63735961914062, 97.62637329101562, 70.5934066772461, 23.120878219604492, 6.719893455505371 ]  |  0.233333  |  7  |  0  |  7  |  0  |  
|  [ -6.031089782714844, -112.46321105957031, 102.83074951171875, 68.80249786376953, 23.16473388671875, 1.8877849578857422 ]  |  [ -6.4175825119018555, -106.63735961914062, 97.62637329101562, 70.24176025390625, 23.120878219604492, 5.256154537200928 ]  |  0.266667  |  8  |  0  |  8  |  0  |  
|  [ -5.7059454917907715, -112.38848876953125, 102.67333984375, 68.23541259765625, 23.341629028320312, 1.8953056335449219 ]  |  [ -5.97802209854126, -106.63735961914062, 97.62637329101562, 69.89010620117188, 23.120878219604492, 4.191616535186768 ]  |  0.3  |  9  |  0  |  9  |  0  |  
|  [ -5.680884838104248, -111.77534484863281, 101.8655776977539, 67.9890365600586, 23.546470642089844, 1.9515495300292969 ]  |  [ -5.626373767852783, -106.63735961914062, 97.62637329101562, 69.62637329101562, 23.120878219604492, 3.5262808799743652 ]  |  0.333333  |  10  |  0  |  10  |  0  |  
|  [ -5.7020697593688965, -111.33981323242188, 102.7746353149414, 67.60681915283203, 23.433340072631836, 1.8101491928100586 ]  |  [ -5.626373767852783, -106.72527313232422, 97.62637329101562, 69.62637329101562, 23.120878219604492, 3.1270792484283447 ]  |  0.366667  |  11  |  0  |  11  |  0  |  
|  [ -5.818217754364014, -111.65310668945312, 102.90167236328125, 67.60289001464844, 23.25284194946289, 1.836106300354004 ]  |  [ -5.626373767852783, -106.72527313232422, 97.62637329101562, 69.36264038085938, 23.120878219604492, 2.8609447479248047 ]  |  0.4  |  12  |  0  |  12  |  0  |  
|  [ -6.569886207580566, -111.71682739257812, 102.8212890625, 67.7083740234375, 23.26192283630371, 1.6881446838378906 ]  |  [ -5.8021979331970215, -106.72527313232422, 97.62637329101562, 69.010986328125, 23.120878219604492, 2.661344051361084 ]  |  0.433333  |  13  |  0  |  13  |  0  |  
|  [ -6.271766662597656, -111.46806335449219, 103.01850891113281, 67.51100158691406, 23.331811904907227, 1.8429689407348633 ]  |  [ -5.890110015869141, -106.72527313232422, 97.62637329101562, 68.83516693115234, 23.120878219604492, 2.5282766819000244 ]  |  0.466667  |  14  |  0  |  14  |  0  |  
|  [ -6.25405740737915, -111.59892272949219, 102.02378845214844, 67.20630645751953, 23.843677520751953, 1.9668874740600586 ]  |  [ -5.97802209854126, -106.72527313232422, 97.62637329101562, 68.74725341796875, 23.120878219604492, 2.461743116378784 ]  |  0.5  |  15  |  0  |  15  |  0  |  
|  [ -5.939018249511719, -111.27664184570312, 102.01687622070312, 67.0464859008789, 23.41781997680664, 1.8032112121582031 ]  |  [ -5.97802209854126, -106.72527313232422, 97.62637329101562, 68.57142639160156, 23.120878219604492, 2.395209550857544 ]  |  0.533333  |  16  |  0  |  16  |  0  |  
|  [ -6.525518417358398, -111.50483703613281, 102.5937728881836, 67.15431213378906, 23.48235511779785, 1.8589744567871094 ]  |  [ -5.97802209854126, -106.72527313232422, 97.62637329101562, 68.3956069946289, 23.120878219604492, 2.395209550857544 ]  |  0.566667  |  17  |  0  |  17  |  0  |  
|  [ -6.536991596221924, -111.07632446289062, 101.72280883789062, 66.8502426147461, 23.402538299560547, 2.0270462036132812 ]  |  [ -6.065934181213379, -106.72527313232422, 97.62637329101562, 68.21977996826172, 23.120878219604492, 2.395209550857544 ]  |  0.6  |  18  |  0  |  18  |  0  |  
|  [ -5.661282062530518, -111.31385803222656, 101.07240295410156, 66.5135498046875, 23.922409057617188, 2.570937156677246 ]  |  [ -6.153846263885498, -106.72527313232422, 97.62637329101562, 68.21977996826172, 23.120878219604492, 2.395209550857544 ]  |  0.633333  |  19  |  0  |  19  |  0  |  
|  [ -5.607682228088379, -111.25013732910156, 101.29844665527344, 66.103759765625, 23.81681251525879, 2.421086311340332 ]  |  [ -6.153846263885498, -106.72527313232422, 97.62637329101562, 68.21977996826172, 23.120878219604492, 2.395209550857544 ]  |  0.666667  |  20  |  0  |  20  |  0  |  
|  [ -6.048420429229736, -110.89169311523438, 100.86640167236328, 66.28128051757812, 24.0372314453125, 3.0057621002197266 ]  |  [ -6.241758346557617, -106.72527313232422, 97.62637329101562, 68.13186645507812, 23.208791732788086, 2.395209550857544 ]  |  0.7  |  21  |  0  |  21  |  0  |  
|  [ -5.7183122634887695, -111.46617126464844, 101.10600280761719, 65.87801361083984, 24.167335510253906, 2.6451501846313477 ]  |  [ -6.065934181213379, -106.72527313232422, 97.62637329101562, 67.69230651855469, 23.296703338623047, 2.395209550857544 ]  |  0.733333  |  22  |  0  |  22  |  0  |  
|  [ -5.625107288360596, -110.48634338378906, 99.66161346435547, 65.89212799072266, 24.189218521118164, 2.896512031555176 ]  |  [ -5.8021979331970215, -106.72527313232422, 97.62637329101562, 67.51648712158203, 23.296703338623047, 2.395209550857544 ]  |  0.766667  |  23  |  0  |  23  |  0  |  
|  [ -5.538973808288574, -110.81272888183594, 99.63021850585938, 65.2795181274414, 24.310941696166992, 3.3951568603515625 ]  |  [ -5.626373767852783, -106.72527313232422, 97.62637329101562, 67.25274658203125, 23.296703338623047, 2.395209550857544 ]  |  0.8  |  24  |  0  |  24  |  0  |  
|  [ -5.483022689819336, -110.77993774414062, 99.73274993896484, 65.24015045166016, 24.648521423339844, 3.6480798721313477 ]  |  [ -5.626373767852783, -106.72527313232422, 97.62637329101562, 67.07691955566406, 23.296703338623047, 2.461743116378784 ]  |  0.833333  |  25  |  0  |  25  |  0  |  
|  [ -4.6027140617370605, -110.08393859863281, 97.34603881835938, 64.42729187011719, 25.31629753112793, 4.613282680511475 ]  |  [ -5.626373767852783, -106.72527313232422, 97.62637329101562, 66.81318664550781, 23.296703338623047, 2.727877616882324 ]  |  0.866667  |  26  |  0  |  26  |  0  |  
|  [ -5.686019420623779, -110.84799194335938, 98.8512954711914, 65.15164184570312, 24.820056915283203, 4.186634063720703 ]  |  [ -5.714285850524902, -106.72527313232422, 97.62637329101562, 66.54945373535156, 23.47252655029297, 2.994011878967285 ]  |  0.9  |  27  |  0  |  27  |  0  |  
|  [ -5.451152324676514, -109.68597412109375, 97.40911865234375, 64.53717041015625, 25.56934356689453, 5.106318950653076 ]  |  [ -5.8021979331970215, -106.72527313232422, 97.62637329101562, 66.10989379882812, 23.91208839416504, 3.1270792484283447 ]  |  0.933333  |  28  |  0  |  28  |  0  |  
|  [ -4.722431182861328, -108.87939453125, 95.38607025146484, 63.89805221557617, 26.097814559936523, 6.2539849281311035 ]  |  [ -5.626373767852783, -106.72527313232422, 97.62637329101562, 65.93406677246094, 24.175825119018555, 3.5262808799743652 ]  |  0.966667  |  29  |  0  |  29  |  0  |  
|  [ -4.7368903160095215, -107.87480163574219, 94.6881103515625, 64.07337951660156, 26.481412887573242, 7.179976463317871 ]  |  [ -5.362637519836426, -106.72527313232422, 97.62637329101562, 65.93406677246094, 24.263736724853516, 3.725881576538086 ]  |  1  |  30  |  0  |  30  |  0  |  
|  [ -5.1028265953063965, -107.72140502929688, 94.91844940185547, 63.97386932373047, 26.207494735717773, 7.071144104003906 ]  |  [ -5.1868133544921875, -106.54945373535156, 97.62637329101562, 65.4945068359375, 24.791208267211914, 4.324684143066406 ]  |  1.033333  |  31  |  0  |  31  |  0  |  
|  [ -5.10106086730957, -104.62452697753906, 90.72807312011719, 63.32006072998047, 27.287532806396484, 8.575908660888672 ]  |  [ -5.098901271820068, -106.63735961914062, 97.62637329101562, 65.31867980957031, 25.230770111083984, 5.1896209716796875 ]  |  1.066667  |  32  |  0  |  32  |  0  |  
|  [ -5.628107070922852, -102.28379821777344, 88.26570129394531, 63.15850830078125, 28.067148208618164, 9.523672103881836 ]  |  [ -5.098901271820068, -106.63735961914062, 97.62637329101562, 65.14286041259766, 25.406593322753906, 5.721889495849609 ]  |  1.1  |  33  |  0  |  33  |  0  |  
|  [ -5.96355676651001, -100.99493408203125, 88.25761413574219, 63.39158630371094, 27.950912475585938, 10.140402793884277 ]  |  [ -5.1868133544921875, -106.46154022216797, 97.53845977783203, 64.87911987304688, 25.846153259277344, 6.38722562789917 ]  |  1.133333  |  34  |  0  |  34  |  0  |  
|  [ -6.352822303771973, -98.7233657836914, 86.16680908203125, 63.39192199707031, 28.315210342407227, 10.960803985595703 ]  |  [ -5.274725437164307, -105.67032623291016, 96.57142639160156, 64.61538696289062, 26.373626708984375, 7.119095325469971 ]  |  1.166667  |  35  |  0  |  35  |  0  |  
|  [ -7.401822090148926, -93.15701293945312, 81.48609924316406, 62.514163970947266, 29.084611892700195, 12.362637519836426 ]  |  [ -5.274725437164307, -104.70330047607422, 95.16483306884766, 64.61538696289062, 26.72527503967285, 7.984032154083252 ]  |  1.2  |  36  |  0  |  36  |  0  |  
|  [ -8.356582641601562, -87.3736801147461, 76.53302001953125, 62.58393096923828, 29.608612060546875, 13.546862602233887 ]  |  [ -5.538461685180664, -103.12088012695312, 93.75823974609375, 64.43955993652344, 27.16483497619629, 8.915502548217773 ]  |  1.233333  |  37  |  0  |  37  |  0  |  
|  [ -9.53247356414795, -81.46661376953125, 71.70793151855469, 62.35956573486328, 30.130138397216797, 15.07366943359375 ]  |  [ -6.153846263885498, -100.92308044433594, 91.9120864868164, 64.17582702636719, 27.69230842590332, 9.780439376831055 ]  |  1.266667  |  38  |  0  |  38  |  0  |  
|  [ -9.753290176391602, -81.06077575683594, 71.07453155517578, 62.82614517211914, 30.402847290039062, 15.778593063354492 ]  |  [ -6.857142925262451, -98.02198028564453, 89.36264038085938, 63.912086486816406, 28.21977996826172, 10.844976425170898 ]  |  1.3  |  39  |  0  |  39  |  0  |  
|  [ -9.790316581726074, -78.2906494140625, 69.95807647705078, 62.960731506347656, 30.272268295288086, 15.92862319946289 ]  |  [ -7.736263751983643, -94.24176025390625, 86.19779968261719, 63.736263275146484, 28.74725341796875, 12.042581558227539 ]  |  1.333333  |  40  |  0  |  40  |  0  |  
|  [ -11.51846694946289, -70.83078002929688, 64.58887481689453, 63.058433532714844, 30.736547470092773, 17.613374710083008 ]  |  [ -8.527472496032715, -90.46154022216797, 82.85713958740234, 63.736263275146484, 29.098901748657227, 13.173652648925781 ]  |  1.366667  |  41  |  0  |  41  |  0  |  
|  [ -12.274421691894531, -68.0716552734375, 61.75892639160156, 63.43789291381836, 30.915822982788086, 18.034183502197266 ]  |  [ -9.230769157409668, -87.03296661376953, 79.95604705810547, 63.736263275146484, 29.36263656616211, 14.038589477539062 ]  |  1.4  |  42  |  0  |  42  |  0  |  
|  [ -13.245437622070312, -62.879119873046875, 57.83211898803711, 63.2967529296875, 31.729930877685547, 18.945650100708008 ]  |  [ -9.406593322753906, -84.04395294189453, 77.84615325927734, 63.736263275146484, 29.626373291015625, 14.637392044067383 ]  |  1.433333  |  43  |  0  |  43  |  0  |  
|  [ -13.794300079345703, -60.26771545410156, 56.52540588378906, 63.519264221191406, 32.095619201660156, 19.823843002319336 ]  |  [ -9.758241653442383, -80.87911987304688, 75.73626708984375, 63.736263275146484, 29.9780216217041, 15.568861961364746 ]  |  1.466667  |  44  |  0  |  44  |  0  |  
|  [ -14.989198684692383, -53.597740173339844, 51.920738220214844, 64.10449981689453, 32.140159606933594, 21.002578735351562 ]  |  [ -10.813186645507812, -76.92308044433594, 73.010986328125, 63.736263275146484, 30.329669952392578, 16.566865921020508 ]  |  1.5  |  45  |  0  |  45  |  0  |  
|  [ -16.5091552734375, -45.42445373535156, 45.80203628540039, 64.19247436523438, 32.666015625, 22.106639862060547 ]  |  [ -12.219779968261719, -72.61538696289062, 69.75823974609375, 63.736263275146484, 30.769229888916016, 17.498336791992188 ]  |  1.533333  |  46  |  0  |  46  |  0  |  
|  [ -16.871158599853516, -43.45595932006836, 44.66603088378906, 64.63427734375, 32.653419494628906, 22.914628982543945 ]  |  [ -13.186813354492188, -68.21977996826172, 66.24176025390625, 63.82417678833008, 31.120878219604492, 18.496339797973633 ]  |  1.566667  |  47  |  0  |  47  |  0  |  
|  [ -16.938312530517578, -41.71648406982422, 43.85252380371094, 64.22893524169922, 33.01771545410156, 22.799503326416016 ]  |  [ -13.978021621704102, -63.29670333862305, 62.5494499206543, 64, 31.47252655029297, 19.56087875366211 ]  |  1.6  |  48  |  0  |  48  |  0  |  
|  [ -16.857831954956055, -42.39794158935547, 43.76540756225586, 64.41015625, 33.2838134765625, 22.971519470214844 ]  |  [ -14.681318283081055, -57.846153259277344, 58.68132019042969, 64.17582702636719, 31.736263275146484, 20.558881759643555 ]  |  1.633333  |  49  |  0  |  49  |  0  |  
|  [ -18.652070999145508, -33.358558654785156, 37.520938873291016, 64.89470672607422, 34.1171760559082, 24.30746841430664 ]  |  [ -15.472527503967285, -52.57143020629883, 55.25274658203125, 64.17582702636719, 32, 21.157684326171875 ]  |  1.666667  |  50  |  0  |  50  |  0  |  
|  [ -19.225502014160156, -29.264446258544922, 35.23740768432617, 65.14116668701172, 34.08955001831055, 24.89298439025879 ]  |  [ -16.175825119018555, -48.79121017456055, 52.96703338623047, 64.26373291015625, 32.35165023803711, 21.62342071533203 ]  |  1.7  |  51  |  0  |  51  |  0  |  
|  [ -20.6038761138916, -23.53293800354004, 31.941116333007812, 65.80070495605469, 34.63285827636719, 25.635852813720703 ]  |  [ -16.703296661376953, -45.80219650268555, 51.20878982543945, 64.52747344970703, 32.79121017456055, 22.288755416870117 ]  |  1.733333  |  52  |  0  |  52  |  0  |  
|  [ -20.665790557861328, -19.89438247680664, 29.812767028808594, 65.1397476196289, 35.16968536376953, 25.42577362060547 ]  |  [ -17.318681716918945, -42.901100158691406, 48.83516311645508, 64.79120635986328, 33.14285659790039, 23.087158203125 ]  |  1.766667  |  53  |  0  |  53  |  0  |  
|  [ -19.731143951416016, -24.49569320678711, 32.74842071533203, 65.15562438964844, 34.724571228027344, 25.566757202148438 ]  |  [ -18.19780158996582, -38.85714340209961, 45.846153259277344, 65.14286041259766, 33.4945068359375, 23.75249481201172 ]  |  1.8  |  54  |  0  |  54  |  0  |  
|  [ -20.644773483276367, -21.264421463012695, 30.881505966186523, 65.30711364746094, 35.1900749206543, 25.733068466186523 ]  |  [ -19.076923370361328, -34.19780349731445, 42.5054931640625, 65.14286041259766, 33.846153259277344, 24.218229293823242 ]  |  1.833333  |  55  |  0  |  55  |  0  |  
|  [ -20.92519760131836, -14.688346862792969, 27.023365020751953, 65.5208740234375, 35.687686920166016, 25.02459144592285 ]  |  [ -19.78022003173828, -29.626373291015625, 39.69230651855469, 65.14286041259766, 33.93406677246094, 24.617431640625 ]  |  1.866667  |  56  |  0  |  56  |  0  |  
|  [ -21.295915603637695, -12.4736328125, 25.428499221801758, 65.57667541503906, 35.88071823120117, 26.070980072021484 ]  |  [ -20.043956756591797, -25.934066772460938, 38.10988998413086, 65.14286041259766, 34.10988998413086, 24.817031860351562 ]  |  1.9  |  57  |  0  |  57  |  0  |  
|  [ -21.688709259033203, -10.098579406738281, 25.417835235595703, 65.67118072509766, 36.09518051147461, 26.666234970092773 ]  |  [ -20.21977996826172, -22.94505500793457, 36.96703338623047, 65.14286041259766, 34.5494499206543, 24.88356590270996 ]  |  1.933333  |  58  |  0  |  58  |  0  |  
|  [ -22.31886863708496, -7.580104827880859, 23.519622802734375, 65.70146179199219, 36.39814758300781, 26.003559112548828 ]  |  [ -20.21977996826172, -19.78022003173828, 35.29670333862305, 65.14286041259766, 34.901100158691406, 25.083166122436523 ]  |  1.966667  |  59  |  0  |  59  |  0  |  
|  [ -22.84661102294922, -5.591651916503906, 23.16814422607422, 66.0597915649414, 36.78119659423828, 26.990463256835938 ]  |  [ -20.659339904785156, -16.439559936523438, 33.36263656616211, 65.14286041259766, 35.07692337036133, 25.48236846923828 ]  |  2  |  60  |  0  |  60  |  0  |  
|  [ -22.558897018432617, -4.742618560791016, 22.027721405029297, 65.68301391601562, 36.965110778808594, 27.909337997436523 ]  |  [ -21.27472496032715, -13.274724960327148, 31.78022003173828, 65.14286041259766, 35.42856979370117, 25.615436553955078 ]  |  2.033333  |  61  |  0  |  61  |  0  |  
|  [ -22.42281723022461, -2.825775146484375, 21.811779022216797, 65.69072723388672, 37.615840911865234, 28.05883026123047 ]  |  [ -21.89011001586914, -10.197802543640137, 30.373626708984375, 65.14286041259766, 35.868133544921875, 25.948102951049805 ]  |  2.066667  |  62  |  0  |  62  |  0  |  
|  [ -22.9560546875, -2.7906646728515625, 21.807886123657227, 66.17899322509766, 37.377464294433594, 27.485774993896484 ]  |  [ -22.329669952392578, -7.648351669311523, 29.14285659790039, 65.14286041259766, 36.131866455078125, 26.546905517578125 ]  |  2.1  |  63  |  0  |  63  |  0  |  
|  [ -23.082260131835938, 1.87603759765625, 18.542396545410156, 65.864990234375, 37.93881607055664, 28.003494262695312 ]  |  [ -22.329669952392578, -5.626373767852783, 28.175825119018555, 65.14286041259766, 36.483516693115234, 26.946107864379883 ]  |  2.133333  |  64  |  0  |  64  |  0  |  
|  [ -22.749862670898438, 1.0102462768554688, 19.986135482788086, 65.99806213378906, 38.047000885009766, 28.231708526611328 ]  |  [ -22.329669952392578, -4.043956279754639, 27.47252655029297, 65.14286041259766, 36.659339904785156, 26.946107864379883 ]  |  2.166667  |  65  |  0  |  65  |  0  |  
|  [ -23.04084014892578, 3.6105003356933594, 18.28106689453125, 65.61078643798828, 38.40960693359375, 27.704647064208984 ]  |  [ -22.241758346557617, -2.8131868839263916, 26.85714340209961, 65.4065933227539, 36.74725341796875, 27.01264190673828 ]  |  2.2  |  66  |  0  |  66  |  0  |  
|  [ -23.22734832763672, 5.6043853759765625, 17.225605010986328, 65.92256927490234, 38.796775817871094, 28.387977600097656 ]  |  [ -22.329669952392578, -1.3186813592910767, 25.89011001586914, 65.5824203491211, 37.18681335449219, 27.278776168823242 ]  |  2.233333  |  67  |  0  |  67  |  0  |  
|  [ -22.989717483520508, 4.799030303955078, 17.868783950805664, 65.98068237304688, 38.75147247314453, 27.79509735107422 ]  |  [ -22.505495071411133, 0.7032967209815979, 24.659339904785156, 65.4945068359375, 37.36263656616211, 27.34531021118164 ]  |  2.266667  |  68  |  0  |  68  |  0  |  
|  [ -22.90751075744629, 6.985958099365234, 16.26937484741211, 65.86735534667969, 39.410194396972656, 28.53402328491211 ]  |  [ -23.03296661376953, 2.9010989665985107, 23.428571701049805, 65.4945068359375, 37.71428680419922, 27.544910430908203 ]  |  2.3  |  69  |  0  |  69  |  0  |  
|  [ -22.77985954284668, 7.780414581298828, 15.126680374145508, 66.02302551269531, 39.88199996948242, 28.411502838134766 ]  |  [ -23.208791732788086, 4.395604610443115, 22.901098251342773, 65.4945068359375, 38.06593322753906, 27.6114444732666 ]  |  2.333333  |  70  |  0  |  70  |  0  |  
|  [ -22.9573974609375, 9.65090560913086, 14.19406509399414, 65.69515228271484, 39.92390441894531, 27.747346878051758 ]  |  [ -23.208791732788086, 5.274725437164307, 22.461538314819336, 65.4945068359375, 38.41758346557617, 27.744510650634766 ]  |  2.366667  |  71  |  0  |  71  |  0  |  
|  [ -23.188199996948242, 10.876846313476562, 14.112585067749023, 65.70064544677734, 40.533424377441406, 28.919485092163086 ]  |  [ -23.120878219604492, 6.593406677246094, 21.406593322753906, 65.4945068359375, 38.769229888916016, 27.877578735351562 ]  |  2.4  |  72  |  0  |  72  |  0  |  
|  [ -22.902137756347656, 10.855525970458984, 13.82891845703125, 65.50517272949219, 40.39753341674805, 28.307035446166992 ]  |  [ -22.94505500793457, 8.175824165344238, 20.263736724853516, 65.4945068359375, 38.769229888916016, 27.877578735351562 ]  |  2.433333  |  73  |  0  |  73  |  0  |  
|  [ -22.481197357177734, 12.064590454101562, 13.680328369140625, 65.6358871459961, 40.94464874267578, 27.788684844970703 ]  |  [ -22.94505500793457, 9.84615421295166, 19.384614944458008, 65.4945068359375, 39.120880126953125, 28.077178955078125 ]  |  2.466667  |  74  |  0  |  74  |  0  |  
|  [ -22.372947692871094, 13.038475036621094, 13.091781616210938, 65.29379272460938, 41.0236930847168, 27.98473358154297 ]  |  [ -22.94505500793457, 10.90109920501709, 18.94505500793457, 65.4945068359375, 39.47252655029297, 28.210247039794922 ]  |  2.5  |  75  |  0  |  75  |  0  |  
|  [ -22.445104598999023, 12.77786636352539, 13.049840927124023, 65.1382827758789, 41.50657272338867, 28.751453399658203 ]  |  [ -22.85714340209961, 11.780220031738281, 18.681318283081055, 65.4945068359375, 39.82417678833008, 28.210247039794922 ]  |  2.533333  |  76  |  0  |  76  |  0  |  
|  [ -22.85634422302246, 13.46359634399414, 12.898077011108398, 65.34017181396484, 41.03739929199219, 28.372425079345703 ]  |  [ -22.94505500793457, 12.835165023803711, 17.9780216217041, 65.4945068359375, 40.087913513183594, 28.210247039794922 ]  |  2.566667  |  77  |  0  |  77  |  0  |  
|  [ -22.74764633178711, 14.100749969482422, 12.341121673583984, 64.7943115234375, 41.51020431518555, 27.22109603881836 ]  |  [ -23.120878219604492, 13.450549125671387, 17.626373291015625, 65.4945068359375, 40.52747344970703, 28.210247039794922 ]  |  2.6  |  78  |  0  |  78  |  0  |  
|  [ -22.554201126098633, 14.072952270507812, 12.106548309326172, 64.85013580322266, 41.601890563964844, 27.205276489257812 ]  |  [ -23.120878219604492, 13.802197456359863, 17.538461685180664, 65.4945068359375, 40.96703338623047, 28.210247039794922 ]  |  2.633333  |  79  |  0  |  79  |  0  |  
|  [ -21.936952590942383, 13.785846710205078, 12.446083068847656, 64.78166961669922, 42.10185623168945, 27.97930335998535 ]  |  [ -23.120878219604492, 14.417582511901855, 17.098901748657227, 65.4945068359375, 40.79121017456055, 28.143712997436523 ]  |  2.666667  |  80  |  0  |  80  |  0  |  
|  [ -22.15726089477539, 14.978416442871094, 11.6807861328125, 64.61368560791016, 41.97291564941406, 27.068256378173828 ]  |  [ -23.120878219604492, 14.94505500793457, 16.83516502380371, 65.4945068359375, 40.96703338623047, 27.877578735351562 ]  |  2.7  |  81  |  0  |  81  |  0  |  
|  [ -21.651853561401367, 14.311344146728516, 11.385108947753906, 64.23640441894531, 42.75032043457031, 27.384111404418945 ]  |  [ -23.120878219604492, 15.032966613769531, 16.74725341796875, 65.4945068359375, 40.96703338623047, 27.877578735351562 ]  |  2.733333  |  82  |  0  |  82  |  0  |  
|  [ -22.18575096130371, 14.762210845947266, 11.408258438110352, 64.52629852294922, 42.232208251953125, 26.81238555908203 ]  |  [ -22.85714340209961, 15.20879077911377, 16.483516693115234, 65.4065933227539, 40.96703338623047, 27.744510650634766 ]  |  2.766667  |  83  |  0  |  83  |  0  |  
|  [ -21.632328033447266, 15.115413665771484, 10.948614120483398, 64.11707305908203, 42.53384780883789, 26.798786163330078 ]  |  [ -22.593406677246094, 15.560439109802246, 15.95604419708252, 65.05494689941406, 41.14285659790039, 27.6114444732666 ]  |  2.8  |  84  |  0  |  84  |  0  |  
|  [ -21.858068466186523, 15.21603012084961, 10.909259796142578, 64.13847351074219, 42.39036178588867, 25.940561294555664 ]  |  [ -22.41758155822754, 15.736263275146484, 15.868131637573242, 64.96703338623047, 41.406593322753906, 27.6114444732666 ]  |  2.833333  |  85  |  0  |  85  |  0  |  
|  [ -21.516576766967773, 16.12582015991211, 11.841873168945312, 64.17707824707031, 42.53055191040039, 26.909988403320312 ]  |  [ -22.065933227539062, 15.824175834655762, 15.780220031738281, 64.96703338623047, 41.758243560791016, 27.34531021118164 ]  |  2.866667  |  86  |  0  |  86  |  0  |  
|  [ -21.873136520385742, 14.790287017822266, 10.623832702636719, 63.612483978271484, 42.374027252197266, 24.830516815185547 ]  |  [ -21.9780216217041, 16, 15.516483306884766, 64.96703338623047, 41.67033004760742, 26.946107864379883 ]  |  2.9  |  87  |  0  |  87  |  0  |  
|  [ -21.4803524017334, 15.01226806640625, 10.727611541748047, 63.772666931152344, 42.625431060791016, 25.976558685302734 ]  |  [ -21.89011001586914, 16.52747344970703, 15.428571701049805, 64.96703338623047, 41.67033004760742, 26.813039779663086 ]  |  2.933333  |  88  |  0  |  88  |  0  |  
|  [ -21.417741775512695, 15.852275848388672, 10.71296501159668, 63.888816833496094, 42.843387603759766, 25.816177368164062 ]  |  [ -21.9780216217041, 16.703296661376953, 15.428571701049805, 64.70330047607422, 41.846153259277344, 26.813039779663086 ]  |  2.966667  |  89  |  0  |  89  |  0  |  
|  [ -21.88382339477539, 14.792552947998047, 10.16201400756836, 63.78178405761719, 42.70871353149414, 23.75754165649414 ]  |  [ -22.153846740722656, 16.791208267211914, 15.428571701049805, 64.52747344970703, 41.93406677246094, 26.546905517578125 ]  |  3  |  90  |  0  |  90  |  0  |  
|  [ -21.547407150268555, 15.902591705322266, 11.036258697509766, 63.3683967590332, 42.71510696411133, 23.666900634765625 ]  |  [ -22.153846740722656, 16.791208267211914, 15.428571701049805, 64.43955993652344, 42.021976470947266, 26.347305297851562 ]  |  3.033333  |  91  |  0  |  91  |  0  |  
|  [ -21.357799530029297, 16.27996063232422, 10.442117691040039, 63.31073760986328, 42.831024169921875, 23.56051254272461 ]  |  [ -22.153846740722656, 16.791208267211914, 15.252747535705566, 64.43955993652344, 42.021976470947266, 26.014636993408203 ]  |  3.066667  |  92  |  0  |  92  |  0  |  
|  [ -20.994068145751953, 15.949455261230469, 10.414249420166016, 63.00905990600586, 43.03545379638672, 22.884803771972656 ]  |  [ -22.153846740722656, 16.791208267211914, 15.076923370361328, 64.35164642333984, 42.021976470947266, 25.349302291870117 ]  |  3.1  |  93  |  0  |  93  |  0  |  
|  [ -21.232892990112305, 16.62246322631836, 10.417848587036133, 63.59041213989258, 42.79942321777344, 22.171138763427734 ]  |  [ -21.9780216217041, 16.879121780395508, 15.076923370361328, 64.17582702636719, 42.021976470947266, 24.750499725341797 ]  |  3.133333  |  94  |  0  |  94  |  0  |  
|  [ -20.890722274780273, 15.899288177490234, 10.001119613647461, 63.050086975097656, 42.74836349487305, 22.10042953491211 ]  |  [ -21.80219841003418, 17.14285659790039, 14.90109920501709, 63.82417678833008, 42.021976470947266, 24.151697158813477 ]  |  3.166667  |  95  |  0  |  95  |  0  |  
|  [ -20.89018440246582, 17.17938232421875, 10.672149658203125, 63.08723449707031, 42.86859130859375, 21.59115219116211 ]  |  [ -21.714284896850586, 17.406593322753906, 14.813186645507812, 63.82417678833008, 42.021976470947266, 23.552894592285156 ]  |  3.2  |  96  |  0  |  96  |  0  |  
|  [ -20.979249954223633, 16.068302154541016, 9.948631286621094, 63.392234802246094, 42.88026809692383, 20.927597045898438 ]  |  [ -21.538461685180664, 17.494504928588867, 14.725275039672852, 63.736263275146484, 42.021976470947266, 23.1536922454834 ]  |  3.233333  |  97  |  0  |  97  |  0  |  
|  [ -20.95201301574707, 16.928543090820312, 10.125984191894531, 63.41417694091797, 42.98833465576172, 21.692604064941406 ]  |  [ -21.450550079345703, 17.494504928588867, 14.725275039672852, 63.64834976196289, 42.021976470947266, 22.687957763671875 ]  |  3.266667  |  98  |  0  |  98  |  0  |  
|  [ -20.391706466674805, 15.725727081298828, 10.159933090209961, 63.09421157836914, 42.637847900390625, 19.82030487060547 ]  |  [ -21.36263656616211, 17.494504928588867, 14.725275039672852, 63.64834976196289, 42.021976470947266, 22.22222137451172 ]  |  3.3  |  99  |  0  |  99  |  0  |  
End of preview. Expand in Data Studio⟨45⟩
* * *
  *  Previous⟨29⟩
  * 1⟨46⟩
  * 2⟨47⟩
  * 3⟨48⟩
  * ...⟨49⟩
  * 18⟨50⟩
  * Next ⟨47⟩


  * Dataset Structure⟨51⟩
  * Citation⟨52⟩


This dataset was created using LeRobot⟨53⟩.
 ![](https://huggingface.co/datasets/huggingface/badges/resolve/main/visualize-this-dataset-xl.svg) ![](https://huggingface.co/datasets/huggingface/badges/resolve/main/visualize-this-dataset-xl-dark.svg) ⟨54⟩
##   ⟨51⟩ Dataset Structure 
meta/info.json⟨55⟩:

```
{
    "codebase_version": "v3.0",
    "fps": 30,
    "features": {
        "action": {
            "dtype": "float32",
            "names": [
                "shoulder_pan.pos",
                "shoulder_lift.pos",
                "elbow_flex.pos",
                "wrist_flex.pos",
                "wrist_roll.pos",
                "gripper.pos"
            ],
            "shape": [
                6
            ]
        },
        "observation.state": {
            "dtype": "float32",
            "names": [
                "shoulder_pan.pos",
                "shoulder_lift.pos",
                "elbow_flex.pos",
                "wrist_flex.pos",
                "wrist_roll.pos",
                "gripper.pos"
            ],
            "shape": [
                6
            ]
        },
        "observation.images.tuy": {
            "dtype": "video",
            "shape": [
                480,
                640,
                3
            ],
            "names": [
                "height",
                "width",
                "channels"
            ],
            "info": {
                "video.height": 480,
                "video.width": 640,
                "video.codec": "av1",
                "video.pix_fmt": "yuv420p",
                "video.is_depth_map": false,
                "video.fps": 30,
                "video.channels": 3,
                "has_audio": false
            }
        },
        "timestamp": {
            "dtype": "float32",
            "shape": [
                1
            ],
            "names": null
        },
        "frame_index": {
            "dtype": "int64",
            "shape": [
                1
            ],
            "names": null
        },
        "episode_index": {
            "dtype": "int64",
            "shape": [
                1
            ],
            "names": null
        },
        "index": {
            "dtype": "int64",
            "shape": [
                1
            ],
            "names": null
        },
        "task_index": {
            "dtype": "int64",
            "shape": [
                1
            ],
            "names": null
        }
    },
    "total_episodes": 1,
    "total_frames": 1788,
    "total_tasks": 1,
    "chunks_size": 1000,
    "data_files_size_in_mb": 100,
    "video_files_size_in_mb": 200,
    "data_path": "data/chunk-{chunk_index:03d}/file-{file_index:03d}.parquet",
    "video_path": "videos/{video_key}/chunk-{chunk_index:03d}/file-{file_index:03d}.mp4",
    "robot_type": "so_follower",
    "splits": {
        "train": "0:1"
    }
}

```

##   ⟨52⟩ Citation 
**BibTeX:**

```
[More Information Needed]

```

Copy to bucket new
Use this dataset 

Downloads last month
    77
License: apache-2.0 Number of rows: 1,788 Total file size: 23.8 MB
##  Collection including Jasonstephane/Cube_bottom_V5
#### Cube Bottom Collection 10 items • Updated 19 days ago ⟨56⟩
System theme
Company
TOS⟨57⟩ Privacy⟨58⟩ About⟨59⟩ Careers⟨60⟩ ⟨1⟩
Website
Models⟨2⟩ Datasets⟨3⟩ Spaces⟨4⟩ Pricing⟨8⟩ Docs⟨6⟩
