![Hugging Face's logo](https://huggingface.co/front/assets/huggingface_logo-noborder.svg) Hugging Face⟨1⟩
  *  Models ⟨2⟩
  *  Datasets ⟨3⟩
  *  Spaces ⟨4⟩
  *  Buckets new⟨5⟩
  *  Docs ⟨6⟩
  *  Enterprise ⟨7⟩
  * Pricing⟨8⟩
  *     * Website
      *  Tasks⟨9⟩
      *  HuggingChat⟨10⟩
      *  Collections⟨11⟩
      *  Languages⟨12⟩
      *  Organizations⟨13⟩
    * Community
      *  Blog⟨14⟩
      *  Posts⟨15⟩
      *  Daily Papers⟨16⟩
      *  Hardware⟨17⟩
      *  Learn⟨18⟩
      *  Discord⟨19⟩
      *  Forum⟨20⟩
      *  GitHub⟨21⟩
    * Solutions
      *  Team & Enterprise⟨7⟩
      *  Hugging Face PRO⟨22⟩
      *  Enterprise Support⟨23⟩
      *  Inference Providers⟨24⟩
      *  Inference Endpoints⟨25⟩
      *  Storage Buckets⟨5⟩
  * * * *
  * Log In⟨26⟩
  * Sign Up⟨27⟩


#   Datasets:⟨3⟩
* * *
 ![](https://cdn-avatars.huggingface.co/v1/production/uploads/noauth/wsp61Va5WeJL8QlVNCFB8.jpeg) ⟨28⟩
Hamyrappy⟨28⟩
/
emnlp-2020-2025-atomic-claims⟨29⟩
like 0
Tasks:  Feature Extraction ⟨30⟩ Text Classification ⟨31⟩
Modalities:  Tabular ⟨32⟩ Text ⟨33⟩
Formats:  parquet ⟨34⟩
Languages:  English ⟨35⟩
Size:  10K - 100K ⟨36⟩
Tags:  Synthetic ⟨37⟩ scientometrics ⟨38⟩ science-of-science ⟨39⟩ acl-anthology ⟨40⟩ emnlp ⟨41⟩ atomic-claims ⟨42⟩ + 4
Libraries:  Datasets ⟨43⟩ pandas ⟨44⟩ Polars ⟨45⟩ + 1
License:
cc-by-4.0
 Dataset card ⟨29⟩ Data Studio ⟨46⟩ Files Files and versions xet ⟨47⟩ Community ⟨48⟩
Dataset Viewer
 Auto-converted to Parquet⟨49⟩ API Embed  Duplicate⟨50⟩ Data Studio
Subset (4)
claims · 18.3k rows
claims (18.3k rows) cluster_summary (81 rows) clusters (16.6k rows) papers (6.52k rows)
Split (1)
train · 18.3k rows
train (18.3k rows)
SQL
Console  
|  claim_id large_stringlengths 20 20  |  paper_id large_stringlengths 17 20  |  year int32 2.02k 2.03k  |  atomic_claim large_stringlengths 18 387  |  claim_index int32 0 8  |  extractor_model large_stringclasses 1 value  |  prompt_hash large_stringclasses 1 value  |  run_id large_stringclasses 2 values  |  created_at large_stringclasses 2 values  |  
| --- | --- | --- | --- | --- | --- | --- | --- | --- |  
|  clm_0ea6495e0a53d81c  |  2021.emnlp-main.602  |  2,021  |  SRU++ is a highly-efficient architecture that combines fast recurrence and attention for sequence modeling.  |  0  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_b60a1755be95a7da  |  2021.emnlp-main.602  |  2,021  |  SRU++ achieves better bits-per-character and perplexity with reduced training cost compared to top-performing Transformer models on standard language modeling tasks.  |  1  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_639ae64d6fc7d8c2  |  2021.emnlp-main.602  |  2,021  |  SRU++ requires minimal attention to achieve near state-of-the-art performance.  |  2  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_7979ce943bfc1a36  |  2020.emnlp-main.593  |  2,020  |  DyERNIE learns evolving entity representations in a product of Riemannian manifolds, with the composed spaces estimated from the sectional curvatures of the data.  |  0  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_915778e463e97925  |  2020.emnlp-main.593  |  2,020  |  DyERNIE uses a velocity vector defined in the tangent space at each timestamp to capture the evolutionary dynamics of temporal knowledge graphs.  |  1  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_0c43f723fe783c91  |  2020.emnlp-main.593  |  2,020  |  The dynamics of multi-relational graph data can be more properly modeled by the evolution of embeddings on Riemannian manifolds.  |  2  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_b71b970484e2e00c  |  2023.emnlp-main.50  |  2,023  |  EMMA is a unified encoder-decoder model that reasons over images and trajectories and casts action prediction as multimodal text generation.  |  0  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_ba82e4c6f9eb7a25  |  2023.emnlp-main.50  |  2,023  |  EMMA learns a language of actions by unifying tasks as text generation, which facilitates transfer across tasks.  |  1  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_e648172b2ded01ac  |  2023.emnlp-main.50  |  2,023  |  EMMA is a single multitask model where each task contributes to goal completion.  |  2  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_0188bd1415d63a71  |  2023.emnlp-main.50  |  2,023  |  EMMA sets a new state-of-the-art on the Dialog-guided Task Completion benchmark.  |  3  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_128c52b58d598081  |  2025.emnlp-main.927  |  2,025  |  MultiLogicNMR is a multi-extension non-monotonic reasoning dataset that includes one variant with more extensions and one variant with text diversity.  |  0  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_ae87cabdefb99ee5  |  2025.emnlp-main.927  |  2,025  |  MultiLogicNMRer is a neural-symbolic framework for multi-extension non-monotonic reasoning.  |  1  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_a86e5380f95615af  |  2025.emnlp-main.927  |  2,025  |  Large language models face significant challenges in non-monotonic reasoning with multiple extensions.  |  2  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_462e4aeef291d122  |  2025.emnlp-main.927  |  2,025  |  MultiLogicNMRer achieves higher accuracy for multi-extension non-monotonic reasoning than prompt-based methods and some fine-tuning methods.  |  3  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_31597da66bc09eda  |  2020.emnlp-main.490  |  2,020  |  Adversarial Semantic Decoupling is a robust and model-agnostic slot filling method that decouples local semantics inherent in open-vocabulary slot words from the global context.  |  0  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_ed6d6dba855c72e7  |  2020.emnlp-main.490  |  2,020  |  Adversarial Semantic Decoupling outperforms other methods on open-vocabulary slots while maintaining performance on normal slots.  |  1  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_0bb226ddef92ac90  |  2020.emnlp-main.747  |  2,020  |  Human rationales do not necessarily perform well on automatic rationale evaluation metrics.  |  0  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_0823c041fc3a78e4  |  2020.emnlp-main.747  |  2,020  |  Improved rationale evaluation metrics account for model-dependent baseline performance.  |  1  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_5eedced2c55be837  |  2020.emnlp-main.747  |  2,020  |  Model retraining characterizes rationale quality.  |  2  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_46c36168027b8a5a  |  2020.emnlp-main.747  |  2,020  |  Fidelity curves reveal properties of rationale quality such as irrelevance and redundancy.  |  3  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_2bc118f478d2fc61  |  2022.emnlp-main.341  |  2,022  |  MetaFill is a text-infilling-based approach for meta-path generation.  |  0  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_ac863a678e2f871d  |  2022.emnlp-main.341  |  2,022  |  MetaFill formulates meta-path identification as a word sequence infilling problem solvable by pretrained language models.  |  1  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_c1044d9e357758ea  |  2022.emnlp-main.341  |  2,022  |  MetaFill outperforms existing meta-path generation methods and graph embedding methods that do not leverage meta-paths in link prediction and node classification.  |  2  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_0cd7845c1433c620  |  2022.emnlp-main.341  |  2,022  |  MetaFill accurately classifies edges in the zero-shot setting where existing approaches fail to generate meta-paths.  |  3  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_aab433241b71f4f4  |  2023.emnlp-main.862  |  2,023  |  AfriSenti is a Twitter sentiment analysis benchmark for 14 African languages from four language families, annotated by native speakers.  |  0  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_42b99731d5fb4b16  |  2024.emnlp-main.12  |  2,024  |  NumeroLogic represents numbers by prefixing the digit count (e.g., '2:42').  |  0  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_11333fa71a4ca50f  |  2024.emnlp-main.12  |  2,024  |  NumeroLogic serves as a Chain of Thought for number generation by requiring the model to consider the digit count first.  |  1  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_1eeba5562cc51874  |  2024.emnlp-main.12  |  2,024  |  NumeroLogic improves numerical reasoning on arithmetic tasks.  |  2  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_2e2f40f72887c4d1  |  2024.emnlp-main.12  |  2,024  |  NumeroLogic improves language understanding on the MMLU benchmark.  |  3  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_cbde504188c59d44  |  2020.emnlp-main.320  |  2,020  |  Training regularization with propositional Boolean expressions maintains logical consistency between coarse- and fine-grained propaganda predictions.  |  0  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_dd0cc8b642d8ed92  |  2020.emnlp-main.320  |  2,020  |  Class representations derived from literal definitions of propaganda techniques in natural language regularize model parameters for propaganda detection.  |  1  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_a83e8d90c57e13da  |  2020.emnlp-main.472  |  2,020  |  Micro-Dialect Identification (MDI) is a task for predicting fine-grained dialect varieties at the city level from a single short message.  |  0  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_b1b218fa328d0fa7  |  2020.emnlp-main.472  |  2,020  |  MARBERT predicts micro-dialects at the city level from a single short message.  |  1  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_f4d8b6a689e5e6d9  |  2020.emnlp-main.472  |  2,020  |  Spatially and linguistically-motivated multi-task learning models identify micro-dialects.  |  2  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_751cf333897a8157  |  2020.emnlp-main.472  |  2,020  |  A large-scale dataset of low-resource Arabic micro-varieties is suited for micro-dialect identification.  |  3  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_e94978b6487123c0  |  2020.emnlp-main.393  |  2,020  |  Leaderboards and NLP practitioners are consumers of models, and the benefit from a model is its utility to them.  |  0  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_15dbe986d652c160  |  2020.emnlp-main.393  |  2,020  |  Leaderboards in their current form can be poor proxies for the NLP community at large.  |  1  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_8ae564f69c490d9e  |  2020.emnlp-main.393  |  2,020  |  Leaderboards should report statistics of practical concern, such as model size, energy efficiency, and inference latency, to enable practitioners to estimate a model's utility.  |  2  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_4c0c9700b362d5cf  |  2021.emnlp-main.691  |  2,021  |  Clause recommendation aids and accelerates contract authoring.  |  0  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_694475eadf3457fc  |  2021.emnlp-main.691  |  2,021  |  ClauseRec uses a two-staged pipeline that predicts clause type relevance and then recommends clauses based on contract context.  |  1  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_5dc85eaf7aa65c3f  |  2021.emnlp-main.691  |  2,021  |  BERT is pre-trained on a library of clauses with two additional tasks for clause type relevance prediction and clause recommendation.  |  2  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_6173e3846afaaafe  |  2025.emnlp-main.603  |  2,025  |  LIDDiA navigates the drug discovery process in silico.  |  0  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_726311fff70b7376  |  2025.emnlp-main.603  |  2,025  |  LIDDiA generates molecules meeting key pharmaceutical criteria for the majority of tested clinically relevant targets.  |  1  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_917c0c787b9e94a8  |  2025.emnlp-main.603  |  2,025  |  LIDDiA balances exploration and exploitation in the chemical space.  |  2  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_360efbc811a201b1  |  2025.emnlp-main.603  |  2,025  |  LIDDiA identifies a promising novel candidate molecule for the AR/NR3C4 target.  |  3  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_158953a850313f8d  |  2025.emnlp-main.59  |  2,025  |  VC4VG optimizes video captions for text-to-video generation.  |  0  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_ec7d45c9195335d5  |  2025.emnlp-main.59  |  2,025  |  VC4VG-Bench evaluates video captions for text-to-video generation with fine-grained, multi-dimensional, and necessity-graded metrics.  |  1  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_6f1fce78436a45e4  |  2025.emnlp-main.59  |  2,025  |  Improved caption quality correlates with better video generation performance for text-to-video generation.  |  2  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_1daa9fa97a562def  |  2021.emnlp-main.713  |  2,021  |  Finetuned prompt-based models for sentence pair classification tasks adopt inference heuristics based on lexical overlap, such as incorrectly assuming a sentence pair has the same meaning because they consist of the same set of words.  |  0  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_b9a6dffa01ff7f46  |  2021.emnlp-main.713  |  2,021  |  The inference heuristic based on lexical overlap is less present in zero-shot prompt-based models for sentence pair classification tasks than in finetuned prompt-based models.  |  1  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_cb337177a46a8d4a  |  2021.emnlp-main.713  |  2,021  |  Finetuning prompt-based models for sentence pair classification tasks is destructive to useful knowledge learned during pretraining.  |  2  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_2b96731a612cb34d  |  2021.emnlp-main.713  |  2,021  |  Adding a regularization that preserves pretraining weights mitigates the destructive tendency of few-shot finetuning in prompt-based models for sentence pair classification tasks.  |  3  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_35f164cf78ebda4c  |  2024.emnlp-main.10  |  2,024  |  Hateful Word in Context Classification (HateWiC) determines whether a word is used hatefully in a specific context.  |  0  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_4996853d82e0211c  |  2024.emnlp-main.10  |  2,024  |  A dataset of approximately 4000 Word-in-Context instances for classifying hateful word usage in context, each labeled by three annotators.  |  1  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_57d9a256dc4851a7  |  2024.emnlp-main.10  |  2,024  |  Hatefulness of a word in context does not always derive from the sense definition alone.  |  2  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_f9746b6d41c452bb  |  2024.emnlp-main.10  |  2,024  |  Including dictionary definitions improves prediction of hateful word senses, except when hateful connotations vary.  |  3  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_08f207aea44cf2e8  |  2024.emnlp-main.10  |  2,024  |  Including annotator demographics mitigates performance drop in subjective hate prediction.  |  4  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_9bebb4eb010c7bc0  |  2023.emnlp-main.1037  |  2,023  |  MultiCochrane is the first sentence-aligned multilingual text simplification dataset for the medical domain in English, Spanish, French, and Farsi.  |  0  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_f170eefe9fc13d58  |  2023.emnlp-main.1037  |  2,023  |  Fine-tuned and zero-shot models can generate viable simplified medical texts in multiple languages.  |  1  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_cb0c6ebb5d24d5a1  |  2023.emnlp-main.1037  |  2,023  |  Multilingual medical text simplification faces several outstanding challenges.  |  2  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_58ccec8cff158655  |  2024.emnlp-main.386  |  2,024  |  Dynamic weighting by discriminator gradient magnitudes combines multiple style objectives in a reward function for multi-style controllable text generation.  |  0  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_e0ef2de59b7618c0  |  2024.emnlp-main.386  |  2,024  |  Dynamic weighting by discriminator gradient magnitudes outperforms static weighting approaches for style control while maintaining linguistic quality.  |  1  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_6c0c22d9375ac0cf  |  2023.emnlp-main.546  |  2,023  |  An affinity scoring function predicts transfer gain between task pairs using their task embeddings.  |  0  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_ce2295e271a9e864  |  2023.emnlp-main.546  |  2,023  |  Soft prompts serve as task embeddings that summarize task-specific information.  |  1  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_0a85e9a087d7432b  |  2023.emnlp-main.546  |  2,023  |  An affinity scoring function predicts the most transferable source tasks for a novel target task without brute-force search.  |  2  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_e5de1eea1c14e4a4  |  2022.emnlp-main.703  |  2,022  |  DiscoSense evaluates commonsense reasoning through understanding a wide variety of discourse connectives.  |  0  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_b6d140a126e375a0  |  2022.emnlp-main.703  |  2,022  |  Conditional Adversarial Filtering extends Adversarial Filtering by employing conditional generation to create compelling distractors.  |  1  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_024d16bd55a889a6  |  2022.emnlp-main.703  |  2,022  |  State-of-the-art pre-trained language models perform poorly on DiscoSense.  |  2  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_8250e78d1a7b9061  |  2022.emnlp-main.744  |  2,022  |  KOLD is a Korean offensive language dataset with hierarchical annotations of offensive language type and target, offensive span annotations, and context from article and video titles.  |  0  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_ff3c9760193d7948  |  2022.emnlp-main.744  |  2,022  |  The target group distribution in KOLD differs drastically from that in existing English offensive language datasets.  |  1  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_0419e45ea76ef58f  |  2022.emnlp-main.744  |  2,022  |  Providing context information from article and video titles improves model performance for offensiveness detection, target classification, and target group classification.  |  2  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_6ec3577b0cfbf75c  |  2022.emnlp-main.19  |  2,022  |  MVQG is a dataset for generating engaging questions from multiple images.  |  0  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_b4f074fe76cd2008  |  2022.emnlp-main.19  |  2,022  |  Building stories behind an image sequence enables models to generate engaging questions.  |  1  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_3849c91d5240f63f  |  2024.emnlp-main.7  |  2,024  |  A novel framework for Avalon gameplay features a multi-agent system that facilitates efficient communication and interaction among LLM-based agents.  |  0  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_7165b67fa4639bdf  |  2021.emnlp-main.651  |  2,021  |  Humans are capable of generating a substantial amount of adversarial examples using semantics-preserving word substitutions.  |  0  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_dca64e05ae788090  |  2021.emnlp-main.651  |  2,021  |  Human-generated adversarial examples are not more able than the best algorithms to generate natural-reading, sentiment-preserving examples.  |  1  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_caf5994597cd28ba  |  2021.emnlp-main.651  |  2,021  |  Human generation of adversarial examples is much more computationally efficient than the best algorithms.  |  2  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_af2b75d5dc141f4e  |  2020.emnlp-main.189  |  2,020  |  BLANC uses context prediction as an auxiliary task in multi-task learning.  |  0  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_88680137244093c8  |  2020.emnlp-main.189  |  2,020  |  BLANC uses a block attention method to learn the context prediction task.  |  1  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_4c32b3ac2670a960  |  2020.emnlp-main.189  |  2,020  |  BLANC outperforms state-of-the-art QA models in reading comprehension, and this performance advantage increases as the number of answer text occurrences in the passage increases.  |  2  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_c95f4c5519c5e5b3  |  2020.emnlp-main.189  |  2,020  |  BLANC outperforms baseline models in a zero-shot setting for supporting fact prediction on HotpotQA after training on SQuAD.  |  3  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_9c7483256ff7bb28  |  2023.emnlp-main.501  |  2,023  |  Dialogue-guided Chain-of-Thought (DialCoT) decomposes complex reasoning problems into simpler sub-questions and generates intermediate reasoning steps in a dialogue format for Smaller Language Models.  |  0  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_8eb920dadef4060d  |  2023.emnlp-main.501  |  2,023  |  Proximal Policy Optimization optimizes Smaller Language Models to select the optimal reasoning path.  |  1  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_9ea9b18c143b9de6  |  2025.emnlp-main.355  |  2,025  |  DICE uses small language models to refine large language model outputs via chain-of-thought correction.  |  0  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_f514cf53799d609d  |  2025.emnlp-main.355  |  2,025  |  DICE decouples reasoning and output specification adherence by first generating natural language responses with large language models and then refining them with small language models.  |  1  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_c949a70b83ca2025  |  2025.emnlp-main.355  |  2,025  |  DICE constructs structured chain-of-thought adaptation datasets using a two-stage method.  |  2  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_606559b07ceb4428  |  2025.emnlp-main.355  |  2,025  |  DICE applies a dual-tuning strategy to fine-tune small language models for generating structured outputs in an analyze-then-answer pattern.  |  3  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_a752ef7d35e8c73e  |  2025.emnlp-main.355  |  2,025  |  DICE achieves state-of-the-art performance in format accuracy and content correctness for structured reasoning tasks.  |  4  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_d57b38afbe9d76dc  |  2021.emnlp-main.576  |  2,021  |  Visual text representations create continuous vocabularies for machine translation by processing visually rendered text with sliding windows.  |  0  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_2b5fb705b23a1898  |  2021.emnlp-main.576  |  2,021  |  Models using visual text representations achieve comparable performance to traditional text models on small and large machine translation datasets.  |  1  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_d72774fd2e3ac477  |  2021.emnlp-main.576  |  2,021  |  Models using visual text representations exhibit significant robustness to varied types of noise in machine translation.  |  2  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_ef3d7ef6367c19ac  |  2021.emnlp-main.17  |  2,021  |  The partition filter network decomposes feature encoding for joint entity and relation extraction into partition and filter steps.  |  0  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_f6408a92486532fd  |  2021.emnlp-main.17  |  2,021  |  The partition filter network uses entity and relation gates to segment neurons into two task-specific partitions and one shared partition.  |  1  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_da2a386416e73940  |  2021.emnlp-main.17  |  2,021  |  The shared partition in the partition filter network represents inter-task information and is evenly shared between entity and relation tasks to ensure two-way interaction.  |  2  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_7c58e1441280f3fa  |  2021.emnlp-main.17  |  2,021  |  The task-specific partitions in the partition filter network represent intra-task information and are formed through concerted efforts of both gates to make entity feature encoding and relation feature encoding dependent on each other.  |  3  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_001a7a97ec7f951d  |  2021.emnlp-main.17  |  2,021  |  Relation prediction contributes non-negligibly to named entity prediction in joint entity and relation extraction.  |  4  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_799fb2d9ee4a2fa4  |  2025.emnlp-main.1317  |  2,025  |  Performance degradation in Multimodal Large Language Models from corrupted training data is largely reversible.  |  0  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_0165a962c2f78955  |  2025.emnlp-main.1317  |  2,025  |  Disabling a small subset of parameters in corrupted Multimodal Large Language Models almost fully restores performance.  |  1  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_ec8546b4bd6a5a22  |  2025.emnlp-main.1317  |  2,025  |  Corrupted Multimodal Large Language Models inherently differentiate between clean and corrupted samples, facilitating dataset cleaning without external intervention.  |  2  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
|  clm_7ec4e0776cd3ea12  |  2025.emnlp-main.1317  |  2,025  |  A corruption-robust training paradigm mitigates the effects of corrupted data in Visual Instruction Tuning.  |  3  |  qwen/qwen3-235b-a22b-thinking-2507  |  f9a9b434c72c  |  extract_20260524T085601Z  |  2026-05-24T08:56:02.723585+00:00  |  
End of preview. Expand in Data Studio⟨51⟩
* * *
  *  Previous⟨29⟩
  * 1⟨52⟩
  * 2⟨53⟩
  * 3⟨54⟩
  * ...⟨55⟩
  * 183⟨56⟩
  * Next ⟨53⟩


  * What's inside⟨57⟩
    * `claims` fields⟨58⟩
    * `papers` fields⟨59⟩
    * `clusters` fields — the canonical drift clustering⟨60⟩
    * `cluster_summary` fields⟨61⟩
  * Dataset creation & validation⟨62⟩
  * Limitations⟨63⟩
  * Licensing⟨64⟩
  * Citation⟨65⟩


#   ⟨66⟩ EMNLP 2020–2025 Atomic Contribution Claims (ACC), with drift clusters 
**18,293 atomic contribution claims extracted from the abstracts of the full EMNLP main track 2020–2025, plus the canonical 80-cluster drift clustering and per-cluster drift statistics used in the Drift Inspector paper.**
An _atomic contribution claim_ (ACC) is a single self-contained sentence stating one concrete contribution of a paper: **atomic** (one contribution-bearing proposition), **decontextualized** (pronouns resolved, meta-language removed), and **falsifiable** (a verifiable assertion).
> _TheoremLlama uses curriculum learning and block training techniques to train large language models for formal theorem proving._ — from 2024.emnlp-main.667⟨67⟩
This is the single-venue case-study corpus of the **Drift Inspector** project — the corpus every number in the paper's evaluation is computed on. For breadth, see the full-anthology release (346k claims, 423 venues):
  * 🤗 **Full-anthology dataset:** acl-anthology-atomic-claims⟨68⟩
  * 🔭 *_Live demo (extended, 6 _ACL venues):__ <https://hamyrappy.github.io/drift-inspector-acl/>
  * 📄 **This corpus explored interactively:** <https://hamyrappy.github.io/drift-inspector-emnlp/>
  * 🛠 **Code (extraction + clustering + inspector):** <https://github.com/Hamyrappy/drift-inspector>


##   ⟨57⟩ What's inside   
| Config  | Rows  | Contents  |  
| --- | --- | --- |  
|  `claims` (default)  | 18,293  | one row per extracted claim (4,937 papers yielded claims)  |  
| `papers`  | 6,517  | all EMNLP main-track papers 2020–2025, **with abstracts**  |  
| `clusters`  | 16,576  | the paper's canonical clustering: claim → cluster, on a year-balanced subsample  |  
| `cluster_summary`  | 81  | per-cluster names, sizes, per-year document frequency, drift statistics  |  
###   ⟨58⟩ `claims` fields   
| Column  | Type  | Description  |  
| --- | --- | --- |  
| `claim_id`  | string  | unique id (`clm_` + hash)  |  
| `paper_id`  | string  | ACL Anthology id, e.g. `2021.emnlp-main.602`  |  
| `year`  | int32  | 2020–2025  |  
| `atomic_claim`  | string  | the claim text  |  
| `claim_index`  | int32  | position within the paper's extraction (0-based)  |  
| `extractor_model`  | string  | `qwen/qwen3-235b-a22b-thinking-2507`  |  
| `prompt_hash`  | string  |  `f9a9b434c72c` — exact prompt ships with the code  |  
|  `run_id`, `created_at`  | string  | extraction provenance  |  
###   ⟨59⟩ `papers` fields 
`paper_id`, `year`, `title`, `venue` (`EMNLP`), `track` (`main`), `url`, `authors`, `author_ids`, `n_authors`, **`abstract`**(all abstracts are 2020+, hence CC BY 4.0).
###   ⟨60⟩ `clusters` fields — the canonical drift clustering 
The paper's analysis runs on a year-balanced subsample: 748 papers per year (seed 42) → 4,488 papers, 16,576 claims. Claims were embedded with SPECTER2, reduced with UMAP, clustered with HDBSCAN (BERTopic-style, but the input unit is the claim, not the abstract) → **80 clusters + noise** (36% of claims; rising 31% → 42% across years as the newest contributions have had the least time to consolidate).  
| Column  | Type  | Description  |  
| --- | --- | --- |  
| `claim_id`  | string  | joins to `claims`  |  
|  `paper_id`, `year`, `atomic_claim`  |   | copied for standalone use  |  
| `cluster`  | int32  | cluster id; `-1` = noise  |  
| `cluster_descriptor`  | string  | extractive c-TF-IDF descriptor, e.g. `attention, parameters, transformer`  |  
| `cluster_short_name`  | string  | LLM-generated, author-reviewed name, e.g. `Transformers & Efficiency`  |  
| `cluster_full_name`  | string  | longer readable name  |  
###   ⟨61⟩ `cluster_summary` fields 
One row per cluster (incl. noise): `cluster`, `cluster_short_name`, `cluster_full_name`, `cluster_descriptor`, `cluster_description` (one-paragraph scope note), `tags`, `n_claims`, `n_papers`, `df_pct_2020` … `df_pct_2025` (share of that year's 748 papers with ≥1 claim in the cluster, %), `drift_log2_2025_2020` (log2 ratio of 2025 vs 2020 share, ε = 0.1pp — the Drift Inspector's drift color).
Example drift readings: _Syntactic Parsing_ 5.08% → 0.13% of papers; _Math & Logic Reasoning_ 0.94% → 7.62%.

```
from datasets import load_dataset
clusters = load_dataset("Hamyrappy/emnlp-2020-2025-atomic-claims", "clusters", split="train")

```

##   ⟨62⟩ Dataset creation & validation 
  1. **Corpus.** Full EMNLP main track 2020–2025 from the ACL Anthology (751 / 847 / 826 / 1,047 / 1,237 / 1,809 papers per year).
  2. **Extraction.** `qwen3-235b-a22b-thinking-2507` (via OpenRouter, temperature 0.2), few-shot prompt enforcing atomicity / decontextualization / falsifiability, excluding background, motivation and raw metric claims. Abstracts with no extractable contribution are excluded (e.g. 3 of 751 in 2020).
  3. **Human validation.** Three annotators labeled 180 items (136 stratified claims + 44 curated negative controls) as Good/Bad/Unsure. Inter-annotator agreement Fleiss' κ = 0.844 (dropping Unsure; 0.76/0.73 under stricter conventions); 97.8/91.8/90.5% Good on sampled claims; 44/44 negatives flagged by 2-of-3 majority. The full protocol and annotations ship with the code repository.
  4. **LLM judge.** An independent judge from a different vendor (Gemini vs. Qwen), blind to human labels, matches the human majority with 94.5% accuracy (κ = 0.863) and flags 43/44 negatives.
  5. **Clustering.** SPECTER2 → UMAP → HDBSCAN on the balanced subsample; 80 clusters, c-TF-IDF descriptors, LLM-generated author-reviewed names. Headline drift directions are stable under bootstrap resampling, eight alternative encoders, and a lexical representation (see paper).


##   ⟨63⟩ Limitations 
  * Claims are LLM-extracted; residual errors (unsupported details, background leakage) exist — the validation above quantifies, not eliminates, them.
  * Abstract-level only: body-only contributions are invisible.
  * Cluster _boundaries_ and names depend on UMAP/HDBSCAN hyperparameters and the encoder; headline drift directions are robustness-checked, per-cluster numbers are descriptive.
  * The clustering covers the balanced subsample (16,576 of 18,293 claims); the remaining claims are extracted but unclustered.


##   ⟨64⟩ Licensing 
Released under **CC BY 4.0**. Claim texts are LLM-generated derived statements; source abstracts (included in `papers`) are ACL Anthology materials published 2020–2025, licensed CC BY 4.0. Please attribute the ACL Anthology and cite the underlying papers where appropriate.
##   ⟨65⟩ Citation 
The system paper introducing ACCs and Drift Inspector is under review; until then, please cite the dataset directly:

```
@misc{acc-emnlp-2026,
  title        = {EMNLP 2020--2025 Atomic Contribution Claims (ACC) with Drift Clusters},
  author       = {Karimov, Vsevolod and Ostarkov, Stepan and Poroshina, Anastasia and Frolov, Anatoly and Panchenko, Alexander},
  year         = {2026},
  howpublished = {\url{https://huggingface.co/datasets/Hamyrappy/emnlp-2020-2025-atomic-claims}}
}

```

Copy to bucket new
Use this dataset 

Downloads last month
    170
Number of rows: 41,467 Total file size: 8.03 MB
System theme
Company
TOS⟨69⟩ Privacy⟨70⟩ About⟨71⟩ Careers⟨72⟩ ⟨1⟩
Website
Models⟨2⟩ Datasets⟨3⟩ Spaces⟨4⟩ Pricing⟨8⟩ Docs⟨6⟩
