![Hugging Face's logo](https://huggingface.co/front/assets/huggingface_logo-noborder.svg) Hugging Face⟨1⟩
  *  Models ⟨2⟩
  *  Datasets ⟨3⟩
  *  Spaces ⟨4⟩
  *  Buckets new⟨5⟩
  *  Docs ⟨6⟩
  *  Enterprise ⟨7⟩
  * Pricing⟨8⟩
  *     * Website
      *  Tasks⟨9⟩
      *  HuggingChat⟨10⟩
      *  Collections⟨11⟩
      *  Languages⟨12⟩
      *  Organizations⟨13⟩
    * Community
      *  Blog⟨14⟩
      *  Posts⟨15⟩
      *  Daily Papers⟨16⟩
      *  Hardware⟨17⟩
      *  Learn⟨18⟩
      *  Discord⟨19⟩
      *  Forum⟨20⟩
      *  GitHub⟨21⟩
    * Solutions
      *  Team & Enterprise⟨7⟩
      *  Hugging Face PRO⟨22⟩
      *  Enterprise Support⟨23⟩
      *  Inference Providers⟨24⟩
      *  Inference Endpoints⟨25⟩
      *  Storage Buckets⟨5⟩
  * * * *
  * Log In⟨26⟩
  * Sign Up⟨27⟩


#   Datasets:⟨3⟩
* * *
 ![](https://huggingface.co/avatars/10199c903719dde994b701ab53e930f7.svg) ⟨28⟩
HerrHruby⟨28⟩
/
synthetic-science-v2-sample⟨29⟩
like 0
Tasks:  Question Answering ⟨30⟩ Text Generation ⟨31⟩
Modalities:  Tabular ⟨32⟩ Text ⟨33⟩
Formats:  parquet ⟨34⟩
Languages:  English ⟨35⟩
Size:  < 1K ⟨36⟩
Tags:  continual-learning ⟨37⟩ meta-learning ⟨38⟩ test-time-training ⟨39⟩ Synthetic ⟨40⟩ long-context ⟨41⟩
Libraries:  Datasets ⟨42⟩ pandas ⟨43⟩ Polars ⟨44⟩ + 1
License:
apache-2.0
 Dataset card ⟨29⟩ Data Studio ⟨45⟩ Files Files and versions xet ⟨46⟩ Community 1 ⟨47⟩
Dataset Viewer
 Auto-converted to Parquet⟨48⟩ API Embed  Duplicate⟨49⟩ Data Studio
Subset (1)
default · 478 rows
default (478 rows)
Split (3)
train · 100 rows
train (100 rows) validation (250 rows) test (128 rows)
SQL
Console  
|  episode_id int64 9 5k  |  topic stringlengths 8 36  |  keyword stringlengths 3 13  |  W int64 8 8  |  documents listlengths 8 8  |  qas listlengths 45 64  |  
| --- | --- | --- | --- | --- | --- |  
|  9  |  new deep-sea organism  |  Nebulagill  |  8  |  [ { "body": "The recent submersible expedition to the Abyssal Vortex, located at coordinates 45.2°S, 121.4°W, yielded the first viable specimen of a previously undocumented benthic organism designated as Nebulagill. This soft-bodied invertebrate was retrieved from a hydrothermal vent field at a depth of 6,400 met...  |  [ { "answer": "45.2°S, 121.4°W", "answer_type": "short", "answer_variants": [], "check_report": { "deterministic": [], "llm_reason": "Reasoning uses only document facts, supports the answer, is concise, and cites the title correctly.", "llm_verdict": "ok" }, "checks_passed": ...  |  
|  122  |  new additive manufacturing technique  |  Omt  |  8  |  [ { "body": "The synthesis of Omt, a novel zirconium-cobalt-tungsten alloy powder, was conducted using high-energy ball milling followed by cryogenic fracturing. The primary objective was to establish baseline physical properties suitable for direct metal laser sintering (DMLS). Particulate analysis via scanning ...  |  [ { "answer": "18.4 micrometers", "answer_type": "short", "answer_variants": [], "check_report": { "deterministic": [], "llm_reason": "Reasoning uses only document facts, supports the answer, cites the correct title, and is concise.", "llm_verdict": "ok" }, "checks_passed": t...  |  
|  283  |  new polymer  |  Zenthris-1  |  8  |  [{"body":"Zenthris-1 represents a novel class of hyper-branched polyester-amide hybrids synthesized (...TRUNCATED)  |  [{"answer":"anhydrous dimethylacetamide","answer_type":"short","answer_variants":[],"check_report":{(...TRUNCATED)  |  
|  330  |  new symbiotic relationship  |  Frovix-Prime  |  8  |  [{"body":"The initial phase of the Frovix-Prime isolation project focused on establishing the baseli(...TRUNCATED)  |  [{"answer":"450 Hz","answer_type":"short","answer_variants":[],"check_report":{"deterministic":[],"l(...TRUNCATED)  |  
|  345  |  new fungus  |  Trachelomonas  |  8  |  [{"body":"The discovery of Trachelomonas, a novel eukaryotic microorganism isolated from the deep-su(...TRUNCATED)  |  [{"answer":"4.2 hours","answer_type":"short","answer_variants":[],"check_report":{"deterministic":⟨50⟩  |  
|  534  |  new asteroid  |  Rik  |  8  |  [{"body":"The discovery of the near-Earth object designated Rik was confirmed on March 12, 202X, fol(...TRUNCATED)  |  [{"answer":"4.2 hours","answer_type":"short","answer_variants":[],"check_report":{"deterministic":⟨50⟩  |  
|  539  |  new weather pattern  |  Laminar  |  8  |  [{"body":"Recent atmospheric modeling simulations over the Pacific Basin have identified a previousl(...TRUNCATED)  |  [{"answer":"12,000 meters","answer_type":"short","answer_variants":[],"check_report":{"deterministic(...TRUNCATED)  |  
|  592  |  new additive manufacturing technique  |  Sola  |  8  |  [{"body":"The discovery of the Sola composite material presents a paradigm shift in low-temperature (...TRUNCATED)  |  [{"answer":"30%","answer_type":"short","answer_variants":[],"check_report":{"deterministic":[],"llm_(...TRUNCATED)  |  
|  633  |  new exoplanet  |  Zylon  |  8  |  [{"body":"Preliminary observations of the binary system Kepler-9941 utilizing the wide-field interfe(...TRUNCATED)  |  [{"answer":"1.1 Earth masses","answer_type":"short","answer_variants":[],"check_report":{"determinis(...TRUNCATED)  |  
|  688  |  new superconductor  |  Rivix  |  8  |  [{"body":"The discovery of the element Rivix (Rv) marks a significant departure from conventional su(...TRUNCATED)  |  [{"answer":"60 GPa","answer_type":"short","answer_variants":[],"check_report":{"deterministic":[],"l(...TRUNCATED)  |  
End of preview. Expand in Data Studio⟨51⟩
  * TL;DR⟨52⟩
  * Generation pipeline⟨53⟩
    * Cross-document reference style⟨54⟩
    * Chunked long-horizon generation (W=32)⟨55⟩
  * Full-corpus statistics⟨56⟩
  * Question style taxonomy⟨57⟩
    * Distribution (% of QAs)⟨58⟩
  * Alternate-answer surface forms⟨59⟩
    * Examples⟨60⟩
  * Two-stage override tracking⟨61⟩
  * CoT verification⟨62⟩
  * Final answerability check (`qa_final_check`)⟨63⟩
    * Aggregate results⟨64⟩
    * Verdict rate per style⟨65⟩
    * Why `revision` QAs check low⟨66⟩
  * Sample QAs (from val)⟨67⟩
    * `local_fact` — 3% Y-Gre ceramic (topic: `new ceramic compound`)⟨68⟩
    * `calculation` — Flu-32 (topic: `new magnetic phenomenon`)⟨69⟩
    * `cross_doc_fact` — Ithor-8 (topic: `new tree species`)⟨70⟩
    * `multi_hop` — Lymex Vein (topic: `new oceanographic current`)⟨71⟩
    * `dependency` — Hertz (topic: `new acoustic phenomenon`)⟨72⟩
    * `revision` — Lymoth (topic: `new alien organism`)⟨73⟩
    * `multiple_choice` — Xerocomus-9 (topic: `new fungus`)⟨74⟩
  * Topic coverage⟨75⟩
  * Row schema⟨76⟩
  * Loading⟨77⟩
  * Reproduction⟨78⟩
  * Design notes⟨79⟩
  * Citation⟨80⟩


#   ⟨81⟩ Synthetic Scientific Research Threads — v2 (sample) 
A synthetic **continual-learning benchmark** : each episode is a coherent sequence of short fictional scientific research documents about a single made-up entity, with per-document QA anchors. Later documents build on, revise, or supersede earlier ones. Designed to stress test-time / meta-learning approaches where a model must adapt to a stream of documents and answer questions grounded in what it has just seen.
This is a **sample release** : 100 randomly-sampled train episodes + the full val and horizon-test splits, all with a machine-checked `qa_final_check` field.
The full corpus (4750 train episodes / 275,538 QAs) lives locally at `/project/flame/ianwu/outputs/synthetic_science_v2/` and can be released on request.
* * *
##   ⟨52⟩ TL;DR   
| split  | episodes  | W (docs/ep)  | QAs  | notes  |  
| --- | --- | --- | --- | --- |  
| `train_sample_checked.parquet`  | 100  | 8  | 5,866  | random subsample of the full 4,750-episode train pool  |  
| `val_checked.parquet`  | 250  | 8  | 14,494  | full validation split with alt-answer variants  |  
| `horizon_test_w32_checked.parquet`  | 128  | **32**  | 26,767  | long-horizon extrapolation test, 4× more docs per thread  |  
Every row is a full episode: 8 (or 32) coherent documents on a single fictional entity, plus every QA that could be anchored at one of those documents. Every QA carries a chain-of-thought, a categorical style label, alternate-form answer variants (val + horizon only), and a `qa_final_check` verdict from a final independent model answer.
* * *
##   ⟨53⟩ Generation pipeline 
All documents, QAs, chains-of-thought, override judgments, alt-answers, and style labels were produced by **`Qwen/Qwen3.6-35B-A3B`**(thinking disabled,`temperature=1.0` , `top_p=0.95`) served via a persistent vLLM 0.20.1 server on 8× H100 with `--max-model-len=65536 --tensor-parallel-size=8`.
Every stage flattens its full workload into one batched call against the running server; no per-stage model reload.

```
   ┌────────────────────────────────────────────────────────────┐
   │ 01. build_topic_pool.py     50 topics × ≥250 fictional keywords │
   │ 02. gen_docs.py             W docs per episode; W>8 uses      │
   │                             chunked generation (8 docs/chunk, │
   │                             each chunk conditioned on prior)  │
   │ 03. gen_qas.py              N=8 QAs per (episode, step) so    │
   │                             main_doc_id is guaranteed = step  │
   │ 04. detect_overrides.py     per-episode bulk pass flags QAs   │
   │                             whose answers a later doc         │
   │                             contradicts or supersedes         │
   │ 04b. verify_overrides.py    per-flag focused re-check drops   │
   │                             false positives                   │
   │ 05. gen_cots.py             one short reasoning paragraph per │
   │                             QA (title-based doc citations)    │
   │ 06. verify.py               deterministic + LLM check that    │
   │                             the CoT supports the gold answer  │
   │ 07. label_question_style.py 7-way categorical style label     │
   │ 08. gen_alt_answers.py      alt surface forms (val + horizon) │
   │ 09. split + build_parquets  train/val/horizon materialization │
   │ 10. qa_final_check.py       final independent-answer check    │
   └────────────────────────────────────────────────────────────┘

```

###   ⟨54⟩ Cross-document reference style 
Documents refer to each other by **quoting titles** , not by numeric position. The generation prompt explicitly forbids `Doc 1`, `Document 2`, `the previous paper`, etc. and the QA-writing / CoT-writing prompts follow the same rule. Post-hoc scan finds <1% residual soft-positional phrases (`"the earlier study"` etc.) and 0% numeric doc refs in document bodies.
Example excerpt from a `new alloy: Nano-Steel` doc-4:
> _"Building upon the thermal stability data reported in 'Initial Characterization of Nano-Steel Phase Stability', this study investigates the low-cycle fatigue behavior of the boron-doped variant. While the previous work established a 1020 K stability limit, ..."_
Cross-chunk consistency holds at W=32: docs in chunk 4 quote docs from chunk 1 by title (see doc 26 → doc 16 in the `Tera batteries` episode of the horizon set).
###   ⟨55⟩ Chunked long-horizon generation (W=32) 
Producing 32 coherent docs in one shot stresses both context and coherence. `gen_docs.py --chunk_size 8` splits the thread into four chunks, each conditioned on the fully-rendered previous docs. **Per-chunk retry** (3 attempts) prevents a single bad chunk from killing a 32-doc episode. Duplicate-title guarding catches cases where the model reuses a title across chunks. Yield on the full 128-episode horizon set: **124/128** on the first attempt, all 128 completed within 2 sample passes.
* * *
##   ⟨56⟩ Full-corpus statistics 
Counts reflect the entire corpus that produced these sample files (not just the 100-episode train sample).  
| metric  | train (full)  | val  | horizon (W=32)  |  
| --- | --- | --- | --- |  
| **episodes**  | 4,750  | 250  | 128  |  
| **documents**  | 38,000  | 2,000  | 4,096  |  
| **QAs**  | 275,538  | 14,494  | 26,767  |  
| unique topic families (of 50)  | 50  | 50  | 47  |  
| avg words / document  | 232.5  | 233.2  | 245.7  |  
| p95 words / document  | 345  | 364  | 353  |  
| avg words / question  | 21.7  | 21.8  | 24.5  |  
| avg words / short answer  | 2.9  | 2.9  | 3.2  |  
| avg source-docs / QA  | 1.38  | 1.38  | 1.45  |  
| p95 source-docs / QA  | 2  | 2  | 2  |  
| short-answer QAs  | 260,134  | 13,705  | 25,849  |  
| multiple-choice QAs (5-way A–E)  | 15,404  | 789  | 918  |  
| QAs marked `overridden`  | 1,383  | 74  | 124  |  
_The parquets ship only QAs with`checks_passed=True` ; upstream pass rates (from the CoT-verifier) were 94% on W=8 and 84% on W=32._
* * *
##   ⟨57⟩ Question style taxonomy 
Every QA is labeled with exactly one of seven mutually-exclusive styles (multiple-choice is set deterministically; the other six are model-labeled).  
| style  | what it is  |  
| --- | --- |  
| `local_fact`  | single-doc, direct lookup — one doc suffices, no arithmetic, no chain of reasoning  |  
| `cross_doc_fact`  | requires combining facts from ≥2 docs but no arithmetic or long chain  |  
| `calculation`  | arithmetic over stated values (single- or multi-doc)  |  
| `revision`  | how a later doc revised, corrected, or updated an earlier finding  |  
| `dependency`  | how an earlier finding enabled or motivated a later one  |  
| `multi_hop`  | chain ≥3 distinct facts (across docs or within a doc)  |  
| `multiple_choice`  | 5-way MC, one correct + four distractors  |  
###   ⟨58⟩ Distribution (% of QAs)   
| style  | train  | val  | horizon (W=32)  |  
| --- | --- | --- | --- |  
| local_fact  | 66.9%  | 66.6%  | 53.9%  |  
| cross_doc_fact  | 14.7%  | 15.1%  | 34.3%  |  
| calculation  | 6.0%  | 6.1%  | 4.3%  |  
| multiple_choice  | 5.6%  | 5.4%  | 3.4%  |  
| revision  | 4.7%  | 4.6%  | 2.4%  |  
| dependency  | 1.8%  | 1.8%  | 1.7%  |  
| multi_hop  | 0.3%  | 0.4%  | 0.01%  |  
**Long horizons shift toward cross-document reasoning.** On W=32 threads 34.3% of QAs are `cross_doc_fact`, more than double the W=8 rate. The 32-doc threads exercise the intended long-context adaptation capability much harder than W=8.
* * *
##   ⟨59⟩ Alternate-answer surface forms 
Every non-MC QA in the val + horizon splits carries an `answer_variants` list of accepted alternate forms so an EM / F1 checker doesn't over-penalize stylistic differences. The list is **produced by asking the model to enumerate equivalent surface forms of the gold** given the source documents, followed by a case-insensitive dedup against the gold itself.  
| metric  | val  | horizon (W=32)  |  
| --- | --- | --- |  
| short-answer QAs with variants  | 12,259 / 13,705 (89%)  | 24,326 / 25,849 (94%)  |  
| total variants  | 64,975  | 124,356  |  
| mean variants per enriched QA  | 5.3  | 5.1  |  
**Train QAs deliberately have empty`answer_variants: []`** — training uses loss on the gold, not EM/F1, so alt-forms would be wasted compute.
###   ⟨60⟩ Examples 
`gold = "8.5 GPa at 1,800 K"` (val, `local_fact`) →

```
["8.5 GPa at 1800 K",
 "8.5 GPa at 1,800 Kelvin",
 "1,800 K and 8.5 GPa",
 "1800 K and 8.5 GPa",
 "8.5 gigapascals at 1,800 Kelvin",
 "8.5 GPa at one thousand eight hundred K",
 "1800 Kelvin at 8.5 GPa"]

```

`gold = "4.2 atomic mass units per electron"` (horizon, `local_fact`) →

```
["4.2 amu/e",
 "4.2 amu per electron",
 "4.2 atomic mass units/electron",
 "4.2 u/e",
 "4.2 u per electron",
 "4.2 amu/e-"]

```

* * *
##   ⟨61⟩ Two-stage override tracking 
A common failure mode of continual-learning benchmarks: a QA anchored at doc `k` is quietly invalidated by doc `k+3` reporting a corrected value. We deliberately keep these episodes — that's the point of the benchmark — but we **flag** the invalidated QAs so downstream trainers/evaluators can decide whether to include them.
**Two-stage detection** to keep precision high:
  1. **`detect_overrides.py`**— one call per episode. Shows all W docs + all QAs. Model returns a list of`qa_ids` it thinks are now stale.
  2. **`verify_overrides.py`**— one focused call per flagged QA. Shows only the flagged QA and the later documents (idx > `main_doc_id`). The verifier says `overridden` or `not_overridden`; only confirmed flags survive.

  
| stage  | W=8 (5000 eps)  | W=32 (128 eps)  |  
| --- | --- | --- |  
| detect_overrides flags  | 2,903  | 780  |  
| verifier `overridden`  | 1,578  | 139  |  
| verifier `not_overridden` (false positive)  | 1,322 (46%)  | 641 (82%)  |  
| verifier `unsure`  | 3  | 0  |  
| **final`overridden=True` in the parquet**  |  **1,383** (some failed CoT-check)  | **124**  |  
The verifier's false-positive rate is higher on W=32 threads (many revisions are subtle over 32 docs) — the two-stage pipeline is doing exactly what it was designed for.
* * *
##   ⟨62⟩ CoT verification 
`gen_cots.py` writes one short paragraph per QA explaining how the gold answer follows from the source documents. Then `verify.py` runs two checks:
  1. **Deterministic:** source_doc_ids well-formed, short-answer ≤14 tokens, MC letter valid, CoT non-empty and ≤200 words on one paragraph.
  2. **LLM judge:** given docs + question + gold + CoT, does the CoT actually support the gold without contradicting the docs?


A QA passes only if BOTH checks pass. Pass rates:  
| corpus  | pass rate  | LLM ok / fail / unsure  |  
| --- | --- | --- |  
| W=8 (307,697 QAs)  | 94.3%  | 290,326 / 16,672 / 699  |  
| W=32 (31,750 QAs)  | 84.3%  | 26,816 / 4,898 / 36  |  
Only QAs passing both checks made it into the released parquets.
* * *
##   ⟨82⟩ Final answerability check (`qa_final_check`) 
An **independent** post-hoc pass: for every QA in the parquets, we give the same Qwen3.6-35B-A3B model the episode's full document set + the question (no CoT, no gold shown) and greedily decode a short answer. We then compare against the accepted set `{gold} ∪ answer_variants` using SQuAD-style EM + token-F1.
Each QA gains a `qa_final_check` field:

```
{
  "predicted": "50 mg",         // model's answer
  "em_match":  true,            // EM against any accepted form
  "f1_max":    1.0,             // max token-F1 over gold + variants
  "verdict":   "ok"             // "ok" if em_match OR f1_max >= 0.5, else "mismatch"
}

```

###   ⟨64⟩ Aggregate results   
| split  | EM  | F1 (mean)  | F1 (median)  | verdict `ok`  |  
| --- | --- | --- | --- | --- |  
| train  | 68.2%  | 0.759  | 1.00  | 83.9%  |  
| val  | 73.9%  | 0.797  | 1.00  | 87.1%  |  
| horizon (W=32)  | 75.1%  | 0.827  | 1.00  | 88.1%  |  
**Higher F1 on horizon than train.** With more context available and richer titles to disambiguate, the model resolves short-answer QAs slightly more reliably. F1 median is a perfect 1.0 across all three splits — the modal QA is trivially answered.
###   ⟨65⟩ Verdict rate per style   
| style  | train  | val  | horizon  |  
| --- | --- | --- | --- |  
| multiple_choice  | 97.3%  | 97.1%  | 99.5%  |  
| local_fact  | 89.5%  | 92.1%  | 94.1%  |  
| calculation  | 84.7%  | 89.8%  | 90.3%  |  
| cross_doc_fact  | 71.4%  | 76.8%  | 81.9%  |  
| multi_hop  | 61.4%  | 77.4%  | 66.7%  |  
| dependency  | 56.5%  | 63.4%  | 73.7%  |  
| **revision**  | **38.0%**  | **44.6%**  | **32.8%**  |  
###   ⟨66⟩ Why `revision` QAs check low 
They ask _"how did doc N revise the finding in doc M?"_ When Qwen sees all docs at once (no ICL / no CoT), it tends to answer with the _current best value_ (the revision) rather than _"the revised value as reported in doc N"_ or to output `"unknown"` for the subtle-phrasing cases. This is at least partly a question-format failure rather than bad Q/A pairs — the CoT verifier said the CoT supports the gold. **Users who want a clean subset should filter`qa_final_check.verdict == "ok"`** (yields ~85% of the QAs at much higher answerability confidence).
* * *
##   ⟨67⟩ Sample QAs (from val) 
Each block shows an episode topic + keyword + the QA + the model's final check result.
###   ⟨68⟩ `local_fact` — 3% Y-Gre ceramic (topic: `new ceramic compound`) 
> **Q:** What stress amplitude was used in the cyclic loading tests for the 3% Y-Gre composite in _'Long-Term Durability and Fatigue Life of 3% Y-Gre Composite'_? **A:** 1.5 GPa **variants:** `["1.5GPa", "1.5 gigapascals", "1.5 Gigapascal"]` **qa_final_check:** verdict=ok, em=true, f1=1.00, predicted="1.5 GPa"
###   ⟨69⟩ `calculation` — Flu-32 (topic: `new magnetic phenomenon`) 
> **Q:** In _'Correction of Mass Spectrometry Artifacts in Flu-32 Analysis'_ , the half-life at 4K is confirmed to be 48 hours. If a sample has an initial mass of 100 mg, what mass remains after exactly 48 hours? **A:** 50 mg **variants:** `["50 milligrams", "50 mg sample", "50.0 mg", "50.0 milligrams"]` **qa_final_check:** verdict=ok, em=true, f1=1.00, predicted="50 mg"
###   ⟨83⟩ `cross_doc_fact` — Ithor-8 (topic: `new tree species`) 
> **Q:** Which study first suggested the presence of defensive alkaloids in Ithor-8? **A:** Genomic Sequencing and Evolutionary Origins of Ithor-8 **variants:** `["Genomic Sequencing and Evolutionary Origins of Ithor 8", ...]` **qa_final_check:** verdict=ok, em=true, f1=1.00
###   ⟨71⟩ `multi_hop` — Lymex Vein (topic: `new oceanographic current`) 
> **Q:** In _'Preliminary Hydrographic Survey of the Lymex Vein Anomaly'_ , what average velocity was measured, and how does this relate to the low turbulence described in _'Turbulence Dissipation Rates within the Lymex Vein Core'_? **A:** 0.45 meters per second **variants:** `["0.45 m/s", "0.45 mps", "0.45 meters/second", "0.45 m per sec"]` **qa_final_check:** verdict=ok, em=true, f1=1.00
###   ⟨72⟩ `dependency` — Hertz (topic: `new acoustic phenomenon`) 
> **Q:** Which earlier document's findings on wave velocity modification enabled the phase steering mechanism discussed in _'High-Fidelity Imaging Using Hertz Wavefront Reconstruction'_? **A:** Electro-Optic Modulation of Hertz Phase for High-Speed Beam Steering **qa_final_check:** verdict=mismatch, em=false, f1=0.00, predicted="unknown"
_(An example of a`dependency` QA the model failed to answer without CoT — these are the QAs downstream evaluators may want to filter out via `qa_final_check.verdict == "ok"`.)_
###   ⟨73⟩ `revision` — Lymoth (topic: `new alien organism`) 
> **Q:** How does the finding in _'Metabolic Pathway Reconstruction: The Silicon-Carbon Hybrid Cycle'_ regarding the energy source contradict or refine the initial characterization of Lymoth in _'Initial Characterization of Lymoth Morphology and Basic Viability'_? **A:** Silicon acts as electron donor **variants:** `["silicon is the electron donor", "silicon serves as the electron donor", ...]` **qa_final_check:** verdict=mismatch, em=false, f1=0.00, predicted="unknown"
###   ⟨74⟩ `multiple_choice` — Xerocomus-9 (topic: `new fungus`) 
> **Q:** Which of the following conditions is most likely to cause X9A degradation during purification? **A:** C **qa_final_check:** verdict=ok, em=true, predicted="C"
* * *
##   ⟨75⟩ Topic coverage 
50 hand-written topic families are seeded and shared across every split. No overlap of `(topic, keyword)` pairs between train / val / horizon.
Top 10 topics by episode count in the full train set:

```
new asteroid                     119
new moon                         118
new insect                       115
new photonic chip architecture   109
new alien organism               105
new fuel cell design             105
new catalyst                     105
new animal                       103
new alloy                        102
new material                     101

```

The full topic list is materials, elements, alloys, ceramics, polymers, superconductors, semiconductors, metamaterials, exoplanets, moons, asteroids, comets, nebulae, astronomical signals, particles, gravitational anomalies, viruses, bacteria, fungi, plants, tree species, animals, insects, deep-sea organisms, ocean microbes, alien organisms, symbiotic relationships, synthetic enzymes, biosynthetic pathways, drug-like compounds, battery chemistries, catalysts, fuel-cell designs, solar absorbers, atmospheric phenomena, weather patterns, geological minerals, tectonic processes, oceanographic currents, volcanic-vent biota, quantum devices, photonic chips, spintronic effects, cryogenic sensors, neuromorphic processors, manufacturing processes, additive-manufacturing techniques, acoustic phenomena, optical phenomena, magnetic phenomena.
* * *
##   ⟨76⟩ Row schema 
One row per episode:

```
{
  "episode_id":  int,          // dense in each split
  "topic":       str,          // one of the 50 topic families
  "keyword":     str,          // fictional entity name
  "W":           int,          // 8 for train/val, 32 for horizon
  "documents":   [
     { "idx":   int,           // 1-based, docs presented in this order
       "title": str,           // becomes the doc's identity across the thread
       "body":  str }          // ~200-350 words, references earlier docs by title
     ...
  ],
  "qas": [
     { "qa_id":            int,
       "question":         str,
       "answer":           str,          // gold; short span (<=10 tok) or letter A-E
       "answer_type":      "short" | "multiple_choice",
       "choices":          null | { "A":str, "B":str, "C":str, "D":str, "E":str },
       "source_doc_ids":   [int, ...],   // always includes main_doc_id
       "main_doc_id":      int,          // == step at which the QA was written
       "cot":              str,          // one-paragraph reasoning that supports the gold
       "overridden":       bool,         // later doc contradicts/supersedes the gold
       "checks_passed":    bool,         // always True in the released parquets
       "check_report":     { ... },      // deterministic fail list + LLM verdict
       "answer_variants":  [str, ...],   // populated on val + horizon; [] on train
       "style":            str,          // 7-way categorical
       "qa_final_check":   {
         "predicted": str,               // Qwen's independent short-answer output
         "em_match":  bool,
         "f1_max":    float,
         "verdict":   "ok" | "mismatch" | "skipped"
       }
     }, ...
  ]
}

```

* * *
##   ⟨77⟩ Loading 
Direct with `datasets`:

```
from datasets import load_dataset
ds = load_dataset("HerrHruby/synthetic-science-v2-sample")
val = ds["val_checked"]
print(val[0]["topic"], val[0]["keyword"], "W=", val[0]["W"])
print("first QA:", val[0]["qas"][0]["question"])

```

Or as a parquet directly:

```
import pandas as pd
val = pd.read_parquet("val_checked.parquet")
q = val.iloc[0]["qas"][0]
accepted = [q["answer"]] + list(q["answer_variants"])
print(q["qa_final_check"])

```

**Recommended filter for evaluation:** `qa_final_check.verdict == "ok"` yields ~85–88% of QAs at much higher answerability confidence.
* * *
##   ⟨78⟩ Reproduction 
Full pipeline: `data/synthetic_science_v2/run_full_pipeline.sh` in the project repo (branch `synthetic-science-v2`). Typical run time on 8× H100 with Qwen3.6-35B-A3B: **~2 hours** for 5000 W=8 episodes + 128 W=32 episodes end-to-end.
* * *
##   ⟨79⟩ Design notes 
  * **Episode-aligned windowing.** The intended use is to stream an episode's W docs through a meta-learner (SO-MAML or FO-MAML), inner-adapting on the docs as they arrive and reading out on the QAs. Random-window stacking across episodes destroys the cross-doc benchmark by interleaving unrelated threads.
  * **Overrides are a feature, not a bug.** Some ~0.5% of QAs in the released parquets are marked `overridden=True`. Continual-learning benchmarks should ideally test whether the model correctly _forgets_ the stale answer — filter these out only if that's not your evaluation target.
  * **Train has no alt-answer variants.** Training uses loss on the gold token sequence; alt-forms would be wasted compute. Val and horizon are where EM/F1 with variants matters.
  * **W=32 horizon is a strict distribution shift.** The train pool is W=8-only; horizon is W=32 with fresh `(topic, keyword)` samples drawn from a disjoint seed and rendered with the same title-based reference style. Use it to measure how well an approach extrapolates from 8-doc to 32-doc continual streams.


* * *
##   ⟨80⟩ Citation 
Generated as part of the `meta_ttt` project (CMU FLAME cluster, Meta-Learning group). If you use the data, please cite the repo.
Copy to bucket new
Use this dataset 

Downloads last month
    95
Number of rows: 478 Total file size: 22.5 MB
System theme
Company
TOS⟨84⟩ Privacy⟨85⟩ About⟨86⟩ Careers⟨87⟩ ⟨1⟩
Website
Models⟨2⟩ Datasets⟨3⟩ Spaces⟨4⟩ Pricing⟨8⟩ Docs⟨6⟩
