![Hugging Face's logo](https://huggingface.co/front/assets/huggingface_logo-noborder.svg) Hugging Face⟨1⟩
  *  Models ⟨2⟩
  *  Datasets ⟨3⟩
  *  Spaces ⟨4⟩
  *  Buckets new⟨5⟩
  *  Docs ⟨6⟩
  *  Enterprise ⟨7⟩
  * Pricing⟨8⟩
  *     * Website
      *  Tasks⟨9⟩
      *  HuggingChat⟨10⟩
      *  Collections⟨11⟩
      *  Languages⟨12⟩
      *  Organizations⟨13⟩
    * Community
      *  Blog⟨14⟩
      *  Posts⟨15⟩
      *  Daily Papers⟨16⟩
      *  Hardware⟨17⟩
      *  Learn⟨18⟩
      *  Discord⟨19⟩
      *  Forum⟨20⟩
      *  GitHub⟨21⟩
    * Solutions
      *  Team & Enterprise⟨7⟩
      *  Hugging Face PRO⟨22⟩
      *  Enterprise Support⟨23⟩
      *  Inference Providers⟨24⟩
      *  Inference Endpoints⟨25⟩
      *  Storage Buckets⟨5⟩
  * * * *
  * Log In⟨26⟩
  * Sign Up⟨27⟩


#   Datasets:⟨3⟩
* * *
 ![](https://huggingface.co/avatars/df538b1b18eea2e9f523a71c0bbb6e4a.svg) ⟨28⟩
MattMMarketing⟨28⟩
/
fmcsa-new-entrant-audit-violations⟨29⟩
like 0
Modalities:  Text ⟨30⟩
Formats:  json ⟨31⟩
Languages:  English ⟨32⟩
Size:  < 1K ⟨33⟩
Tags:  fmcsa ⟨34⟩ motor-carrier ⟨35⟩ safety-audit ⟨36⟩ cfr ⟨37⟩ compliance ⟨38⟩ transportation ⟨39⟩
Libraries:  Datasets ⟨40⟩ pandas ⟨41⟩ Polars ⟨42⟩ + 1
License:
cc-by-4.0
 Dataset card ⟨29⟩ Data Studio ⟨43⟩ Files Files and versions xet ⟨44⟩ Community ⟨45⟩
Dataset Viewer
 Auto-converted to Parquet⟨46⟩ API Embed  Duplicate⟨47⟩ Data Studio
Subset (1)
default · 103 rows
default (103 rows)
Split (1)
train · 103 rows
train (103 rows)
SQL
Console  
|  id stringlengths 14 14  |  cfr_cite stringlengths 5 16  |  audit_factor stringclasses 5 values  |  severity stringclasses 2 values  |  automatic_failure stringclasses 2 values  |  auto_fail_guideline stringclasses 3 values  |  description stringlengths 27 297  |  plain_meaning stringlengths 281 551  |  source_url stringclasses 1 value  |  auto_fail_source_url stringclasses 2 values  |  verified_on timestamp[s]date 2026-07-04 00:00:00 2026-07-04 00:00:00  |  notes stringclasses 1 value  |  
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |  
|  fmcsa-nesa-001  |  382.115(a)  |  Driver  |  acute  |  yes  |  Single occurrence.  |  Failing to implement an alcohol and/or controlled substances testing program (domestic motor carrier)  |  This is an acute violation of 49 CFR 382.115(a): failing to implement an alcohol and/or controlled substances testing program (domestic motor carrier). An acute regulation is one where noncompliance is severe enough to require immediate corrective action, regardless of a carrier's overall safety posture. A single docum...  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/subpart-G/section-385.321  |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-002  |  382.115(b)  |  Driver  |  acute  |  yes  |  Single occurrence.  |  Failing to implement an alcohol and/or controlled substances testing program (foreign motor carrier)  |  This is an acute violation of 49 CFR 382.115(b): failing to implement an alcohol and/or controlled substances testing program (foreign motor carrier). An acute regulation is one where noncompliance is severe enough to require immediate corrective action, regardless of a carrier's overall safety posture. A single docume...  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/subpart-G/section-385.321  |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-003  |  382.201  |  Driver  |  acute  |  yes  |  Single occurrence.  |  Using a driver known to have an alcohol concentration of 0.04 or greater  |  This is an acute violation of 49 CFR 382.201: using a driver known to have an alcohol concentration of 0.04 or greater. An acute regulation is one where noncompliance is severe enough to require immediate corrective action, regardless of a carrier's overall safety posture. A single documented occurrence counts against ...  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/subpart-G/section-385.321  |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-004  |  382.211  |  Driver  |  acute  |  yes  |  Single occurrence.  |  Using a driver who has refused to submit to an alcohol or controlled substances test required under part 382  |  This is an acute violation of 49 CFR 382.211: using a driver who has refused to submit to an alcohol or controlled substances test required under part 382. An acute regulation is one where noncompliance is severe enough to require immediate corrective action, regardless of a carrier's overall safety posture. A single d...  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/subpart-G/section-385.321  |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-005  |  382.213(c)  |  Driver  |  acute  |  no  |   |  Using a driver known to have used a controlled substance  |  This is an acute violation of 49 CFR 382.213(c): using a driver known to have used a controlled substance. An acute regulation is one where noncompliance is severe enough to require immediate corrective action, regardless of a carrier's overall safety posture. A single documented occurrence counts against you.  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |   |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-006  |  382.215  |  Driver  |  acute  |  yes  |  Single occurrence.  |  Using a driver known to have tested positive for a controlled substance  |  This is an acute violation of 49 CFR 382.215: using a driver known to have tested positive for a controlled substance. An acute regulation is one where noncompliance is severe enough to require immediate corrective action, regardless of a carrier's overall safety posture. A single documented occurrence counts against y...  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/subpart-G/section-385.321  |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-007  |  382.301(a)  |  Driver  |  critical  |  no  |   |  Using a driver before the motor carrier has received a negative pre-employment controlled substance test result  |  This is a critical violation of 49 CFR 382.301(a): using a driver before the motor carrier has received a negative pre-employment controlled substance test result. A critical regulation relates to management or operational controls; it is scored when auditors find a pattern (more than one occurrence, generally at least...  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |   |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-008  |  382.303(a)  |  Driver  |  critical  |  no  |   |  Failing to conduct post accident testing on driver for alcohol  |  This is a critical violation of 49 CFR 382.303(a): failing to conduct post accident testing on driver for alcohol. A critical regulation relates to management or operational controls; it is scored when auditors find a pattern (more than one occurrence, generally at least 10% of the records examined).  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |   |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-009  |  382.303(b)  |  Driver  |  critical  |  no  |   |  Failing to conduct post accident testing on driver for controlled substances  |  This is a critical violation of 49 CFR 382.303(b): failing to conduct post accident testing on driver for controlled substances. A critical regulation relates to management or operational controls; it is scored when auditors find a pattern (more than one occurrence, generally at least 10% of the records examined).  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |   |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-010  |  382.305(a)  |  Driver  |  acute  |  yes  |  Single occurrence.  |  Failing to implement a random controlled substances and/or an alcohol testing program  |  This is an acute violation of 49 CFR 382.305(a): failing to implement a random controlled substances and/or an alcohol testing program. An acute regulation is one where noncompliance is severe enough to require immediate corrective action, regardless of a carrier's overall safety posture. A single documented occurrence...  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/subpart-G/section-385.321  |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-011  |  382.305(b)(1)  |  Driver  |  critical  |  no  |   |  Failing to conduct random alcohol testing at an annual rate of not less than the applicable annual rate of the average number of driver positions  |  This is a critical violation of 49 CFR 382.305(b)(1): failing to conduct random alcohol testing at an annual rate of not less than the applicable annual rate of the average number of driver positions. A critical regulation relates to management or operational controls; it is scored when auditors find a pattern (more th...  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |   |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-012  |  382.305(b)(2)  |  Driver  |  critical  |  no  |   |  Failing to conduct random controlled substances testing at an annual rate of not less than the applicable annual rate of the average number of driver positions  |  This is a critical violation of 49 CFR 382.305(b)(2): failing to conduct random controlled substances testing at an annual rate of not less than the applicable annual rate of the average number of driver positions. A critical regulation relates to management or operational controls; it is scored when auditors find a pa...  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |   |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-013  |  382.309  |  Driver  |  acute  |  no  |   |  Using a driver who has not undergone return-to-duty testing with a negative drug test result and/or an alcohol test with an alcohol concentration of less than 0.02 in accordance with 49 CFR 40.305  |  This is an acute violation of 49 CFR 382.309: using a driver who has not undergone return-to-duty testing with a negative drug test result and/or an alcohol test with an alcohol concentration of less than 0.02 in accordance with 49 CFR 40.305. An acute regulation is one where noncompliance is severe enough to require i...  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |   |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-014  |  382.503  |  Driver  |  critical  |  no  |   |  Allowing a driver to perform safety sensitive function, after engaging in conduct prohibited by subpart B, without being evaluated by substance abuse professional, as required by § 382.605  |  This is a critical violation of 49 CFR 382.503: allowing a driver to perform safety sensitive function, after engaging in conduct prohibited by subpart B, without being evaluated by substance abuse professional, as required by § 382.605. A critical regulation relates to management or operational controls; it is scored ...  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |   |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-015  |  382.505(a)  |  Driver  |  acute  |  no  |   |  Using a driver within 24 hours after being found to have an alcohol concentration of 0.02 or greater but less than 0.04  |  This is an acute violation of 49 CFR 382.505(a): using a driver within 24 hours after being found to have an alcohol concentration of 0.02 or greater but less than 0.04. An acute regulation is one where noncompliance is severe enough to require immediate corrective action, regardless of a carrier's overall safety postu...  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |   |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-016  |  382.605  |  Driver  |  critical  |  no  |   |  Failing to subject a driver who has been identified as needing assistance to at least six unannounced follow-up drug and/or alcohol tests in the first 12 months following the driver's return-to-duty in accordance with 49 CFR 40.307  |  This is a critical violation of 49 CFR 382.605: failing to subject a driver who has been identified as needing assistance to at least six unannounced follow-up drug and/or alcohol tests in the first 12 months following the driver's return-to-duty in accordance with 49 CFR 40.307. A critical regulation relates to manage...  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |   |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-017  |  383.23(a)  |  Driver  |  critical  |  yes  |  Single occurrence.  |  Operating a commercial motor vehicle without a valid commercial driver's license  |  This is a critical violation of 49 CFR 383.23(a): operating a commercial motor vehicle without a valid commercial driver's license. A critical regulation relates to management or operational controls; it is scored when auditors find a pattern (more than one occurrence, generally at least 10% of the records examined).  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/subpart-G/section-385.321  |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-018  |  383.37(a)  |  Driver  |  acute  |  no  |   |  Allowing, requiring, permitting, or authorizing a driver to operate a CMV who the employer knew or should reasonably have known does not have a current CLP or CDL, does not have a CLP or CDL with the proper class or endorsements, or operates a CMV in violation of any restriction on the CLP or CDL  |  This is an acute violation of 49 CFR 383.37(a): allowing, requiring, permitting, or authorizing a driver to operate a CMV who the employer knew or should reasonably have known does not have a current CLP or CDL, does not have a CLP or CDL with the proper class or endorsements, or operates a CMV in violation of any rest...  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |   |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-019  |  383.37(b)  |  Driver  |  acute  |  yes  |  Single occurrence.  |  Allowing, requiring, permitting, or authorizing a driver to operate a CMV who the employer knew or should reasonably have known has a CLP or CDL disqualified by a State, has lost the right to operate a CMV in a State, or has been disqualified  |  This is an acute violation of 49 CFR 383.37(b): allowing, requiring, permitting, or authorizing a driver to operate a CMV who the employer knew or should reasonably have known has a CLP or CDL disqualified by a State, has lost the right to operate a CMV in a State, or has been disqualified. An acute regulation is one w...  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/subpart-G/section-385.321  |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-020  |  383.37(c)  |  Driver  |  acute  |  no  |   |  Allowing, requiring, permitting, or authorizing a driver to operate a CMV who the employer knew or should reasonably have known has more than one CLP or CDL  |  This is an acute violation of 49 CFR 383.37(c): allowing, requiring, permitting, or authorizing a driver to operate a CMV who the employer knew or should reasonably have known has more than one CLP or CDL. An acute regulation is one where noncompliance is severe enough to require immediate corrective action, regardless...  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |   |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-021  |  383.51(a)  |  Driver  |  acute  |  yes  |  Single occurrence.  |  Knowingly allowing, requiring, permitting, or authorizing a driver to drive who is disqualified to drive a commercial motor vehicle  |  This is an acute violation of 49 CFR 383.51(a): knowingly allowing, requiring, permitting, or authorizing a driver to drive who is disqualified to drive a commercial motor vehicle. An acute regulation is one where noncompliance is severe enough to require immediate corrective action, regardless of a carrier's overall s...  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/subpart-G/section-385.321  |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-022  |  387.7(a)  |  General  |  acute  |  yes  |  Single occurrence.  |  Operating a motor vehicle without having in effect the required minimum levels of financial responsibility coverage  |  This is an acute violation of 49 CFR 387.7(a): operating a motor vehicle without having in effect the required minimum levels of financial responsibility coverage. An acute regulation is one where noncompliance is severe enough to require immediate corrective action, regardless of a carrier's overall safety posture. A ...  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/subpart-G/section-385.321  |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-023  |  387.7(d)  |  General  |  critical  |  no  |   |  Failing to maintain at principal place of business required proof of financial responsibility  |  This is a critical violation of 49 CFR 387.7(d): failing to maintain at principal place of business required proof of financial responsibility. A critical regulation relates to management or operational controls; it is scored when auditors find a pattern (more than one occurrence, generally at least 10% of the records ...  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |   |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-024  |  387.31(a)  |  General  |  acute  |  yes  |  Single occurrence.  |  Operating a passenger carrying vehicle without having in effect the required minimum levels of financial responsibility  |  This is an acute violation of 49 CFR 387.31(a): operating a passenger carrying vehicle without having in effect the required minimum levels of financial responsibility. An acute regulation is one where noncompliance is severe enough to require immediate corrective action, regardless of a carrier's overall safety postur...  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/subpart-G/section-385.321  |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-025  |  387.31(d)  |  General  |  critical  |  no  |   |  Failing to maintain at principal place of business required proof of financial responsibility for passenger carrying vehicles  |  This is a critical violation of 49 CFR 387.31(d): failing to maintain at principal place of business required proof of financial responsibility for passenger carrying vehicles. A critical regulation relates to management or operational controls; it is scored when auditors find a pattern (more than one occurrence, gener...  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |   |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-026  |  390.15(b)(2)  |  General  |  critical  |  no  |   |  Failing to maintain copies of all accident reports required by State or other governmental entities or insurers  |  This is a critical violation of 49 CFR 390.15(b)(2): failing to maintain copies of all accident reports required by State or other governmental entities or insurers. A critical regulation relates to management or operational controls; it is scored when auditors find a pattern (more than one occurrence, generally at lea...  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |   |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-027  |  390.35  |  General  |  acute  |  no  |   |  Making, or causing to make fraudulent or intentionally false statements or records and/or reproducing fraudulent records  |  This is an acute violation of 49 CFR 390.35: making, or causing to make fraudulent or intentionally false statements or records and/or reproducing fraudulent records. An acute regulation is one where noncompliance is severe enough to require immediate corrective action, regardless of a carrier's overall safety posture....  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |   |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-028  |  391.11(b)(4)  |  Driver  |  acute  |  yes  |  Single occurrence.  |  Using a physically unqualified driver  |  This is an acute violation of 49 CFR 391.11(b)(4): using a physically unqualified driver. An acute regulation is one where noncompliance is severe enough to require immediate corrective action, regardless of a carrier's overall safety posture. A single documented occurrence counts against you.  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/subpart-G/section-385.321  |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-029  |  391.15(a)  |  Driver  |  acute  |  yes  |  Single occurrence.  |  Using a disqualified driver  |  This is an acute violation of 49 CFR 391.15(a): using a disqualified driver. An acute regulation is one where noncompliance is severe enough to require immediate corrective action, regardless of a carrier's overall safety posture. A single documented occurrence counts against you.  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/subpart-G/section-385.321  |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-030  |  391.45(a)  |  Driver  |  critical  |  no  |   |  Using a driver not medically examined and certified  |  This is a critical violation of 49 CFR 391.45(a): using a driver not medically examined and certified. A critical regulation relates to management or operational controls; it is scored when auditors find a pattern (more than one occurrence, generally at least 10% of the records examined).  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |   |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-031  |  391.45(b)  |  Driver  |  critical  |  no  |   |  Using a driver not medically examined and certified during the preceding 24 months  |  This is a critical violation of 49 CFR 391.45(b): using a driver not medically examined and certified during the preceding 24 months. A critical regulation relates to management or operational controls; it is scored when auditors find a pattern (more than one occurrence, generally at least 10% of the records examined).  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |   |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-032  |  391.51(a)  |  Driver  |  critical  |  no  |   |  Failing to maintain driver qualification file on each driver employed  |  This is a critical violation of 49 CFR 391.51(a): failing to maintain driver qualification file on each driver employed. A critical regulation relates to management or operational controls; it is scored when auditors find a pattern (more than one occurrence, generally at least 10% of the records examined).  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |   |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-033  |  391.51(b)(2)  |  Driver  |  critical  |  no  |   |  Failing to maintain inquiries into driver's driving record in driver's qualification file  |  This is a critical violation of 49 CFR 391.51(b)(2): failing to maintain inquiries into driver's driving record in driver's qualification file. A critical regulation relates to management or operational controls; it is scored when auditors find a pattern (more than one occurrence, generally at least 10% of the records ...  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |   |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-034  |  391.51(b)(6)  |  Driver  |  critical  |  no  |   |  Failing to maintain medical examiner's certificate in driver's qualification file  |  This is a critical violation of 49 CFR 391.51(b)(6): failing to maintain medical examiner's certificate in driver's qualification file. A critical regulation relates to management or operational controls; it is scored when auditors find a pattern (more than one occurrence, generally at least 10% of the records examined...  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |   |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-035  |  392.2  |  Operational  |  critical  |  no  |   |  Operating a motor vehicle not in accordance with the laws, ordinances, and regulations of the jurisdiction in which it is being operated  |  This is a critical violation of 49 CFR 392.2: operating a motor vehicle not in accordance with the laws, ordinances, and regulations of the jurisdiction in which it is being operated. A critical regulation relates to management or operational controls; it is scored when auditors find a pattern (more than one occurrence...  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |   |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-036  |  392.4(b)  |  Operational  |  acute  |  no  |   |  Requiring or permitting a driver to drive while under the influence of, or in possession of, a narcotic drug, amphetamine, or any other substance capable of rendering the driver incapable of safely operating a motor vehicle  |  This is an acute violation of 49 CFR 392.4(b): requiring or permitting a driver to drive while under the influence of, or in possession of, a narcotic drug, amphetamine, or any other substance capable of rendering the driver incapable of safely operating a motor vehicle. An acute regulation is one where noncompliance i...  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |   |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-037  |  392.5(b)(1)  |  Operational  |  acute  |  no  |   |  Requiring or permitting a driver to drive a motor vehicle while under the influence of, or in possession of, an intoxicating beverage  |  This is an acute violation of 49 CFR 392.5(b)(1): requiring or permitting a driver to drive a motor vehicle while under the influence of, or in possession of, an intoxicating beverage. An acute regulation is one where noncompliance is severe enough to require immediate corrective action, regardless of a carrier's overa...  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |   |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-038  |  392.5(b)(2)  |  Operational  |  acute  |  no  |   |  Requiring or permitting a driver who shows evidence of having consumed an intoxicating beverage within 4 hours to operate a motor vehicle  |  This is an acute violation of 49 CFR 392.5(b)(2): requiring or permitting a driver who shows evidence of having consumed an intoxicating beverage within 4 hours to operate a motor vehicle. An acute regulation is one where noncompliance is severe enough to require immediate corrective action, regardless of a carrier's o...  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |   |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-039  |  392.6  |  Operational  |  critical  |  no  |   |  Scheduling a run which would necessitate the vehicle being operated at speeds in excess of those prescribed  |  This is a critical violation of 49 CFR 392.6: scheduling a run which would necessitate the vehicle being operated at speeds in excess of those prescribed. A critical regulation relates to management or operational controls; it is scored when auditors find a pattern (more than one occurrence, generally at least 10% of t...  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |   |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-040  |  392.9(a)(1)  |  Operational  |  critical  |  no  |   |  Requiring or permitting a driver to drive without the vehicle's cargo being properly distributed and adequately secured  |  This is a critical violation of 49 CFR 392.9(a)(1): requiring or permitting a driver to drive without the vehicle's cargo being properly distributed and adequately secured. A critical regulation relates to management or operational controls; it is scored when auditors find a pattern (more than one occurrence, generally...  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |   |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-041  |  395.1(h)(2)(i)  |  Operational  |  critical  |  no  |   |  Requiring or permitting a passenger-carrying commercial motor vehicle driver to drive more than 15 hours (Driving in Alaska)  |  This is a critical violation of 49 CFR 395.1(h)(2)(i): requiring or permitting a passenger-carrying commercial motor vehicle driver to drive more than 15 hours (Driving in Alaska). A critical regulation relates to management or operational controls; it is scored when auditors find a pattern (more than one occurrence, g...  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |   |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-042  |  395.1(h)(2)(ii)  |  Operational  |  critical  |  no  |   |  Requiring or permitting a passenger-carrying commercial motor vehicle driver to drive after having been on duty 20 hours (Driving in Alaska)  |  This is a critical violation of 49 CFR 395.1(h)(2)(ii): requiring or permitting a passenger-carrying commercial motor vehicle driver to drive after having been on duty 20 hours (Driving in Alaska). A critical regulation relates to management or operational controls; it is scored when auditors find a pattern (more than ...  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |   |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-043  |  395.1(h)(2)(iii)  |  Operational  |  critical  |  no  |   |  Requiring or permitting a passenger-carrying commercial motor vehicle driver to drive after having been on duty more than 70 hours in 7 consecutive days (Driving in Alaska)  |  This is a critical violation of 49 CFR 395.1(h)(2)(iii): requiring or permitting a passenger-carrying commercial motor vehicle driver to drive after having been on duty more than 70 hours in 7 consecutive days (Driving in Alaska). A critical regulation relates to management or operational controls; it is scored when au...  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |   |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-044  |  395.1(h)(2)(iv)  |  Operational  |  critical  |  no  |   |  Requiring or permitting a passenger-carrying commercial motor vehicle driver to drive after having been on duty more than 80 hours in 8 consecutive days (Driving in Alaska)  |  This is a critical violation of 49 CFR 395.1(h)(2)(iv): requiring or permitting a passenger-carrying commercial motor vehicle driver to drive after having been on duty more than 80 hours in 8 consecutive days (Driving in Alaska). A critical regulation relates to management or operational controls; it is scored when aud...  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |   |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-045  |  395.1(o)  |  Operational  |  critical  |  no  |   |  Requiring or permitting a property-carrying commercial motor vehicle driver to drive after having been on duty 16 consecutive hours  |  This is a critical violation of 49 CFR 395.1(o): requiring or permitting a property-carrying commercial motor vehicle driver to drive after having been on duty 16 consecutive hours. A critical regulation relates to management or operational controls; it is scored when auditors find a pattern (more than one occurrence, ...  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |   |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-046  |  395.3(a)(1)  |  Operational  |  critical  |  no  |   |  Requiring or permitting a property-carrying commercial motor vehicle driver to drive without taking an off-duty period of at least 10 consecutive hours prior to driving  |  This is a critical violation of 49 CFR 395.3(a)(1): requiring or permitting a property-carrying commercial motor vehicle driver to drive without taking an off-duty period of at least 10 consecutive hours prior to driving. A critical regulation relates to management or operational controls; it is scored when auditors fi...  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |   |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-047  |  395.3(a)(2)  |  Operational  |  critical  |  no  |   |  Requiring or permitting a property-carrying commercial motor vehicle driver to drive after the end of the 14th hour after coming on duty  |  This is a critical violation of 49 CFR 395.3(a)(2): requiring or permitting a property-carrying commercial motor vehicle driver to drive after the end of the 14th hour after coming on duty. A critical regulation relates to management or operational controls; it is scored when auditors find a pattern (more than one occu...  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |   |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-048  |  395.3(a)(3)(i)  |  Operational  |  critical  |  no  |   |  Requiring or permitting a property-carrying commercial motor vehicle driver to drive more than 11 hours  |  This is a critical violation of 49 CFR 395.3(a)(3)(i): requiring or permitting a property-carrying commercial motor vehicle driver to drive more than 11 hours. A critical regulation relates to management or operational controls; it is scored when auditors find a pattern (more than one occurrence, generally at least 10%...  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |   |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-049  |  395.3(a)(3)(ii)  |  Operational  |  critical  |  no  |   |  Requiring or permitting a property-carrying commercial motor vehicle driver to drive if more than 8 hours of driving time have passed without a consecutive interruption in driving status of at least 30 minutes, either off-duty, sleeper berth or on-duty not driving  |  This is a critical violation of 49 CFR 395.3(a)(3)(ii): requiring or permitting a property-carrying commercial motor vehicle driver to drive if more than 8 hours of driving time have passed without a consecutive interruption in driving status of at least 30 minutes, either off-duty, sleeper berth or on-duty not driving...  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |   |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-050  |  395.3(b)(1)  |  Operational  |  critical  |  no  |   |  Requiring or permitting a property-carrying commercial motor vehicle driver to drive after having been on duty more than 60 hours in 7 consecutive days  |  This is a critical violation of 49 CFR 395.3(b)(1): requiring or permitting a property-carrying commercial motor vehicle driver to drive after having been on duty more than 60 hours in 7 consecutive days. A critical regulation relates to management or operational controls; it is scored when auditors find a pattern (mor...  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |   |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-051  |  395.3(b)(2)  |  Operational  |  critical  |  no  |   |  Requiring or permitting a property-carrying commercial motor vehicle driver to drive after having been on duty more than 70 hours in 8 consecutive days  |  This is a critical violation of 49 CFR 395.3(b)(2): requiring or permitting a property-carrying commercial motor vehicle driver to drive after having been on duty more than 70 hours in 8 consecutive days. A critical regulation relates to management or operational controls; it is scored when auditors find a pattern (mor...  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |   |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-052  |  395.5(a)(1)  |  Operational  |  critical  |  no  |   |  Requiring or permitting a passenger-carrying commercial motor vehicle driver to drive more than 10 hours  |  This is a critical violation of 49 CFR 395.5(a)(1): requiring or permitting a passenger-carrying commercial motor vehicle driver to drive more than 10 hours. A critical regulation relates to management or operational controls; it is scored when auditors find a pattern (more than one occurrence, generally at least 10% o...  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |   |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-053  |  395.5(a)(2)  |  Operational  |  critical  |  no  |   |  Requiring or permitting a passenger-carrying commercial motor vehicle driver to drive after having been on duty 15 hours  |  This is a critical violation of 49 CFR 395.5(a)(2): requiring or permitting a passenger-carrying commercial motor vehicle driver to drive after having been on duty 15 hours. A critical regulation relates to management or operational controls; it is scored when auditors find a pattern (more than one occurrence, generall...  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |   |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-054  |  395.5(b)(1)  |  Operational  |  critical  |  no  |   |  Requiring or permitting a passenger-carrying commercial motor vehicle driver to drive after having been on duty more than 60 hours in 7 consecutive days  |  This is a critical violation of 49 CFR 395.5(b)(1): requiring or permitting a passenger-carrying commercial motor vehicle driver to drive after having been on duty more than 60 hours in 7 consecutive days. A critical regulation relates to management or operational controls; it is scored when auditors find a pattern (mo...  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |   |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-055  |  395.5(b)(2)  |  Operational  |  critical  |  no  |   |  Requiring or permitting a passenger-carrying commercial motor vehicle driver to drive after having been on duty more than 70 hours in 8 consecutive days  |  This is a critical violation of 49 CFR 395.5(b)(2): requiring or permitting a passenger-carrying commercial motor vehicle driver to drive after having been on duty more than 70 hours in 8 consecutive days. A critical regulation relates to management or operational controls; it is scored when auditors find a pattern (mo...  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |   |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-056  |  395.8(a)(1)  |  Operational  |  critical  |  yes  |  Requires a violation threshold (51% or more of examined records) to trigger automatic failure.  |  Failing to require a driver to prepare a record of duty status using appropriate method  |  This is a critical violation of 49 CFR 395.8(a)(1): failing to require a driver to prepare a record of duty status using appropriate method. A critical regulation relates to management or operational controls; it is scored when auditors find a pattern (more than one occurrence, generally at least 10% of the records exa...  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/subpart-G/section-385.321  |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-057  |  395.8(a)(2)(ii)  |  Operational  |  critical  |  no  |   |  Failure to require a driver to submit record of duty status  |  This is a critical violation of 49 CFR 395.8(a)(2)(ii): failure to require a driver to submit record of duty status. A critical regulation relates to management or operational controls; it is scored when auditors find a pattern (more than one occurrence, generally at least 10% of the records examined).  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |   |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-058  |  395.8(e)(1)  |  Operational  |  critical  |  no  |   |  Making, or permitting a driver to make, a false report regarding duty status  |  This is a critical violation of 49 CFR 395.8(e)(1): making, or permitting a driver to make, a false report regarding duty status. A critical regulation relates to management or operational controls; it is scored when auditors find a pattern (more than one occurrence, generally at least 10% of the records examined).  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |   |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-059  |  395.8(e)(2)  |  Operational  |  acute  |  no  |   |  Disabling, deactivating, disengaging, jamming, or otherwise blocking or degrading a signal transmission or reception, tampering with an automatic on-board recording device or ELD, or permitting or requiring another person to engage in such activity  |  This is an acute violation of 49 CFR 395.8(e)(2): disabling, deactivating, disengaging, jamming, or otherwise blocking or degrading a signal transmission or reception, tampering with an automatic on-board recording device or ELD, or permitting or requiring another person to engage in such activity. An acute regulation ...  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |   |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-060  |  395.8(k)(1)  |  Operational  |  critical  |  no  |   |  Failing to preserve a driver's record of duty status or supporting documents for 6 months  |  This is a critical violation of 49 CFR 395.8(k)(1): failing to preserve a driver's record of duty status or supporting documents for 6 months. A critical regulation relates to management or operational controls; it is scored when auditors find a pattern (more than one occurrence, generally at least 10% of the records e...  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |   |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-061  |  395.11(b)  |  Operational  |  critical  |  no  |   |  Failing to require a driver to submit supporting documents  |  This is a critical violation of 49 CFR 395.11(b): failing to require a driver to submit supporting documents. A critical regulation relates to management or operational controls; it is scored when auditors find a pattern (more than one occurrence, generally at least 10% of the records examined).  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |   |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-062  |  395.11(c)  |  Operational  |  critical  |  no  |   |  Failing to retain types of supporting documents as required by § 395.11(c)  |  This is a critical violation of 49 CFR 395.11(c): failing to retain types of supporting documents as required by § 395.11(c). A critical regulation relates to management or operational controls; it is scored when auditors find a pattern (more than one occurrence, generally at least 10% of the records examined).  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |   |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-063  |  395.11(e)  |  Operational  |  critical  |  no  |   |  Failing to retain supporting documents in a manner that permits the effective matching of the documents to the driver's record of duty status  |  This is a critical violation of 49 CFR 395.11(e): failing to retain supporting documents in a manner that permits the effective matching of the documents to the driver's record of duty status. A critical regulation relates to management or operational controls; it is scored when auditors find a pattern (more than one o...  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |   |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-064  |  395.11(f)  |  Operational  |  critical  |  no  |   |  Altering, defacing, destroying, mutilating, or obscuring a supporting document  |  This is a critical violation of 49 CFR 395.11(f): altering, defacing, destroying, mutilating, or obscuring a supporting document. A critical regulation relates to management or operational controls; it is scored when auditors find a pattern (more than one occurrence, generally at least 10% of the records examined).  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |   |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-065  |  395.30(f)  |  Operational  |  acute  |  no  |   |  Failing to retain ELD information  |  This is an acute violation of 49 CFR 395.30(f): failing to retain ELD information. An acute regulation is one where noncompliance is severe enough to require immediate corrective action, regardless of a carrier's overall safety posture. A single documented occurrence counts against you.  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |   |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-066  |  396.3(b)  |  Vehicle  |  critical  |  no  |   |  Failing to keep minimum records of inspection and vehicle maintenance  |  This is a critical violation of 49 CFR 396.3(b): failing to keep minimum records of inspection and vehicle maintenance. A critical regulation relates to management or operational controls; it is scored when auditors find a pattern (more than one occurrence, generally at least 10% of the records examined).  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |   |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-067  |  396.9(c)(2)  |  Vehicle  |  acute  |  yes  |  Single occurrence.  |  Requiring or permitting the operation of a motor vehicle declared “out-of-service” before repairs were made  |  This is an acute violation of 49 CFR 396.9(c)(2): requiring or permitting the operation of a motor vehicle declared “out-of-service” before repairs were made. An acute regulation is one where noncompliance is severe enough to require immediate corrective action, regardless of a carrier's overall safety posture. A singl...  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/subpart-G/section-385.321  |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-068  |  396.11(a)  |  Vehicle  |  critical  |  yes  |  Single occurrence.  |  Failing to require driver to prepare driver vehicle inspection report  |  This is a critical violation of 49 CFR 396.11(a): failing to require driver to prepare driver vehicle inspection report. A critical regulation relates to management or operational controls; it is scored when auditors find a pattern (more than one occurrence, generally at least 10% of the records examined).  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/subpart-G/section-385.321  |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-069  |  396.17(a)  |  Vehicle  |  critical  |  yes  |  Requires a violation threshold (51% or more of examined records) to trigger automatic failure.  |  Using a commercial motor vehicle not periodically inspected  |  This is a critical violation of 49 CFR 396.17(a): using a commercial motor vehicle not periodically inspected. A critical regulation relates to management or operational controls; it is scored when auditors find a pattern (more than one occurrence, generally at least 10% of the records examined).  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/subpart-G/section-385.321  |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-070  |  396.17(g)  |  Vehicle  |  acute  |  no  |   |  Failing to promptly repair parts and accessories not meeting minimum periodic inspection standards  |  This is an acute violation of 49 CFR 396.17(g): failing to promptly repair parts and accessories not meeting minimum periodic inspection standards. An acute regulation is one where noncompliance is severe enough to require immediate corrective action, regardless of a carrier's overall safety posture. A single documente...  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |   |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-071  |  397.5(a)  |  Hazardous Materials  |  acute  |  no  |   |  Failing to ensure a motor vehicle containing Division 1.1, 1.2, or 1.3 (explosive) material is attended at all times by its driver or a qualified representative  |  This is an acute violation of 49 CFR 397.5(a): failing to ensure a motor vehicle containing Division 1.1, 1.2, or 1.3 (explosive) material is attended at all times by its driver or a qualified representative. An acute regulation is one where noncompliance is severe enough to require immediate corrective action, regardl...  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |   |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-072  |  397.7(a)(1)  |  Hazardous Materials  |  critical  |  no  |   |  Parking a motor vehicle containing Division 1.1, 1.2, or 1.3 materials within 5 feet of traveled portion of highway or street  |  This is a critical violation of 49 CFR 397.7(a)(1): parking a motor vehicle containing Division 1.1, 1.2, or 1.3 materials within 5 feet of traveled portion of highway or street. A critical regulation relates to management or operational controls; it is scored when auditors find a pattern (more than one occurrence, gen...  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |   |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-073  |  397.7(b)  |  Hazardous Materials  |  critical  |  no  |   |  Parking a motor vehicle containing hazardous material(s) other than Division 1.1, 1.2, or 1.3 materials within 5 feet of traveled portion of highway or street  |  This is a critical violation of 49 CFR 397.7(b): parking a motor vehicle containing hazardous material(s) other than Division 1.1, 1.2, or 1.3 materials within 5 feet of traveled portion of highway or street. A critical regulation relates to management or operational controls; it is scored when auditors find a pattern ...  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |   |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-074  |  397.13(a)  |  Hazardous Materials  |  critical  |  no  |   |  Permitting a person to smoke or carry a lighted cigarette, cigar or pipe within 25 feet of a motor vehicle containing Class 1 materials, Class 5 materials, or flammable materials classified as Division 2.1, Class 3, Divisions 4.1 and 4.2  |  This is a critical violation of 49 CFR 397.13(a): permitting a person to smoke or carry a lighted cigarette, cigar or pipe within 25 feet of a motor vehicle containing Class 1 materials, Class 5 materials, or flammable materials classified as Division 2.1, Class 3, Divisions 4.1 and 4.2. A critical regulation relates t...  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |   |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-075  |  397.19(a)  |  Hazardous Materials  |  critical  |  no  |   |  Failing to furnish driver of motor vehicle transporting Division 1.1, 1.2, or 1.3 (explosive) materials with a copy of the rules of part 397 and/or emergency response instructions  |  This is a critical violation of 49 CFR 397.19(a): failing to furnish driver of motor vehicle transporting Division 1.1, 1.2, or 1.3 (explosive) materials with a copy of the rules of part 397 and/or emergency response instructions. A critical regulation relates to management or operational controls; it is scored when au...  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |   |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-076  |  397.67(d)  |  Hazardous Materials  |  critical  |  no  |   |  Requiring or permitting the operation of a motor vehicle containing explosives in Class 1, Divisions 1.1, 1.2, or 1.3 that is not accompanied by a written route plan  |  This is a critical violation of 49 CFR 397.67(d): requiring or permitting the operation of a motor vehicle containing explosives in Class 1, Divisions 1.1, 1.2, or 1.3 that is not accompanied by a written route plan. A critical regulation relates to management or operational controls; it is scored when auditors find a ...  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |   |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-077  |  171.15  |  Hazardous Materials  |  critical  |  no  |   |  Carrier failing to give immediate telephone notice of an incident involving hazardous materials  |  This is a critical violation of 49 CFR 171.15: carrier failing to give immediate telephone notice of an incident involving hazardous materials. A critical regulation relates to management or operational controls; it is scored when auditors find a pattern (more than one occurrence, generally at least 10% of the records ...  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |   |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-078  |  171.16  |  Hazardous Materials  |  critical  |  no  |   |  Carrier failing to make a written report of an incident involving hazardous materials  |  This is a critical violation of 49 CFR 171.16: carrier failing to make a written report of an incident involving hazardous materials. A critical regulation relates to management or operational controls; it is scored when auditors find a pattern (more than one occurrence, generally at least 10% of the records examined).  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |   |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-079  |  172.313(a)  |  Hazardous Materials  |  acute  |  no  |   |  Accepting for transportation or transporting a package containing a poisonous-by-inhalation material that is not marked with the words “Inhalation Hazard”  |  This is an acute violation of 49 CFR 172.313(a): accepting for transportation or transporting a package containing a poisonous-by-inhalation material that is not marked with the words “Inhalation Hazard”. An acute regulation is one where noncompliance is severe enough to require immediate corrective action, regardless ...  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |   |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-080  |  172.704(a)(4)  |  Hazardous Materials  |  critical  |  no  |   |  Failing to provide security awareness training  |  This is a critical violation of 49 CFR 172.704(a)(4): failing to provide security awareness training. A critical regulation relates to management or operational controls; it is scored when auditors find a pattern (more than one occurrence, generally at least 10% of the records examined).  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |   |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-081  |  172.704(a)(5)  |  Hazardous Materials  |  critical  |  no  |   |  Failing to provide in-depth security awareness training  |  This is a critical violation of 49 CFR 172.704(a)(5): failing to provide in-depth security awareness training. A critical regulation relates to management or operational controls; it is scored when auditors find a pattern (more than one occurrence, generally at least 10% of the records examined).  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |   |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-082  |  172.800(b)  |  Hazardous Materials  |  acute  |  no  |   |  Transporting hazardous materials without a security plan (or without one conforming to Subpart I, or failure to adhere to a required security plan)  |  This is an acute violation of 49 CFR 172.800(b): transporting hazardous materials without a security plan (or without one conforming to Subpart I, or failure to adhere to a required security plan). An acute regulation is one where noncompliance is severe enough to require immediate corrective action, regardless of a ca...  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |   |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-083  |  173.24(b)(1)  |  Hazardous Materials  |  acute  |  no  |   |  Accepting for transportation or transporting a package that has an identifiable release of a hazardous material to the environment  |  This is an acute violation of 49 CFR 173.24(b)(1): accepting for transportation or transporting a package that has an identifiable release of a hazardous material to the environment. An acute regulation is one where noncompliance is severe enough to require immediate corrective action, regardless of a carrier's overall...  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |   |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-084  |  173.421  |  Hazardous Materials  |  acute  |  no  |   |  Accepting for transportation or transporting a Class 7 (radioactive) material described, marked, and packaged as a limited quantity when the radiation level on the surface of the package exceeds 0.005mSv/hour (0.5 mrem/hour)  |  This is an acute violation of 49 CFR 173.421: accepting for transportation or transporting a Class 7 (radioactive) material described, marked, and packaged as a limited quantity when the radiation level on the surface of the package exceeds 0.005mSv/hour (0.5 mrem/hour). An acute regulation is one where noncompliance i...  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |   |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-085  |  173.431(a)  |  Hazardous Materials  |  acute  |  no  |   |  Accepting for transportation or transporting in a Type A packaging a greater quantity of Class 7 (radioactive) material than authorized  |  This is an acute violation of 49 CFR 173.431(a): accepting for transportation or transporting in a Type A packaging a greater quantity of Class 7 (radioactive) material than authorized. An acute regulation is one where noncompliance is severe enough to require immediate corrective action, regardless of a carrier's over...  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |   |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-086  |  173.431(b)  |  Hazardous Materials  |  acute  |  no  |   |  Accepting for transportation or transporting in a Type B packaging a greater quantity of Class 7 (radioactive) material than authorized  |  This is an acute violation of 49 CFR 173.431(b): accepting for transportation or transporting in a Type B packaging a greater quantity of Class 7 (radioactive) material than authorized. An acute regulation is one where noncompliance is severe enough to require immediate corrective action, regardless of a carrier's over...  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |   |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-087  |  173.441(a)  |  Hazardous Materials  |  acute  |  no  |   |  Accepting for transportation or transporting a package containing Class 7 (radioactive) material with external radiation exceeding allowable limits  |  This is an acute violation of 49 CFR 173.441(a): accepting for transportation or transporting a package containing Class 7 (radioactive) material with external radiation exceeding allowable limits. An acute regulation is one where noncompliance is severe enough to require immediate corrective action, regardless of a ca...  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |   |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-088  |  173.442(b)  |  Hazardous Materials  |  acute  |  no  |   |  Accepting for transportation or transporting a package containing Class 7 (radioactive) material when the temperature of the accessible external surface of the loaded package exceeds 50 °C (122 °F) in other than an exclusive use shipment, or 85 °C (185 °F) in an exclusive use shipment  |  This is an acute violation of 49 CFR 173.442(b): accepting for transportation or transporting a package containing Class 7 (radioactive) material when the temperature of the accessible external surface of the loaded package exceeds 50 °C (122 °F) in other than an exclusive use shipment, or 85 °C (185 °F) in an exclusiv...  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |   |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-089  |  173.443(a)  |  Hazardous Materials  |  acute  |  no  |   |  Accepting for transportation or transporting a package containing Class 7 (radioactive) material with removable contamination on the external surfaces of the package in excess of permissible limits  |  This is an acute violation of 49 CFR 173.443(a): accepting for transportation or transporting a package containing Class 7 (radioactive) material with removable contamination on the external surfaces of the package in excess of permissible limits. An acute regulation is one where noncompliance is severe enough to requi...  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |   |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-090  |  177.800(c)  |  Hazardous Materials  |  critical  |  no  |   |  Failing to instruct a category of employees in hazardous materials regulations  |  This is a critical violation of 49 CFR 177.800(c): failing to instruct a category of employees in hazardous materials regulations. A critical regulation relates to management or operational controls; it is scored when auditors find a pattern (more than one occurrence, generally at least 10% of the records examined).  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |   |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-091  |  177.801  |  Hazardous Materials  |  acute  |  no  |   |  Accepting for transportation or transporting a forbidden material  |  This is an acute violation of 49 CFR 177.801: accepting for transportation or transporting a forbidden material. An acute regulation is one where noncompliance is severe enough to require immediate corrective action, regardless of a carrier's overall safety posture. A single documented occurrence counts against you.  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |   |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-092  |  177.835(a)  |  Hazardous Materials  |  acute  |  no  |   |  Loading or unloading a Class 1 (explosive) material with the engine running  |  This is an acute violation of 49 CFR 177.835(a): loading or unloading a Class 1 (explosive) material with the engine running. An acute regulation is one where noncompliance is severe enough to require immediate corrective action, regardless of a carrier's overall safety posture. A single documented occurrence counts ag...  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |   |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-093  |  177.835(c)  |  Hazardous Materials  |  acute  |  no  |   |  Accepting for transportation or transporting Division 1.1 or 1.2 (explosive) materials in a motor vehicle or combination of vehicles that is not permitted  |  This is an acute violation of 49 CFR 177.835(c): accepting for transportation or transporting Division 1.1 or 1.2 (explosive) materials in a motor vehicle or combination of vehicles that is not permitted. An acute regulation is one where noncompliance is severe enough to require immediate corrective action, regardless ...  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |   |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-094  |  177.835(j)  |  Hazardous Materials  |  acute  |  no  |   |  Transferring Division 1.1, 1.2, or 1.3 (explosive) materials between containers or motor vehicles when not permitted  |  This is an acute violation of 49 CFR 177.835(j): transferring Division 1.1, 1.2, or 1.3 (explosive) materials between containers or motor vehicles when not permitted. An acute regulation is one where noncompliance is severe enough to require immediate corrective action, regardless of a carrier's overall safety posture....  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |   |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-095  |  177.817(a)  |  Hazardous Materials  |  critical  |  no  |   |  Transporting a shipment of hazardous materials not accompanied by a properly prepared shipping paper  |  This is a critical violation of 49 CFR 177.817(a): transporting a shipment of hazardous materials not accompanied by a properly prepared shipping paper. A critical regulation relates to management or operational controls; it is scored when auditors find a pattern (more than one occurrence, generally at least 10% of the...  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |   |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-096  |  177.817(e)  |  Hazardous Materials  |  critical  |  no  |   |  Failing to maintain proper accessibility of shipping papers  |  This is a critical violation of 49 CFR 177.817(e): failing to maintain proper accessibility of shipping papers. A critical regulation relates to management or operational controls; it is scored when auditors find a pattern (more than one occurrence, generally at least 10% of the records examined).  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |   |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-097  |  177.823(a)  |  Hazardous Materials  |  critical  |  no  |   |  Moving a transport vehicle containing hazardous material that is not properly marked or placarded  |  This is a critical violation of 49 CFR 177.823(a): moving a transport vehicle containing hazardous material that is not properly marked or placarded. A critical regulation relates to management or operational controls; it is scored when auditors find a pattern (more than one occurrence, generally at least 10% of the re...  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |   |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-098  |  177.841(e)  |  Hazardous Materials  |  acute  |  no  |   |  Transporting a package bearing a poison label in the same transport vehicle with material marked or known to be foodstuff, feed, or any edible material intended for consumption by humans or animals unless an exception in § 177.841(e)(i) or (ii) is met  |  This is an acute violation of 49 CFR 177.841(e): transporting a package bearing a poison label in the same transport vehicle with material marked or known to be foodstuff, feed, or any edible material intended for consumption by humans or animals unless an exception in § 177.841(e)(i) or (ii) is met. An acute regulatio...  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |   |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-099  |  180.407(a)  |  Hazardous Materials  |  critical  |  no  |   |  Transporting a shipment of hazardous material in cargo tank that has not been inspected or retested in accordance with § 180.407  |  This is a critical violation of 49 CFR 180.407(a): transporting a shipment of hazardous material in cargo tank that has not been inspected or retested in accordance with § 180.407. A critical regulation relates to management or operational controls; it is scored when auditors find a pattern (more than one occurrence, g...  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |   |  2026-07-04T00:00:00  |   |  
|  fmcsa-nesa-100  |  180.407(c)  |  Hazardous Materials  |  critical  |  no  |   |  Failing to periodically test and inspect a cargo tank  |  This is a critical violation of 49 CFR 180.407(c): failing to periodically test and inspect a cargo tank. A critical regulation relates to management or operational controls; it is scored when auditors find a pattern (more than one occurrence, generally at least 10% of the records examined).  |  https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385  |   |  2026-07-04T00:00:00  |   |  
End of preview. Expand in Data Studio⟨48⟩
* * *
  *  Previous⟨29⟩
  * 1⟨49⟩
  * 2⟨50⟩
  * Next ⟨50⟩


  * Dataset Summary⟨51⟩
  * Supported Tasks⟨52⟩
  * Languages⟨53⟩
  * Dataset Structure⟨54⟩
    * Files⟨55⟩
    * Column Schema⟨56⟩
    * Example rows⟨57⟩
  * Data Collection and Processing⟨58⟩
  * Source Data⟨59⟩
  * Licensing⟨60⟩
  * Citation⟨61⟩
  * Publisher notes⟨62⟩


#   ⟨63⟩ FMCSA New-Entrant Safety-Audit Violations Dataset 
##   ⟨51⟩ Dataset Summary 
103 acute and critical CFR regulations scored in an FMCSA new-entrant safety audit, including the 16 violations that automatically fail the audit under 49 CFR 385.321(b). Each row is sourced directly from the official Code of Federal Regulations and verified against ecfr.gov.
  * **Rows:** 103
  * **Scope:** All violations listed in 49 CFR Appendix B to Part 385
  * **Automatic-failure violations:** 16 (per 49 CFR 385.321(b))
  * **Severity classes:** acute (42 rows), critical (61 rows)
  * **Audit factors covered:** General, Driver, Operational, Vehicle, Hazardous Materials
  * **Verified:** 2026-07-04


**Use cases:** motor-carrier compliance tooling, safety audit preparation, regulatory research, transportation data analysis.
##   ⟨52⟩ Supported Tasks 
  * Reference lookup by CFR citation, factor, or automatic-failure status
  * Compliance gap analysis for new motor carriers
  * Safety audit preparation tools
  * Regulatory research


##   ⟨53⟩ Languages 
English (en)
##   ⟨54⟩ Dataset Structure 
###   ⟨55⟩ Files   
| File  | Format  | Description  |  
| --- | --- | --- |  
| `new-entrant-audit-violations.csv`  | CSV (UTF-8)  | All 103 rows  |  
| `new-entrant-audit-violations.json`  | JSON array  | Same data  |  
###   ⟨56⟩ Column Schema   
| Column  | Type  | Description  |  
| --- | --- | --- |  
| `id`  | string  | Stable row ID (e.g. `fmcsa-nesa-001`)  |  
| `cfr_cite`  | string  | CFR section (e.g. `395.3(a)(1)`)  |  
| `audit_factor`  | string  | Audit factor: General, Driver, Operational, Vehicle, or Hazardous Materials  |  
| `severity`  | enum  |  `acute` or `critical`  |  
| `automatic_failure`  | enum  |  `yes` if a single occurrence fails the audit; `no` otherwise  |  
| `auto_fail_guideline`  | string  | §385.321 guideline text (auto-fail rows only)  |  
| `description`  | string  | Verbatim short description from 49 CFR Appendix B  |  
| `plain_meaning`  | string  | Plain-language explanation of what the regulation requires  |  
| `source_url`  | URL  | Primary source — 49 CFR Appendix B to Part 385 at ecfr.gov  |  
| `auto_fail_source_url`  | URL  | 49 CFR 385.321(b) at ecfr.gov (auto-fail rows only)  |  
| `verified_on`  | ISO date  | Date the source URL was live-checked  |  
| `notes`  | string  | Optional disambiguation  |  
###   ⟨57⟩ Example rows 
**Automatic-failure violation (acute):**

```
{
  "id": "fmcsa-nesa-001",
  "cfr_cite": "382.115(a)",
  "audit_factor": "Driver",
  "severity": "acute",
  "automatic_failure": "yes",
  "auto_fail_guideline": "Single occurrence.",
  "description": "Failing to implement an alcohol and/or controlled substances testing program (domestic motor carrier)",
  "source_url": "https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385",
  "auto_fail_source_url": "https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/subpart-G/section-385.321",
  "verified_on": "2026-07-04"
}

```

**Critical violation (not automatic failure):**

```
{
  "id": "fmcsa-nesa-007",
  "cfr_cite": "382.301(a)",
  "audit_factor": "Driver",
  "severity": "critical",
  "automatic_failure": "no",
  "description": "Using a driver before the motor carrier has received a negative pre-employment controlled substance test result",
  "source_url": "https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385",
  "verified_on": "2026-07-04"
}

```

##   ⟨58⟩ Data Collection and Processing 
Every row is sourced directly from the official Code of Federal Regulations:
  1. **Primary source:** 49 CFR Appendix B to Part 385 ("List of Acute and Critical Regulations") at ecfr.gov — the authoritative list of regulations scored in an FMCSA safety audit.
  2. **Automatic-failure source:** 49 CFR 385.321(b) at ecfr.gov — the 16 regulations that automatically fail a new-entrant safety audit on a single occurrence.
  3. **Verification:** Each source URL was live-checked on 2026-07-04. No rows were fabricated or inferred.
  4. **Severity definitions:** Acute = noncompliance severe enough to require immediate corrective action regardless of overall safety posture (single occurrence scored); Critical = relates to management or operational controls, scored when auditors find a pattern (generally more than one occurrence, or at least 10% of records examined).


##   ⟨59⟩ Source Data 
  * **49 CFR Appendix B to Part 385** — List of Acute and Critical Regulations: <https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/appendix-Appendix%20B%20to%20Part%20385>
  * **49 CFR 385.321(b)** — Automatic failure violations: <https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-385/subpart-G/section-385.321>
  * **Full dataset + methodology:** <https://newentrantauditkit.com/data/new-entrant-audit-violations>


##   ⟨60⟩ Licensing 
This dataset is published under the **Creative Commons Attribution 4.0 International (CC BY 4.0)** license.
You are free to share and adapt for any purpose, including commercial use, with attribution.
**Attribution line:**
> CarrierReady (<https://newentrantauditkit.com/data/new-entrant-audit-violations>), CC BY 4.0.
The underlying CFR text (49 CFR Appendix B to Part 385 and 49 CFR 385.321) is US government work and not subject to copyright.
##   ⟨61⟩ Citation 

```
@misc{carrierready_fmcsa_violations_2026,
  title        = {{FMCSA New-Entrant Safety-Audit Violations Dataset}},
  author       = {{CarrierReady}},
  year         = {2026},
  url          = {https://newentrantauditkit.com/data/new-entrant-audit-violations},
  note         = {103 acute and critical CFR regulations scored in an FMCSA new-entrant safety audit, CC BY 4.0},
}

```

##   ⟨62⟩ Publisher notes 
  * Not legal advice. Always verify regulations against the official text at ecfr.gov, as the CFR is amended over time.
  * Not affiliated with, endorsed by, or connected to the FMCSA or any US government agency.
  * The Accident audit factor is scored by accident rate, not individual violations, so it has no rows in this dataset.


**To publish on HuggingFace/Kaggle:** use the brand account (not the founder's personal account). See builder-os/23-earned-media-and-data-assets.md for instructions.
Copy to bucket new
Use this dataset 

Downloads last month
    48
Number of rows: 103 Total file size: 183 kB
System theme
Company
TOS⟨64⟩ Privacy⟨65⟩ About⟨66⟩ Careers⟨67⟩ ⟨1⟩
Website
Models⟨2⟩ Datasets⟨3⟩ Spaces⟨4⟩ Pricing⟨8⟩ Docs⟨6⟩
