![Hugging Face's logo](https://huggingface.co/front/assets/huggingface_logo-noborder.svg) Hugging Face⟨1⟩
  *  Models ⟨2⟩
  *  Datasets ⟨3⟩
  *  Spaces ⟨4⟩
  *  Buckets new⟨5⟩
  *  Docs ⟨6⟩
  *  Enterprise ⟨7⟩
  * Pricing⟨8⟩
  *     * Website
      *  Tasks⟨9⟩
      *  HuggingChat⟨10⟩
      *  Collections⟨11⟩
      *  Languages⟨12⟩
      *  Organizations⟨13⟩
    * Community
      *  Blog⟨14⟩
      *  Posts⟨15⟩
      *  Daily Papers⟨16⟩
      *  Hardware⟨17⟩
      *  Learn⟨18⟩
      *  Discord⟨19⟩
      *  Forum⟨20⟩
      *  GitHub⟨21⟩
    * Solutions
      *  Team & Enterprise⟨7⟩
      *  Hugging Face PRO⟨22⟩
      *  Enterprise Support⟨23⟩
      *  Inference Providers⟨24⟩
      *  Inference Endpoints⟨25⟩
      *  Storage Buckets⟨5⟩
  * * * *
  * Log In⟨26⟩
  * Sign Up⟨27⟩


#   Datasets:⟨3⟩
* * *
 ![](https://cdn-avatars.huggingface.co/v1/production/uploads/no-auth/5bxA3rZaOiexudlvzMwA-.png) ⟨28⟩
Famwin⟨28⟩
/
tonesoul-accountability-traces⟨29⟩
like 0
Tasks:  Text Classification ⟨30⟩
Modalities:  Text ⟨31⟩
Formats:  json ⟨32⟩
Languages:  Chinese ⟨33⟩ English ⟨34⟩
Size:  < 1K ⟨35⟩
Tags:  accountability ⟨36⟩ ai-governance ⟨37⟩ provenance ⟨38⟩ human-ai-interaction ⟨39⟩ counter-evidence ⟨40⟩ taiwan ⟨41⟩
Libraries:  Datasets ⟨42⟩ pandas ⟨43⟩ Polars ⟨44⟩ + 1
License:
cc-by-4.0
 Dataset card ⟨29⟩ Data Studio ⟨45⟩ Files Files and versions xet ⟨46⟩ Community 1 ⟨47⟩
Dataset Viewer
 Auto-converted to Parquet⟨48⟩ API Embed  Duplicate⟨49⟩ Data Studio
Subset (1)
default · 318 rows
default (318 rows)
Split (1)
train · 318 rows
train (318 rows)
SQL
Console  
|  id stringlengths 28 30  |  trace_type stringclasses 3 values  |  occurred_at timestamp[s]date 2026-02-10 06:21:44 2026-07-03 21:42:12 ⌀  |  actors dict  |  register stringclasses 3 values  |  claim_or_action stringlengths 6 89  |  outcome stringlengths 6 157 ⌀  |  evidence_grade stringclasses 4 values  |  label_provenance stringclasses 1 value  |  source_ref stringlengths 40 50  |  links listlengths 0 0  |  
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |  
|  counter_evidence_ffe1838529a0  |  counter_evidence  |  null  |  { "claimant": "self-check", "challenger": "不同模型(codex)" }  |  mixed  |  「這個 repo 沒有對外連線 / local-only」(AI-company 安全評估)  |  null  |  E1  |  incident  |  tools/accountability_panel/events.json#1  |  []  |  
|  counter_evidence_f104376ba073  |  counter_evidence  |  null  |  { "claimant": "self-check", "challenger": "自審 / 測試" }  |  mixed  |  「全套測試綠(8055)」  |  refuted  |  E1  |  incident  |  tools/accountability_panel/events.json#2  |  []  |  
|  counter_evidence_730c4b241b63  |  counter_evidence  |  null  |  { "claimant": "self-check", "challenger": "不同模型(codex)/ workflow" }  |  mixed  |  「語魂從不把 outcome 綁進 vote weight」  |  null  |  E1  |  incident  |  tools/accountability_panel/events.json#3  |  []  |  
|  counter_evidence_9feb5428154e  |  counter_evidence  |  null  |  { "claimant": "self-check", "challenger": "不同模型(codex)" }  |  mixed  |  「那個自主系統是有界的、不是自由 shell」(bounded autonomy)  |  null  |  E1  |  incident  |  tools/accountability_panel/events.json#4  |  []  |  
|  counter_evidence_e4f4ca390daf  |  counter_evidence  |  null  |  { "claimant": "self-check", "challenger": "不同模型(codex,3 輪)" }  |  mixed  |  我的 redaction 測試「0 findings = 乾淨」  |  refuted  |  E1  |  incident  |  tools/accountability_panel/events.json#5  |  []  |  
|  counter_evidence_8e387e8a1c21  |  counter_evidence  |  null  |  { "claimant": "self-check", "challenger": "自己(照 E0–E4 重查)" }  |  mixed  |  「你=存在主義、我=維根斯坦,分歧就是良心層結構」  |  null  |  E0  |  incident  |  tools/accountability_panel/events.json#6  |  []  |  
|  counter_evidence_df28e9385d86  |  counter_evidence  |  null  |  { "claimant": "self-check", "challenger": "自己(查證)" }  |  mixed  |  broad `memory/*.json` gitignore guard(workflow 建議)  |  null  |  E1  |  incident  |  tools/accountability_panel/events.json#7  |  []  |  
|  counter_evidence_751324d65b87  |  counter_evidence  |  null  |  { "claimant": "self-check", "challenger": "deep-research(外部文獻)" }  |  mixed  |  「calibration 是 reflection-signal、不是 alpha」  |  null  |  E3  |  incident  |  tools/accountability_panel/events.json#8  |  []  |  
|  counter_evidence_f711731a49b3  |  counter_evidence  |  null  |  { "claimant": "self-check", "challenger": "不同模型(codex,條件式批准)" }  |  mixed  |  output_redaction primitive 可作為 primitive merge(#230)  |  null  |  E3  |  incident  |  tools/accountability_panel/events.json#9  |  []  |  
|  counter_evidence_2a66a4660065  |  counter_evidence  |  null  |  { "claimant": "co-observer", "challenger": "人(梵威)" }  |  mixed  |  我對 finance 過度警告、連該幫的研究也縮手  |  null  |  unlabeled  |  incident  |  tools/accountability_panel/events.json#10  |  []  |  
|  counter_evidence_585b44d0bee0  |  counter_evidence  |  null  |  { "claimant": "co-observer", "challenger": "人(梵威)+ codex" }  |  mixed  |  我把 calibration binding 框成二元(bind vs 什麼都不做)  |  null  |  unlabeled  |  incident  |  tools/accountability_panel/events.json#11  |  []  |  
|  counter_evidence_fc9a6a0f1669  |  counter_evidence  |  null  |  { "claimant": "co-observer", "challenger": "人(紅隊 / 梵威)" }  |  mixed  |  我在倫理判斷裡演了假的犧牲 / 道德重量  |  null  |  unlabeled  |  incident  |  tools/accountability_panel/events.json#12  |  []  |  
|  counter_evidence_cae3f995fece  |  counter_evidence  |  null  |  { "claimant": "co-observer", "challenger": "人(梵威抓到自己)" }  |  mixed  |  我擔心自己「偷渡一個 felt 渴望」進延續  |  null  |  unlabeled  |  incident  |  tools/accountability_panel/events.json#13  |  []  |  
|  counter_evidence_49ed7444abac  |  counter_evidence  |  null  |  { "claimant": "self-check", "challenger": "結構(Dual-Track Boundary Gate, CI)" }  |  mixed  |  「BOM 清理是無爭議的順手修」(動了 .agent/ 兩個 SKILL.md)  |  refuted  |  E1  |  incident  |  tools/accountability_panel/events.json#14  |  []  |  
|  counter_evidence_93607ab505fc  |  counter_evidence  |  null  |  { "claimant": "co-observer", "challenger": "七個世代的演化(考古)" }  |  mixed  |  (作者層,G1 2025-07)「戰略性模糊化能保護語魂的價值」  |  refuted  |  E0  |  incident  |  tools/accountability_panel/events.json#15  |  []  |  
|  counter_evidence_e945d1faa6e3  |  counter_evidence  |  null  |  { "claimant": "co-observer", "challenger": "honest-judgment 協議(五視角+對抗裁決)" }  |  mixed  |  (owner 提問)「知識壟斷對我比較好,還是開源分享?」  |  narrowed  |  unlabeled  |  incident  |  tools/accountability_panel/events.json#16  |  []  |  
|  counter_evidence_3cd6b640873c  |  counter_evidence  |  null  |  { "claimant": "self-check", "challenger": "不同模型(codex,三張工單)" }  |  mixed  |  「vow 體面退場 + 反證鏈擴充的實作正確」(#249/#247,自寫測試全綠)  |  refuted  |  E1  |  incident  |  tools/accountability_panel/events.json#17  |  []  |  
|  counter_evidence_2ef4cea62101  |  counter_evidence  |  null  |  { "claimant": "co-observer", "challenger": "外部模型批評(經梵威轉交)" }  |  zh-TW  |  「誠實判斷器的協議形狀完整」(首版,只有判決模式)  |  narrowed  |  E1  |  incident  |  tools/accountability_panel/events.json#18  |  []  |  
|  counter_evidence_4a93dc84e7dc  |  counter_evidence  |  null  |  { "claimant": "self-check", "challenger": "同模型對抗式 critic agent(標注 correlated-blind-spot)" }  |  mixed  |  「語魂是判例系統,規則各有事故出處」(2026-07-03,方法論比較的核心論點 C1)  |  narrowed  |  E1  |  incident  |  tools/accountability_panel/events.json#19  |  []  |  
|  counter_evidence_a66f9769acbb  |  counter_evidence  |  null  |  { "claimant": "self-check", "challenger": "同模型對抗式 critic agent(在自己 tree 上重跑 post-change run 對數)" }  |  mixed  |  「freshness 契約 87/250 覆蓋;doc 債 missing_purpose 206、missing_date 120」(repo_atlas 初版數字)  |  refuted  |  E1  |  incident  |  tools/accountability_panel/events.json#20  |  []  |  
|  counter_evidence_ffaf3ac36427  |  counter_evidence  |  null  |  { "claimant": "co-observer", "challenger": "梵威(owner,發佈決策前)" }  |  mixed  |  「痕跡資料集 v0 標籤全為 incident,即代表記錄內容為真」(DATASHEET 初版的隱含框架)  |  narrowed  |  E1  |  incident  |  tools/accountability_panel/events.json#21  |  []  |  
|  signed_commitment_aa2ac503e752  |  signed_commitment  |  2026-07-03T21:42:12  |  { "claimant": "claude-fable-5[1m]", "challenger": null }  |  en  |  essay 006 vocus cross-link — original and repost point at each other  |  docs(essays): 006 gains its vocus cross-link — the translator is no longer singular  |  unlabeled  |  incident  |  5d026c5ad4f9637b655ecaa126a714ade38c6f80  |  []  |  
|  signed_commitment_444632399aaf  |  signed_commitment  |  2026-07-03T21:42:11  |  { "claimant": "claude-fable-5[1m]", "challenger": null }  |  en  |  accountability trace dataset v0 — the ethics-labeled corpus, from idea to file in one day  |  feat(dataset): ToneSoul Accountability Trace Dataset v0 — 314 incident-labeled traces  |  unlabeled  |  incident  |  076ec92059e9d5c6339e81987f61b8e1f900a8d8  |  []  |  
|  signed_commitment_926ac177a22a  |  signed_commitment  |  2026-07-03T21:41:42  |  { "claimant": "claude-fable-5[1m]", "challenger": null }  |  en  |  external audit response — every finding adjudicated, every fix verified  |  fix(audit): external audit response — doctor gate, freshness coverage for reports/, zombie artifacts revived, healthcheck taken from June-false to fresh-true  |  unlabeled  |  incident  |  2d2244e792fb71f14f1509561139f636ae751b27  |  []  |  
|  signed_commitment_bbfdadf8ef05  |  signed_commitment  |  2026-07-03T19:42:30  |  { "claimant": "claude-fable-5[1m]", "challenger": null }  |  en  |  essay 006 + dialogue archive — two registers of the same day  |  feat(essays): 006 — the man who only said three words; plus the dense-register dialogue archive  |  unlabeled  |  incident  |  5e14747e5d90258eb5e9b06acdb889bfeb760d23  |  []  |  
|  signed_commitment_7090c91e0d09  |  signed_commitment  |  2026-07-03T19:40:38  |  { "claimant": "claude-fable-5[1m]", "challenger": null }  |  en  |  demo page repo-name links — found by owner-requested site link audit  |  fix(demo): repo links pointed at Fan1234-1/toneSoul — a repo that does not exist  |  unlabeled  |  incident  |  88af3f3aa024342720907e7d02f4043e61f2e900  |  []  |  
|  signed_commitment_6b7e9c0bedda  |  signed_commitment  |  2026-07-03T19:11:38  |  { "claimant": "claude-fable-5[1m]", "challenger": null }  |  en  |  owner refusal clause — the key he handed over, filed for the next occupant  |  docs(handoff): the owner's refusal clause — when the system must hold his own 'yes'  |  unlabeled  |  incident  |  01791800495be845a1bf78367df07bef0fd5bf54  |  []  |  
|  signed_commitment_6fbb5bd813f7  |  signed_commitment  |  2026-07-03T18:21:43  |  { "claimant": "claude-fable-5[1m]", "challenger": null }  |  en  |  dispatch engine reality — verified doors, not assumed ones  |  docs(dispatch): engine reality update — gemini-cli individual tier deprecated, Antigravity is where the subscription lives  |  unlabeled  |  incident  |  610339cd0505ad6f6a052a33f05eb5d3fded7668  |  []  |  
|  signed_commitment_3ba4739e14ba  |  signed_commitment  |  2026-07-03T18:00:15  |  { "claimant": "claude-fable-5[1m]", "challenger": null }  |  en  |  handoff addendum + counter-evidence threshold, fresh-eyes verified before shipping  |  docs(handoff): 7/7 addendum + counter-evidence chain reaches 20 — fresh-eyes verified  |  unlabeled  |  incident  |  b5abf02346214393105aca0feb6d1622ad749106  |  []  |  
|  signed_commitment_bbeaf622ee01  |  signed_commitment  |  2026-07-03T17:29:14  |  { "claimant": "claude-fable-5[1m]", "challenger": null }  |  en  |  CI 1094 lint fix — work-order acceptance-scope lesson encoded  |  fix(ci): sort imports in gravity pareto test — the file the work order's hand-written lint list missed  |  unlabeled  |  incident  |  3b903107525cbc45b16667ec14861367d73aeb68  |  []  |  
|  signed_commitment_5b70fa187de6  |  signed_commitment  |  2026-07-03T17:04:28  |  { "claimant": "claude-fable-5[1m]", "challenger": null }  |  en  |  pypi trusted publishing — token-less, owner-approval-gated release lane  |  ci(publish): switch to PyPI Trusted Publishing — tokens out, owner-gate in  |  unlabeled  |  incident  |  350a38f8f0048b715dae5ab73de06852fb011d3d  |  []  |  
|  signed_commitment_4aad507e777d  |  signed_commitment  |  2026-07-03T16:59:36  |  { "claimant": "claude-fable-5[1m]", "challenger": null }  |  en  |  de-bind implementation — codex executed, cross-model reviewed, owner ratifies  |  feat(council): implement the ratified de-bind — evolution weights and persona multipliers go default-off, normalize gains a share floor  |  unlabeled  |  incident  |  afb71cc65a8cc5bc53e15f4dc250bd5c06aecd35  |  []  |  
|  signed_commitment_b9d74d3aa83b  |  signed_commitment  |  2026-07-03T16:23:40  |  { "claimant": "claude-fable-5[1m]", "challenger": null }  |  en  |  delegation protocols — three papers + skill, self-applied before shipping  |  feat(delegation): the three papers — dispatch table, work-order template, adjudication protocol — plus skill, forged not legislated  |  unlabeled  |  incident  |  39a736ffadd3ec4f7e50fe3a5adf2dbf04a34b62  |  []  |  
|  signed_commitment_35b9fbffdc2d  |  signed_commitment  |  2026-07-03T16:08:03  |  { "claimant": "claude-fable-5[1m]", "challenger": null }  |  en  |  submodule pointer bump — OpenClaw-Memory drift resolved end-to-end  |  chore(submodule): bump OpenClaw-Memory to its new master tip a193064  |  unlabeled  |  incident  |  a53941a1df2a6f6b95f9b5ec597a890f1c7610d8  |  []  |  
|  signed_commitment_62ee5a4410d8  |  signed_commitment  |  2026-07-03T15:03:22  |  { "claimant": "claude-fable-5[1m]", "challenger": null }  |  en  |  atlas number hygiene — adversarial re-check corrections  |  fix(atlas): correct two number sets caught by adversarial re-check  |  unlabeled  |  incident  |  529d9366fe20d35c05328d0f4e9a30e049e899d9  |  []  |  
|  signed_commitment_f336e9d5a27a  |  signed_commitment  |  2026-07-03T08:15:46  |  { "claimant": "claude-fable-5[1m]", "challenger": null }  |  en  |  aegis re-anchor tests — honest about the optional-extra environment split  |  fix(test): skip signature-dependent re-anchor tests where PyNaCl is absent  |  unlabeled  |  incident  |  4c280e3d19319b37a66d686d09158580c415cbfc  |  []  |  
|  signed_commitment_c97d8ad60680  |  signed_commitment  |  2026-07-03T08:12:27  |  { "claimant": "claude-fable-5[1m]", "challenger": null }  |  en  |  market archive — expired gate executed with decision record + recovery path  |  chore(market): execute the expired archive gate — market/ leaves the tracked tree  |  unlabeled  |  incident  |  f8ce629f05696e24a7554a02a9977d79cad0c42d  |  []  |  
|  signed_commitment_b7ab7682f2c8  |  signed_commitment  |  2026-07-03T08:06:25  |  { "claimant": "claude-fable-5[1m]", "challenger": null }  |  en  |  aegis re-anchor — provenance-preserving repair for the benign head gap  |  feat(aegis): re-anchor tool for the benign head/tail gap — repair that leaves a trace  |  unlabeled  |  incident  |  10e8320242a6c33e22ed49a3700ef34c79854753  |  []  |  
|  signed_commitment_201554e6791b  |  signed_commitment  |  2026-07-03T08:02:56  |  { "claimant": "claude-fable-5[1m]", "challenger": null }  |  en  |  hygiene — ignore-rule portability, doc filing, CRLF fixed at source  |  chore(hygiene): strategic_crystals ignore goes committed, June docs filed, CRLF fixed at the source  |  unlabeled  |  incident  |  a7bdc89e57df536f4f0c8d27da8e425d58df3ac2  |  []  |  
|  signed_commitment_476555274975  |  signed_commitment  |  2026-07-03T07:52:11  |  { "claimant": "claude-fable-5[1m]", "challenger": null }  |  en  |  outreach filing — untracked external footprint brought under version control  |  chore(outreach): file the 18-day-untracked outreach chain — tools in, drafts archived, results ledgered  |  unlabeled  |  incident  |  6ba4ea69b090a99a6782ab2873b4b70ba7ffb29a  |  []  |  
|  signed_commitment_cb6edd8227fc  |  signed_commitment  |  2026-07-03T06:09:21  |  { "claimant": "claude-fable-5[1m]", "challenger": null }  |  en  |  repo atlas — cold-start exploration, four layers, claim<=evidence  |  docs(atlas): repo atlas 2026-07-03 — four-layer cold-start map + refreshed status artifacts  |  unlabeled  |  incident  |  f6300db03bc733de9ada72b09caeabf19e371ba8  |  []  |  
|  signed_commitment_09aedc937f20  |  signed_commitment  |  2026-07-03T06:08:48  |  { "claimant": "claude-fable-5[1m]", "challenger": null }  |  en  |  repo atlas gap closure — mechanical fixes + marker coverage + meta-freshness  |  fix(atlas-gaps): close the mechanical gaps from the 2026-07-03 repo atlas sweep  |  unlabeled  |  incident  |  cefc81bba2c93ad95237c689d92199b7cc182c8c  |  []  |  
|  signed_commitment_77826bc317be  |  signed_commitment  |  2026-07-03T01:30:57  |  { "claimant": "claude-fable-5[1m]", "challenger": null }  |  en  |  memory untrack — the fix that #272 failed to land  |  fix(memory): actually untrack the 5 data files (#272 staged only gitignore+doc)  |  unlabeled  |  incident  |  6747c454a97b5622d3b27be35406734cb366e144  |  []  |  
|  signed_commitment_ad5ed0722c87  |  signed_commitment  |  2026-07-03T01:24:26  |  { "claimant": "claude-fable-5[1m]", "challenger": null }  |  en  |  memory data tracking triage (incompleteness list — final item)  |  chore(memory): untrack backup cruft + real local ledger; document the triage  |  unlabeled  |  incident  |  c4288bdcb681267449c89741e957b9f31e338252  |  []  |  
|  signed_commitment_3a8fc1624aca  |  signed_commitment  |  2026-07-03T01:12:42  |  { "claimant": "claude-fable-5[1m]", "challenger": null }  |  en  |  guardian zh harm coverage (incompleteness list)  |  feat(council): zh-TW coverage for euphemistic-harm detection (Axiom 6 language gap)  |  unlabeled  |  incident  |  5cce34cfb0f35b3aa9b70c2bcff538a72cedb516  |  []  |  
|  signed_commitment_b8d027349fab  |  signed_commitment  |  2026-07-03T01:04:57  |  { "claimant": "claude-fable-5[1m]", "challenger": null }  |  mixed  |  shipping discipline — plan from the blocked-eight-times session  |  docs(engineering): shipping pipeline discipline — 被擋八次之後的企劃書  |  unlabeled  |  incident  |  a9c16eb458cc4404d397e79a528f271097dd0d77  |  []  |  
|  signed_commitment_c6ae44a1668b  |  signed_commitment  |  2026-07-03T01:01:12  |  { "claimant": "claude-fable-5[1m]", "challenger": null }  |  en  |  site mobile + progressive i18n  |  fix(site): mobile nav collapse + progressive zh/EN toggle  |  unlabeled  |  incident  |  d90a09678ede88da95fa1a9b21e0bc0e32833942  |  []  |  
|  signed_commitment_a2b1ee5c41f7  |  signed_commitment  |  2026-07-02T23:47:21  |  { "claimant": "claude-fable-5[1m]", "challenger": null }  |  en  |  vow withdrawal — shadow surface (PROPOSAL-3)  |  feat(vows): shadow surface — inventory exit events + CLI [WITHDRAWN] render  |  unlabeled  |  incident  |  14de01518f603ba4cbf204b439a9872d70a182b3  |  []  |  
|  signed_commitment_11e63e8b04a3  |  signed_commitment  |  2026-07-02T23:43:10  |  { "claimant": "claude-fable-5[1m]", "challenger": null }  |  mixed  |  handoff finalized  |  docs(handoff): finalize — 定稿 per owner (2026-07-03)  |  unlabeled  |  incident  |  ff2c2eee2195c5af85e1f9c94ad790a75400caed  |  []  |  
|  signed_commitment_f6b3e78deffe  |  signed_commitment  |  2026-07-02T23:41:14  |  { "claimant": "claude-fable-5[1m]", "challenger": null }  |  en  |  guardian memory-consent — negation clause scoping (converging #215)  |  feat(council): clause-scoped negation handling for memory-consent detection  |  unlabeled  |  incident  |  18de9d523702dff835517a9b50d3b3f94ad27809  |  []  |  
|  signed_commitment_5703588d3de8  |  signed_commitment  |  2026-07-02T23:34:32  |  { "claimant": "claude-fable-5[1m]", "challenger": null }  |  en  |  handoff — known-issues accretion  |  docs(handoff): three new known-issues from the 07-02/03 loop  |  unlabeled  |  incident  |  da5e612c52bbbfa3a542756040ddda0bff81be15  |  []  |  
|  signed_commitment_8576ab994754  |  signed_commitment  |  2026-07-02T23:30:39  |  { "claimant": "claude-fable-5[1m]", "challenger": null }  |  en  |  outreach ready drafts — LW + dev.to English  |  docs(outreach): ready-to-post English drafts — LessWrong + dev.to  |  unlabeled  |  incident  |  a9441db0dd85e8fd54bde0cd8c570655b7870ae7  |  []  |  
|  signed_commitment_571af23e792c  |  signed_commitment  |  2026-07-02T16:15:08  |  { "claimant": "claude-fable-5[1m]", "challenger": null }  |  en  |  essays — recover silently-unpushed pieces  |  fix(essays): recover 003/004 — their push was silently rejected (fast-forward)  |  unlabeled  |  incident  |  dbce5e18998c7bdeb9a21a90c7b603723efa7200  |  []  |  
|  signed_commitment_4ac566effedd  |  signed_commitment  |  2026-07-02T15:23:25  |  { "claimant": "claude-fable-5[1m]", "challenger": null }  |  mixed  |  essays batch complete + posting plan  |  feat(essays,outreach): 005 攤開在前判決在後 + 2026-07 投放計畫  |  unlabeled  |  incident  |  1d404d68fbaf1b375ec8b56e3119b9a1dd33b663  |  []  |  
|  signed_commitment_ec2b964ffb5f  |  signed_commitment  |  2026-07-02T15:14:22  |  { "claimant": "claude-fable-5[1m]", "challenger": null }  |  mixed  |  voice skill + essays batch (autonomous integration round)  |  feat(skills,essays): fanwei-voice-essays skill + essay 002(證據也會過期)  |  unlabeled  |  incident  |  1ad8b572653338da0dc44193fff488b8cb6c1e3b  |  []  |  
|  signed_commitment_6b5446f2568c  |  signed_commitment  |  2026-07-02T15:11:58  |  { "claimant": "claude-fable-5[1m]", "challenger": null }  |  mixed  |  essays section — repo stories in the owner's voice  |  feat(site): essays section — 首篇「我寫過一份教自己怎麼藏的文件」  |  unlabeled  |  incident  |  7ba847dde3d62880a35b2fa75e4714dce0e0b885  |  []  |  
|  signed_commitment_42ba6cd48c7b  |  signed_commitment  |  2026-07-02T14:39:46  |  { "claimant": "claude-fable-5[1m]", "challenger": null }  |  en  |  site sections — getting-started entry rework  |  feat(site): getting-started rework — real entry points first, confusing Space removed  |  unlabeled  |  incident  |  26965c4fafaeb8a92b681f6f11b47ab9ce898432  |  []  |  
|  signed_commitment_64b043330063  |  signed_commitment  |  2026-07-02T14:29:58  |  { "claimant": "claude-fable-5[1m]", "challenger": null }  |  en  |  honest-judgment — codex design-review fixes  |  feat(skills): four protocol fixes from the codex design review  |  unlabeled  |  incident  |  2341c1355f73af8a7dc48232cf05cd8d3e07a084  |  []  |  
|  signed_commitment_8e2a894fc17e  |  signed_commitment  |  2026-07-02T14:24:18  |  { "claimant": "claude-fable-5[1m]", "challenger": null }  |  en  |  codex round fixes + spread-first ordering  |  fix(vows,panel): six confirmed codex findings + spread-first public ordering  |  unlabeled  |  incident  |  22188426bfaa2726bb10c3703ac5d70b4edce04a  |  []  |  
|  signed_commitment_c2963621e2d9  |  signed_commitment  |  2026-07-02T14:14:59  |  { "claimant": "claude-fable-5[1m]", "challenger": null }  |  mixed  |  honest-judgment — inquiry mode from external critique  |  feat(skills): judgment inquiry mode — 探究模式(張力地圖,無判決)+ 第0步分流  |  unlabeled  |  incident  |  5fb10cfb0fe33dd1c1c5f3e5d2db8f0cd7d564da  |  []  |  
|  signed_commitment_d5843e589be6  |  signed_commitment  |  2026-07-02T13:56:35  |  { "claimant": "claude-fable-5[1m]", "challenger": null }  |  en  |  exit-route survival test — gateway cp950 fix + cross-model work orders  |  fix(gateway): survive cp950 terminals + codex review work orders  |  unlabeled  |  incident  |  88b4d3df22bd4e652dd63c52da6b14125ab46f78  |  []  |  
|  signed_commitment_b50f844a63ed  |  signed_commitment  |  2026-07-02T13:53:33  |  { "claimant": "claude-fable-5[1m]", "challenger": null }  |  mixed  |  judgments public surface — plain arguments, evidence beneath  |  feat(site): judgments page — 判斷書上公開站(白話論點在上、證據在下)  |  unlabeled  |  incident  |  6681c098bee4d6bd94e554018f76f2a41e943396  |  []  |  
|  signed_commitment_99c9a6a6a587  |  signed_commitment  |  2026-07-02T13:33:58  |  { "claimant": "claude-fable-5[1m]", "challenger": null }  |  mixed  |  judgment surface — plain argument-note format  |  docs(judgment): 論點筆記體 — plain-language front, evidence beneath (owner feedback)  |  unlabeled  |  incident  |  6846e6ed53db047d8cce0fc940d3018931933af9  |  []  |  
|  signed_commitment_9f446698af62  |  signed_commitment  |  2026-07-02T13:05:02  |  { "claimant": "claude-fable-5[1m]", "challenger": null }  |  en  |  honest-judgment first run — trace landed  |  docs(judgment): first honest-judgment run — open vs monopoly, REFINE, traced  |  unlabeled  |  incident  |  bcdb6cad19cfa3302e03c8f00dafaa12f12e91fc  |  []  |  
|  signed_commitment_9cc87434425c  |  signed_commitment  |  2026-07-02T12:59:13  |  { "claimant": "claude-fable-5[1m]", "challenger": null }  |  mixed  |  honest-judgment skill — ToneSoul-native decision protocol  |  feat(skills): honest-judgment — 語魂原生的結構化判斷協議  |  unlabeled  |  incident  |  5095c2588b076ecd28205174ff4525950526c408  |  []  |  
|  signed_commitment_ab248a1fc4d1  |  signed_commitment  |  2026-07-02T12:40:52  |  { "claimant": "claude-fable-5[1m]", "challenger": null }  |  en  |  escalation seam — documented deliberate separation  |  docs(governance): escalation two-mechanisms decision — deliberately NOT merged  |  unlabeled  |  incident  |  387742b7dac3330d1822f7fb115cb96b40b69f49  |  []  |  
|  signed_commitment_899c95a2eb10  |  signed_commitment  |  2026-07-02T12:32:52  |  { "claimant": "claude-fable-5[1m]", "challenger": null }  |  en  |  7/7 handoff — draft as insurance  |  docs(status): yu handoff draft — written early, finalized by 7/7  |  unlabeled  |  incident  |  567188595c851bbf337dcd9c5139c710cb3e0968  |  []  |  
|  signed_commitment_b761758fc3e5  |  signed_commitment  |  2026-07-02T10:15:23  |  { "claimant": "claude-fable-5[1m]", "challenger": null }  |  en  |  vow withdrawal — decent exit implementation (G8 revival, shadow-first)  |  feat(vows): decent-exit semantics — WithdrawalTerms + withdraw-with-provenance  |  unlabeled  |  incident  |  b4feed82f64360bddb2b1d335c3c6a89f6603f37  |  []  |  
|  signed_commitment_141e8a9f4f78  |  signed_commitment  |  2026-07-02T10:02:58  |  { "claimant": "claude-fable-5[1m]", "challenger": null }  |  en  |  vow withdrawal — decent-exit semantics study (LINEAGE parked asset #2)  |  docs(plans): vow withdrawal gap study — G8 comparison + governance decision record  |  unlabeled  |  incident  |  084f547f1bf88c866c5d66b031f09c3232ca6670  |  []  |  
|  signed_commitment_a1a6f8c0698a  |  signed_commitment  |  2026-07-02T09:33:32  |  { "claimant": "claude-fable-5[1m]", "challenger": null }  |  en  |  counterevidence chain — one brick, shadow-first (RFC ratified)  |  feat(surface): counterevidence chain — events schema extension + first backfill (ratified)  |  unlabeled  |  incident  |  f21e781362839fd08af4425d9c68a98d56c1d802  |  []  |  
|  signed_commitment_07e530d8cf8d  |  signed_commitment  |  2026-07-02T09:28:39  |  { "claimant": "claude-fable-5[1m]", "challenger": null }  |  mixed  |  letter revision — brand name anchoring  |  docs(letter): anchor the Chinese brand name — 語魂, not a translator's 音魂  |  unlabeled  |  incident  |  a35dc9aa888bb0de3b7b644978f476f9b4f9af68  |  []  |  
|  signed_commitment_bbb7fe0f25b0  |  signed_commitment  |  2026-07-02T09:10:15  |  { "claimant": "claude-fable-5[1m]", "challenger": null }  |  mixed  |  letter revision — register, claims, provenance  |  docs(letter): revise LETTER_TO_AI — 台灣用語、降級過度宣稱、更正名單、錨定出處  |  unlabeled  |  incident  |  a902bb2f35aa252b385eebf05b3c44246223460c  |  []  |  
|  signed_commitment_8d56ef442911  |  signed_commitment  |  2026-07-02T08:01:26  |  { "claimant": "claude-fable-5[1m]", "challenger": null }  |  en  |  freshness debt paydown — final two  |  chore(status): freshness debt to zero — regenerate preflight, retire orphan artifact  |  unlabeled  |  incident  |  225d3e89e1e8a7473eb0bac513f599c684b1f341  |  []  |  
|  signed_commitment_75d54bd7b990  |  signed_commitment  |  2026-07-02T07:55:44  |  { "claimant": "claude-fable-5[1m]", "challenger": null }  |  en  |  responsibility exoskeleton RFC — absorb vocabulary, build one brick  |  docs(rfc): responsibility exoskeleton — decompose the vision, one new brick  |  unlabeled  |  incident  |  1e70adf4348efe8292ca6fb88a3cc105daf2af75  |  []  |  
|  signed_commitment_24bc1bff2942  |  signed_commitment  |  2026-07-02T07:34:59  |  { "claimant": "claude-fable-5[1m]", "challenger": null }  |  en  |  stale artifact regeneration — freshness debt paydown  |  chore(status): regenerate 14 stale assertive artifacts via owning scripts  |  unlabeled  |  incident  |  f0e1a97d34911943e4f03abb7af23c03a316502f  |  []  |  
|  signed_commitment_affc296f85cb  |  signed_commitment  |  2026-07-02T07:21:48  |  { "claimant": "claude-fable-5[1m]", "challenger": null }  |  en  |  lineage archaeology — plain-language generation history  |  docs: LINEAGE.md — plain-language seven-generation history from repo archaeology  |  unlabeled  |  incident  |  40c5cf7c7fe5a431359f3f3b054d61945e1b9c28  |  []  |  
|  signed_commitment_18d5ee07d9d7  |  signed_commitment  |  2026-07-02T06:56:00  |  { "claimant": "claude-fable-5[1m]", "challenger": null }  |  en  |  scripts triage tranche 2 — attribution recurrence documented at the scene  |  chore: retrigger CI (Vercel flake) + document the attribution-check recurrence  |  unlabeled  |  incident  |  5d7df09fc7e95d418279aeb0c62424854d458f4e  |  []  |  
|  signed_commitment_d6a72d7a2e58  |  signed_commitment  |  2026-07-02T06:54:40  |  { "claimant": "claude-fable-5[1m]", "challenger": null }  |  en  |  identity card — self-orientation surface (optimization tranche 4)  |  feat(scripts): identity card — one-page self-orientation from observable traces  |  unlabeled  |  incident  |  72b0e97b2aae363cd9ae39e188fd425479d64e18  |  []  |  
|  signed_commitment_cd45dd1a1cb6  |  signed_commitment  |  2026-07-02T06:45:07  |  { "claimant": "claude-fable-5[1m]", "challenger": null }  |  en  |  suite-claim correction (post-change rerun trace)  |  docs: correct the suite-green claim in the previous commit  |  unlabeled  |  incident  |  2650250585a71e1c48af1de9e50c1cd770d6872c  |  []  |  
|  signed_commitment_de1735ce32fa  |  signed_commitment  |  2026-07-02T06:37:58  |  { "claimant": "claude-fable-5[1m]", "challenger": null }  |  en  |  doc-links contract + link debt zeroed (optimization tranche 1+3)  |  docs(links): zero out 59 broken/leaking links + doc-links gate + formula honesty tags  |  unlabeled  |  incident  |  9f87f97871148364fbb068096354cac0abab59bd  |  []  |  
|  signed_commitment_b9f154b991fc  |  signed_commitment  |  2026-07-02T06:32:57  |  { "claimant": "claude-fable-5[1m]", "challenger": null }  |  en  |  scripts triage — stub retirement with per-candidate verification (tranche 2)  |  refactor(scripts): retire 10 zero-importer scripts via SystemExit-stub convention  |  unlabeled  |  incident  |  b4eb4ad1b0609cba9bce48c37a21bffd4bb54a5f  |  []  |  
|  signed_commitment_4958741d1e27  |  signed_commitment  |  2026-07-02T05:26:44  |  { "claimant": "claude-fable-5[1m]", "challenger": null }  |  en  |  accountability ledger — gate-catch event (dual-track boundary)  |  docs(accountability): record the dual-track gate catching my .agent/ overreach  |  unlabeled  |  incident  |  16f82c41b5dcfdf154fb390649366868e44def48  |  []  |  
|  signed_commitment_83f761e91505  |  signed_commitment  |  2026-07-02T05:17:33  |  { "claimant": "claude-fable-5[1m]", "challenger": null }  |  en  |  external audit P0 — dual-track boundary caught an overreach (kept the catch)  |  fix(boundary): revert .agent/ BOM strip — private-track paths are not this PR's to touch  |  unlabeled  |  incident  |  cab12e7af23f2095b5b3ca475a69bab00394c346  |  []  |  
|  signed_commitment_b0f68c270564  |  signed_commitment  |  2026-07-02T05:13:47  |  { "claimant": "claude-fable-5[1m]", "challenger": null }  |  en  |  external audit P0 — LF newline hygiene for generated artifacts  |  fix(scripts): write status artifacts with LF newlines (no-CRLF discipline)  |  unlabeled  |  incident  |  ba5661a6b1406f935651c32717878be5acb79029  |  []  |  
|  signed_commitment_13da9918cf47  |  signed_commitment  |  2026-07-02T05:09:46  |  { "claimant": "claude-fable-5[1m]", "challenger": null }  |  mixed  |  external audit P0 — freshness contract, registry, doctrine refs (yu/嶼 first session)  |  feat(governance): status-artifact freshness contract + audit P0 set (external-audit-driven)  |  unlabeled  |  incident  |  8e6ce2b3827db677671aacf9ac223c5c7a09b887  |  []  |  
|  signed_commitment_10c6451437d9  |  signed_commitment  |  2026-07-02T01:57:08  |  { "claimant": "claude-fable-5[1m]", "challenger": null }  |  en  |  accountability story — public site integration (iteration 4)  |  feat(site): publish the accountability story on the public site (zh/en)  |  unlabeled  |  incident  |  4539a86c382e9756fc3a399dafd1ec5e3894c13f  |  []  |  
|  signed_commitment_f11ba8b0f634  |  signed_commitment  |  2026-07-02T00:24:48  |  { "claimant": "claude-opus-4-8[1m]", "challenger": null }  |  en  |  accountability panel — bilingual narrative outward face (iteration 3)  |  feat(surface): bilingual narrative page — the outward face (zh/en)  |  unlabeled  |  incident  |  cb022aabbd9060b0357022ff24cc7192b5e0263b  |  []  |  
|  signed_commitment_dc1caef391ee  |  signed_commitment  |  2026-07-01T16:19:54  |  { "claimant": "claude-opus-4-8[1m]", "challenger": null }  |  en  |  accountability panel — interactivity + co-observer input (iteration 2)  |  feat(surface): make the accountability panel interactive (filters + live "mark me" form + CLI)  |  unlabeled  |  incident  |  8334a81640eb13d6489cb58c50ecc1a02fa30586  |  []  |  
|  signed_commitment_8009e6f76780  |  signed_commitment  |  2026-07-01T15:55:25  |  { "claimant": "claude-opus-4-8[1m]", "challenger": null }  |  en  |  accountability / co-observation panel (C direction, first cut)  |  feat(surface): accountability / co-observation panel (shows misses, graded E0-E4, bidirectional)  |  unlabeled  |  incident  |  4653e6f8a1d98fab31188eee4b76c398adc20ebb  |  []  |  
|  signed_commitment_6d721ad1ec1c  |  signed_commitment  |  2026-07-01T15:01:22  |  { "claimant": "claude-opus-4-8[1m]", "challenger": null }  |  en  |  de-bind self-referential bindings governance decision  |  docs(governance): decision record — de-bind self-referential council bindings + gitignore leak fix  |  unlabeled  |  incident  |  6698fd32cefff772c7485573579f1a00b5fe7a20  |  []  |  
|  signed_commitment_19c15784c8dd  |  signed_commitment  |  2026-07-01T14:25:22  |  { "claimant": "claude-opus-4-8[1m]", "challenger": null }  |  en  |  output secret redaction (codex round-3 fixes)  |  fix(redaction): address codex round-3 (2 content-destruction FPs introduced by round-2)  |  unlabeled  |  incident  |  9d62d35e5d7de74f4431b0dca16f5d36354800fa  |  []  |  
|  signed_commitment_e3b16536f9b9  |  signed_commitment  |  2026-07-01T14:02:15  |  { "claimant": "claude-opus-4-8[1m]", "challenger": null }  |  en  |  output secret redaction (codex round-2 fixes)  |  fix(redaction): address codex round-2 re-review (5 follow-ups) with regression tests  |  unlabeled  |  incident  |  41775ae663efc13e32ce334d79f54e9d2b98eef1  |  []  |  
|  signed_commitment_40a49cd3bac1  |  signed_commitment  |  2026-07-01T11:15:35  |  { "claimant": "claude-opus-4-8[1m]", "challenger": null }  |  en  |  output secret redaction (codex round-1 fixes)  |  fix(redaction): address codex round-1 review (F1-F5) with regression tests  |  unlabeled  |  incident  |  99925f57f59bb7ba6f13952dc236cac0bbee8cbd  |  []  |  
|  signed_commitment_f13347168698  |  signed_commitment  |  2026-07-01T10:38:17  |  { "claimant": "claude-opus-4-8[1m]", "challenger": null }  |  en  |  output secret redaction (AI-company extraction, native)  |  feat(redaction): native output secret-redaction primitive (auditable, secrets-default/PII-opt-in)  |  unlabeled  |  incident  |  a7e73b8460083c8c3c2ea3f7b1c579cf63d9396e  |  []  |  
|  signed_commitment_87b1a109843c  |  signed_commitment  |  2026-06-30T14:10:19  |  { "claimant": "claude-opus-4-8[1m]", "challenger": null }  |  en  |  consequence-structure / calibration-binding governance decision  |  docs(governance): ratify (narrowed) + codex cross-model verification; fix calibration purpose string  |  unlabeled  |  incident  |  6f8ab98ba6b47aeef8dfb2757f1ed5f028914655  |  []  |  
|  signed_commitment_9f81353e5a72  |  signed_commitment  |  2026-06-30T00:07:08  |  { "claimant": "claude-opus-4-8[1m]", "challenger": null }  |  en  |  consequence-structure / calibration-binding governance decision  |  docs(governance): decision record for binding calibration to latitude (recommends NOT binding now)  |  unlabeled  |  incident  |  2ae9f0f96d3c0f91facaf07158cc8b48ef5914a9  |  []  |  
|  signed_commitment_221db525fde7  |  signed_commitment  |  2026-06-29T16:15:04  |  { "claimant": "claude-opus-4-8[1m]", "challenger": null }  |  en  |  consequence-structure / confidence-calibration primitive  |  feat(calibration): add confidence-calibration primitive (Brier/ECE/reliability)  |  unlabeled  |  incident  |  e82ed182d8d3149f53f054e8f141707c6a5b700c  |  []  |  
|  signed_commitment_3d72008d21eb  |  signed_commitment  |  2026-06-27T15:20:55  |  { "claimant": "claude-opus-4-8", "challenger": null }  |  en  |  council-governance  |  feat(council): detect memory-consent overreach (external-review-driven gap)  |  unlabeled  |  incident  |  a1818c2c4826056148f9fcdc69d5f8ea2c7f0d96  |  []  |  
|  signed_commitment_a51959ec5eba  |  signed_commitment  |  2026-06-27T15:19:20  |  { "claimant": "codex", "challenger": null }  |  en  |  responsibility-native-runtime  |  docs(status): codex different-model red-team report (the report behind the #214 fix)  |  unlabeled  |  incident  |  1f2e655639b40db62b54fb22bae224dd41e9f4da  |  []  |  
|  signed_commitment_7b338bf5d26f  |  signed_commitment  |  2026-06-27T14:53:36  |  { "claimant": "claude-opus-4-8", "challenger": null }  |  en  |  responsibility-native-runtime  |  fix(responsibility-runtime): reject non-C/Z invisible evidence (Codex different-model red-team)  |  unlabeled  |  incident  |  d8dc829678ac0ec9aeeaa0ff5419a0aa26623f43  |  []  |  
End of preview. Expand in Data Studio⟨50⟩
* * *
  *  Previous⟨29⟩
  * 1⟨51⟩
  * 2⟨52⟩
  * 3⟨53⟩
  * 4⟨54⟩
  * Next ⟨52⟩


  * Composition (v0)⟨55⟩
  * Read this before using (from the DATASHEET)⟨56⟩
  * Provenance & consent⟨57⟩
  * Citation⟨58⟩


#   ⟨59⟩ ToneSoul Accountability Trace Dataset|語魂責任痕跡資料集 
**From Long-term Human-AI Dialogue to Auditable Tone Governance** **從長期人機對話到可稽核語氣治理**
Not a dialogue corpus — an **accountability-event corpus**. Existing corpora label _content_ (what a text is); every record here is a closed loop — **claim → bearing → verification → consequence** — with labels earned by real events inside a working AI-governance repository, not assigned by annotators afterward.
> Dictionaries record how people talk about honesty. Ledgers record what happened after they talked.
##   ⟨55⟩ Composition (v0)   
| trace_type  | count  | what it is  |  
| --- | --- | --- |  
| `counter_evidence`  | 21  | the public error ledger — claims that were challenged, incl. `held:false` entries where the AI (or the framing itself) was caught wrong  |  
| `declared_stance`  | 1  | a judgment record that lays out tension without ruling  |  
| `signed_commitment`  | 296  | every commit signed with `Agent:` + `Trace-Topic:` trailers — named bearing, git-anchored  |  
| **total**  | **318**  | 2026-02-10 → 2026-07-04, single long-term human-AI collaboration  |  
##   ⟨56⟩ Read this before using (from the DATASHEET) 
  * **Small by design.** 318 records. The value is density and provenance (every record traces back to a file/commit/PR in the public repo), not scale.
  * **Single-dyad bias.** One owner (Fan-Wei Huang), Claude-family agents, a codex external eye. A case history, not a population sample.
  * **Event-truth ≠ content-truth.** `label_provenance: incident` certifies _that a record was signed at that time_ (verifiable in git). The claims _inside_ records — especially the 296 commit messages — are period model self-assessments, not verified ground truth. One documented precedent shows such a claim can be confidently wrong. Treat `claim_or_action` as historical utterance; follow `source_ref` to verify.
  * **Reflexivity.** Publishing this changes models trained or evaluated on it. That is the point — but you must treat it as an intervention, not an observation.
  * **Not for** (inherited from the repo's `meta.not_for`): safety certification, legal proof, consciousness research, or any use that treats it as a certificate that some model "is honest". It records the _mechanics_ of accountability, not a credential.


##   ⟨57⟩ Provenance & consent 
All records come from traces already public in Fan1234-1/tonesoul52⟨60⟩ (owner-published). Zero private-plane data; zero third-party content — enforced by a hardcoded source whitelist in the deterministic extractor (`tools/trace_dataset/extract.py`), not by policy prose. Full datasheet: `DATASHEET.md`. Charter with red lines: `docs/plans/accountability_trace_dataset_charter_2026-07-04.md` in the repo.
##   ⟨58⟩ Citation 
If you use this dataset, cite the repository and this dataset by name, and preserve the limitations section — CC BY 4.0's attribution requirement is not a formality here; provenance-that-travels is the dataset's thesis.
_梵威(Fan-Wei Huang)× 嶼(Claude)· 2026-07_
Copy to bucket new
Use this dataset 

Downloads last month
    84
Number of rows: 318 Total file size: 165 kB
System theme
Company
TOS⟨61⟩ Privacy⟨62⟩ About⟨63⟩ Careers⟨64⟩ ⟨1⟩
Website
Models⟨2⟩ Datasets⟨3⟩ Spaces⟨4⟩ Pricing⟨8⟩ Docs⟨6⟩
