![Hugging Face's logo](https://huggingface.co/front/assets/huggingface_logo-noborder.svg) Hugging Face⟨1⟩
  *  Models ⟨2⟩
  *  Datasets ⟨3⟩
  *  Spaces ⟨4⟩
  *  Buckets new⟨5⟩
  *  Docs ⟨6⟩
  *  Enterprise ⟨7⟩
  * Pricing⟨8⟩
  *     * Website
      *  Tasks⟨9⟩
      *  HuggingChat⟨10⟩
      *  Collections⟨11⟩
      *  Languages⟨12⟩
      *  Organizations⟨13⟩
    * Community
      *  Blog⟨14⟩
      *  Posts⟨15⟩
      *  Daily Papers⟨16⟩
      *  Hardware⟨17⟩
      *  Learn⟨18⟩
      *  Discord⟨19⟩
      *  Forum⟨20⟩
      *  GitHub⟨21⟩
    * Solutions
      *  Team & Enterprise⟨7⟩
      *  Hugging Face PRO⟨22⟩
      *  Enterprise Support⟨23⟩
      *  Inference Providers⟨24⟩
      *  Inference Endpoints⟨25⟩
      *  Storage Buckets⟨5⟩
  * * * *
  * Log In⟨26⟩
  * Sign Up⟨27⟩


#   Datasets:⟨3⟩
* * *
 ![](https://huggingface.co/avatars/613fa529eca3b465e20268928efea501.svg) ⟨28⟩
Cocoyawn32⟨28⟩
/
dreamdojo-piper-warmup-4step⟨29⟩
like 0
Tasks:  Robotics ⟨30⟩
Size:  10K<n<100K ⟨31⟩
ArXiv:
arxiv: 2602.06949
Tags:  piper ⟨32⟩ robot-manipulation ⟨33⟩ video-diffusion ⟨34⟩ dreamdojo ⟨35⟩ self-forcing ⟨36⟩ distillation ⟨37⟩ + 1
License:
apache-2.0
 Dataset card ⟨29⟩ Data Studio ⟨38⟩ Files Files and versions xet ⟨39⟩ Community ⟨40⟩
Dataset Preview
API Embed  Duplicate⟨41⟩ Data Studio
Subset (1)
default
default
Split (1)
train
train
The full dataset viewer is not available (click to read why). Only showing a preview of the rows.
The dataset generation failed

```
Error code:   DatasetGenerationError
Exception:    TypeError
Message:      int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
Traceback:    Traceback (most recent call last):
                File "/usr/local/lib/python3.14/site-packages/datasets/builder.py", line 1520, in _prepare_split_single
                  for key, record in generator:
                                     ^^^^^^^^^
                File "/src/services/worker/src/worker/job_runners/config/parquet_and_info.py", line 613, in wrapped
                  for item in generator(*args, **kwargs):
                              ~~~~~~~~~^^^^^^^^^^^^^^^^^
                File "/usr/local/lib/python3.14/site-packages/datasets/packaged_modules/webdataset/webdataset.py", line 130, in _generate_examples
                  for example_idx, example in enumerate(self._get_pipeline_from_tar(tar_path, tar_iterator)):
                                              ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                File "/usr/local/lib/python3.14/site-packages/datasets/packaged_modules/webdataset/webdataset.py", line 34, in _get_pipeline_from_tar
                  for filename, f in tar_iterator:
                                     ^^^^^^^^^^^^
                File "/usr/local/lib/python3.14/site-packages/datasets/utils/track.py", line 49, in __iter__
                  for x in self.generator(*self.args):
                           ~~~~~~~~~~~~~~^^^^^^^^^^^^
                File "/usr/local/lib/python3.14/site-packages/datasets/utils/file_utils.py", line 1405, in _iter_from_urlpath
                  with xopen(urlpath, "rb", download_config=download_config, block_size=0) as f:
                       ~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                File "/usr/local/lib/python3.14/site-packages/datasets/utils/file_utils.py", line 982, in xopen
                  file_obj = fs.open(paths[0], mode)
                File "<string>", line 3, in open
                File "/usr/local/lib/python3.14/unittest/mock.py", line 1176, in __call__
                  return self._mock_call(*args, **kwargs)
                         ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
                File "/usr/local/lib/python3.14/unittest/mock.py", line 1180, in _mock_call
                  return self._execute_mock_call(*args, **kwargs)
                         ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
                File "/usr/local/lib/python3.14/unittest/mock.py", line 1247, in _execute_mock_call
                  result = effect(*args, **kwargs)
                File "/src/services/worker/src/worker/job_runners/config/parquet_and_info.py", line 786, in wrapped
                  tracker.files[urlpath] = {"read": 0, "size": int(f.size)}
                                                               ~~~^^^^^^^^
              TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
              
              The above exception was the direct cause of the following exception:
              
              Traceback (most recent call last):
                File "/src/services/worker/src/worker/job_runners/config/parquet_and_info.py", line 1369, in compute_config_parquet_and_info_response
                  parquet_operations, partial, estimated_dataset_info = stream_convert_to_parquet(
                                                                        ~~~~~~~~~~~~~~~~~~~~~~~~~^
                      builder, max_dataset_size_bytes=max_dataset_size_bytes
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                  )
                  ^
                File "/src/services/worker/src/worker/job_runners/config/parquet_and_info.py", line 948, in stream_convert_to_parquet
                  builder._prepare_split(split_generator=splits_generators[split], file_format="parquet")
                  ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                File "/usr/local/lib/python3.14/site-packages/datasets/builder.py", line 1382, in _prepare_split
                  for job_id, done, content in self._prepare_split_single(
                                               ~~~~~~~~~~~~~~~~~~~~~~~~~~^
                      gen_kwargs=gen_kwargs, job_id=job_id, **_prepare_split_args
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                  ):
                  ^
                File "/usr/local/lib/python3.14/site-packages/datasets/builder.py", line 1560, in _prepare_split_single
                  raise DatasetGenerationError("An error occurred while generating the dataset") from e
              datasets.exceptions.DatasetGenerationError: An error occurred while generating the dataset
```

Need help to make the dataset viewer work? Make sure to review how to configure the dataset viewer⟨42⟩, and open a discussion⟨43⟩ for direct support.  
|  json list  |  __key__ string  |  __url__ string  |  
| --- | --- | --- |  
|  [ [ -0.4350287914276123, -0.5542640089988708, 0.31140920519828796, 0.00039071994251571596, 0.7165706753730774, 0.077138252556324, 0.37659797072410583, 0.6470142006874084, -0.7452951073646545, 0.6284604072570801, -0.4008021056652069, 0.48456647992134094, 0.2193864583...  |  actions/0  |  hf://datasets/Cocoyawn32/dreamdojo-piper-warmup-4step@7c29f0c202cfa880594d4ced49228d029f79fa53/actions.tar  |  
|  [ [ -0.4350287914276123, -0.5542640089988708, 0.31140920519828796, 0.00039071994251571596, 0.7165706753730774, 0.077138252556324, 0.37659797072410583, 0.6470142006874084, -0.7452951073646545, 0.6284604072570801, -0.4008021056652069, 0.48456647992134094, 0.2193864583...  |  actions/1  |  hf://datasets/Cocoyawn32/dreamdojo-piper-warmup-4step@7c29f0c202cfa880594d4ced49228d029f79fa53/actions.tar  |  
|  [ [ -0.4350287914276123, -0.5542640089988708, 0.31140920519828796, 0.00039071994251571596, 0.7165706753730774, 0.077138252556324, 0.37659797072410583, 0.6470142006874084, -0.7452951073646545, 0.6284604072570801, -0.39544007182121277, 0.48141908645629883, 0.219386458...  |  actions/10  |  hf://datasets/Cocoyawn32/dreamdojo-piper-warmup-4step@7c29f0c202cfa880594d4ced49228d029f79fa53/actions.tar  |  
|  [ [ -0.3929007351398468, -0.5542640089988708, 0.31140920519828796, 0.008876503445208073, 0.6790618300437927, 0.0104453694075346, 0.4729596972465515, 0.6470142006874084, -0.7452951073646545, 0.6284604072570801, -0.3812284469604492, 0.47849252820014954, 0.219386458396...  |  actions/100  |  hf://datasets/Cocoyawn32/dreamdojo-piper-warmup-4step@7c29f0c202cfa880594d4ced49228d029f79fa53/actions.tar  |  
|  [ [ 0.042946621775627136, -0.15111209452152252, 0.05750959366559982, 0.9988178014755249, -0.4162657558917999, -0.72237229347229, 0.6715830564498901, 0.4405725598335266, -0.8088060021400452, 0.716020405292511, 0.07864336669445038, 0.27813366055488586, 0.0123776523396...  |  actions/1000  |  hf://datasets/Cocoyawn32/dreamdojo-piper-warmup-4step@7c29f0c202cfa880594d4ced49228d029f79fa53/actions.tar  |  
|  [ [ 0.042946621775627136, -0.15940162539482117, 0.06059659644961357, 0.9988178014755249, -0.41480669379234314, -0.7243826985359192, 0.6715830564498901, 0.4405725598335266, -0.8088060021400452, 0.716020405292511, 0.08308994770050049, 0.27813366055488586, 0.0123776523...  |  actions/1001  |  hf://datasets/Cocoyawn32/dreamdojo-piper-warmup-4step@7c29f0c202cfa880594d4ced49228d029f79fa53/actions.tar  |  
|  [ [ 0.042946621775627136, -0.16597741842269897, 0.06593544781208038, 0.9988178014755249, -0.41480669379234314, -0.728726863861084, 0.6715830564498901, 0.4405725598335266, -0.8088060021400452, 0.716020405292511, 0.08308994770050049, 0.27813366055488586, 0.01237765233...  |  actions/1002  |  hf://datasets/Cocoyawn32/dreamdojo-piper-warmup-4step@7c29f0c202cfa880594d4ced49228d029f79fa53/actions.tar  |  
|  [ [ 0.042946621775627136, -0.17560818791389465, 0.06568117439746857, 0.9988178014755249, -0.41480669379234314, -0.7336043119430542, 0.6715830564498901, 0.4405725598335266, -0.8088060021400452, 0.716020405292511, 0.08308994770050049, 0.27813366055488586, 0.0123776523...  |  actions/1003  |  hf://datasets/Cocoyawn32/dreamdojo-piper-warmup-4step@7c29f0c202cfa880594d4ced49228d029f79fa53/actions.tar  |  
|  [ [ 0.042946621775627136, -0.18250058591365814, 0.06568117439746857, 0.9988178014755249, -0.4162244498729706, -0.7368909120559692, 0.6715830564498901, 0.4405725598335266, -0.8088060021400452, 0.716020405292511, 0.08308994770050049, 0.27813366055488586, 0.01237765233...  |  actions/1004  |  hf://datasets/Cocoyawn32/dreamdojo-piper-warmup-4step@7c29f0c202cfa880594d4ced49228d029f79fa53/actions.tar  |  
|  [ [ 0.042946621775627136, -0.18846161663532257, 0.06568117439746857, 0.9988178014755249, -0.4177248179912567, -0.741672158241272, 0.6715830564498901, 0.4405725598335266, -0.8088060021400452, 0.716020405292511, 0.08308994770050049, 0.27813366055488586, 0.012377652339...  |  actions/1005  |  hf://datasets/Cocoyawn32/dreamdojo-piper-warmup-4step@7c29f0c202cfa880594d4ced49228d029f79fa53/actions.tar  |  
End of preview. 
  * Files⟨44⟩
  * Download & extract⟨45⟩
  * Structure⟨46⟩
  * Fixes vs upstream default⟨47⟩
  * Reproducibility⟨48⟩
  * Related⟨49⟩


#   ⟨50⟩ DreamDojo Piper Warmup ODE Dataset (1440×640, fps=10, 3-view) 
Teacher-generated ODE trajectories for **DreamDojo Piper warmup distillation**. 10,000 samples covering the `piper_insert_mouse_battery` LeRobot task, each containing a 13-frame video clip + teacher latents at 5 denoising snapshots.
Data is packaged as **4 uncompressed tar archives** for fast transfer (many small files → few large files).
##   ⟨44⟩ Files   
| File  | Size  | Contents  |  
| --- | --- | --- |  
| `latents.tar`  | ~207 GB  | 10 000 × `latents/{idx}.pt` — teacher ODE snapshots at 5+1 denoising steps  |  
| `images.tar`  | ~2.4 GB  | 10 000 × `images/{idx}.png` — 1440×640 RGB first frames  |  
| `videos.tar`  | ~0.4 GB  | 10 000 × `videos/{idx}.mp4` — 13-frame 1440×640 clips  |  
| `actions.tar`  | ~0.6 GB  | 10 000 × `actions/{idx}.json` — (12, 384) relative-action arrays  |  
##   ⟨45⟩ Download & extract 

```
# Full download
HF_HUB_ENABLE_HF_TRANSFER=1 hf download \
  Cocoyawn32/dreamdojo-piper-warmup-4step \
  --repo-type=dataset \
  --local-dir /path/to/piper_warmup_regenerated_4step

# Then unpack in place
cd /path/to/piper_warmup_regenerated_4step
for f in latents.tar images.tar videos.tar actions.tar; do tar -xf "$f" && rm "$f"; done

```

After unpacking you get the exact layout `ActionDatasetSFWarmup` expects:

```
piper_warmup_regenerated_4step/
├── actions/{idx}.json
├── images/{idx}.png
├── videos/{idx}.mp4
└── latents/{idx}.pt

```

Only need latents / images ? Download selectively:

```
hf download Cocoyawn32/dreamdojo-piper-warmup-4step \
  --repo-type=dataset \
  --include "latents.tar" --local-dir .

```

##   ⟨46⟩ Structure 
  * **idx** ranges 0..9999 (matches lerobot episode index in `piper_insert_mouse_battery`)
  * **actions/{idx}.json** : `(12, 384)` float relative actions (normalized)
  * **images/{idx}.png** : `(1440, 640, 3)` uint8 first frame of the clip
  * **videos/{idx}.mp4** : 13 frames at 1440×640, fps=10 (see below for 3-view layout)
  * **latents/{idx}.pt** : `dict[int → tensor(16, 4, 180, 80)]` teacher ODE snapshots
    * keys `[0, 9, 18, 27, 34, 35]` — latents at those denoising steps of a 35-step teacher trajectory
    * key 0 = pure noise · key 34 = near-clean · key 35 = final clean (redundant, warmup training uses keys 0/9/18/27/34)
  * **3-view stack** : rows [0:480] = `cam_high`, [480:960] = `cam_left_wrist`, [960:1440] = `cam_right_wrist`
  * **Latent grid** : 180×80 = 1440/8 × 640/8 (WAN2.1 VAE 8× spatial, 4× temporal → 13 video frames = 4 latent frames)


##   ⟨47⟩ Fixes vs upstream default 
Compared to the upstream `inference_gr00t_warmup.py` default arguments, this dataset **fixes three misalignments** :  
| aspect  | upstream default (bug)  | fixed here  |  
| --- | --- | --- |  
| resolution  | 480×640  |  **1440×640** (teacher's native)  |  
| video_key  | cam_left_wrist (middle-view only)  |  **cam_vertical** (3-view stack)  |  
| fps  | 4 (library default)  |  **10** (teacher trained at fps=10)  |  
Discovered during an alignment audit of the `teacher_gen → warmup → self-forcing` pipeline against the DreamDojo paper⟨51⟩.
##   ⟨48⟩ Reproducibility 

```
NPROC=8 CUDA_VISIBLE_DEVICES=0..7 bash local_jobs/teacher_gen.sh

```

runs `inference_gr00t_warmup` with:

```
--experiment dreamdojo_2b_1440_640_piper
--ckpt_path checkpoints/dreamdojo-piper-vertical-1440-640-fps10-iter30000/model
--resolution 1440,640 --video_key video.cam_vertical --fps 10
--guidance 0 --chunk_size 12 --query_steps 0,9,18,27,34

```

Total gen time: 16.2 hours on 8× A800.
##   ⟨49⟩ Related 
  * Model: Cocoyawn32/dreamdojo-piper-warmup-iter17000⟨52⟩ (old warmup ckpt, wrist-view-only — deprecated)
  * Teacher: Shirk6/dreamdojo-piper-vertical-1440-640-fps10-iter30000⟨53⟩
  * Code: github.com/Cocoyawn/dreamdojo-distill⟨54⟩
  * Paper: arXiv:2602.06949⟨51⟩ DreamDojo: A Generalist Robot World Model


Copy to bucket new 

Downloads last month
    379
Total file size: 225 GB
##  Paper for Cocoyawn32/dreamdojo-piper-warmup-4step
#### DreamDojo: A Generalist Robot World Model from Large-Scale Human Videos Paper • 2602.06949 • Published Feb 6 • 37 ⟨55⟩
System theme
Company
TOS⟨56⟩ Privacy⟨57⟩ About⟨58⟩ Careers⟨59⟩ ⟨1⟩
Website
Models⟨2⟩ Datasets⟨3⟩ Spaces⟨4⟩ Pricing⟨8⟩ Docs⟨6⟩
The table displays a preview with only the first rows.
