![Hugging Face's logo](https://huggingface.co/front/assets/huggingface_logo-noborder.svg) Hugging Face⟨1⟩
  *  Models ⟨2⟩
  *  Datasets ⟨3⟩
  *  Spaces ⟨4⟩
  *  Buckets new⟨5⟩
  *  Docs ⟨6⟩
  *  Enterprise ⟨7⟩
  * Pricing⟨8⟩
  *     * Website
      *  Tasks⟨9⟩
      *  HuggingChat⟨10⟩
      *  Collections⟨11⟩
      *  Languages⟨12⟩
      *  Organizations⟨13⟩
    * Community
      *  Blog⟨14⟩
      *  Posts⟨15⟩
      *  Daily Papers⟨16⟩
      *  Hardware⟨17⟩
      *  Learn⟨18⟩
      *  Discord⟨19⟩
      *  Forum⟨20⟩
      *  GitHub⟨21⟩
    * Solutions
      *  Team & Enterprise⟨7⟩
      *  Hugging Face PRO⟨22⟩
      *  Enterprise Support⟨23⟩
      *  Inference Providers⟨24⟩
      *  Inference Endpoints⟨25⟩
      *  Storage Buckets⟨5⟩
  * * * *
  * Log In⟨26⟩
  * Sign Up⟨27⟩


#   Datasets:⟨3⟩
* * *
 ![](https://huggingface.co/avatars/73045fcc9d30332183777378d0738517.svg) ⟨28⟩
Shreyasrao⟨28⟩
/
Indian-law-supreme-court-judgements-2016⟨29⟩
like 1
Tasks:  Text Classification ⟨30⟩ Text Generation ⟨31⟩ Summarization ⟨32⟩
Modalities:  Document ⟨33⟩ Text ⟨34⟩
Languages:  English ⟨35⟩
Size:  < 1K ⟨36⟩
Tags:  legal ⟨37⟩ indian-supreme-court ⟨38⟩ case-law ⟨39⟩ judgements ⟨40⟩ legal-nlp ⟨41⟩
License:
cc-by-4.0
 Dataset card ⟨29⟩ Data Studio ⟨42⟩ Files Files and versions xet ⟨43⟩ Community 1 ⟨44⟩
Dataset Viewer
 Auto-converted to Parquet⟨45⟩ API Embed  Duplicate⟨46⟩ Data Studio
Subset (1)
default · 589 rows
default (589 rows)
Split (1)
train · 589 rows
train (589 rows)
SQL
Console  
|  filename stringlengths 16 22  |  metadata dict  |  entities dict  |  raw_text_preview stringlengths 793 5k  |  
| --- | --- | --- | --- |  
|  2016-1-1-17-en.md  |  { "year": 2016, "month": 1, "page_start": 1, "page_end": 17, "language": "en" }  |  { "case_title": { "title": "UNITED INDIA INSURANCE CO. LTD. v. M/S ORIENT TREASURES PVT. LTD." }, "summary": { "summary": "The Supreme Court allowed an insurance company's appeal, holding that stolen jewelry was not covered under the policy because it was kept in window displays or out of safe at night, a...  |  # UNITED INDIA INSURANCE CO. LTD. M/S ORIENT TREASURES PVT. LTD. (Civil Appeal No. 2140 of 2007 etc.) JANUARY 13, 2016 #### [J. CHELAMESWAR AND ABHAY MANOHAR SAPRE, JJ.] Insurance – Contract of insurance – Between insurance company and the insured company – Insurance of the jewellery in the shop of the insured – Burg...  |  
|  2016-1-1011-1024-en.md  |  { "year": 2016, "month": 1, "page_start": 1011, "page_end": 1024, "language": "en" }  |  { "case_title": { "title": "GOVT. OF NCT OF DELHI AND ANR. V. ANAND ARYA AND ORS." }, "summary": { "summary": "The Supreme Court examined the legality of constructing the Millennium Bus Depot on a designated river flood plain, which violated the Master Plan 2021 and environmental safeguards. Weighing the ...  |  # GOVT. OF NCT OF DELHI AND ANR. V. ANAND ARYA AND ORS. (Civil Appeal No.888 of 2016) FEBRUARY 05, 2016 [T.S. THAKUR CJI, A.K. SIKRI AND R. BANUMATHI, JJ.] Land laws: Change of land use - Matter perisons to the construction of bus depot by the appellants on an area situated next to Nizamuddin Bridge and behind L....  |  
|  2016-1-1025-1044-en.md  |  { "year": 2016, "month": 1, "page_start": 1025, "page_end": 1044, "language": "en" }  |  { "case_title": { "title": "GOA FOUNDATION & ANR. v. STATE OF GOA & ANR." }, "summary": { "summary": "The Supreme Court upheld the constitutional validity of the Land Acquisition (Goa Amendment) Act, 2009, which retrospectively deleted a restrictive clause prohibiting construction on government-acquired l...  |  # GOA FOUNDATION & ANR. $ V_{n} $ STATE OF GOA & ANR. (Writ Petition (Civil) No.131 of 2009) MARCH 29, 2016 [RANJAN GOGOI AND PRAFULLA C. PANT, JJ.] Land Acquisition Act, 1891-s. 41 - Land Acquisition (Goa Amendment) Act, 2009 - Constitutional validity - Agreement executed between the Government and respondent n...  |  
|  2016-1-103-111-en.md  |  { "year": 2016, "month": 1, "page_start": 103, "page_end": 111, "language": "en" }  |  { "case_title": { "title": "Bobbili Ramakrishna Raju Yadav & Ors. v. State of Andhra Pradesh" }, "summary": { "summary": "The Supreme Court partly allowed the appeal, quashing criminal proceedings against the deceased wife's in-laws under Section 6 of the Dowry Prohibition Act, 1961. The Court held that g...  |  # BOBBILI RAMAKRISHNA RAJU YADAV & ORS. STATE OF ANDHRA PRADESH REP. BY ITS PUBLIC PROSECUTOR HIGH COURT OF A.P. HYDERABAD, A.P. & ANR. (Criminal Appeal No. 45 of 2016) JANUARY 19, 2016 [T.S. THAKUR, CJI, A. K. SIKRI AND R. BANUMATHI, JJ.] Code of Criminal Procedure, 1973: s.482 – Quashing of proceedings – Wife of...  |  
|  2016-1-1045-1058-en.md  |  { "year": 2016, "month": 1, "page_start": 1045, "page_end": 1058, "language": "en" }  |  { "case_title": { "title": "Royal Western India Turf Club Ltd. v. E.S.I. Corporation" }, "summary": { "summary": "The Court examined whether casual workers engaged on race days by the Turf Club fall under the definition of 'employee' under Section 2(9) of the ESI Act, 1948, and determined the liable perio...  |  # ROYAL WESTERN INDIA TURF CLUB LTD. ######## E.S.I. CORPORATION & ORS. (Civil Appeal No. 49 of 2006 etc.) FEBRUARY 29, 2016 #### [V. GOPALA GOWDA AND ARUN MISHRA, JJ.] Employees' State Insurance Act, 1948-s. 2(9) - Definition of 'employee' - Whether would cover 'casual workers' - Held: In view of ss. 2(22), 2(27) o...  |  
|  2016-1-1059-1070-en.md  |  { "year": 2016, "month": 1, "page_start": 1059, "page_end": 1070, "language": "en" }  |  { "case_title": { "title": "TEKAN ALIAS TEKRAM v. STATE OF MADHYA PRADESH" }, "summary": { "summary": "The Supreme Court dismissed the criminal appeal, upholding the appellant's conviction and seven-year rigorous imprisonment for raping a blind girl under the false promise of marriage, as the prosecution ...  |  # TEKAN ALIAS TEKRAM STATE OF MADHYA PRADESH (NOW CHHATTISGARH) (Criminal Appeal No. 884 of 2015) FEBRUARY 11, 2016 ##### [M.Y. EQBAL AND ARUN MISHRA, JJ.] Penal Code, 1860: s.376 – Rape – Prosecutrix-blind girl subjected to sexual intercourse on the promise of marriage – Conviction of accused and 7 years rigorous im...  |  
|  2016-1-1071-1079-en.md  |  { "year": 2016, "month": 1, "page_start": 1071, "page_end": 1079, "language": "en" }  |  { "case_title": { "title": "SURESH NARAYAN KADAM v. CENTRAL BANK OF INDIA" }, "summary": { "summary": "The Supreme Court upheld the eviction of employee allottees from service quarters under the Public Premises (Eviction of Unauthorised Occupants) Act, 1971, holding that the allotment was discretionary an...  |  # SURESH NARAYAN KADAM & ORS [MADAN B. LOKUR AND R.K. AGRAWAL, JJ.] Public Premises (Eviction of Unauthorised Occupants) Act. 1971: Eviction and damages – MHADA constructed some buildings for lower and middle income group – Leased out the land underneath the buildings to the respondent-Bank for 90 years – Bank took...  |  
|  2016-1-1080-1083-en.md  |  { "year": 2016, "month": 1, "page_start": 1080, "page_end": 1083, "language": "en" }  |  { "case_title": { "title": "State of Madhya Pradesh v. Rajaram, Udaibhan and Hakim Singh" }, "summary": { "summary": "The State appealed against the High Court's order converting convictions under Section 307 IPC to Section 326 IPC and reducing the sentence to the period already undergone. The Supreme Cou...  |  ### STATE OF M.P ## B ### [DIPAK MISRA AND SHIVA KIRTI SINGH, JJ.] Sentence /Sentencing – Conviction of one accused inter alia w/s. 307 IPC and other two accused w/s. 307/34 IPC – Sentence of 10 years RI – High Court altered the conviction w/s.307 & 307/34 to one w/s.326 and 326/34 and reduced the sentence to the pe...  |  
|  2016-1-1084-1089-en.md  |  { "year": 2016, "month": 1, "page_start": 1084, "page_end": 1089, "language": "en" }  |  { "case_title": { "title": "ASHOK KUMAR & ANR. ETC. v. STATE OF HARYANA" }, "summary": { "summary": "The Supreme Court held that the 1984 amendment to Section 25 of the Land Acquisition Act, 1894 removed the upper cap restricting compensation to the amount claimed by the applicant. The Court emphasized it...  |  ## A # ASHOK KUMAR & ANR. ETC. STATE OF HARYANA (Civil Appeal Nos. 2714-2721 OF 2012) ### FEBRUARY 18, 2016 [KURIAN JOSEPH AND ROHINTON FALI NARIMAN, JJ.] Land Acquisition Act, 1894 - s.25 (as amended) – Amount of compensation awarded by the Court – Held. There is no restriction that compensation should be awarded...  |  
|  2016-1-1090-1114-en.md  |  { "year": 2016, "month": 1, "page_start": 1090, "page_end": 1114, "language": "en" }  |  { "case_title": { "title": "RE-INHUMAN CONDITIONS IN 1382 PRISONS (Writ Petition (C) No. 406 of 2013)" }, "summary": { "summary": "The Supreme Court addressed a public interest litigation concerning inhuman conditions across Indian prisons, affirming that prisoners retain fundamental rights to life and di...  |  ## A ####### RE-INHUMAN CONDITIONS IN 1382 PRISONS (Write Petition (C) No. 406 of 2013) FEBRUARY 05, 2016 [MADAN B. LOKUR AND R.K. AGRAWAL, JJ.] B Prison reforms: Present case pertaining to conditions of prisons in India – By instant order this Court held: Prisoners like all human beings deserve to be treated with d...  |  
|  2016-1-1115-1117-en.md  |  { "year": 2016, "month": 1, "page_start": 1115, "page_end": 1117, "language": "en" }  |  { "case_title": { "title": "Hina v. Union of India & Ors." }, "summary": { "summary": "The Supreme Court allowed the appeal against the rejection of the appellant's application for a petroleum dealership, holding that rejecting a Higher Secondary School certificate as age proof is unreasonable when a Seco...  |  ## HINA UNION OF INDIA & ORS. (Civil Appeal NO. 1676 OF 2016) FEBRUARY 23, 2016 NARIMAN JJ.] Public Distribution – Allotment of outlet of petroleum/diesel dealership – Rejected on the ground that the age proof provided by the applicant was not of the Senior Secondary School as per the norms, but of Higher Secondar...  |  
|  2016-1-1118-1140-en.md  |  { "year": 2016, "month": 1, "page_start": 1118, "page_end": 1140, "language": "en" }  |  { "case_title": { "title": "Securities and Exchange Board of India v. Kishore R. Ajmera" }, "summary": { "summary": "The Supreme Court examined the standard of proof required to hold brokers liable for manipulative or fraudulent trading practices under SEBI regulations. It held that liability may be infer...  |  # SECURITIES AND EXCHANGE BOARD OF INDIA ## A KISHORE R. AJMERA (Civil Appeal No.2818 OF 2008) FEBRUARY 23, 2016 [RANJAN GOGOI AND PRAFULLA C. PANT. JJ.] Securities and Exchange Board of India Act, 1992- s. 19-Securities and Exchange Board of India (Stock Brokers and Sub-Brokers) Regulations, 1992- Reg -9 Securiti...  |  
|  2016-1-112-116-en.md  |  { "year": 2016, "month": 1, "page_start": 112, "page_end": 116, "language": "en" }  |  { "case_title": { "title": "M/S RAHMAN INDUSTRIES PVT. LTD. v. STATE OF U.P." }, "summary": { "summary": "The Supreme Court held that under the Industrial Disputes Act, 1947, the Government has the statutory jurisdiction to examine whether an industrial dispute exists before referring it for adjudication,...  |  # M/S RAHMAN INDUSTRIES PVT. LTD. STATE OF U.P. AND OTHERS (Civil Appeal No. 286 of 2016) JANUARY 18, 2016 ##### [KURIAN JOSEPH AND R. F. NARIMAN, JJ.] Industrial Disputes Act, 1947 – Power of Government – To refer the industrial dispute for adjudication – Judicial interference – Permissibility – Held: In the sche...  |  
|  2016-1-117-136-en.md  |  { "year": 2016, "month": 1, "page_start": 117, "page_end": 136, "language": "en" }  |  { "case_title": { "title": "M/S. ALKALI MANUFACTURERS ASSN. OF INDIA v. DESIGNATED AUTHORITY, D.A.D.A.S. & ORS." }, "summary": { "summary": "The Supreme Court examined whether the Customs Excise & Service Tax Appellate Tribunal correctly determined anti-dumping duties on imported caustic soda and applied ...  |  # M/S. ALKALI MANUFACTURERS ASSN. OF INDIA DESIGNATED AUTHORITY, D.A.D.A.S. & ORS. (Civil Appeal No. 2242 OF 2006 etc.) JANUARY 07, 2016 ### [DIPAK MISRA AND SHIVA KIRTI SINGH, JJ.] Customs Tariff Act, 1995 – s. 9A – Anti-dumping duty on dumped articles – Customs Tariff (Identification, Assessment and Collection of A...  |  
|  2016-1-137-150-en.md  |  { "year": 2016, "month": 1, "page_start": 137, "page_end": 150, "language": "en" }  |  { "case_title": { "title": "Susanta Das & Ors. v. State of Orissa" }, "summary": { "summary": "The Supreme Court dismissed criminal appeals filed by five appellants convicted for murder and grievous hurt under Sections 302 and 326 read with Section 149 of the Indian Penal Code. The Court upheld the High C...  |  SUSANTA DAS & ORS. STATE OF ORISSA (Criminal Appeal No. 244 of 2009) ### [FAKKIR MOHAMED IBRAHIM KALIFULLA, UDAY UMESH LALIT, JJ.] Penal Code, 1860: s.302 v/w s.149 and s.326 - Conviction under - Prosecution case that on the day of incident, PW8, PW11 and deceased were on motorcycle - Appellants five in number arme...  |  
|  2016-1-151-161-en.md  |  { "year": 2016, "month": 1, "page_start": 151, "page_end": 161, "language": "en" }  |  { "case_title": { "title": "M/S. SCIEMED OVERSEAS INC. v. BOC INDIA LIMITED & ORS." }, "summary": { "summary": "The Supreme Court upheld the High Court's imposition of costs of Rs. 10 lakhs on the petitioner contractor for filing a false or misleading affidavit claiming a works contract was near completio...  |  M/S. SCIEMED OVERSEAS INC. BOC INDIA LIMITED & ORS. (Petition For Special Leave To Appeal (C) No. 29125 of 2008) JANUARY 11, 2016 [MADAN B. LOKUR AND R. K. AGRAWAL, JJ.] Cost – Imposition of – For filing a false or misleading affidavit Written Petition challenging award of works contract – Dismissed on the ground...  |  
|  2016-1-162-173-en.md  |  { "year": 2016, "month": 1, "page_start": 162, "page_end": 173, "language": "en" }  |  { "case_title": { "title": "Commissioner of Customs v. M/s K. M. Ganatra & Co." }, "summary": { "summary": "The Supreme Court set aside the orders of the Customs Tribunal and High Court, restoring the Commissioner's decision to permanently revoke a Customs House Agent's licence for habitual subletting and...  |  # COMMISSIONER OF CUSTOMS M/S K. M. GANATRA & CO. (Civil Appeal No. 2940 of 2008) JANUARY 14, 2016 ##### [DIPAK MISRA AND N. V. RAMANA, JJ.] Customs House Agents Licensing Regulations, 1984 - Regulations 10, 13, 14 - Misuse of Customs House Agent licence (CHA) issued in favour of respondent - Transfer of licence b...  |  
|  2016-1-174-178-en.md  |  { "year": 2016, "month": 1, "page_start": 174, "page_end": 178, "language": "en" }  |  { "case_title": { "title": "Surender Kala v. State of Haryana" }, "summary": { "summary": "The appellant challenged his conviction under Section 18 of the Narcotic Drugs and Psychotropic Substances Act for possessing 1 kg of opium, contending that the investigation was flawed as the complainant also condu...  |  ## A # SURENDER @ KALA STATE OF HARYANA (Criminal Appeal No. 50 of 2016) JANUARY 19, 2016 A GOWDA AND UDAY UMESH ## R #### [V. GOPALA GOWDA AND UDAY UMESH LALIT, JJ.] Narcotic Drugs and Psychotropic Substances Act, 1985: ss.18, 50 – Appellant suspected to be in possession of opium without any permit or licence – Op...  |  
|  2016-1-179-186-en.md  |  { "year": 2016, "month": 1, "page_start": 179, "page_end": 186, "language": "en" }  |  { "case_title": { "title": "State of Assam v. Ramen Dowarah" }, "summary": { "summary": "The Supreme Court restored the trial court's conviction, reversing the High Court's decision that treated the incident as consensual intercourse and culpable homicide. The Court held that the victim's cries, threats t...  |  ### STATE OF ASSAM RAMEN DOWARAH (Criminal Appeal No. 668 of 2011) JANUARY 11, 2016 AN JOSEPH AND ARUN MISHRA, JJ Penal Code, 1860 – ss.302/376/454 – Prosecution under – Of respondent-accused alongwith co-accused – For the commission of offence of rape and thereafter causing death of prosecutrix setting her ablaze by ...  |  
|  2016-1-18-33-en.md  |  { "year": 2016, "month": 1, "page_start": 18, "page_end": 33, "language": "en" }  |  { "case_title": { "title": "TMT. KASTHURI RADHAKRISHNAN & ORS. v. M. CHINNIYAN & ANR." }, "summary": { "summary": "The Supreme Court examined the scope of a High Court's revisional jurisdiction in rent control matters and clarified that a power of attorney holder acquires no personal rights or title over ...  |  # TMT. KASTHURI RADHAKRISHNAN & ORS. M. CHINNIYAN & ANR. (Civil Appeal No. 5158 OF 2009) JANUARY 28, 2016. #### [J. CHELAMESWAR AND ABHAY MANOHAR SAPRE, JJ.] Rent Control and Eviction: Revision – Revisional jurisdiction – Exercise of, by the High Court in rent matters – Held: High Court is entitled to satisfy its...  |  
|  2016-1-187-193-en.md  |  { "year": 2016, "month": 1, "page_start": 187, "page_end": 193, "language": "en" }  |  { "case_title": { "title": "M/S GANAPATHY & CO., BANGALORE v. COMMISSIONER, INCOME TAX BANGALORE" }, "summary": { "summary": "The Supreme Court upheld the High Court's rejection of the assessee's claims for income tax deductions regarding service charges, film business losses, and donations to an ashram, ...  |  # M/S GANAPATHY & CO., BANGALORE THE COMMISSIONER, INCOME TAX BANGALORE (Civil Appeal No. 1964 of 2008) JANUARY 18, 2016 [RANJAN GOGOI AND PRAFULLA C. PANT, JJ.] Income Tax Act, 1961: Disallowance of service charges – Assessee claiming benefit of disallowance of service charges paid to the Company – Assessing office...  |  
|  2016-1-194-206-en.md  |  { "year": 2016, "month": 1, "page_start": 194, "page_end": 206, "language": "en" }  |  { "case_title": { "title": "Dharam Pal v. State of Haryana & Ors." }, "summary": { "summary": "The Supreme Court examined whether constitutional courts can direct the transfer of a criminal investigation to the CBI after the trial has already commenced. Holding that the power to order further or de novo i...  |  ## DHARAM PAL # STATE OF HARYANA & ORS. (Criminal Appeal No. 85 of 2016) JANUARY 29, 2016 MISRA AND PRAFULLA C. #### [DIPAK MISRA AND PRAFULLA C. PANT, JJ.] Code of Criminal Procedure, 1973: s.173 – Investigation, transfer of – Rape of appellant's daughter and after few days murder of his wife – Acquittal of accused...  |  
|  2016-1-207-215-en.md  |  { "year": 2016, "month": 1, "page_start": 207, "page_end": 215, "language": "en" }  |  { "case_title": { "title": "Supreme Court Women Lawyers Association (SCWLA) v. Union of India & Anr." }, "summary": { "summary": "The petitioner invoked Article 32 to seek chemical castration as an additional punishment for rapists of girl children. The Court declined to prescribe punishment, holding that...  |  # SUPREME COURT WOMEN LAWYERS ASSOCIATION (SCWLA) UNION OF INDIA & ANR. (Writ Petition (Civil) No.4 of 2016) JANUARY 11, 2016 [DIPAK MISRA AND N. V. RAMANA, JJ.] Constitution of India, 1950–Art. 32– Remedies for enforcement of rights conferred by this Part—Rape and abuse of a girl child—Writ petition to consider i...  |  
|  2016-1-216-241-en.md  |  { "year": 2016, "month": 1, "page_start": 216, "page_end": 241, "language": "en" }  |  { "case_title": { "title": "State of Rajasthan and Ors. v. Gotan Lime Stone Khanji Udyog Pvt. Ltd. and Anr." }, "summary": { "summary": "The Supreme Court held that mining rights vest in the State under the public trust doctrine and cannot be traded by lessees for private benefit. Applying the doctrine of...  |  STATE OF RAJASTHAN AND ORS. ## A GOTAN LIME STONE KHANJI UDYOG PVT. LTD. AND ANR. (Civil Appeal No. 434 of 2016) ## B JANUARY 20, 2016 #### [ANIL R. DAVE AND ADARSH KUMAR GOEL, JJ.] Rajasthan Minor Mineral Concession Rules, 1986 - r15 - Mining rights - Transfer of - Partnership firm holding mining rights - The f...  |  
|  2016-1-242-249-en.md  |  { "year": 2016, "month": 1, "page_start": 242, "page_end": 249, "language": "en" }  |  { "case_title": { "title": "State of Haryana v. Eros City Developers Pvt. Ltd. and Others" }, "summary": { "summary": "The Supreme Court heard appeals challenging the High Court's quashing of land acquisition notifications under Sections 4 and 6 of the Land Acquisition Act, 1894, for developing the Surajk...  |  STATE OF HARYANA EROS CITY DEVELOPERS PVT. LTD. AND OTHERS (Civil Appeal No. 354 of 2016 etc.) JANUARY 19, 2016 (RANJAN GOGOI AND PRAFULLA C. PANT, JJ.) Land Acquisition Act, 1894: ss.4 and 6 – Acquisition Notification of land measuring 172 kanals 19 marlas in village Lakarpur District Faridabad – Out of that 129 k...  |  
|  2016-1-250-255-en.md  |  { "year": 2016, "month": 1, "page_start": 250, "page_end": 255, "language": "en" }  |  { "case_title": { "title": "Commissioner of Central Excise, Pune v. Hindustan National Glass and Industries Limited" }, "summary": { "summary": "The appeal concerns under-valuation of manufactured goods and short payment of central excise duty arising from the non-addition of notional interest on advances...  |  ## A # COMMISSIONER OF CENTRAL EXCISE, PUNE HINDUSTAN NATIONAL GLASS AND INDUSTRIES LIMITED (Civil Appeal No. 1829 of 2008) JANUARY 14, 2016. ## B [DIPAK MISRA AND N.V. RAMANA, JJ.] Central Excise Act, 1944 – Under Valuation – Short payment of duty – Manufacturers-assessee received advance from purchasers for the g...  |  
|  2016-1-256-265-en.md  |  { "year": 2016, "month": 1, "page_start": 256, "page_end": 265, "language": "en" }  |  { "case_title": { "title": "L. Gowramma (D) by LR. v. Sunanda (D) by LRS. & Anr." }, "summary": { "summary": "The appeal concerns the determination of succession rights to property of a Hindu male dying intestate under the Mysore Hindu Law Women's Rights Act, 1933. The Supreme Court held that under Sectio...  |  L. GOWRAMMA (D) BY LR. SUNANDA (D) BY LRS. & ANR. (Civil Appeal Nos. 174-175 of 2016) JANUARY 12, 2016 AN JOSEPH AND R. F. NARIMA Hindu Law Women's Rights Act, 1933 (Mysore Act No. X of 1933) - ss. 4, 10 and 8 - Succession to Hindu male dying intestate - On facts, constitution of joint Hindu family between two bro...  |  
|  2016-1-266-282-en.md  |  { "year": 2016, "month": 1, "page_start": 266, "page_end": 282, "language": "en" }  |  { "case_title": { "title": "Bussa Overseas & Properties (P) Ltd. & Anr. v. Union of India & Anr." }, "summary": { "summary": "The Supreme Court dismissed the civil appeal as not maintainable, holding that an appeal cannot be filed solely against an order dismissing a review petition when the original judg...  |  ## A # BUSSA OVERSEAS & PROPERTIES (P) LTD. & ANR. # UNION OF INDIA & ANR. (Civil Appeal No. 2687 of 2006) JANUARY 22, 2016 ## B ## [DIPAK MISRA AND SHIVA KIRTI SINGH, JJ] Review: Scope of – Refund claim – Custom duty – Department dismissed the claim on the ground that same was filed w/s.27 of Customs Act and the ...  |  
|  2016-1-283-298-en.md  |  { "year": 2016, "month": 1, "page_start": 283, "page_end": 298, "language": "en" }  |  { "case_title": { "title": "VIPINCHANDRA VADILAL BAVISHI (D) BY LRS. AND ANOTHER v. STATE OF GUJARAT AND OTHERS" }, "summary": { "summary": "The Supreme Court examined whether the State of Gujarat could vest disputed lands by issuing a handwritten corrigendum to alter plot numbers in a statutory notificat...  |  # VIPINCHANDRA VADILAL BAVISHI (D) BY LRS. AND ANOTHER STATE OF GUJARAT AND OTHERS (Civil Appeal No. 7434 of 2012) JANUARY 28, 2016 [M.Y. EQBAL AND C. NAGAPPAN, JJ.] Urban Land (Ceiling and Regulation) Act, 1976 - ss. 8, 9 and 10 - Handwritten corrigendum and the alleged panchnama - Reliance upon - On the basis of...  |  
End of preview. Expand in Data Studio⟨47⟩
* * *
  *  Previous⟨29⟩
  * 1⟨48⟩
  * 2⟨49⟩
  * 3⟨50⟩
  * ...⟨51⟩
  * 6⟨52⟩
  * Next ⟨49⟩


  * Dataset Description⟨53⟩
  * Dataset Structure⟨54⟩
    * Naming Convention⟨55⟩
    * Data Formats⟨56⟩
  * Dataset Statistics⟨57⟩
    * Monthly Distribution⟨58⟩
    * Topic Category Distribution⟨59⟩
    * Top Legal Topics⟨60⟩
    * Most Frequently Cited Acts⟨61⟩
    * Most Frequent Judges⟨62⟩
  * Data Provenance⟨63⟩
  * Data Quality Notes⟨64⟩
  * Intended Uses⟨65⟩
  * Limitations and Biases⟨66⟩
  * License⟨67⟩
    * Citation⟨68⟩


#   ⟨69⟩ Dataset Card: Indian Supreme Court Judgments 2016 
##   ⟨53⟩ Dataset Description 
A comprehensive, structured dataset of **589 judgments** delivered by the Supreme Court of India during the calendar year **2016** , plus a small number of spill-over judgments from **2017** bundled in the original source PDFs. Each judgment is available in three forms: the original scanned PDF as downloaded from the official eCourts portal, a full text extracted via OCR as Markdown, and a fully structured JSON with extracted entities (case title, summary, judges, parties, legal sections, and topic labels across 11 categories).
The dataset was curated by downloading the 2016 subset from the Indian Supreme Court Judgments registry on AWS Open Data⟨70⟩ (managed by Dattam Labs, CC-BY-4.0), then OCR-processing every PDF through **PaddleOCR-VL-1.6** to produce the Markdown and structured JSON outputs.
##   ⟨54⟩ Dataset Structure 

```
indian-supreme-court-judgements-2016/
  raw_data/          # 589 PDFs (282 MB compressed, 368 MB uncompressed)
  extracted_mds/     # 589 Markdown files (28 MB) — full OCR text
  extracted_jsons/   # 589 JSON files (4.1 MB) — structured entities
  DATASET_CARD.md    # this file

```

###   ⟨55⟩ Naming Convention 
Files follow the pattern `{year}_{month}_{page_start}_{page_end}_{language}.{ext}`, where:
  * **year** : 2016 (one 2017 spill-over bundle from same source)
  * **month** : numeric month of delivery (1=January through 12=December)
  * **page_start** / **page_end** : page range within the original eCourts pagination scheme
  * **language** : EN (English only in this dataset)
  * **ext** : pdf / md / json


**Example** : `2016-1-179-186-en.json` → judgment delivered in January 2016 (month 1), spanning pages 179-186 of the eCourts index, in English.
###   ⟨56⟩ Data Formats 
####   ⟨71⟩ 1. Raw PDFs (`raw_data/`) 
Original scanned PDFs from the eCourts portal. 589 files, 368 MB total. Contains the full scanned judgment text including OCR layer where available.
####   ⟨72⟩ 2. Extracted Markdown (`extracted_mds/`) 
Full text extracted via PaddleOCR-VL-1.6, formatted as Markdown with:
  * A YAML-style header with metadata (page count, processing time)
  * Full OCR output per page with `## Page N` separators
  * Case law references, citations, and the complete judgment text
  * Error annotations where OCR processing of a specific page failed (shown inline)


Example header:

```
# 2016_1_179_186_EN
*Converted via PaddleOCR-VL-1.6 | 8 pages | 37s*

```

####   ⟨73⟩ 3. Structured JSON (`extracted_jsons/`) 
Machine-readable JSON with the following schema:

```
{
  "filename": "2016-1-179-186-en.md",
  "metadata": {
    "year": 2016,
    "month": 1,
    "page_start": 179,
    "page_end": 186,
    "language": "en"
  },
  "entities": {
    "case_title": { "title": "State of Assam v. Ramen Dowarah" },
    "summary": { "summary": "The Supreme Court restored..." },
    "judges": [{ "name": "A. N. Joseph", "role": "bench_member" },
               { "name": "Arun Mishra",   "role": "author" }],
    "parties": [{ "name": "State of Assam", "role": "appellant" },
                { "name": "Ramen Dowarah",  "role": "respondent" }],
    "sections": [{ "section": "302",              "act": "Indian Penal Code" },
                 { "section": "376",              "act": "Indian Penal Code" },
                 { "section": "164",              "act": "Code of Criminal Procedure" }],
    "topics": [{ "text": "Rape",                  "category": "criminal" },
               { "text": "Murder",                "category": "criminal" },
               { "text": "Dying Declaration",     "category": "procedural" }]
  },
  "raw_text_preview": "### STATE OF ASSAM RAMEN DOWARAH..."
}

```

##   ⟨57⟩ Dataset Statistics   
| Metric  | Value  |  
| --- | --- |  
| Total judgments  | **589**  |  
| Total pages  | **11,667**  |  
| Raw PDF size  | 367.7 MB  |  
| Extracted Markdown size  | 26.2 MB  |  
| Structured JSON size  | 4.1 MB  |  
| JSON size (per file)  | 2.2–8.9 KB (avg 7.3 KB)  |  
| Cases with summary  | 586 / 589  |  
| Cases with judges extracted  | 582 / 589  |  
| Cases with parties extracted  | 585 / 589  |  
| Cases with title  | 584 / 589  |  
| Total section references  | 2,765  |  
| Total topic labels  | 3,041 (2,291 unique)  |  
| Unique acts referenced  | 447  |  
| Unique judges  | 34  |  
###   ⟨58⟩ Monthly Distribution   
| Month  | Cases  | Month  | Cases  |  
| --- | --- | --- | --- |  
| January  | 80  | July  | 35  |  
| February  | 108  | August  | 51  |  
| March  | 68  | September  | 50  |  
| April  | 66  | October  | 1  |  
| May  | 58  | November  | 36  |  
| June  | 24  | December  | 12  |  
The spike in February (108 cases) and concentration in the first half of the year reflects the Court's calendar — the Supreme Court typically hears its heaviest docket during the pre-summer term.
###   ⟨59⟩ Topic Category Distribution   
| Category  | Labels  | Description  |  
| --- | --- | --- |  
| Procedural  | 840  | Criminal appeals, writs, evidentiary issues, jurisdiction  |  
| Administrative  | 511  | Service law, disciplinary proceedings, administrative orders  |  
| Criminal  | 455  | Murder, rape, NDPS, corruption, criminal appeals  |  
| Constitutional  | 346  | Fundamental rights, constitutional interpretation, ordinances  |  
| Civil  | 294  | Contract, tort, tenancy, civil procedure  |  
| Property  | 194  | Land acquisition, lease, eviction, title disputes  |  
| Tax  | 159  | Income tax, customs, excise, GST  |  
| Corporate  | 106  | Company law, winding up, SARFAESI, insolvency  |  
| Other  | 70  | Miscellaneous  |  
| Family  | 46  | Divorce, maintenance, succession, custody  |  
| Environmental  | 20  | Forest conservation, pollution, mining  |  
###   ⟨60⟩ Top Legal Topics 
The most frequently occurring topics include **Statutory Interpretation** (42 cases), **Murder** (38), **Service Law** (34), **Land Acquisition** (24), **Criminal Appeal** (23), **Public Interest Litigation** (21), **Compensation** (14), **Judicial Review** (14), **Arbitration** (14), and **Writ Jurisdiction** (14).
###   ⟨61⟩ Most Frequently Cited Acts   
| Act  | References  |  
| --- | --- |  
| Indian Penal Code  | 437  |  
| Constitution of India  | 386  |  
| Land Acquisition Act, 1894  | 99  |  
| Code of Criminal Procedure, 1973  | 97 (combined with "Code of Criminal Procedure": 186)  |  
| Income Tax Act, 1961  | 76  |  
| Code of Civil Procedure, 1908  | 71  |  
| Arbitration and Conciliation Act, 1996  | 58  |  
| Indian Evidence Act  | 38  |  
| Electricity Act, 2003  | 32  |  
| Prevention of Corruption Act, 1988  | 28  |  
###   ⟨62⟩ Most Frequent Judges   
| Judge  | Cases  |  
| --- | --- |  
| Dipak Misra  | 104  |  
| T. S. Thakur  | 81  |  
| A. K. Sikri  | 74  |  
| Rohinton F. Nariman  | 74  |  
| Kurian Joseph  | 68  |  
| Shiva Kirti Singh  | 66  |  
| Abhay Manohar Sapre  | 63  |  
| R. Banumathi  | 57  |  
| Prafulla C. Pant  | 53  |  
| V. Gopala Gowda  | 42  |  
##   ⟨63⟩ Data Provenance 
  1. **Source** : Indian Supreme Court Judgments⟨70⟩ on AWS Open Data Registry, managed by **Dattam Labs**. The complete dataset covers judgments from 1950 to 2025 in both English and regional Indian languages. Only the 2016 English subset was used here.
  2. **Download date** : 27 May 2026, via `aws s3 cp --no-sign-request`.
  3. **OCR processing** : Every PDF was processed through **PaddleOCR-VL-1.6** (a vision-language OCR model by PaddlePaddle), running via llama.cpp server. Each judgment took 10–60 seconds depending on page count. The OCR output was captured as Markdown with per-page pagination.
  4. **Entity extraction** : A structured JSON was generated from each Markdown file by LLM-based information extraction, identifying: case title, summary, judges on the bench (with author designation), parties with roles, legal sections cited (with corresponding act names), and topic labels (text + category).
  5. **Topic classification** : Topics are assigned into 11 broad categories: procedural, administrative, criminal, constitutional, civil, property, tax, corporate, other, family, and environmental.


##   ⟨64⟩ Data Quality Notes 
  * **OCR fidelity** : PaddleOCR-VL-1.6 is a vision-language model, not a traditional OCR engine. Text extraction quality is high for clean scanned pages but may exhibit errors on:
    * Faint or degraded scans (common in older judgments)
    * Complex layouts (multi-column text, footnotes)
    * Tables and non-standard formatting
    * Handwritten annotations
Some pages failed OCR entirely and are marked with:

```
[Error processing page N: Exception from the 'vlm' worker: ...]

```

  * **Summary generation** : 3 cases lack AI-generated summaries (likely very short or header-only PDFs). 5 case titles could not be extracted. 7 judgments have no judge information and 4 have no party information — these are very short procedural orders where entity extraction was unreliable.
  * **Section deduplication** : The same act may appear under slightly different names (e.g., "Code of Criminal Procedure, 1973" vs "Code of Criminal Procedure" vs "Cr.P.C."). No normalization has been applied; all forms appear as extracted.
  * **Topic sparsity** : The 3,041 topic labels span 2,291 unique topics, indicating high diversity. Only **Statutory Interpretation** (42) and **Murder** (38) appear with significant frequency; most topics are unique to a single case. This reflects the wide-ranging docket of the Supreme Court.
  * **The October anomaly** : Only 1 judgment is recorded for month 10 (October). This is not a gap — the Supreme Court of India typically observes a long **autumn/Diwali vacation** in October, during which very few bench days occur.
  * **Spill-over 2017 file** : One PDF (2017-5-160-276) is included in the source data despite being filed under the 2016 directory. It has been retained as-is. It is a 7-judge constitution bench judgment on the validity of Bihar's ordinance re-promulgation practice.


##   ⟨65⟩ Intended Uses 
This dataset is suitable for:
  * **Legal NLP research** : Judgment summarization, legal text classification, topic modelling, and named entity recognition on Indian case law
  * **Legal information retrieval** : Training query-based retrieval systems for Indian Supreme Court jurisprudence
  * **Legal analytics** : Studying court trends, judicial behaviour, citation networks, and topic evolution
  * **Legal education** : Providing structured, labelled access to landmark and routine Supreme Court judgments for curriculum development
  * **Benchmarking OCR systems** : The raw PDFs paired with cleaned structured JSON serve as an evaluation set for legal domain OCR


##   ⟨66⟩ Limitations and Biases 
  * **Single year** : This dataset covers only 2016 (plus one 2017 bundle). It does not capture temporal trends or the evolution of legal doctrine across decades.
  * **English only** : Only English-language judgments are included. The source dataset includes judgments in Hindi and other regional languages which are excluded here.
  * **Topic taxonomy** : The 11-category topic model was chosen for broad coverage, but it inevitably loses nuance at the boundaries (e.g., certain administrative matters touch on constitutional questions).
  * **OCR quality variance** : Older, poorly scanned PDFs produce lower quality OCR output, which in turn affects entity extraction reliability.
  * **Judge role assignment** : The "author" vs "bench_member" distinction in the JSON is an LLM inference, not official court metadata. For multi-judge opinions the designated author may not always be correctly identified.


##   ⟨67⟩ License 
The underlying source data is licensed under **CC-BY-4.0** as per the AWS Open Data Registry entry. The derived Markdown and JSON outputs in this dataset are made available under the same **CC-BY-4.0** license.
###   ⟨68⟩ Citation 
If you use this dataset, please cite:

```
@misc{indian_supreme_court_judgments_2016,
  title = {Indian Supreme Court Judgments 2016: A Structured Dataset},
  author = {Shreyas Rao},
  year = {2026},
  month = {May},
  howpublished = {\url{https://registry.opendata.aws/indian-supreme-court-judgments/}},
  note = {Accessed 27 May 2026. OCR-processed with PaddleOCR-VL-1.6.}
}

```

Copy to bucket new 

Downloads last month
    646
Number of rows: 589 Total file size: 417 MB
System theme
Company
TOS⟨74⟩ Privacy⟨75⟩ About⟨76⟩ Careers⟨77⟩ ⟨1⟩
Website
Models⟨2⟩ Datasets⟨3⟩ Spaces⟨4⟩ Pricing⟨8⟩ Docs⟨6⟩
