![Hugging Face's logo](https://huggingface.co/front/assets/huggingface_logo-noborder.svg) Hugging Face⟨1⟩
  *  Models ⟨2⟩
  *  Datasets ⟨3⟩
  *  Spaces ⟨4⟩
  *  Buckets new⟨5⟩
  *  Docs ⟨6⟩
  *  Enterprise ⟨7⟩
  * Pricing⟨8⟩
  *     * Website
      *  Tasks⟨9⟩
      *  HuggingChat⟨10⟩
      *  Collections⟨11⟩
      *  Languages⟨12⟩
      *  Organizations⟨13⟩
    * Community
      *  Blog⟨14⟩
      *  Posts⟨15⟩
      *  Daily Papers⟨16⟩
      *  Hardware⟨17⟩
      *  Learn⟨18⟩
      *  Discord⟨19⟩
      *  Forum⟨20⟩
      *  GitHub⟨21⟩
    * Solutions
      *  Team & Enterprise⟨7⟩
      *  Hugging Face PRO⟨22⟩
      *  Enterprise Support⟨23⟩
      *  Inference Providers⟨24⟩
      *  Inference Endpoints⟨25⟩
      *  Storage Buckets⟨5⟩
  * * * *
  * Log In⟨26⟩
  * Sign Up⟨27⟩


#   Datasets:⟨3⟩
* * *
 ![](https://huggingface.co/avatars/9f7956f7126ed969044dfe6fee5fb788.svg) ⟨28⟩
Min142857⟨28⟩
/
KBSI_ResearchAIAgent⟨29⟩
like 0
ArXiv:
arxiv: 2402.14207
arxiv: 2408.15232
 Dataset card ⟨29⟩ Files Files and versions xet ⟨30⟩ Community ⟨31⟩
Dataset Viewer
The dataset viewer is not available because its heuristics could not detect any supported data files⟨32⟩. You can try uploading⟨33⟩ some data files, or configuring⟨34⟩ the data files location manually.
**YAML Metadata Warning:** empty or missing yaml metadata in repo card
Check out the documentation⟨35⟩ for more information.
  * 목차⟨36⟩
  * 1. 시스템 개요⟨37⟩
    * 1.1 정체성⟨38⟩
    * 1.2 세 가지 파이프라인⟨39⟩
    * 1.3 대표 사용 시나리오⟨40⟩
  * 2. 전체 아키텍처⟨41⟩
    * 2.1 계층 구조⟨42⟩
    * 2.2 런타임 서비스 토폴로지⟨43⟩
    * 2.3 기술 스택⟨44⟩
  * 3. 기반 프레임워크 계층 (STORM / Co-STORM)⟨45⟩
    * 3.1 `interface.py` — 추상 계약 계층⟨46⟩
    * 3.2 `lm.py` — LM 래퍼⟨47⟩
    * 3.3 `dataclass.py` — Co-STORM 핵심 구조 (Analytical STORM이 재사용)⟨48⟩
    * 3.4 `collaborative_storm/engine.py` — Co-STORM 설정·러너⟨49⟩
    * 3.5 STORM(위키) 파이프라인 참고⟨50⟩
  * 4. Analytical STORM 파이프라인 (핵심 커스텀 계층)⟨51⟩
    * 4.1 상태 머신과 오케스트레이터⟨52⟩
    * 4.2 Phase 1 — 요구사항 수집 (Requirement Gathering)⟨53⟩
    * 4.3 Phase 2 — 연구 (Research)⟨54⟩
    * 4.4 Phase 3 — 보고서 생성 (Report Generation)⟨55⟩
    * 4.5 Phase 4 — 후속 Q&A (Post-Report QA)⟨56⟩
    * 4.6 번역 계층⟨57⟩
    * 4.7 실행 로깅⟨58⟩
    * 4.8 종단 데이터 흐름⟨59⟩
  * 5. 검색·임베딩 인프라⟨60⟩
    * 5.1 `rm.py` — 검색 모듈⟨61⟩
    * 5.2 `db_retriever/` — 로컬 검색 내부⟨62⟩
    * 5.3 `encoder.py` — 임베딩 인코더⟨63⟩
    * 5.4 `query_expansion.py` — Wikipedia 쿼리 확장⟨64⟩
  * 6. 웹 애플리케이션 (FastAPI)⟨65⟩
    * 6.1 API 엔드포인트⟨66⟩
    * 6.2 파이프라인 호출⟨67⟩
    * 6.3 Q&A 경로⟨68⟩
    * 6.4 동시성 / GPU 큐⟨69⟩
    * 6.5 세션 관리 / 영속화⟨70⟩
  * 7. 데이터 구조 명세⟨71⟩
    * 7.1 `state.json` (세션 상태)⟨72⟩
    * 7.2 `pipeline_log_*.json` (파이프라인 로그)⟨73⟩
    * 7.3 `pipeline_trace_*.md` (사람 가독 트레이스)⟨74⟩
    * 7.4 보고서 `report.md`⟨75⟩
  * 8. 배치·성능 테스트 하네스⟨76⟩
  * 9. 배포·운영 토폴로지⟨77⟩
    * 9.1 하드웨어 요구사항 (DEPLOY_GUIDE.md 기준)⟨78⟩
    * 9.2 서비스 기동 (`start_services.sh`)⟨79⟩
    * 9.3 서버 이전 시 필수 수정 지점⟨80⟩
    * 9.4 인증·설정⟨81⟩
  * 10. 주요 설정값 레퍼런스⟨82⟩
  * 11. 부록: 주요 클래스·파일 인덱스⟨83⟩
    * 11.1 커스텀 계층 (본 시스템 고유)⟨84⟩
    * 11.2 재사용된 기반 프레임워크⟨85⟩
  * 부록 A. 참고 논문·원본⟨86⟩


#   ⟨87⟩ KBSI_ResearchAIAgent 시스템 기술 명세서 
> **문서 성격** : 코드베이스 전수 조사 기반 기술 명세서 (Technical Specification) **대상 시스템** : `KBSI_ResearchAIAgent` — 분석과학(Analytical Science) AI 에이전트 **기반 프레임워크** : Stanford OVAL Lab **STORM / Co-STORM** (`knowledge-storm`) **작성 기준일** : 2026-07-08
* * *
##   ⟨36⟩ 목차 
  1. 시스템 개요⟨37⟩
  2. 전체 아키텍처⟨41⟩
  3. 기반 프레임워크 계층 (STORM / Co-STORM)⟨45⟩
  4. Analytical STORM 파이프라인 (핵심 커스텀 계층)⟨51⟩
  5. 검색·임베딩 인프라⟨88⟩
  6. 웹 애플리케이션 (FastAPI)⟨65⟩
  7. 데이터 구조 명세⟨71⟩
  8. 배치·성능 테스트 하네스⟨89⟩
  9. 배포·운영 토폴로지⟨90⟩
  10. 주요 설정값 레퍼런스⟨82⟩
  11. 부록: 주요 클래스·파일 인덱스⟨91⟩


* * *
##   ⟨37⟩ 1. 시스템 개요 
###   ⟨38⟩ 1.1 정체성 
`KBSI_ResearchAIAgent`는 Stanford OVAL Lab의 오픈소스 **STORM**(Synthesis of Topic Outlines through Retrieval and Multi-perspective Question Asking)과 그 협업 확장판 **Co-STORM** 을 기반으로, **분석과학·재료과학 분야의 실험 방법론 보고서를 자동 생성** 하도록 특화한 커스텀 시스템이다.
기본 STORM은 "위키백과 수준의 글을 자동 작성"하는 범용 시스템이지만, 본 시스템은 그 위에 다음 커스텀 계층을 얹어 **분석 장비·측정 기법 중심의 심층 기술 보고서 생성기** 로 재구성했다.
  * **요구사항 수집(Requirement Gathering) 프런트엔드** — 사용자의 자연어 질의를 구조화된 분석 요구사항으로 변환
  * **KBSI 논문/SOP 사내 지식 검색** — 로컬 Milvus 벡터 DB + PostgreSQL 기반 사내 문서 검색
  * **한국어↔영어 번역 계층** — 영어로 추론하고 한국어로 산출하는 이중언어 파이프라인
  * **인용·범위(scope) 후처리 품질 제어** — 참조 중복 제거, 인용 검증, 개념 소유권(concept ownership) 강제
  * **구조화 실행 로깅** — 파이프라인 전 과정을 JSON/Markdown으로 추적
  * **FastAPI 웹 애플리케이션** — NotebookLM 스타일 UI, 다중 사용자 GPU 작업 큐, 세션 영속화


###   ⟨39⟩ 1.2 세 가지 파이프라인   
| 시스템  | 성격  | 실행 방식  | 본 시스템에서의 위치  |  
| --- | --- | --- | --- |  
| **STORM**  | 완전 자동 위키 기사 생성 (4단계 순차)  | CLI 스크립트  | 기반 프레임워크 (직접 사용 안 함)  |  
| **Co-STORM**  | 인간-AI 협업 담론 (턴 기반, 마인드맵)  | CLI 스크립트  | **연구(Research) 단계 엔진으로 재사용**  |  
| **Analytical STORM**  | 분석과학 특화 심층 보고서 (5단계)  | Jupyter / **웹앱**  | **본 시스템의 실제 제품 파이프라인**  |  
| _Analytical STORM은 현재 베타테스트 진행 및 보완 진행 단계로 개발 완료 후 추가 공개예정_  |   |   |   |  
| _베타버전 활용 및 지원 관련 문의는kms0609@kbsi.re.kr로 연락부탁드립니다._  |   |   |   |  
###   ⟨40⟩ 1.3 대표 사용 시나리오 
사용자가 한국어로 `"리튬황 전지에서 폴리설파이드 셔틀 억제를 위한 분석 전략을 정리해줘"`와 같은 질의를 입력하면:
  1. 시스템이 대상 물질·분석 목표·시료 형태 등을 구조화하고,
  2. 다수의 분석기법 전문가(XPS·XAS·Raman 등) 에이전트가 사내 논문·웹을 검색하며 담론을 전개해 지식 마인드맵을 구축하고,
  3. 이를 인용이 달린 다중 섹션 한국어 기술 보고서(`report.md`)로 합성하며,
  4. 생성된 보고서에 대해 후속 Q&A를 지원한다.


실제 산출물 예시는 `web_app/sessions/*/report.md`, `storm/examples/costorm_examples/results/analytical-storm/Q1/report.md` 등에서 확인할 수 있으며, 리튬 금속 표면 분석(XPS/ToF-SIMS/STM)·Li-S 전지 폴리설파이드 분석 등 실제 분석과학 도메인 보고서가 저장되어 있다.
* * *
##   ⟨41⟩ 2. 전체 아키텍처 
###   ⟨42⟩ 2.1 계층 구조 

```
┌─────────────────────────────────────────────────────────────────────┐
│  프레젠테이션 계층                                                     │
│  web_app/static (index.html, app.js, style.css)  ── NotebookLM UI     │
└───────────────┬─────────────────────────────────────────────────────┘
                │ HTTP / SSE
┌───────────────▼─────────────────────────────────────────────────────┐
│  애플리케이션 계층  web_app/app.py (FastAPI, :17777)                   │
│   · 세션 관리 / 영속화     · GPU 작업 큐(세마포어)                      │
│   · 파일 업로드·청킹        · 요청 라우팅 / 게이트웨이 터널링           │
└───────────────┬─────────────────────────────────────────────────────┘
                │ in-process 호출
┌───────────────▼─────────────────────────────────────────────────────┐
│  파이프라인 계층  knowledge_storm/analytical_storm/                    │
│   AnalyticalScienceRunner (상태 머신: 5-phase)                         │
│    ├─ RequirementGatheringAgent / AutoFillAgent   (요구사항)          │
│    ├─ CoStormRunner + AnalyticalExpertGeneration  (연구·담론)         │
│    ├─ AnalyticalReportGenerationModule            (보고서 합성)       │
│    ├─ PostReportQAAgent                           (후속 Q&A)          │
│    ├─ TranslationAgent / TranslatingRM            (한↔영 번역)        │
│    └─ PipelineLogger                              (실행 로깅)         │
└───────────────┬───────────────────────────┬─────────────────────────┘
                │                           │
┌───────────────▼──────────┐   ┌────────────▼─────────────────────────┐
│  기반 프레임워크           │   │  검색·임베딩 인프라                    │
│  interface / lm / dataclass│   │  rm.py (KBSIPaperRM, CombinedRM …)   │
│  collaborative_storm       │   │  db_retriever/ (Milvus, PostgreSQL)  │
│  KnowledgeBase(마인드맵)   │   │  encoder.py, query_expansion.py      │
└───────────────┬──────────┘   └────────────┬─────────────────────────┘
                │                           │
┌───────────────▼───────────────────────────▼─────────────────────────┐
│  외부 서비스 계층                                                      │
│   vLLM LLM 서버 (gpt-oss-120b, :8000)                                 │
│   임베딩 서버 (llama-embed-nemotron-8b, :9093, sentence-transformers) │
│   Milvus-lite 벡터 DB (kbsi_papers_)   PostgreSQL(SOP)   Tavily(웹)   │
└──────────────────────────────────────────────────────────────────────┘

```

###   ⟨43⟩ 2.2 런타임 서비스 토폴로지 
`start_services.sh` 기준 단일 GPU 호스트(B200) 배치:  
| 서비스  | 모델/엔진  | 자원  | 포트  | 프로토콜  |  
| --- | --- | --- | --- | --- |  
| **LLM 생성**  |  `gpt-oss-120b` (vLLM)  | GPU 0  | 8000/8002  | OpenAI 호환 `/v1`  |  
| **임베딩**  |  `nvidia/llama-embed-nemotron-8b` (sentence-transformers)  | GPU 1  | 9093  | OpenAI 호환 `/v1/embeddings`  |  
| **벡터 DB**  | milvus-lite (`kbsi_papers_`)  | 로컬 파일  | —  | pymilvus (in-process)  |  
| **SOP DB**  | PostgreSQL (`rnd_docs.kbsi_sop`)  | 원격  | 5432  | psycopg2  |  
| **웹앱**  | FastAPI/uvicorn  | CPU  | 17777 (배포)/49003  | HTTP/SSE  |  
> **주의 (환경 불일치)** : 임베딩 서버 주소가 파일마다 다르다. `web_app/app.py`는 `localhost:9093`, `run_batch_analysis.py`는 원격 `203.250.238.31:9093`을 사용한다. `DEPLOY_GUIDE.md`는 또 다른 임베딩 모델(`intfloat/multilingual-e5-large-instruct`)을 예시로 든다. 서버 이전 시 이 값들을 반드시 일치시켜야 한다.
###   ⟨44⟩ 2.3 기술 스택 
  * **오케스트레이션** : DSPy (`dspy_ai==2.4.9` 고정 — 버전 간 API 파괴적 변경 이력, 업그레이드 금지)
  * **LM 접근** : LiteLLM 기반 통합 래퍼 + vLLM OpenAI 호환 클라이언트
  * **웹** : FastAPI + uvicorn + Pydantic
  * **벡터 검색** : pymilvus (milvus-lite), BM25 하이브리드 옵션
  * **키워드 검색** : PostgreSQL ILIKE
  * **임베딩** : sentence-transformers / LangChain HuggingFace / 원격 vLLM 임베딩
  * **문서 파싱** : PyMuPDF(fitz) / pdfplumber, langchain-text-splitters


* * *
##   ⟨45⟩ 3. 기반 프레임워크 계층 (STORM / Co-STORM) 
`storm/knowledge_storm/` 패키지. 본 시스템은 이 중 **`interface`,`lm` , `dataclass`, `collaborative_storm`, `encoder`, `rm`, `query_expansion`** 을 재사용한다.
###   ⟨46⟩ 3.1 `interface.py` — 추상 계약 계층 
모든 엔진·모듈이 상속하는 기반 계약.  
| 클래스  | 성격  | 역할  |  
| --- | --- | --- |  
|  `Information` (:41)  | 데이터 클래스  |  **검색 지식의 원자 단위**. `description·snippets·title·url·meta·citation_uuid`. `url`이 UUID 역할, `__hash__`는 (url + 정렬된 snippets + meta질의) MD5  |  
|  `InformationTable` (:23)  | ABC  | 지식 큐레이션 결과 저장, `retrieve_information()`  |  
|  `ArticleSectionNode` (:136)  | 트리 노드  | 섹션 트리(`section_name·content·children·preference`)  |  
|  `Article` (:162)  | ABC  | 기사 트리 루트 보유, `to_string()`/`from_string()`  |  
|  `Retriever` (:260)  | 구상 클래스  |  `dspy.Retrieve`(rm)를 감싸 스레드풀 검색 + 쿼리 확장 + 인용 제거 → `List[Information]`  |  
|  `LMConfigs` (:430)  | ABC  |  **LM 역할 번들의 기반**. 규약: 모든 LM 속성은 `_lm` 접미사 필수. 리플렉션으로 토큰/히스토리 집계  |  
|  `Engine` (:488)  | ABC  | 파이프라인 러너 기반. `run_*` 메서드 자동 데코레이션(실행시간·토큰 기록)  |  
|  `Agent` (:568)  | ABC  | 대화형 에이전트 기반. `generate_utterance(kb, history, …) → ConversationTurn`  |  
**핵심 규약** : `LMConfigs`의 `_lm` 접미사 리플렉션이 두 파이프라인(STORM/Co-STORM) 전반의 토큰 집계·히스토리 수집을 일관되게 만든다. 각 LM 래퍼의 `get_usage_and_reset()` → `collect_and_reset_lm_usage()` → `Engine.lm_cost`로 비용이 흐른다.
###   ⟨47⟩ 3.2 `lm.py` — LM 래퍼   
| 클래스  | 제공자  | 비고  |  
| --- | --- | --- |  
|  **`LitellmModel`**(:192)  | LiteLLM 지원 전체  |  **주력 래퍼**. 기본 `openai/gpt-4o-mini`, 스레드-세이프 토큰 추적  |  
|  **`VLLMClient`**(:845)  | 자체 호스팅 vLLM  |  **본 시스템 실사용**. OpenAI 호환 서버  |  
|  `OpenAIModel` / `AzureOpenAIModel`  | OpenAI/Azure  | 레거시(v1.1.0 이후 deprecated)  |  
|  `ClaudeModel` (:709)  | Anthropic  |  `messages` API, RateLimit 재시도 max 8회  |  
|  `DeepSeekModel`·`GroqModel`·`GoogleModel`·`TogetherClient`·`OllamaClient`·`TGIClient`  | 각 제공자  | 레거시 호환  |  
  * **캐싱** : LiteLLM 디스크 캐시 `~/.storm_local_cache` + `lru_cache(maxsize=3000)`
  * **재시도** : 레거시 래퍼는 `backoff` 지수 백오프(`max_time=1000`); LitellmModel은 LiteLLM 내부 재시도
  * **공통 인터페이스** : 모든 래퍼가 `get_usage_and_reset() → {model: {prompt_tokens, completion_tokens}}` 노출


###   ⟨48⟩ 3.3 `dataclass.py` — Co-STORM 핵심 구조 (Analytical STORM이 재사용)   
| 클래스  | 역할  | 주요 필드  |  
| --- | --- | --- |  
|  **`ConversationTurn`**(:11)  | 담론 한 턴  |  `role`, `role_description`, `raw_utterance`, `utterance`(정제), `utterance_type`, `queries`, `raw_retrieved_info: List[Information]`, `cited_info: Dict[int, Information]`  |  
|  **`KnowledgeNode`**(:86)  | 마인드맵 노드  |  `name`, `content: Set[int]`(인용 UUID 집합), `children`, `parent`, `synthesize_output`(캐시된 요약)  |  
|  **`KnowledgeBase`**(:291)  | **동적 계층형 마인드맵**  |  `root`, `info_uuid_to_info_dict`, `info_hash_to_uuid_dict`, `kb_embedding`(구조 임베딩 캐시), 4개 DSPy 서브모듈(insert/expand/article-gen/summary)  |  
`KnowledgeBase`는 Co-STORM 논문 §3.2의 "공유 개념 공간(shared conceptual space)"을 구현한다. 주요 연산:
  * `insert_information()` — 스레드 락 하에 인용 UUID 부여 후 노드 삽입
  * `update_from_conv_turn()` — 담론 턴의 인용 정보 삽입 및 인용 인덱스 재매핑
  * `reorganize()` — 상향식 노드 확장 + 하향식 정리 (트리 재구성)
  * `get_node_hierarchy_string()` — 인덱스/전체경로/해시태그/인용강조(`⭐`) 옵션 트리 문자열
  * `to_report()` — 마인드맵 → 보고서 변환


###   ⟨49⟩ 3.4 `collaborative_storm/engine.py` — Co-STORM 설정·러너 
**`CollaborativeStormLMConfigs`**(:24) — Analytical STORM이 그대로 재사용하는**6개 LM 역할** 번들:  
| LM 역할  | 용도  | 기본 max_tokens  |  
| --- | --- | --- |  
| `question_answering_lm`  | 답변/전문가 발화 생성  | 1000  |  
| `discourse_manage_lm`  | 담론 제어·전문가 목록 생성  | 500  |  
| `utterance_polishing_lm`  | 발화 정제  | 2000  |  
| `warmstart_outline_gen_lm`  | 워밍업 아웃라인 생성  | 500  |  
| `question_asking_lm`  | 중재자·질문 생성  | 300  |  
| `knowledge_base_lm`  | 마인드맵 모듈 구동  | 1000  |  
  * **`RunnerArgument`**(:234):`total_conv_turn=20` , `retrieve_top_k=10`, `warmstart_max_num_experts=3`, `max_num_round_table_experts=2`, `node_expansion_trigger_count=10` 등 파이프라인 노브
  * **`DiscourseManager`**(:370): 에이전트 역할(SimulatedUser·PureRAGAgent·Moderator·CoStormExpert) 조율,`get_next_turn_policy()` 로 다음 발화 주체 결정
  * **`CoStormRunner`**(:561):`warm_start()`(미니-STORM 초기 마인드맵 구축), `step()`(턴 진행), `generate_report()`, 전체 상태 `to_dict/from_dict` 직렬화


###   ⟨50⟩ 3.5 STORM(위키) 파이프라인 참고 
`storm_wiki/engine.py`의 `STORMWikiRunner`는 5개 LM 역할(`conv_simulator_lm`·`question_asker_lm`·`outline_gen_lm`·`article_gen_lm`·`article_polish_lm`)로 **조사 → 아웃라인 → 기사 → 교정** 4단계를 순차 실행한다. 본 시스템은 이 파이프라인을 직접 쓰지 않으나 동일 기반 계약(`InformationTable`/`Article`/`Engine`)을 공유한다. 관련 데이터 구조는 `storm_dataclass.py`의 `StormInformationTable`(SentenceTransformer 시맨틱 검색 인덱스), `StormArticle`(통합 인용 인덱스 트리)에 있다.
* * *
##   ⟨51⟩ 4. Analytical STORM 파이프라인 (핵심 커스텀 계층) 
`storm/knowledge_storm/analytical_storm/`. 본 시스템의 실제 제품 로직.
###   ⟨52⟩ 4.1 상태 머신과 오케스트레이터 
**`AnalysisPhase`**(engine.py:33) 상태 전이:

```
IDLE → REQUIREMENT_GATHERING → RESEARCH → REPORT_GENERATION → POST_REPORT_QA

```

**`AnalyticalScienceRunner`**(engine.py:88)가 전 과정을 조율한다. 생성자는`CollaborativeStormLMConfigs` , `RunnerArgument`, `rm`(검색), `encoder`, `translation_agent`, `query_expander`와 루프 한도(`max_requirement_questions=3`, `max_research_turns=10`)를 받는다.
**`AnalysisStepResult`**(engine.py:43) — 모든 러너 메서드가 반환하는 통일 객체:`phase` , `message`, `question`, `report`, `conversation_turn`, `requirements`, `is_phase_complete`.
전 단계를 관통하는 두 핵심 데이터 구조는 **`AnalysisRequirements`**(요구사항)와**`KnowledgeBase`**(마인드맵)이며, 단계별 반환 객체는 **`AnalysisStepResult` **·**`ConversationTurn` **이다.
###   ⟨53⟩ 4.2 Phase 1 — 요구사항 수집 (Requirement Gathering) 
`modules/requirement_agents.py`. **표준 STORM에는 없는 완전 커스텀 프런트엔드.**
**`AnalysisRequirements`**데이터 클래스 (중심 구조):  
| 필드  | 타입  | 필수/자동보완  |  
| --- | --- | --- |  
| `target_material`  | str  | **필수**  |  
| `analysis_goals`  | List  | **필수**  |  
| `material_type`  | str  | 자동보완  |  
| `sample_form`  | str  | 자동보완  |  
| `known_composition`  | str  | 자동보완  |  
| `target_properties`  | List  | 자동보완  |  
| `constraints`  | List  | 선택  |  
| `context`  | str  | 선택  |  
  * `REQUIRED_FIELDS = ["target_material", "analysis_goals"]` — `is_complete()` 게이트
  * `to_research_topic()` — 요구사항을 영어 연구 주제 문자열로 변환해 Co-STORM에 주입 (예: "Analytical characterization methods for {material} focusing on {goals} in {form} form")
  * `update_from_dict()` — `None` 및 센티넬(`"unknown"/"null"/"none"/"n/a"`) 값 무시


**두 에이전트** :
  1. **`RequirementGatheringAgent`**(question_answering_lm 사용): 3개 DSPy 모듈로 구성
     * `ParseInitialRequirements` — 자유 텍스트 → 8키 구조화 JSON
     * `RequirementQuestionGeneration` — 가장 중요한 결측 필드에 대해 질문 1개 생성
     * `RequirementUpdateFromResponse` — 사용자 답변 → 필드값 추출
  2. **`AutoFillAgent`**:`AutoFillRequirement` + `Retriever`. 자동보완 필드마다 `FIELD_METADATA` 템플릿으로 검색 → 상위 5개 스니펫에서 LM이 값 추출 → 리스트 필드는 JSON/콤마 파싱


**흐름** : `parse_initial_input()` → (미완성 시) 최대 3회 질문 루프 → 여전히 미완성이면 `auto_fill()`로 나머지 채움 → 연구 단계 전환. **웹앱은 사용자 상호작용 없이 빈 입력(`step(user_input="")`)으로 자동보완을 강제**한다.
###   ⟨54⟩ 4.3 Phase 2 — 연구 (Research) 
`CoStormRunner`를 연구 엔진으로 위임한다.
  1. `_transition_to_research()` — `requirements.to_research_topic()`으로 주제 설정 후 `CoStormRunner` 생성
  2. `warm_start()` — 미니-STORM 배경 조사로 초기 마인드맵 구축 (**최대 3회 재시도** : RuntimeError 또는 빈 대화 이력 시 러너 재초기화)
  3. **`AnalyticalExpertGenerationModule`**(engine.py:56) — 표준 Co-STORM 전문가 생성기를 대체.`GenerateAnalyticalExpert` 시그니처로 XRD·SEM·TEM·FTIR·Raman·XPS·NMR·DSC-TGA·BET·ICP·AFM·UV-Vis 등 **분석기법별 다양한 전문가** 를 선정 → `CoStormExpert` 인스턴스로 담론 매니저에 주입
  4. 담론 루프(`step()`, 최대 10턴): 전문가/중재자가 검색·발화하며 `KnowledgeBase`가 성장. 한국어 입력은 `TranslationAgent`로 영어 변환 후 처리


각 턴은 `ConversationTurn`으로 반환되며, `PipelineLogger`가 발화·질의·검색문서·인용·KB 스냅샷을 기록한다.
###   ⟨55⟩ 4.4 Phase 3 — 보고서 생성 (Report Generation) 
`modules/analytical_report_generation.py`의 **`AnalyticalReportGenerationModule`**— 본 시스템에서 가장 정교한 커스텀 품질 제어 로직.
**섹션 생성** :
  * `target_lang`에 따라 `WriteAnalyticalSectionKo`(한국어) 또는 `WriteAnalyticalSection`(영어) 시그니처 선택
  * 노드별 순차 생성. 누적 `previously_covered`(이전 섹션 요약, `SummarizeCoveredTopics` 사용)를 다음 섹션에 주입 → **반복 방지(anti-repetition)**
  * 업로드 문서는 4000단어 예산 내에서 우선 배치(`★ 사용자 업로드 문서` 라벨)


**참조 후처리 5단계 파이프라인** :  
| 단계  | 처리  | 시그니처  |  
| --- | --- | --- |  
| 1  | 제목 정규화/퍼지 매칭으로 참조 중복 제거, `[old]→[canonical]` 재매핑  | —  |  
| 2  | LLM 관련성 필터링(50자 미만 스니펫 제거)  | `CheckRetrievalRelevance`  |  
| 3  | 각 `[N]` 문장의 인용 검증  | `VerifyCitation`  |  
| 4  | 순차 재번호(3-pass placeholder swap), 최대 15개 참조 제한  | —  |  
| 5  | 학술 형식 참조 목록 생성, 내부 URL(`kbsi-*`, `upload://`) 은닉  | —  |  
**추가 후처리** :
  * 제목 레벨 정규화(형제 노드 레벨 정렬 + 갭 클로징)
  * LaTeX → 유니코드 변환(대규모 치환 테이블)
  * 마크다운 표 복구
  * `CheckValueConsistency` — 결합에너지·압력·온도 등 모순 수치 경고 로깅
  * **`_enforce_scope()`**— 비핵심 섹션이 전체의 30% 초과 시 제목+2문장으로 절삭 (**핵심 기법 ~60% 범위 강제**)


**개념 소유권(concept ownership)** : `AnalyticalReportOutline` 시그니처가 각 개념을 정확히 한 섹션이 소유하도록 규칙 인코딩(글러브박스→§1.2, 안전→§5, 비용→§6 등).
산출: `language != "ko"`이고 번역 에이전트가 있으면 영어 보고서를 한국어로 번역(`translate_report()`).
###   ⟨56⟩ 4.5 Phase 4 — 후속 Q&A (Post-Report QA) 
`modules/qa_agent.py`의 **`PostReportQAAgent`**:
  * `AnswerFromReport` 시그니처 사용. 추가 검색(있으면) 또는 KB 스니펫 최대 10개 + 보고서(5000단어 절삭)로 답변
  * 후처리: `remove_uncompleted_sentences_with_citations` + `separate_citations`
  * **번역 로직** : `language=="ko"`면 질문·답변 모두 한국어 유지. `language=="en"`이면 한국어 질문→영어 변환→영어 답변→한국어 재번역


###   ⟨57⟩ 4.6 번역 계층 
`modules/translation_agent.py`:
  * **`TranslationAgent`**— DSPy 시그니처 없이 직접 프롬프트.`to_english()` /`to_korean()`(인용·마크다운·약어 보존), `translate_query()`(PostgreSQL ILIKE용 조사 제거 키워드), `translate_search_results()`(전 세그먼트를 `%%%` 구분자로 **단일 LLM 호출 배치**), `translate_report()`(헤더별 분할 번역)
  * **`TranslatingRM`**(dspy.Retrieve 래퍼) — 영어 질의→한국어 변환→내부 RM→한국어 결과→영어 변환.**영어 LLM 파이프라인이 한국어 DB(KBSI SOP)를 투명하게 조회** 하게 함


###   ⟨58⟩ 4.7 실행 로깅 
`modules/pipeline_logger.py`의 **`PipelineLogger`**(BaseCallbackHandler 상속) — STORM 콜백 가로채기 + 노트북 HTML 표시 + JSON/Markdown 익스포트를 결합.
  * **13개 콜백 오버라이드** : `on_expert_information_collection_*`, `on_mindmap_insert_*`, `on_warmstart_update` 등
  * **수동 로깅** : `start_phase/end_phase`(duration 계산), `log_requirements`, `log_conversation_turn`(가장 풍부: 턴번호·역할·발화·질의·검색정보·인용인덱스·재구성인용·콜백이벤트·KB스냅샷), `log_report`, `log_qa_turn`
  * **익스포트** : `export_json()`(`pipeline_log_*.json`), `export_readable_trace()`(`pipeline_trace_*.md`)


###   ⟨59⟩ 4.8 종단 데이터 흐름 

```
사용자 질의 (str)
  └─ start_analysis → RequirementGatheringAgent.parse_initial_input → AnalysisRequirements
        └─ [루프] generate_question → 사용자 답변 → update_from_response   (최대 3회)
        └─ AutoFillAgent.auto_fill (검색) → 나머지 필드 채움
  └─ _transition_to_research → to_research_topic() → CoStormRunner
        └─ warm_start (≤3 재시도) → AnalyticalExpertGeneration → CoStormExpert[]
        └─ [루프] step() → ConversationTurn, KnowledgeBase 성장  (최대 10턴)
  └─ generate_report → AnalyticalReportGenerationModule.forward(KnowledgeBase, requirements)
        └─ 섹션별 Write → 중복제거 → 관련성 → 인용검증 → 재번호 → 참조목록
           → LaTeX/표 정리 → 범위 강제 → report (str)
        └─ (lang≠ko) TranslationAgent.translate_report → 한국어 보고서
  └─ POST_REPORT_QA: PostReportQAAgent.answer_question(보고서 + KB + 검색) → 답변

```

* * *
##   ⟨60⟩ 5. 검색·임베딩 인프라 
###   ⟨61⟩ 5.1 `rm.py` — 검색 모듈 
모든 클래스는 `dspy.Retrieve`를 상속하고 `forward(query_or_queries, exclude_urls) → List[dict]`(`description·snippets·title·url`)을 구현한다.
**표준 STORM 검색기** : `YouRM`, `BingSearch`, `VectorRM`(Qdrant), `SerperRM`, `BraveRM`, `SearXNG`, `DuckDuckGoSearchRM`, `TavilySearchRM`, `GoogleSearch`, `MilvusRM`, `AzureAISearch`, `CombinedRM`.
> **TavilySearchRM 로컬 패치** (rm.py:940): 쿼리를 400자로 클램프하고 `.search()`를 try/except로 감쌈 — STORM 쿼리 확장이 과길이 쿼리를 낼 수 있기 때문.
**커스텀 검색기 (핵심)** :  
| 클래스  | 백엔드  | 방식  | 특징  |  
| --- | --- | --- | --- |  
|  **`KBSIPaperRM`**(:1308)  | 로컬 milvus-lite (`kbsi_papers_`)  | 밀집+BM25 하이브리드  |  `k=12`, `alpha=0.6`(밀집/희소 가중), URL `kbsi-paper://{paper_id}#{paragraph_id}`, 제목 한→영 폴백  |  
|  **`KBSISopRM`**(:1395)  | KBSI PostgreSQL  | 키워드 ILIKE (벡터 아님)  | 쿼리 토큰화 후 최대 3키워드 `search_all()`, URL `kbsi-sop://{doc_id}`  |  
|  **`CombinedRM`**(:1236)  | 다중 RM 조합  | 라운드로빈 인터리브 + URL 중복제거  | 사내 DB + 웹 결과 융합  |  
|  **`UserDocumentRM`**(app.py:324)  | 인메모리  | 코사인 유사도  | 업로드 문서 청크, URL `upload://{filename}#chunk{N}`  |  
###   ⟨62⟩ 5.2 `db_retriever/` — 로컬 검색 내부 
**A. Milvus (벡터) — 논문**
  * `milvus_backend.py`: **milvus-lite**(인프로세스 로컬 파일, 네트워크 서버 아님). `MilvusSettings`: `collection_name="kbsi_papers_"`, 임베딩 `nvidia/llama-embed-nemotron-8b`, `base_url=http://localhost:9093/v1`, 필드 `content/dense/sparse`. `build_milvus_objects()`가 `sparse` 필드 존재로 BM25 지원 자동 감지. `get_milvus_objects()`는 컬렉션별 스레드-세이프 캐시 싱글턴
  * `retrieve.py`: `search_by_query(query, ctx, top_k=3, alpha=0.6)` — 쿼리 임베딩 후 하이브리드(밀집 COSINE + 희소 BM25, `WeightedRanker(alpha, 1-alpha)`) 또는 밀집 전용. `OUTPUT_FIELDS`가 문서/청크 스키마 노출: `content, paper_id, paragraph_id, title_ko/en, authors_ko/en, institutions, sequence, head, level` (논문이 문단 단위로 청킹, 이중언어 메타데이터)


**B. PostgreSQL — SOP 문서**
  * `postgre_engine.py`: 테이블 `kbsi_sop`, **접속 정보 하드코딩**(host `203.250.238.31:5432`, dbname `rnd_docs`). 스키마: `doc_id`(PK), `protocol_kor`(기법명), `code`, `category/category_kor`(장비), `model_name`, 연락처(`person_name/phone/mail`), `content`(마크다운). `search_all(keyword)` — 6개 컬럼 OR-ILIKE (KBSISopRM이 호출)


> **현재 배포 상태** : SOP/PostgreSQL 검색기는 웹앱에서 **비활성화**(app.py:502) — SOP DB 덤프가 없고 `kbsi_papers` Milvus 컬렉션만 프로비저닝됨. 단, `run_batch_analysis.py`에서는 활성화.
###   ⟨63⟩ 5.3 `encoder.py` — 임베딩 인코더 
`Encoder` 클래스 — LiteLLM 기반 임베딩 래퍼(병렬 처리, 디스크 캐시, 토큰 추적). `encoder_type`으로 백엔드 선택:  
| 타입  | 모델 기본값  | 백엔드  |  
| --- | --- | --- |  
| `openai`  | text-embedding-3-small  | litellm  |  
| `azure`  | azure/text-embedding-3-small  | litellm  |  
| `ollama`  | nomic-embed-text  | litellm  |  
| **`vllm`** |  **nvidia/llama-embed-nemotron-8b** (`:9093/v1`)  | local (`VLLMEmbeddings`)  |  
| `hf_local`  | HuggingFace 로컬  | local  |  
**본 시스템은`vllm` 타입 사용**. 색인 시(milvus_backend)와 질의 시(Encoder) 동일한 원격 임베딩 클라이언트(`VLLMEmbeddings`, `db_retriever/embedding.py`)를 써서 임베딩 일관성 유지.
###   ⟨64⟩ 5.4 `query_expansion.py` — Wikipedia 쿼리 확장 
**`WikipediaQueryExpander`**— DSPy 아님, 규칙/API 기반. 약어 중심 과학 쿼리(예: XPS)를 별칭 집합으로 OR 확장해 검색 매칭률을 높임.
  * 약어 감지 정규식(`^[A-Z][A-Z0-9]{1,}$`), 2단계 과학 관련성 티어(분석기법 / 광범위 과학)
  * `expand_query()` — 후보 추출 → `get_aliases()`(Wikipedia 정규 제목 해석 + MediaWiki 리다이렉트 API로 별칭 수집) → `"XPS" OR "X-ray photoelectron spectroscopy" OR "ESCA"` OR절 생성
  * `~/.storm_local_cache/wiki_expansion/` 디스크 캐시(7일 TTL), `drain_history()`로 확장 이벤트 텔레메트리 제공


* * *
##   ⟨65⟩ 6. 웹 애플리케이션 (FastAPI) 
`web_app/app.py` (약 1,248행). NotebookLM 스타일 분석 보고서 생성 UI.
###   ⟨66⟩ 6.1 API 엔드포인트   
| 경로  | 메서드  | 함수  | 설명  |  
| --- | --- | --- | --- |  
| `/`  | GET  | `serve_index_or_tunnel`  |  `index.html` 서빙 또는 `?cmd=<b64-json>` 터널  |  
| `/`  | POST  | `gateway_polyglot`  |  `{path, method, body}` 재디스패치 게이트웨이  |  
| `/api/init`  | POST  | 공유 리소스 초기화  |   |  
| `/api/sessions/create`  | POST  | 8자 UUID 세션 생성  |   |  
|  `/api/sessions` / `/api/sessions/{id}`  | GET  | 세션 목록/조회  |   |  
| `/api/sessions/{id}`  | DELETE  | 세션 삭제  |   |  
| `/api/upload`  | POST  | 파일 업로드(멀티파트) + 텍스트 추출·청킹  |   |  
| `/api/analyze`  | POST  | 파이프라인 큐잉  |   |  
| `/api/status/{id}`  | GET  | 상태 폴링  |   |  
| `/api/report/{id}`  | GET  | 보고서 조회  |   |  
| `/api/chat`  | POST  | 블로킹 Q&A  |   |  
| `/api/chat/stream`  | GET  |  **SSE** 토큰 스트리밍 Q&A  |   |  
| `/api/logs/{id}`  | GET  | JSONL 로그 조회  |   |  
| `/api/queue`  | GET  | 큐 상태  |   |  
| `/api/settings/{id}`  | POST  | Tavily/KBSI 토글  |   |  
> **게이트웨이 터널링** : `cl1.gpuhub` 리버스 프록시가 `/`만 전달하고 `/api/*`는 안 하기 때문에, GET `?cmd=` 터널과 POST 폴리글롯 디스패처가 ASGI scope를 재구성해 인프로세스로 `app(scope, receive, send)` 호출.
###   ⟨67⟩ 6.2 파이프라인 호출 
  * **공유 리소스**(`_init_shared_resources`, 1회 지연 생성): 6개 역할별 `VLLMClient`로 `CollaborativeStormLMConfigs` 구성, `Encoder(vllm)`, `KBSIPaperRM(k=12, alpha=0.6)`, `TavilySearchRM(k=5)`, `WikipediaQueryExpander`, `TranslationAgent`, 폴백 `qa_lm`
  * **세션별 검색기**(`build_rm_for_session`): 업로드 문서 있으면 `UserDocumentRM`을 우선(k=12, 총 k=20), 없으면 총 k=15의 `CombinedRM`
  * **파이프라인 본체**(`_run_analysis_pipeline`): 스레드풀에서 동기 실행. `RunnerArgument(language="ko", total_conv_turn=<1..>, …)`로 `AnalyticalScienceRunner` 구성 후 3단계 실행. **업로드 문서 청크를 KB 루트에`Information` 으로 주입**(ISS-002 fix)해 모든 섹션이 인용 가능하게 함
  * **산출물** : `sessions/{id}/`에 `report.md`, `pipeline_log_*.json`, `pipeline_trace_*.md`. 러너는 Q&A용으로 메모리 유지


###   ⟨68⟩ 6.3 Q&A 경로 
  * `_run_qa`: 인메모리 러너 생존 시 `runner.phase=POST_REPORT_QA` 설정 후 `runner.step()`; 없으면(재시작 후) `_run_qa_fallback`이 `dspy.Predict(AnswerFromReport)` + 신규 검색
  * 스트리밍(`chat_stream`): KBSI+Tavily 신규 검색 후 vLLM OpenAI 엔드포인트 직접 호출(`stream=True`)로 SSE `data: {token}` 프레임 방출


###   ⟨69⟩ 6.4 동시성 / GPU 큐 
  * `MAX_CONCURRENT_PIPELINES=4`, `MAX_CONCURRENT_QA=8` — asyncio 세마포어 2개 + `pipeline_queue` 리스트(락 보호)
  * `start_analysis`가 큐에 추가 → `run_pipeline_with_queue()` 태스크가 세마포어 획득 후 실행 → 대기 순번 메시징


###   ⟨70⟩ 6.5 세션 관리 / 영속화 
  * 인메모리 `sessions: Dict[str, dict]`(락 보호). 세션 필드: `id, created_at, query, status, progress_message, report, runner, chat_history, uploaded_files, use_tavily, use_kbsi, total_conv_turn, user_doc_rm, logger`
  * 디스크 영속: `_save_session_state` → `sessions/{id}/state.json`(직렬화 불가 필드 제외). 시작 시 `_load_sessions_from_disk`로 복원(러너 `None` → 폴백 QA 강제, 진행중 상태는 `error`로 리셋)
  * 이벤트 로그: `SessionLogger` → `logs/{id}.jsonl` (`user_query`, `llm_call`, `retrieval`, `report_generated`, `qa_turn`, `error`, `file_upload`, `phase_change` 등)
  * 업로드: PyMuPDF/pdfplumber로 PDF 추출, 800자 청크·200 오버랩


**상태 머신** : `idle → queued → starting → requirement_gathering → researching → generating_report → ready` (실패 시 `error`)
* * *
##   ⟨71⟩ 7. 데이터 구조 명세 
###   ⟨72⟩ 7.1 `state.json` (세션 상태) 

```
{
  "id": "187d5f20",
  "created_at": "2026-06-29T11:07:05",   // ISO
  "query": "리튬황 전지에서 폴리설파이드 셔틀 억제…",
  "status": "ready",                       // 상태 머신 값
  "progress_message": "보고서가 준비되었습니다.",
  "report": "# 셀 호환 분광 구성\n…",        // 전체 마크다운
  "chat_history": [{"question", "answer", "timestamp"}],
  "uploaded_files": [{"filename", "size", "chunks", "uploaded_at"}],
  "use_tavily": true,
  "use_kbsi": true
}

```

※ `runner·logger·user_doc_rm`은 직렬화 불가로 의도적 제외.
###   ⟨92⟩ 7.2 `pipeline_log_*.json` (파이프라인 로그) 
최상위 키 **`meta`·`requirements` · `phases` · `events`**:
  * **`meta`**:`{version:"1.0", created_at, pipeline:"AnalyticalScienceSTORM", total_duration_seconds}`
  * **`requirements`**:`target_material, material_type, analysis_goals[], sample_form, constraints[], target_properties[], known_composition, context`
  * **`phases`**:
    * `requirement_gathering`: `{start_time, end_time, duration_seconds}`
    * `warm_start`: `query_expansions[]` — 각 `{original_query, candidates[], alias_map{}, expanded_query, was_expanded}`
    * `research`: `{…, kb_snapshots[], turns[]}`; `turns[]` = `{turn_number, role, role_description, utterance_type, utterance, queries[], raw_retrieved_info[], cited_indices[], cited_info_reconstructed[], callback_events[], query_expansions[], kb_snapshot_after}`
    * `report_generation`: `{…, report_text, report_word_count, all_citation_indices[]}`
  * **`events`**: 전 실행의 콜백 이벤트 평면 배열`{event_id, timestamp, phase, event_type, payload}`


**소스 식별자 규약** : `kbsi-paper://<paperid>#<paragraph>`(사내 논문), `kbsi-sop://<doc_id>`(SOP), `upload://<file>#chunk<N>`(업로드), `http(s)://…`(웹). 내부 URL은 최종 보고서 참조 목록에서 은닉됨.
###   ⟨93⟩ 7.3 `pipeline_trace_*.md` (사람 가독 트레이스) 
`pipeline_log`의 동일 데이터를 사람이 읽기 쉬운 마크다운으로 렌더링. 섹션: **① Requirements 표 · ② Warm-Start(쿼리 확장 표, KB 스냅샷) · ③ Research(턴별 발화/질의/확장/검색/KB 델타) · ④ Report Summary(단어수·인용수) · ⑤ Pipeline Timing(단계별 소요시간)**.
###   ⟨75⟩ 7.4 보고서 `report.md`
  * 다중 섹션 한국어 기술 보고서(레벨 계층 정규화된 마크다운 제목)
  * 본문 인라인 인용 `[N]`, 말미 `## 참고 문헌` 학술 형식 목록 `[N] authors, "title" (url)`
  * 마크다운 표, 유니코드(LaTeX 금지) 수식, 검증 필요 수치는 `[확인 필요]` 표기


* * *
##   ⟨76⟩ 8. 배치·성능 테스트 하네스 
루트 레벨 오케스트레이션 스크립트:  
| 스크립트  | 실행 방식  | 목적  |  
| --- | --- | --- |  
| **`run_batch_analysis.py`** | **인프로세스 직접**  | 하드코딩된 ~54개 한국어 분석 쿼리 순차 실행. 쿼리별 `q{NN}_{label}/`에 report/log/trace. 배치 요약 `batch_summary.json`. `--start/--end/--only/--dry-run/--compare`  |  
| **`run_batch_queries.py`** | **HTTP API**  |  `샘플질의.csv`(열 `Q`)를 실행 중 웹앱에 전송(최대 4 동시). create→analyze→폴링→report, 쿼리별 `.md`  |  
| **`run_stress_and_iteration_test.py`** | **HTTP API**  | ① 스트레스: 동시성 N=1..10 벤치마크. ② 반복: `total_conv_turn=1..10` 품질 비교, **GPT-4o로 5개 지표 채점**(정확도·완전성·구조·인용품질·실용성). HTML/MD/JSON 리포트  |  
| **`compare_reports.py`** |  오프라인(LLM 없음)  |  `report.md` 정적 구조 분석: 제목 수/깊이/레벨건너뜀, **메타데이터 에코**(프롬프트 누출), 중복 토픽, 단어 수. 단일/양방 배치 비교  |  
**인프라 빌드 스크립트** :  
| 스크립트  | 목적  |  
| --- | --- |  
| **`embed_server.py`** |  FastAPI+uvicorn 임베딩 서버(:9093). sentence-transformers로 `llama-embed-nemotron-8b`(4096차원) 서빙. vLLM 0.13이 이 양방향 인코더를 못 서빙해서 대체. `/health`, `/v1/embeddings`(OpenAI 형식, L2 정규화)  |  
| **`build_milvus_lite.py`** |  pymilvus로 JSONL 덤프 → `kbsi_papers_` milvus-lite 컬렉션 구축. **사전 계산된 4096차원`dense` 벡터를 그대로 삽입**(재임베딩 없음). 밀집(FLAT/COSINE) + 선택적 BM25 스파스. `--recreate/--no-bm25/--filter-ids`  |  
* * *
##   ⟨77⟩ 9. 배포·운영 토폴로지 
###   ⟨78⟩ 9.1 하드웨어 요구사항 (DEPLOY_GUIDE.md 기준)   
| 항목  | 최소  | 권장  |  
| --- | --- | --- |  
| GPU  | A100 80GB × 2 (TP2)  | A100 80GB × 2 이상  |  
| RAM  | 64GB  | 128GB  |  
| 디스크  | 300GB  | 500GB  |  
###   ⟨79⟩ 9.2 서비스 기동 (`start_services.sh`) 

```
bash start_services.sh [llm|embed|web|all]
  · embed  → CUDA_VISIBLE_DEVICES=1  python embed_server.py         (:9093)
  · llm    → CUDA_VISIBLE_DEVICES=0  vllm serve gpt-oss-120b         (:8000/8002)
  · web    → uvicorn web_app.app:app --port 49003 --workers 1

```

  * 환경변수: `MILVUS_LITE_PATH`(배터리 필터 DB 우선, 없으면 전체 KBSI 덤프), `EMBED_BASE_URL`, `VLLM_PORT/VLLM_BASE_URL`
  * `/tmp` noexec 대응으로 `TMPDIR`·Triton/Inductor/vLLM 캐시를 실행 허용 파일시스템으로 지정
  * `stop_services.sh`로 종료


###   ⟨80⟩ 9.3 서버 이전 시 필수 수정 지점 
  * Milvus: `db_retriever/milvus_backend.py` (또는 `MILVUS_HOST/PORT` 환경변수)
  * PostgreSQL: `db_retriever/postgre_engine.py` (하드코딩된 접속 정보)
  * 임베딩 서버: `web_app/app.py` `Encoder(api_base=…)`
  * LLM: `web_app/app.py` `VLLM_MODEL`, `VLLM_PORT`


###   ⟨81⟩ 9.4 인증·설정 
  * `secrets.toml`(루트): `TAVILY_API_KEY`, `OPENAI_API_KEY`(GPT 평가용 선택), `OPENAI_API_TYPE`, `ENCODER_API_TYPE`. `utils.load_api_key()`로 환경변수 로드
  * GPT-4o 평가용 키는 `openai.txt`에 별도 저장


* * *
##   ⟨82⟩ 10. 주요 설정값 레퍼런스   
| 설정  | 파일·위치  | 값  | 설명  |  
| --- | --- | --- | --- |  
| 동시 파이프라인  | app.py:69  | 4  | GPU 성능 따라 조정  |  
| 동시 QA  | app.py:70  | 8  |   |  
| Co-STORM 반복 턴  | app.py:105,538  | 1  | 1=빠름(~~8분), 7=최고품질(~~ 12분)  |  
| Tavily 웹 검색  | app.py 기본  | True(웹앱)  | 세션별 토글  |  
| 섹션 생성 max_tokens  | app.py:419  | 3000  | 복잡 표 포함 시 증가  |  
| QA max_tokens  | app.py:449  | 3000  |   |  
| QA 보고서 입력 한도  | app.py:697  | 5000 words  |   |  
| 요구사항 질문 한도  | engine 생성자  | 3  |   |  
| 연구 최대 턴  | engine 생성자  | 10  |   |  
| KBSI 논문 검색 k  | app.py:439  | 12  |  `alpha=0.6` 하이브리드  |  
| Tavily 검색 k  | app.py:444  | 5  |   |  
| CombinedRM 총 k  | app.py:513  | 15 (업로드 시 20)  |   |  
| 임베딩 차원  | build_milvus_lite  | 4096  | llama-embed-nemotron-8b  |  
| 참조 최대 개수  | 보고서 후처리  | 15  |   |  
| LLM 생성 파라미터  | app.py:419  | temp 0.2, top_p 0.9  |   |  
| 웹 포트  | uvicorn 인자  | 17777(배포)/49003  |   |  
* * *
##   ⟨83⟩ 11. 부록: 주요 클래스·파일 인덱스 
###   ⟨84⟩ 11.1 커스텀 계층 (본 시스템 고유)   
| 파일  | 주요 심볼  |  
| --- | --- |  
| `analytical_storm/engine.py`  |  `AnalyticalScienceRunner`, `AnalysisPhase`, `AnalysisStepResult`, `AnalyticalExpertGenerationModule`  |  
| `analytical_storm/modules/requirement_agents.py`  |  `AnalysisRequirements`, `RequirementGatheringAgent`, `AutoFillAgent`  |  
| `analytical_storm/modules/analytical_signatures.py`  | 전 DSPy 시그니처(`ParseInitialRequirements`, `GenerateAnalyticalExpert`, `AnalyticalReportOutline`, `WriteAnalyticalSection(Ko)`, `VerifyCitation`, `CheckRetrievalRelevance`, `AnswerFromReport` …)  |  
| `analytical_storm/modules/analytical_report_generation.py`  |  `AnalyticalReportGenerationModule` (5단계 참조 후처리, 범위 강제)  |  
| `analytical_storm/modules/qa_agent.py`  | `PostReportQAAgent`  |  
| `analytical_storm/modules/translation_agent.py`  |  `TranslationAgent`, `TranslatingRM`  |  
| `analytical_storm/modules/pipeline_logger.py`  | `PipelineLogger`  |  
| `rm.py`  |  `KBSIPaperRM`, `KBSISopRM` (커스텀)  |  
| `db_retriever/`  |  `milvus_backend`, `retrieve`, `postgre_engine`, `embedding(VLLMEmbeddings)`  |  
| `encoder.py`  |  `Encoder` (vllm 백엔드)  |  
| `query_expansion.py`  | `WikipediaQueryExpander`  |  
| `web_app/app.py`  | FastAPI 앱, `UserDocumentRM`, `SessionLogger`, `_run_analysis_pipeline`  |  
| 루트 스크립트  |  `embed_server.py`, `build_milvus_lite.py`, `run_batch_analysis.py`, `run_batch_queries.py`, `run_stress_and_iteration_test.py`, `compare_reports.py`  |  
###   ⟨85⟩ 11.2 재사용된 기반 프레임워크   
| 파일  | 주요 심볼  |  
| --- | --- |  
| `interface.py`  |  `Information`, `LMConfigs`, `Engine`, `Retriever`, `Agent`, `Article`  |  
| `lm.py`  |  `LitellmModel`, `VLLMClient` (+ 다수 제공자 래퍼)  |  
| `dataclass.py`  |  `KnowledgeBase`, `KnowledgeNode`, `ConversationTurn`  |  
| `collaborative_storm/engine.py`  |  `CollaborativeStormLMConfigs`, `RunnerArgument`, `DiscourseManager`, `CoStormRunner`  |  
| `storm_wiki/engine.py`  |  `STORMWikiRunner`, `STORMWikiLMConfigs` (직접 미사용)  |  
* * *
##   ⟨86⟩ 부록 A. 참고 논문·원본 
  * STORM 논문: arxiv 2402.14207⟨94⟩ (NAACL 2024)
  * Co-STORM 논문: arxiv 2408.15232⟨95⟩ (EMNLP 2024)
  * 원본 저장소: stanford-oval/storm⟨96⟩


Copy to bucket new 

Downloads last month
    75
Total file size: 235 MB
##  Papers for Min142857/KBSI_ResearchAIAgent
#### Into the Unknown Unknowns: Engaged Human Learning through Participation in Language Model Agent Conversations Paper • 2408.15232 • Published Aug 27, 2024 • 2 ⟨97⟩#### Assisting in Writing Wikipedia-like Articles From Scratch with Large Language Models Paper • 2402.14207 • Published Feb 22, 2024 • 10 ⟨98⟩
System theme
Company
TOS⟨99⟩ Privacy⟨100⟩ About⟨101⟩ Careers⟨102⟩ ⟨1⟩
Website
Models⟨2⟩ Datasets⟨3⟩ Spaces⟨4⟩ Pricing⟨8⟩ Docs⟨6⟩
