![Hugging Face's logo](https://huggingface.co/front/assets/huggingface_logo-noborder.svg) Hugging Face⟨1⟩
  *  Models ⟨2⟩
  *  Datasets ⟨3⟩
  *  Spaces ⟨4⟩
  *  Buckets new⟨5⟩
  *  Docs ⟨6⟩
  *  Enterprise ⟨7⟩
  * Pricing⟨8⟩
  *     * Website
      *  Tasks⟨9⟩
      *  HuggingChat⟨10⟩
      *  Collections⟨11⟩
      *  Languages⟨12⟩
      *  Organizations⟨13⟩
    * Community
      *  Blog⟨14⟩
      *  Posts⟨15⟩
      *  Daily Papers⟨16⟩
      *  Hardware⟨17⟩
      *  Learn⟨18⟩
      *  Discord⟨19⟩
      *  Forum⟨20⟩
      *  GitHub⟨21⟩
    * Solutions
      *  Team & Enterprise⟨7⟩
      *  Hugging Face PRO⟨22⟩
      *  Enterprise Support⟨23⟩
      *  Inference Providers⟨24⟩
      *  Inference Endpoints⟨25⟩
      *  Storage Buckets⟨5⟩
  * * * *
  * Log In⟨26⟩
  * Sign Up⟨27⟩


#   Datasets:⟨3⟩
* * *
 ![](https://huggingface.co/avatars/f25d32817b26fe968c65a60511d9ed60.svg) ⟨28⟩
Anonymousblind⟨28⟩
/
agent-failure-dynamics⟨29⟩
like 0
Tasks:  Text Classification ⟨30⟩ Time Series Forecasting ⟨31⟩
Modalities:  Document ⟨32⟩ Image ⟨33⟩ Text ⟨34⟩
Formats:  json ⟨35⟩
Languages:  English ⟨36⟩
Size:  1K - 10K ⟨37⟩
Tags:  ai-agents ⟨38⟩ swe-bench ⟨39⟩ trajectory-analysis ⟨40⟩ benchmark ⟨41⟩ failure-dynamics ⟨42⟩ coding-agents ⟨43⟩ + 3
Libraries:  Datasets ⟨44⟩ Dask ⟨45⟩ Polars ⟨46⟩ + 1
License:
cc-by-4.0
 Dataset card ⟨29⟩ Data Studio ⟨47⟩ Files Files and versions xet ⟨48⟩ Community 1 ⟨49⟩
Dataset Viewer
 Auto-converted to Parquet⟨50⟩ API Embed  Duplicate⟨51⟩ Data Studio
Subset (1)
default · 6.09k rows
default (6.09k rows)
Split (3)
train · 3.04k rows
train (3.04k rows) validation (1.01k rows) test (2.03k rows)
SQL
Console  
|  id stringlengths 11 11  |  scaffold stringclasses 3 values  |  n_edits int64 8 115  |  edit_outcomes listlengths 8 115  |  resolved bool 2 classes  |  
| --- | --- | --- | --- | --- |  
|  train_00000  |  xml  |  13  |  [ false, false, false, true, false, true, true, false, false, false, false, false, false ]  |  true  |  
|  train_00001  |  xml  |  17  |  [ false, true, false, false, true, false, false, false, false, true, false, false, false, false, false, false, false ]  |  true  |  
|  train_00002  |  tool  |  17  |  [ false, true, false, false, false, false, false, true, false, false, false, false, false, true, true, false, true ]  |  true  |  
|  train_00003  |  xml  |  14  |  [ true, false, false, false, false, false, false, false, false, false, false, false, false, false ]  |  false  |  
|  train_00004  |  xml  |  13  |  [ false, false, false, false, false, false, false, true, false, true, false, false, false ]  |  true  |  
|  train_00005  |  xml  |  29  |  [ false, false, true, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false ]  |  false  |  
|  train_00006  |  xml  |  8  |  [ true, true, false, false, false, false, true, false ]  |  true  |  
|  train_00007  |  xml  |  8  |  [ true, true, true, true, false, false, false, false ]  |  true  |  
|  train_00008  |  tool  |  44  |  [ false, false, false, false, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, ...  |  false  |  
|  train_00009  |  xml  |  20  |  [ true, false, false, true, false, false, false, false, false, false, false, false, false, true, false, false, false, false, false, false ]  |  false  |  
|  train_00010  |  tool  |  18  |  [ false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true ]  |  false  |  
|  train_00011  |  xml  |  35  |  [ true, false, false, false, false, true, true, true, false, false, false, false, false, false, false, false, false, true, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false ]  |  false  |  
|  train_00012  |  ticks  |  13  |  [ true, false, true, false, true, true, false, false, true, false, false, false, false ]  |  false  |  
|  train_00013  |  xml  |  19  |  [ true, false, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, false ]  |  true  |  
|  train_00014  |  xml  |  9  |  [ true, false, true, false, false, true, false, true, true ]  |  true  |  
|  train_00015  |  xml  |  28  |  [ false, true, false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false ]  |  false  |  
|  train_00016  |  tool  |  8  |  [ false, false, false, false, false, false, false, false ]  |  false  |  
|  train_00017  |  tool  |  11  |  [ true, true, false, true, false, false, false, true, true, false, false ]  |  true  |  
|  train_00018  |  ticks  |  9  |  [ false, false, true, true, false, false, false, false, false ]  |  false  |  
|  train_00019  |  xml  |  11  |  [ true, true, false, false, false, true, true, true, true, false, false ]  |  true  |  
|  train_00020  |  ticks  |  19  |  [ false, false, false, false, true, false, true, false, false, false, false, false, false, false, false, false, false, false, false ]  |  false  |  
|  train_00021  |  tool  |  29  |  [ true, false, true, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, true, true, false, false, false, true, true, false, true, false ]  |  false  |  
|  train_00022  |  ticks  |  10  |  [ true, true, true, true, false, true, false, true, false, false ]  |  false  |  
|  train_00023  |  ticks  |  13  |  [ true, false, false, false, false, true, false, false, true, false, false, false, false ]  |  true  |  
|  train_00024  |  ticks  |  16  |  [ true, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false ]  |  false  |  
|  train_00025  |  ticks  |  10  |  [ true, true, false, false, false, true, false, true, false, false ]  |  true  |  
|  train_00026  |  xml  |  13  |  [ true, true, true, false, false, false, false, false, false, false, true, false, false ]  |  false  |  
|  train_00027  |  xml  |  21  |  [ true, true, true, false, true, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false ]  |  true  |  
|  train_00028  |  ticks  |  54  |  [ false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false, fal...  |  false  |  
|  train_00029  |  xml  |  50  |  [ true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, fa...  |  false  |  
|  train_00030  |  ticks  |  50  |  [ false, true, true, true, true, false, false, true, false, false, false, true, false, true, false, false, false, true, true, true, true, true, true, false, true, false, true, true, true, false, true, false, true, true, true, false, false, true...  |  false  |  
|  train_00031  |  xml  |  8  |  [ false, false, false, false, false, false, false, false ]  |  true  |  
|  train_00032  |  tool  |  12  |  [ false, false, true, true, false, false, true, false, true, false, false, false ]  |  true  |  
|  train_00033  |  xml  |  12  |  [ true, false, false, false, false, false, false, false, false, false, false, false ]  |  true  |  
|  train_00034  |  ticks  |  11  |  [ false, false, false, false, false, false, false, false, false, false, false ]  |  false  |  
|  train_00035  |  tool  |  47  |  [ false, true, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, fals...  |  false  |  
|  train_00036  |  ticks  |  15  |  [ true, false, false, false, false, false, false, false, false, false, false, true, false, false, false ]  |  false  |  
|  train_00037  |  xml  |  8  |  [ true, false, false, false, false, false, false, false ]  |  true  |  
|  train_00038  |  ticks  |  23  |  [ false, true, false, false, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false ]  |  false  |  
|  train_00039  |  xml  |  15  |  [ false, false, true, false, true, true, false, false, true, false, true, true, true, true, false ]  |  true  |  
|  train_00040  |  tool  |  15  |  [ true, false, false, false, false, false, false, false, false, true, false, false, false, false, false ]  |  true  |  
|  train_00041  |  tool  |  10  |  [ true, false, false, false, false, false, false, false, false, false ]  |  false  |  
|  train_00042  |  ticks  |  51  |  [ false, false, false, false, true, false, false, false, true, false, true, true, false, false, false, false, false, false, true, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, ...  |  false  |  
|  train_00043  |  ticks  |  44  |  [ false, true, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, fal...  |  false  |  
|  train_00044  |  tool  |  10  |  [ false, false, false, false, false, false, false, false, false, false ]  |  true  |  
|  train_00045  |  xml  |  24  |  [ false, true, true, true, true, true, false, false, false, false, false, false, true, false, false, false, false, true, true, false, true, false, false, false ]  |  false  |  
|  train_00046  |  xml  |  22  |  [ true, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false ]  |  false  |  
|  train_00047  |  ticks  |  36  |  [ false, true, true, true, false, false, false, false, false, true, true, false, false, false, true, false, true, false, false, true, false, false, false, false, true, true, false, false, false, true, false, false, true, false, false, false ]  |  false  |  
|  train_00048  |  xml  |  27  |  [ true, true, true, false, true, false, true, true, true, true, true, false, true, true, false, true, true, true, false, false, false, true, false, false, false, false, false ]  |  false  |  
|  train_00049  |  ticks  |  23  |  [ true, true, false, false, false, true, true, false, false, true, true, true, false, true, false, true, false, false, true, true, false, true, false ]  |  false  |  
|  train_00050  |  ticks  |  15  |  [ true, false, false, false, false, false, false, false, false, false, false, false, false, false, false ]  |  false  |  
|  train_00051  |  ticks  |  11  |  [ false, false, false, false, false, false, false, false, false, false, false ]  |  false  |  
|  train_00052  |  tool  |  19  |  [ false, false, false, false, false, false, true, true, false, true, true, false, true, false, true, true, false, false, false ]  |  true  |  
|  train_00053  |  xml  |  14  |  [ true, true, false, true, true, true, false, true, true, false, false, false, true, false ]  |  false  |  
|  train_00054  |  ticks  |  14  |  [ false, false, false, false, false, false, false, false, false, false, false, false, false, false ]  |  true  |  
|  train_00055  |  xml  |  12  |  [ true, false, false, false, false, false, false, false, false, false, false, false ]  |  true  |  
|  train_00056  |  ticks  |  11  |  [ true, true, false, false, false, false, false, false, true, true, false ]  |  true  |  
|  train_00057  |  xml  |  15  |  [ true, false, false, false, false, true, false, false, false, false, true, false, false, true, false ]  |  false  |  
|  train_00058  |  tool  |  10  |  [ false, false, false, false, false, false, false, false, false, false ]  |  true  |  
|  train_00059  |  ticks  |  34  |  [ false, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false ]  |  false  |  
|  train_00060  |  ticks  |  40  |  [ true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, fa...  |  false  |  
|  train_00061  |  ticks  |  23  |  [ true, false, false, true, true, false, false, false, true, true, false, true, true, true, true, true, false, false, false, false, true, false, false ]  |  false  |  
|  train_00062  |  ticks  |  13  |  [ true, false, true, true, false, false, true, true, false, true, true, true, false ]  |  false  |  
|  train_00063  |  xml  |  24  |  [ false, true, true, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false ]  |  false  |  
|  train_00064  |  ticks  |  20  |  [ false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false ]  |  false  |  
|  train_00065  |  ticks  |  17  |  [ false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false ]  |  true  |  
|  train_00066  |  tool  |  29  |  [ true, false, false, false, true, true, true, true, false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false ]  |  true  |  
|  train_00067  |  tool  |  17  |  [ false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false ]  |  false  |  
|  train_00068  |  xml  |  25  |  [ false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false ]  |  false  |  
|  train_00069  |  xml  |  22  |  [ true, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false, true, true, true, false, false, false ]  |  true  |  
|  train_00070  |  xml  |  18  |  [ true, false, true, false, true, true, true, true, true, true, false, false, false, false, false, true, false, false ]  |  false  |  
|  train_00071  |  xml  |  14  |  [ true, true, true, true, true, false, false, false, false, true, false, false, false, false ]  |  true  |  
|  train_00072  |  tool  |  8  |  [ false, true, false, false, false, false, false, false ]  |  true  |  
|  train_00073  |  xml  |  34  |  [ true, false, true, false, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, true, false, false, false, false, false, false, false, false, false, false, false ]  |  false  |  
|  train_00074  |  tool  |  10  |  [ false, false, true, true, false, true, false, true, false, false ]  |  true  |  
|  train_00075  |  tool  |  22  |  [ true, false, false, false, false, false, false, false, false, false, false, false, true, false, true, false, true, false, true, true, false, false ]  |  false  |  
|  train_00076  |  xml  |  21  |  [ false, false, false, false, false, false, false, false, false, true, false, false, false, true, false, true, false, true, false, false, false ]  |  false  |  
|  train_00077  |  ticks  |  9  |  [ false, false, true, false, false, false, false, true, false ]  |  true  |  
|  train_00078  |  tool  |  12  |  [ true, true, false, false, false, false, false, false, false, false, true, false ]  |  true  |  
|  train_00079  |  tool  |  10  |  [ true, true, false, false, false, true, true, true, false, false ]  |  true  |  
|  train_00080  |  tool  |  15  |  [ true, false, false, true, true, true, true, false, false, false, true, false, true, false, true ]  |  true  |  
|  train_00081  |  ticks  |  8  |  [ false, false, false, false, false, false, false, false ]  |  false  |  
|  train_00082  |  tool  |  37  |  [ false, true, true, false, false, true, true, true, false, true, true, false, false, false, true, false, true, false, true, false, true, false, true, false, true, false, false, false, true, false, true, true, true, false, true, true, true ]  |  true  |  
|  train_00083  |  ticks  |  34  |  [ false, true, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false ]  |  false  |  
|  train_00084  |  tool  |  13  |  [ false, false, true, true, false, false, false, false, false, false, false, false, false ]  |  true  |  
|  train_00085  |  tool  |  25  |  [ true, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false ]  |  false  |  
|  train_00086  |  ticks  |  21  |  [ false, false, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false ]  |  false  |  
|  train_00087  |  ticks  |  16  |  [ true, true, false, false, false, false, true, false, false, false, false, false, false, false, false, false ]  |  true  |  
|  train_00088  |  xml  |  20  |  [ true, true, false, false, false, false, false, true, false, true, true, false, false, true, false, true, false, false, true, false ]  |  true  |  
|  train_00089  |  tool  |  33  |  [ true, false, true, true, false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false ]  |  false  |  
|  train_00090  |  ticks  |  27  |  [ false, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false ]  |  true  |  
|  train_00091  |  tool  |  13  |  [ true, true, false, true, false, false, false, false, false, false, false, false, false ]  |  true  |  
|  train_00092  |  ticks  |  19  |  [ true, false, false, false, false, true, false, false, true, false, false, false, false, true, false, false, false, false, false ]  |  false  |  
|  train_00093  |  ticks  |  16  |  [ false, false, true, false, false, false, false, true, false, false, false, false, false, false, false, false ]  |  false  |  
|  train_00094  |  ticks  |  13  |  [ true, false, false, false, false, false, false, false, false, false, false, false, false ]  |  true  |  
|  train_00095  |  ticks  |  25  |  [ true, false, true, false, false, false, false, false, false, true, false, true, false, true, false, false, false, false, false, false, false, false, false, false, false ]  |  false  |  
|  train_00096  |  ticks  |  21  |  [ false, false, false, false, false, false, false, true, true, false, false, false, false, false, true, false, false, false, false, false, true ]  |  false  |  
|  train_00097  |  xml  |  10  |  [ true, true, true, false, true, false, false, false, false, false ]  |  false  |  
|  train_00098  |  ticks  |  34  |  [ false, true, false, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, false, false, true, true, false, false ]  |  false  |  
|  train_00099  |  ticks  |  27  |  [ true, false, false, true, false, true, false, false, false, false, false, false, false, false, false, false, false, true, false, true, false, false, false, false, false, false, false ]  |  false  |  
End of preview. Expand in Data Studio⟨52⟩
* * *
  *  Previous⟨29⟩
  * 1⟨53⟩
  * 2⟨54⟩
  * 3⟨55⟩
  * ...⟨56⟩
  * 31⟨57⟩
  * Next ⟨54⟩


  * Why AgentHazard?⟨58⟩
  * How AgentHazard Compares⟨59⟩
  * Key Empirical Findings⟨60⟩
  * Motivation⟨61⟩
  * Composition⟨62⟩
    * What does the dataset contain?⟨63⟩
    * Data Schema⟨64⟩
    * Instance counts⟨65⟩
    * Label noise⟨66⟩
  * Benchmark Tasks⟨67⟩
    * Prediction⟨68⟩
    * Characterization⟨69⟩
    * Intervention⟨70⟩
  * Collection Process⟨71⟩
  * Intended Uses⟨72⟩
  * Limitations⟨73⟩
  * Ethical Considerations⟨74⟩
  * Related Datasets⟨75⟩
  * Variance Decomposition (134 agents x 12 repos)⟨76⟩
  * Reproducing Our Results⟨77⟩
  * Repository Structure⟨78⟩
  * Citation⟨79⟩
  * License⟨80⟩
  * Contact⟨81⟩


#   ⟨82⟩ AgentHazard: Process-Centric Benchmark for AI Agent Trajectory Analysis 
AgentHazard is the first benchmark designed specifically for **process-level analysis** of AI coding agent trajectories. Unlike existing benchmarks that evaluate only final outcomes (pass/fail), AgentHazard provides **standardized edit-level annotations** , **hazard estimation protocols** , and **stopping-policy evaluation tasks** with unified evaluation across 85,050 trajectories from 6+ agent families.
##   ⟨58⟩ Why AgentHazard? 
Existing trajectory datasets publish raw logs but provide no standardized way to study _how_ agents fail. AgentHazard fills this gap with:
  * **Edit-level process labels** : every trajectory is parsed into a binary edit-outcome sequence (error/clean after each file modification)
  * **Hazard estimation framework** : power-law decay fitting with shuffling controls and sensitivity analysis
  * **Stopping-policy evaluation** : the first benchmark task for designing and comparing agent stopping rules
  * **Off-policy vs on-policy validation** : we show that off-policy evaluations overestimate stopping gains by an order of magnitude (5.2% edit fraction)


##   ⟨59⟩ How AgentHazard Compares   
| Feature  | SWE-bench  | SWE-smith  | TrajEval  | SWE-PRM  | **AgentHazard**  |  
| --- | --- | --- | --- | --- | --- |  
| Raw trajectories  | No  | Yes  | Yes  | No  | **Yes**  |  
| Edit-level process labels  | No  | No  | Stage labels  | Step rewards  | **Binary edit outcomes**  |  
| Hidden test split  | Yes  | No  | No  | No  | **Yes**  |  
| Train/val/test splits  | N/A  | No  | No  | Train/test  | **60/20/20 stratified**  |  
| Stopping-policy task  | No  | No  | No  | No  | **Yes (with bootstrap CIs)**  |  
| Hazard estimation task  | No  | No  | No  | No  | **Yes (with protocol)**  |  
| Collapse prediction task  | No  | No  | No  | No  | **Yes (leakage-free)**  |  
| Edit detector task  | No  | No  | No  | No  | **Yes (ground-truth labels)**  |  
| Off-policy vs on-policy  | No  | No  | No  | No  | **Yes (harness-verified)**  |  
| Evaluation script  | Yes  | No  | No  | No  | **Yes**  |  
| Multiple agent families  | N/A  | 3 models  | 3 agents  | 1 agent  | **6+ families, 134 ecosystem**  |  
| Harness-verified labels  | Yes  | No  | No  | Partial  | **Yes (433 trajectories)**  |  
| Cross-domain  | No  | No  | No  | No  | **Yes (7 domains via AgentBoard)**  |  
##   ⟨60⟩ Key Empirical Findings   
| Finding  | Number  | Implication  |  
| --- | --- | --- |  
| Within-task hazard decay  | alpha=0.95, R2=0.97  | Agents exhibit genuine per-edit learning  |  
| Shuffling control (within length bins)  | delta-alpha=0.3-0.8, all p less than 0.01  | Not a statistical artifact  |  
| Edit fraction  |  **5.2%** (median, 432 tasks)  | 95% of agent steps are non-edit exploration  |  
| Off-policy stopping gain  | +17.1% (edit budget)  | Appears effective in simulation  |  
| On-policy stopping gain  |  **0%** (0/20 resolved, step budget)  | Does NOT transfer to practice  |  
| Prediction ceiling  | AUC=0.69 regardless of features  | Resolution is fundamentally hard to predict  |  
| Pre-trajectory features  | AUC=0.671 (13 features)  | Matches post-trajectory length (0.634)  |  
| Efficiency peak  | **75 steps**  | 85% of resolutions at 30% of compute  |  
| Variance: agent vs repo  | 50.3% agent, 38.5% repo  | Capability and difficulty are additive  |  
| Beta-Bernoulli theory  | Beta(0.50,0.50) recovers alpha=0.99  | Agents behave as Bayesian updaters  |  
* * *
#   ⟨83⟩ Dataset Card 
##   ⟨61⟩ Motivation 
**Why was AgentHazard created?** AI coding agents (SWE-agent, OpenHands, Agentless, etc.) are evaluated primarily on final resolution rates. But understanding _how_ agents fail -- the temporal dynamics of errors, the structure of fix attempts, the relationship between process and outcome -- requires edit-level trajectory analysis. No existing benchmark provides the standardized annotations, evaluation protocols, and benchmark tasks needed for this research direction.
**What gap does it fill?** Prior trajectory datasets (SWE-smith, TrajEval) provide raw logs but no process labels, no hidden test sets, and no evaluation scripts. Researchers studying agent reliability, process reward models, or stopping rules must implement their own parsing, splitting, and evaluation from scratch, leading to incomparable results. AgentHazard standardizes this pipeline.
**Who funded this work?** Self-funded. DeepSeek replication cost $21. On-policy experiments cost $3-15.
##   ⟨62⟩ Composition 
###   ⟨63⟩ What does the dataset contain? 
AgentHazard contains two types of data, clearly separated:
**A. Raw Trajectories** (for analysis and new research)  
| Source  | Count  | Content  | Labels  |  
| --- | --- | --- | --- |  
| SWE-smith tool scaffold  | 1,998  | Full message logs with function-call annotations  | Resolution (training labels)  |  
| SWE-smith XML scaffold  | 2,000  | Full message logs  | Resolution (training labels)  |  
| SWE-smith ticks scaffold  | 1,999  | Full message logs  | Resolution (training labels)  |  
| DeepSeek-V4-Flash  | 433  | Full message logs from mini-SWE-agent  | Resolution (harness-verified)  |  
| On-policy experiments  | 120+  | StoppingAgent runs with git-diff edit detection  | Resolution (harness-verified)  |  
**B. Benchmark Evaluation Data** (for standardized comparison)  
| Split  | Count  | Labels  | Purpose  |  
| --- | --- | --- | --- |  
| train.json  | ~3,600  | Included (resolution + edit outcomes)  | Model training  |  
| val.json  | ~1,200  | Included  | Hyperparameter tuning  |  
| test.json  | ~1,200  | **Hidden**  | Final evaluation  |  
| test_labels_hidden.json  | ~1,200  | Held out  | Released when benchmark is superseded  |  
**C. Ecosystem Context** (for positioning)  
| Source  | Content  |  
| --- | --- |  
| ecosystem_134_agents.json  | Resolution counts for 134 agent configurations from the official SWE-bench leaderboard  |  
###   ⟨64⟩ Data Schema 
Each trajectory in the benchmark splits contains:

```
{
  "id": "train_00001",           // unique identifier
  "scaffold": "tool",            // agent scaffold type
  "n_edits": 12,                 // number of detected file edits
  "edit_outcomes": [0,1,0,0,...], // binary: 1=error after edit, 0=clean
  "resolved": true               // task outcome (hidden in test split)
}

```

###   ⟨65⟩ Instance counts 
  * Total trajectories (all sources): 85,050
  * Benchmark split trajectories: ~6,000 (stratified 60/20/20)
  * Unique SWE-bench tasks covered: ~2,000
  * Agent families with edit-level data: 6+
  * Agent configurations in ecosystem: 134
  * Repositories: 12 (django, sympy, scikit-learn, etc.)


###   ⟨66⟩ Label noise 
The keyword-based edit detector has precision 0.986 but recall 0.546 -- approximately 45% of real edits are missed (primarily scripted patches via python3 /tmp/fix.py). We address this explicitly: Task 6 benchmarks edit detection as a first-class problem; all hazard analyses include sensitivity across recall levels (0.55-1.0); on-policy runs use git-diff detection (100% recall) for validation.
##   ⟨67⟩ Benchmark Tasks 
###   ⟨68⟩ Prediction 
**Task 1: Resolution Prediction** -- Predict whether a trajectory resolves the task.
  * Input: trajectory-level features extracted from edit_outcomes
  * Output: P(resolved) per trajectory
  * Metric: AUC-ROC
  * Baselines: LR=0.689, RF=0.690, GBM=0.688
  * Significance: the ceiling at ~0.69 demonstrates that resolution has irreducible stochasticity


**Task 2: Collapse Prediction** -- Predict whether a damaging error streak will occur.
  * Input: causal features at edit k (only edits 0..k visible, NO future information)
  * Output: P(streak >= 3 errors in next 5 edits)
  * Metric: AUC-ROC
  * Baselines: LR=0.796, RF=0.798, GBM=0.795
  * Constraint: using max_streak or any post-hoc feature is leakage (see PROTOCOL.md)
  * Significance: collapse IS predictable from causal features, enabling early warning systems


###   ⟨69⟩ Characterization 
**Task 3: Trajectory Length Prediction** -- Predict how long the agent will work from its early behavior.
  * Input: features from first 3 edits only
  * Output: predicted total trajectory length
  * Metric: MAE
  * Baselines: Mean=9.09, Linear=9.01, GBM=9.05
  * Significance: NO model beats the mean -- length is unpredictable from early edits


**Task 4: Hazard Exponent Estimation** -- Characterize an agent family's learning dynamics.
  * Input: set of N trajectories from one agent family
  * Output: estimated alpha, R2, and 95% bootstrap CI
  * Metric: |alpha_estimate - alpha_groundtruth|
  * Protocol: compute empirical hazard h(k), fit power law h(k)=c*(k+1)^(-alpha), bootstrap B>=1000
  * Baselines: N=500 gives |delta-alpha|=0.053; N=1000 gives 0.024
  * Significance: characterizes agent learning rate; enables cross-agent comparison


###   ⟨70⟩ Intervention 
**Task 5: Stopping Policy Evaluation** -- Design a rule to stop failing agents early.
  * Input: a causal stopping function f(edit_outcomes_so_far, k) -> stop/continue
  * Output: net gain = 100 * (rescued - harmed) / total
  * Metric: net gain % with bootstrap 95% CI
  * Baselines: k=5 (+20.5%), k=10 (+25.9%), k=15 (+23.2%)
  * Critical caveat: off-policy gains do NOT transfer on-policy (0/20 resolved at k=15 step budget)
  * Significance: the first standardized stopping-rule comparison with honest off/on-policy evaluation


**Task 6: Edit Detector Evaluation** -- Improve the infrastructure underlying all other tasks.
  * Input: agent command string
  * Output: boolean (file edit or not)
  * Metric: F1, Recall at Precision >= 0.95
  * Ground truth: SWE-smith tool scaffold function.name labels (13,203 labeled actions)
  * Baseline: keyword heuristic P=0.986, R=0.546, F1=0.703
  * Significance: detector quality directly affects Tasks 2, 4, and 5; improving recall from 0.55 to 1.0 shifts alpha from 0.95 to 0.70


##   ⟨71⟩ Collection Process 
**SWE-smith trajectories** : downloaded from the public SWE-smith release. Parsed using custom trajectory parser that extracts edit-level annotations from function-call metadata (tool scaffold) or command heuristics (XML/ticks scaffolds).
**DeepSeek-V4-Flash trajectories** : independently generated using mini-SWE-agent on SWE-bench Verified (500 tasks). Cost: $21 via DeepSeek API. 433 tasks completed within timeout. Evaluated with the official SWE-bench test harness: 299/407 resolved (73.5%).
**On-policy experiments** : generated using StoppingAgent (subclass of mini-SWE-agent DefaultAgent) with git-diff-based edit detection. Multiple experimental conditions: budget-limited (k=15, k=25 step budgets), same-task comparisons across 3 arms (baseline, fixed-k, hazard).
**Ecosystem data** : extracted from swe-bench/experiments GitHub repository, which contains official leaderboard results for 134 agent configurations evaluated on SWE-bench Verified.
**Processing pipeline** : Raw trajectories -> edit detection (keyword or git-diff) -> binary outcome labeling (error keywords in observations) -> feature extraction -> stratified splitting (seed=42).
##   ⟨72⟩ Intended Uses 
**Primary intended uses:**
  * Benchmarking trajectory analysis methods (prediction, characterization, intervention)
  * Studying agent failure dynamics and learning patterns
  * Evaluating process reward models against the prediction ceiling (AUC~0.69)
  * Designing and comparing stopping rules with standardized off-policy evaluation
  * Characterizing new agents via hazard exponent estimation


**Out-of-scope uses:**
  * Training production coding agents (these are analysis trajectories, not demonstrations)
  * Evaluating agent architectures on resolution rate (use SWE-bench directly)
  * Drawing conclusions about proprietary/closed-source agents not represented in the data


##   ⟨73⟩ Limitations 
  1. **Edit detection noise** : keyword detector has 54.6% recall. All analyses include sensitivity analysis across recall levels. Task 6 benchmarks this as an open problem.
  2. **Domain scope** : primary data covers Python open-source repositories. Cross-domain results (AgentBoard) use reconstructed trajectories. Generalization to other languages/domains requires caution.
  3. **On-policy scale** : on-policy experiments use n=10-20 per condition. The observed 73.5pp effect is significant (Fisher p=0.003, power >99%), but smaller effects between controllers would require n>=50 per arm.
  4. **Agent diversity** : edit-level data covers 6 agent families. The ecosystem context (134 agents) provides resolution labels only, not edit-level trajectories. Adding edit-level data for more agents is an ongoing effort.
  5. **Representativeness** : SWE-smith training trajectories may differ from production agent behavior. The DeepSeek replication with harness verification mitigates this for one agent family.
  6. **Benchmark staleness** : as agents improve, the benchmark tasks may become less discriminative. VERSION.json tracks the benchmark version; we plan periodic updates with new agent families.


##   ⟨74⟩ Ethical Considerations 
  * All source data is publicly available (SWE-smith, SWE-bench, AgentBoard)
  * No human subjects or personal data involved
  * No private code repositories; all tasks use open-source projects
  * DeepSeek API usage complied with their terms of service
  * Benchmark results should not be used to make employment or capability claims about specific AI systems
  * Data released under CC-BY-4.0 to enable open research


##   ⟨75⟩ Related Datasets   
| Dataset  | Focus  | Relationship to AgentHazard  |  
| --- | --- | --- |  
| SWE-bench (Jimenez et al., 2024)  | Task definitions + test harness  | We evaluate on SWE-bench Verified tasks  |  
| SWE-smith (Yang et al., 2025)  | Training trajectory generation  | Our primary data source (76,977 trajectories)  |  
| TrajEval (Tang et al., 2026)  | Stage-level trajectory decomposition  | We compare: our edit-level approach captures finer dynamics  |  
| SWE-PRM (Wang et al., 2025)  | Process reward modeling  | We show prediction ceiling (AUC~0.69) that bounds PRM gains  |  
| SWE-Shepherd (Zhang et al., 2026)  | Step-level reward labels  | Complementary: they label reward, we label process structure  |  
| AgentBoard (Ma et al., 2024)  | Multi-domain agent evaluation  | Our cross-domain validation source (7 domains, 15 models)  |  
##   ⟨76⟩ Variance Decomposition (134 agents x 12 repos)   
| Source  | Variance share  |  
| --- | --- |  
| Between-agent (capability)  | **50.3%**  |  
| Between-repo (difficulty)  | **38.5%**  |  
| Interaction  | 11.2%  |  
Rankings are moderately stable across repos (mean Spearman rho = 0.661).
##   ⟨77⟩ Reproducing Our Results 
**Colab (free, 30 min):** all analysis scripts in analysis/ run on free Google Colab with no GPU required.
**DeepSeek replication ($21, 8 hours):** requires Docker + DeepSeek API key. See REPRODUCIBILITY.md and the mini-swe-agent repository⟨84⟩.
**On-policy experiments ($3-15):** StoppingAgent with git-diff detector. See GitHub repository.
**Expected results:**  
| Finding  | Expected value  | Tolerance  |  
| --- | --- | --- |  
| alpha (keyword detector)  | 0.95  | +/- 0.05  |  
| alpha (shuffled)  | 0.30-0.45  | +/- 0.10  |  
| Edit fraction  | 5.2%  | +/- 1.0%  |  
| Resolution AUC (LR)  | 0.689  | +/- 0.02  |  
| Collapse AUC (LR)  | 0.796  | +/- 0.03  |  
| Peak efficiency budget  | 75 steps  | +/- 10  |  
| DeepSeek resolution  | 73.5%  | +/- 3% (run variance)  |  
##   ⟨78⟩ Repository Structure 

```
benchmark_package/
  train.json              3,600 trajectories with labels (60%)
  val.json                1,200 trajectories with labels (20%)
  test.json               1,200 trajectories without labels (20%)
  test_labels_hidden.json held-out for evaluation
  evaluate.py             standardized evaluation script
  submission_format.json  JSON format for each task
  PROTOCOL.md             benchmark rules and procedures
  SCHEMA.json             data field definitions
  REPRODUCIBILITY.md      step-by-step reproduction guide
  DATASHEET.md            data card (Gebru et al.)
  VERSION.json            version 1.0.0 with changelog
  example_submissions/    sample prediction files

figures/                  all paper figures (PDF + PNG)
analysis/                 all analysis scripts (Python)

data/
  all_scaffolds_parsed.json    76,977 parsed trajectories
  ecosystem_134_agents.json    leaderboard resolution data

```

##   ⟨79⟩ Citation 

```
@inproceedings{agenthazard2027,
  title={Within-Task Hazard Decay in AI Agent Trajectories:
         A Benchmark Study of 85,000 Coding Attempts},
  author={Anonymous},
  booktitle={Proceedings of the 33rd ACM SIGKDD Conference on Knowledge
             Discovery and Data Mining (Datasets and Benchmarks Track)},
  year={2027}
}

```

##   ⟨80⟩ License 
  * Benchmark code and evaluation scripts: MIT License
  * Parsed trajectory data and annotations: CC-BY-4.0
  * SWE-smith source data: used under its original license
  * SWE-bench task definitions: used under their original license


##   ⟨81⟩ Contact 
For questions, to report issues, or to contribute new agent families, please open an issue on GitHub⟨84⟩.
Copy to bucket new
Use this dataset 

Downloads last month
    3,195
Number of rows: 6,087 Total file size: 4.53 MB
System theme
Company
TOS⟨85⟩ Privacy⟨86⟩ About⟨87⟩ Careers⟨88⟩ ⟨1⟩
Website
Models⟨2⟩ Datasets⟨3⟩ Spaces⟨4⟩ Pricing⟨8⟩ Docs⟨6⟩
