![Hugging Face's logo](https://huggingface.co/front/assets/huggingface_logo-noborder.svg) Hugging Face⟨1⟩
  *  Models ⟨2⟩
  *  Datasets ⟨3⟩
  *  Spaces ⟨4⟩
  *  Buckets new⟨5⟩
  *  Docs ⟨6⟩
  *  Enterprise ⟨7⟩
  * Pricing⟨8⟩
  *     * Website
      *  Tasks⟨9⟩
      *  HuggingChat⟨10⟩
      *  Collections⟨11⟩
      *  Languages⟨12⟩
      *  Organizations⟨13⟩
    * Community
      *  Blog⟨14⟩
      *  Posts⟨15⟩
      *  Daily Papers⟨16⟩
      *  Hardware⟨17⟩
      *  Learn⟨18⟩
      *  Discord⟨19⟩
      *  Forum⟨20⟩
      *  GitHub⟨21⟩
    * Solutions
      *  Team & Enterprise⟨7⟩
      *  Hugging Face PRO⟨22⟩
      *  Enterprise Support⟨23⟩
      *  Inference Providers⟨24⟩
      *  Inference Endpoints⟨25⟩
      *  Storage Buckets⟨5⟩
  * * * *
  * Log In⟨26⟩
  * Sign Up⟨27⟩


#   Datasets:⟨3⟩
* * *
 ![](https://huggingface.co/avatars/a20318492906e6048d345a09a426564b.svg) ⟨28⟩
Jasonstephane⟨28⟩
/
Cube_bottom_V10⟨29⟩
like 0
Tasks:  Robotics ⟨30⟩
Modalities:  Tabular ⟨31⟩ Time-series ⟨32⟩ Video ⟨33⟩
Formats:  parquet ⟨34⟩
Size:  1K - 10K ⟨35⟩
Tags:  LeRobot ⟨36⟩
Libraries:  Datasets ⟨37⟩ pandas ⟨38⟩ Polars ⟨39⟩ + 2
License:
apache-2.0
 Dataset card ⟨29⟩ Data Studio ⟨40⟩ Files Files and versions xet ⟨41⟩ Community ⟨42⟩
Dataset Viewer
 Auto-converted to Parquet⟨43⟩ API Embed  Duplicate⟨44⟩ Data Studio
Subset (1)
default · 1.79k rows
default (1.79k rows)
Split (1)
train · 1.79k rows
train (1.79k rows)
Search is not available for this dataset
SQL
Console  
|  action list  |  observation.state list  |  timestamp float32 0 59.5  |  frame_index int64 0 1.79k  |  episode_index int64 0 0  |  index int64 0 1.79k  |  task_index int64 0 0  |  
| --- | --- | --- | --- | --- | --- | --- |  
|  [ -7.3278422355651855, -112.07868957519531, 101.06944274902344, 70.17008209228516, 17.71038055419922, 1.983713150024414 ]  |  [ -10.021978378295898, -105.84615325927734, 98.4175796508789, 72.61538696289062, 21.27472496032715, 16.167665481567383 ]  |  0  |  0  |  0  |  0  |  0  |  
|  [ -7.483966827392578, -112.060302734375, 101.654541015625, 70.02714538574219, 17.711702346801758, 1.975356101989746 ]  |  [ -10.021978378295898, -105.84615325927734, 98.4175796508789, 72.61538696289062, 21.27472496032715, 16.167665481567383 ]  |  0.033333  |  1  |  0  |  1  |  0  |  
|  [ -5.513879776000977, -111.29183959960938, 100.84626007080078, 68.2802505493164, 18.549283981323242, 2.440445899963379 ]  |  [ -9.670330047607422, -105.84615325927734, 98.32967376708984, 72.35164642333984, 20.74725341796875, 16.034597396850586 ]  |  0.066667  |  2  |  0  |  2  |  0  |  
|  [ -7.589481353759766, -112.06716918945312, 101.8082275390625, 69.83645629882812, 17.57146644592285, 1.992574691772461 ]  |  [ -8.879120826721191, -105.93406677246094, 97.80220031738281, 71.82417297363281, 19.78022003173828, 14.437790870666504 ]  |  0.1  |  3  |  0  |  3  |  0  |  
|  [ -7.034382343292236, -112.419677734375, 101.95556640625, 69.62300109863281, 18.013065338134766, 2.0721168518066406 ]  |  [ -7.736263751983643, -106.10989379882812, 97.62637329101562, 71.03296661376953, 19.428571701049805, 12.17564868927002 ]  |  0.133333  |  4  |  0  |  4  |  0  |  
|  [ -6.4492268562316895, -112.36106872558594, 101.50588989257812, 68.86319732666016, 17.987394332885742, 2.053201675415039 ]  |  [ -6.94505500793457, -106.54945373535156, 97.62637329101562, 70.4175796508789, 18.901098251342773, 9.580838203430176 ]  |  0.166667  |  5  |  0  |  5  |  0  |  
|  [ -6.827516555786133, -112.07539367675781, 101.74702453613281, 68.7525634765625, 17.903573989868164, 2.035923957824707 ]  |  [ -6.94505500793457, -106.63735961914062, 97.62637329101562, 70.4175796508789, 18.63736343383789, 7.185628890991211 ]  |  0.2  |  6  |  0  |  6  |  0  |  
|  [ -6.169809818267822, -111.30357360839844, 101.12635040283203, 68.30594635009766, 18.632741928100586, 2.0544204711914062 ]  |  [ -7.384615421295166, -106.63735961914062, 97.62637329101562, 70.4175796508789, 18.63736343383789, 5.522288799285889 ]  |  0.233333  |  7  |  0  |  7  |  0  |  
|  [ -6.843545913696289, -112.0921630859375, 101.93339538574219, 68.62012481689453, 18.25691795349121, 1.991434097290039 ]  |  [ -7.472527503967285, -106.63735961914062, 97.62637329101562, 70.15384674072266, 18.461538314819336, 4.3912177085876465 ]  |  0.266667  |  8  |  0  |  8  |  0  |  
|  [ -6.7859721183776855, -112.09884643554688, 102.10055541992188, 68.26342010498047, 18.297801971435547, 1.961655616760254 ]  |  [ -7.120879173278809, -106.63735961914062, 97.62637329101562, 69.80220031738281, 18.461538314819336, 3.725881576538086 ]  |  0.3  |  9  |  0  |  9  |  0  |  
|  [ -6.455420017242432, -111.56291198730469, 100.93207550048828, 67.86835479736328, 18.60485076904297, 2.0520591735839844 ]  |  [ -6.681318759918213, -106.63735961914062, 97.62637329101562, 69.62637329101562, 18.461538314819336, 3.3266799449920654 ]  |  0.333333  |  10  |  0  |  10  |  0  |  
|  [ -6.526952743530273, -111.25686645507812, 101.48460388183594, 67.61211395263672, 18.401756286621094, 1.8216609954833984 ]  |  [ -6.593406677246094, -106.63735961914062, 97.62637329101562, 69.45054626464844, 18.461538314819336, 2.994011878967285 ]  |  0.366667  |  11  |  0  |  11  |  0  |  
|  [ -6.515647888183594, -111.39045715332031, 102.06913757324219, 67.47086334228516, 18.29031753540039, 1.7787017822265625 ]  |  [ -6.769230842590332, -106.63735961914062, 97.62637329101562, 69.18681335449219, 18.461538314819336, 2.7944111824035645 ]  |  0.4  |  12  |  0  |  12  |  0  |  
|  [ -7.20471715927124, -111.076904296875, 101.65673065185547, 67.78949737548828, 18.42461395263672, 1.7341651916503906 ]  |  [ -6.94505500793457, -106.63735961914062, 97.62637329101562, 68.92308044433594, 18.461538314819336, 2.5948104858398438 ]  |  0.433333  |  13  |  0  |  13  |  0  |  
|  [ -6.96915340423584, -111.19297790527344, 101.93110656738281, 67.47925567626953, 18.36208152770996, 1.6995353698730469 ]  |  [ -7.0329670906066895, -106.63735961914062, 97.62637329101562, 68.74725341796875, 18.461538314819336, 2.461743116378784 ]  |  0.466667  |  14  |  0  |  14  |  0  |  
|  [ -6.952777862548828, -110.77359008789062, 101.35310363769531, 66.90054321289062, 18.75728988647461, 1.6766700744628906 ]  |  [ -7.0329670906066895, -106.63735961914062, 97.62637329101562, 68.74725341796875, 18.461538314819336, 2.461743116378784 ]  |  0.5  |  15  |  0  |  15  |  0  |  
|  [ -6.701565265655518, -110.67620849609375, 101.18451690673828, 66.73328399658203, 18.325414657592773, 1.6182403564453125 ]  |  [ -6.94505500793457, -106.63735961914062, 97.62637329101562, 68.74725341796875, 18.461538314819336, 2.395209550857544 ]  |  0.533333  |  16  |  0  |  16  |  0  |  
|  [ -7.171063423156738, -110.56745910644531, 101.83218383789062, 66.9200210571289, 18.420310974121094, 1.5244140625 ]  |  [ -6.94505500793457, -106.63735961914062, 97.62637329101562, 68.57142639160156, 18.461538314819336, 2.3286759853363037 ]  |  0.566667  |  17  |  0  |  17  |  0  |  
|  [ -7.029623985290527, -110.60015869140625, 100.92166137695312, 66.74568176269531, 18.42721939086914, 1.6597671508789062 ]  |  [ -6.94505500793457, -106.63735961914062, 97.62637329101562, 68.21977996826172, 18.461538314819336, 2.3286759853363037 ]  |  0.6  |  18  |  0  |  18  |  0  |  
|  [ -6.555717945098877, -110.37017822265625, 100.82456970214844, 66.4056396484375, 18.768882751464844, 1.8034601211547852 ]  |  [ -7.0329670906066895, -106.63735961914062, 97.62637329101562, 68.21977996826172, 18.461538314819336, 2.3286759853363037 ]  |  0.633333  |  19  |  0  |  19  |  0  |  
|  [ -6.499638080596924, -110.54606628417969, 100.80619812011719, 65.96631622314453, 18.862619400024414, 1.7095022201538086 ]  |  [ -7.0329670906066895, -106.63735961914062, 97.62637329101562, 67.95604705810547, 18.461538314819336, 2.3286759853363037 ]  |  0.666667  |  20  |  0  |  20  |  0  |  
|  [ -6.552002906799316, -109.86189270019531, 100.21731567382812, 65.77603149414062, 19.064834594726562, 2.096663475036621 ]  |  [ -7.0329670906066895, -106.63735961914062, 97.62637329101562, 67.69230651855469, 18.461538314819336, 2.3286759853363037 ]  |  0.7  |  21  |  0  |  21  |  0  |  
|  [ -6.392377853393555, -109.99378967285156, 100.4451904296875, 65.47434997558594, 19.23599624633789, 1.9176559448242188 ]  |  [ -7.0329670906066895, -106.63735961914062, 97.62637329101562, 67.42857360839844, 18.461538314819336, 2.3286759853363037 ]  |  0.733333  |  22  |  0  |  22  |  0  |  
|  [ -6.15871000289917, -109.64425659179688, 99.18119049072266, 65.49826049804688, 19.255229949951172, 2.1039953231811523 ]  |  [ -7.0329670906066895, -106.63735961914062, 97.62637329101562, 67.16483306884766, 18.461538314819336, 2.3286759853363037 ]  |  0.766667  |  23  |  0  |  23  |  0  |  
|  [ -6.206427097320557, -109.25534057617188, 99.42030334472656, 64.8974380493164, 19.285831451416016, 2.1098155975341797 ]  |  [ -7.0329670906066895, -106.63735961914062, 97.62637329101562, 66.9011001586914, 18.461538314819336, 2.3286759853363037 ]  |  0.8  |  24  |  0  |  24  |  0  |  
|  [ -6.144339561462402, -109.06283569335938, 99.21798706054688, 64.75670623779297, 19.53706932067871, 2.5426130294799805 ]  |  [ -7.0329670906066895, -106.63735961914062, 97.62637329101562, 66.72527313232422, 18.461538314819336, 2.3286759853363037 ]  |  0.833333  |  25  |  0  |  25  |  0  |  
|  [ -5.093990325927734, -108.87373352050781, 97.33113098144531, 63.77515411376953, 20.181560516357422, 3.343873977661133 ]  |  [ -7.0329670906066895, -106.63735961914062, 97.62637329101562, 66.46154022216797, 18.461538314819336, 2.3286759853363037 ]  |  0.866667  |  26  |  0  |  26  |  0  |  
|  [ -5.922581195831299, -109.03701782226562, 98.03471374511719, 64.4791030883789, 20.26104736328125, 3.286160469055176 ]  |  [ -7.0329670906066895, -106.63735961914062, 97.62637329101562, 66.10989379882812, 18.549449920654297, 2.3286759853363037 ]  |  0.9  |  27  |  0  |  27  |  0  |  
|  [ -5.8194732666015625, -108.47074890136719, 97.49964904785156, 64.1141586303711, 20.59373664855957, 3.677122116088867 ]  |  [ -6.505494594573975, -106.63735961914062, 97.62637329101562, 65.67032623291016, 18.989011764526367, 2.461743116378784 ]  |  0.933333  |  28  |  0  |  28  |  0  |  
|  [ -4.736229419708252, -107.95378112792969, 95.11929321289062, 62.93467712402344, 21.42585563659668, 5.204121112823486 ]  |  [ -5.97802209854126, -106.63735961914062, 97.62637329101562, 65.4945068359375, 19.340660095214844, 2.7944111824035645 ]  |  0.966667  |  29  |  0  |  29  |  0  |  
|  [ -4.650183200836182, -108.07232666015625, 95.10907745361328, 63.03544998168945, 21.575746536254883, 5.58502721786499 ]  |  [ -5.890110015869141, -106.63735961914062, 97.62637329101562, 65.31867980957031, 19.69230842590332, 2.927478313446045 ]  |  1  |  30  |  0  |  30  |  0  |  
|  [ -5.196049213409424, -106.88424682617188, 94.31851196289062, 62.63557052612305, 21.87600326538086, 6.222033500671387 ]  |  [ -5.97802209854126, -106.63735961914062, 97.62637329101562, 64.79120635986328, 20.131868362426758, 3.260146379470825 ]  |  1.033333  |  31  |  0  |  31  |  0  |  
|  [ -4.968012809753418, -104.67463684082031, 91.71383666992188, 62.23551940917969, 22.720645904541016, 7.376514911651611 ]  |  [ -5.714285850524902, -106.63735961914062, 97.62637329101562, 64.43955993652344, 20.571428298950195, 3.992016077041626 ]  |  1.066667  |  32  |  0  |  32  |  0  |  
|  [ -4.831460952758789, -104.46209716796875, 89.83665466308594, 61.6072883605957, 23.531530380249023, 8.23586654663086 ]  |  [ -5.1868133544921875, -106.63735961914062, 97.62637329101562, 64.0879135131836, 20.923076629638672, 4.657351970672607 ]  |  1.1  |  33  |  0  |  33  |  0  |  
|  [ -5.261252403259277, -103.67805480957031, 90.46875762939453, 62.089717864990234, 23.39822006225586, 8.400140762329102 ]  |  [ -5.1868133544921875, -106.37362670898438, 97.36264038085938, 63.736263275146484, 21.36263656616211, 5.389221668243408 ]  |  1.133333  |  34  |  0  |  34  |  0  |  
|  [ -5.380621433258057, -101.00763702392578, 87.22457885742188, 61.620967864990234, 24.46265983581543, 10.178755760192871 ]  |  [ -5.274725437164307, -105.4945068359375, 96.48351287841797, 63.38461685180664, 21.9780216217041, 6.187624931335449 ]  |  1.166667  |  35  |  0  |  35  |  0  |  
|  [ -5.742754936218262, -97.44497680664062, 82.7083740234375, 60.65586853027344, 25.41286277770996, 12.052027702331543 ]  |  [ -5.538461685180664, -105.14286041259766, 95.69230651855469, 63.20878982543945, 22.329669952392578, 6.852960586547852 ]  |  1.2  |  36  |  0  |  36  |  0  |  
|  [ -6.637770175933838, -92.75637817382812, 79.81332397460938, 60.7017936706543, 25.941753387451172, 13.21185302734375 ]  |  [ -5.538461685180664, -104.61538696289062, 94.989013671875, 62.94505310058594, 22.94505500793457, 7.651363849639893 ]  |  1.233333  |  37  |  0  |  37  |  0  |  
|  [ -7.2733988761901855, -89.08402252197266, 76.46694946289062, 60.19052505493164, 26.61367416381836, 14.723064422607422 ]  |  [ -5.626373767852783, -102.85713958740234, 93.75823974609375, 62.593406677246094, 23.648351669311523, 8.848968505859375 ]  |  1.266667  |  38  |  0  |  38  |  0  |  
|  [ -7.738255023956299, -86.66571044921875, 73.12278747558594, 60.25979232788086, 27.377710342407227, 16.082664489746094 ]  |  [ -5.538461685180664, -100.13186645507812, 91.47252655029297, 62.241756439208984, 24.351648330688477, 10.113106727600098 ]  |  1.3  |  39  |  0  |  39  |  0  |  
|  [ -8.108715057373047, -82.65748596191406, 71.18329620361328, 60.3161735534668, 27.58391571044922, 16.777915954589844 ]  |  [ -5.8021979331970215, -97.5824203491211, 88.65933990478516, 61.978023529052734, 24.96703338623047, 11.443778991699219 ]  |  1.333333  |  40  |  0  |  40  |  0  |  
|  [ -9.803363800048828, -74.91069030761719, 65.8366928100586, 60.37176513671875, 28.506103515625, 18.49354362487793 ]  |  [ -6.505494594573975, -94.68132019042969, 85.5824203491211, 61.80219650268555, 25.58241844177246, 12.77445125579834 ]  |  1.366667  |  41  |  0  |  41  |  0  |  
|  [ -10.903226852416992, -69.76900482177734, 62.02155303955078, 60.55253601074219, 28.885377883911133, 19.465641021728516 ]  |  [ -7.472527503967285, -91.34066009521484, 82.4175796508789, 61.71428680419922, 26.10988998413086, 14.038589477539062 ]  |  1.4  |  42  |  0  |  42  |  0  |  
|  [ -10.927197456359863, -69.60379028320312, 61.37120056152344, 60.05010223388672, 29.484006881713867, 19.447769165039062 ]  |  [ -8.087912559509277, -87.82417297363281, 79.34066009521484, 61.626373291015625, 26.72527503967285, 15.169660568237305 ]  |  1.433333  |  43  |  0  |  43  |  0  |  
|  [ -11.807517051696777, -65.21468353271484, 58.94668960571289, 60.285926818847656, 29.875202178955078, 20.769519805908203 ]  |  [ -8.615385055541992, -83.78022003173828, 76, 61.53845977783203, 27.428571701049805, 16.433799743652344 ]  |  1.466667  |  44  |  0  |  44  |  0  |  
|  [ -13.346957206726074, -57.28165054321289, 53.072235107421875, 61.087711334228516, 30.470476150512695, 22.40230369567871 ]  |  [ -9.230769157409668, -79.38461303710938, 72.65933990478516, 61.36263656616211, 27.956043243408203, 17.36526870727539 ]  |  1.5  |  45  |  0  |  45  |  0  |  
|  [ -14.75046157836914, -50.12080001831055, 47.936031341552734, 61.35639572143555, 31.076522827148438, 23.22541618347168 ]  |  [ -10.021978378295898, -75.6043930053711, 69.84615325927734, 61.36263656616211, 28.483516693115234, 18.230205535888672 ]  |  1.533333  |  46  |  0  |  46  |  0  |  
|  [ -16.106523513793945, -42.5751953125, 43.809871673583984, 61.423858642578125, 31.467620849609375, 24.72332763671875 ]  |  [ -10.98901081085205, -71.73626708984375, 67.03296661376953, 61.36263656616211, 29.010988235473633, 19.427810668945312 ]  |  1.566667  |  47  |  0  |  47  |  0  |  
|  [ -15.728509902954102, -43.28761291503906, 43.997093200683594, 61.30557632446289, 31.60565948486328, 24.490341186523438 ]  |  [ -12.219779968261719, -66.9011001586914, 63.60439682006836, 61.53845977783203, 29.538461685180664, 20.558881759643555 ]  |  1.6  |  48  |  0  |  48  |  0  |  
|  [ -16.570737838745117, -38.42582321166992, 41.25651931762695, 61.46037673950195, 32.086578369140625, 25.323318481445312 ]  |  [ -13.450549125671387, -61.36263656616211, 59.82417678833008, 61.53845977783203, 30.065933227539062, 21.62342071533203 ]  |  1.633333  |  49  |  0  |  49  |  0  |  
|  [ -17.300146102905273, -35.509395599365234, 38.621795654296875, 61.79465103149414, 32.79497528076172, 25.830238342285156 ]  |  [ -14.681318283081055, -55.736263275146484, 56.131866455078125, 61.53845977783203, 30.505495071411133, 22.488357543945312 ]  |  1.666667  |  50  |  0  |  50  |  0  |  
|  [ -18.73678207397461, -28.41740608215332, 34.227760314941406, 62.47742462158203, 32.789520263671875, 26.679046630859375 ]  |  [ -15.384614944458008, -50.72527313232422, 52.879119873046875, 61.53845977783203, 30.85714340209961, 23.220226287841797 ]  |  1.7  |  51  |  0  |  51  |  0  |  
|  [ -20.213483810424805, -21.846460342407227, 30.180551528930664, 62.87604522705078, 33.4619140625, 27.126901626586914 ]  |  [ -15.912087440490723, -45.978023529052734, 50.06593322753906, 61.53845977783203, 31.384614944458008, 24.01862907409668 ]  |  1.733333  |  52  |  0  |  52  |  0  |  
|  [ -20.548858642578125, -17.317291259765625, 27.64307975769043, 62.59071350097656, 34.132991790771484, 27.523115158081055 ]  |  [ -16.263736724853516, -41.58241653442383, 47.07692337036133, 61.626373291015625, 31.736263275146484, 24.750499725341797 ]  |  1.766667  |  53  |  0  |  53  |  0  |  
|  [ -19.502460479736328, -23.543243408203125, 31.604740142822266, 62.235450744628906, 33.520606994628906, 27.23975372314453 ]  |  [ -17.494504928588867, -36.74725341796875, 43.82417678833008, 61.978023529052734, 32.17582321166992, 25.415834426879883 ]  |  1.8  |  54  |  0  |  54  |  0  |  
|  [ -20.98879623413086, -15.819459915161133, 27.522136688232422, 62.747230529785156, 34.316078186035156, 27.77452850341797 ]  |  [ -18.373626708984375, -31.648351669311523, 40.57143020629883, 62.06593322753906, 32.70329666137695, 25.948102951049805 ]  |  1.833333  |  55  |  0  |  55  |  0  |  
|  [ -21.104040145874023, -11.704307556152344, 25.071346282958984, 63.0781135559082, 34.67336654663086, 27.264453887939453 ]  |  [ -19.340660095214844, -26.989011764526367, 37.758243560791016, 61.978023529052734, 32.879119873046875, 26.280771255493164 ]  |  1.866667  |  56  |  0  |  56  |  0  |  
|  [ -21.69915771484375, -7.997592926025391, 22.82410430908203, 63.24246597290039, 34.892372131347656, 28.087047576904297 ]  |  [ -19.516483306884766, -22.94505500793457, 36, 61.978023529052734, 33.14285659790039, 26.613439559936523 ]  |  1.9  |  57  |  0  |  57  |  0  |  
|  [ -22.436487197875977, -4.609504699707031, 21.50136375427246, 63.6490478515625, 35.50907897949219, 28.818708419799805 ]  |  [ -19.78022003173828, -19.340660095214844, 34.41758346557617, 62.5054931640625, 33.58241653442383, 26.74650764465332 ]  |  1.933333  |  58  |  0  |  58  |  0  |  
|  [ -22.728986740112305, -3.5907821655273438, 21.203214645385742, 63.59349822998047, 35.53810501098633, 28.308528900146484 ]  |  [ -20.131868362426758, -15.560439109802246, 32.483516693115234, 62.68132019042969, 33.846153259277344, 26.946107864379883 ]  |  1.966667  |  59  |  0  |  59  |  0  |  
|  [ -23.59946632385254, 0.11040496826171875, 18.98993492126465, 64.38835906982422, 36.2791748046875, 29.155014038085938 ]  |  [ -20.74725341796875, -12.04395580291748, 30.373626708984375, 63.03296661376953, 34.28571319580078, 27.478376388549805 ]  |  2  |  60  |  0  |  60  |  0  |  
|  [ -22.959217071533203, -2.1663131713867188, 19.57090950012207, 63.675453186035156, 36.31037902832031, 29.661502838134766 ]  |  [ -21.450550079345703, -8.703296661376953, 28.791208267211914, 63.120880126953125, 34.46154022216797, 27.677976608276367 ]  |  2.033333  |  61  |  0  |  61  |  0  |  
|  [ -23.193815231323242, 2.998950958251953, 17.96767234802246, 63.80647659301758, 37.393802642822266, 30.1402587890625 ]  |  [ -22.241758346557617, -5.714285850524902, 27.384614944458008, 63.47252655029297, 34.989009857177734, 27.877578735351562 ]  |  2.066667  |  62  |  0  |  62  |  0  |  
|  [ -23.773067474365234, 2.9490890502929688, 18.27303695678711, 64.21924591064453, 36.99859619140625, 29.565088272094727 ]  |  [ -22.85714340209961, -3.076923131942749, 26.065933227539062, 63.56044006347656, 35.516483306884766, 28.409847259521484 ]  |  2.1  |  63  |  0  |  63  |  0  |  
|  [ -23.7216739654541, 5.589141845703125, 16.985443115234375, 63.913360595703125, 37.31300735473633, 30.219282150268555 ]  |  [ -22.94505500793457, -0.7032967209815979, 24.923076629638672, 63.56044006347656, 35.9560432434082, 28.875581741333008 ]  |  2.133333  |  64  |  0  |  64  |  0  |  
|  [ -23.689298629760742, 5.413387298583984, 17.496471405029297, 64.07789611816406, 37.77304458618164, 30.462190628051758 ]  |  [ -22.94505500793457, 1.3186813592910767, 23.956043243408203, 63.56044006347656, 36.21977996826172, 29.14171600341797 ]  |  2.166667  |  65  |  0  |  65  |  0  |  
|  [ -23.78833770751953, 7.894187927246094, 16.638967514038086, 63.51354217529297, 38.18978500366211, 30.42352294921875 ]  |  [ -22.85714340209961, 2.7252748012542725, 23.428571701049805, 63.56044006347656, 36.30769348144531, 29.208250045776367 ]  |  2.2  |  66  |  0  |  66  |  0  |  
|  [ -23.76963233947754, 9.060184478759766, 15.819169998168945, 64.06365203857422, 38.546607971191406, 30.76542091369629 ]  |  [ -22.85714340209961, 4.219780445098877, 22.813186645507812, 63.56044006347656, 36.659339904785156, 29.474384307861328 ]  |  2.233333  |  67  |  0  |  67  |  0  |  
|  [ -23.802026748657227, 8.596614837646484, 16.13112449645996, 64.07398223876953, 38.56645584106445, 30.450422286987305 ]  |  [ -23.03296661376953, 5.8021979331970215, 22.0219783782959, 63.56044006347656, 36.83516311645508, 29.74051856994629 ]  |  2.266667  |  68  |  0  |  68  |  0  |  
|  [ -23.595264434814453, 10.38311767578125, 15.352836608886719, 63.896018981933594, 39.352149963378906, 31.088863372802734 ]  |  [ -23.47252655029297, 7.736263751983643, 21.230770111083984, 63.56044006347656, 37.53845977783203, 30.00665283203125 ]  |  2.3  |  69  |  0  |  69  |  0  |  
|  [ -23.492883682250977, 11.952999114990234, 15.174806594848633, 63.776920318603516, 39.96781921386719, 31.330326080322266 ]  |  [ -23.824174880981445, 8.79120922088623, 20.96703338623047, 63.56044006347656, 37.89011001586914, 30.00665283203125 ]  |  2.333333  |  70  |  0  |  70  |  0  |  
|  [ -23.631799697875977, 12.6868896484375, 14.805522918701172, 63.85016632080078, 39.87638854980469, 30.93313217163086 ]  |  [ -23.824174880981445, 9.582417488098145, 20.703296661376953, 63.56044006347656, 38.32966995239258, 30.206254959106445 ]  |  2.366667  |  71  |  0  |  71  |  0  |  
|  [ -23.839920043945312, 13.015636444091797, 14.627107620239258, 63.968666076660156, 40.35048294067383, 32.10015869140625 ]  |  [ -23.824174880981445, 10.813186645507812, 20.08791160583496, 63.56044006347656, 38.5054931640625, 30.472389221191406 ]  |  2.4  |  72  |  0  |  72  |  0  |  
|  [ -23.494937896728516, 13.180912017822266, 14.441463470458984, 63.707000732421875, 40.31974792480469, 31.518766403198242 ]  |  [ -23.736263275146484, 12.307692527770996, 19.384614944458008, 63.56044006347656, 38.68132019042969, 30.538921356201172 ]  |  2.433333  |  73  |  0  |  73  |  0  |  
|  [ -23.309852600097656, 14.264209747314453, 14.41470718383789, 63.855010986328125, 40.97049331665039, 31.724180221557617 ]  |  [ -23.736263275146484, 13.274724960327148, 19.208791732788086, 63.56044006347656, 39.20878982543945, 30.87158966064453 ]  |  2.466667  |  74  |  0  |  74  |  0  |  
|  [ -22.780954360961914, 15.330074310302734, 13.767389297485352, 63.59935760498047, 41.323280334472656, 32.04608917236328 ]  |  [ -23.648351669311523, 13.714285850524902, 19.120878219604492, 63.56044006347656, 39.82417678833008, 31.071191787719727 ]  |  2.5  |  75  |  0  |  75  |  0  |  
|  [ -22.982019424438477, 14.445854187011719, 14.082231521606445, 63.36531066894531, 41.69217300415039, 32.57130432128906 ]  |  [ -23.560440063476562, 14.15384578704834, 19.03296661376953, 63.56044006347656, 39.736263275146484, 31.137723922729492 ]  |  2.533333  |  76  |  0  |  76  |  0  |  
|  [ -23.260866165161133, 15.60843276977539, 13.811071395874023, 63.768592834472656, 41.402706146240234, 32.30723190307617 ]  |  [ -23.648351669311523, 15.120879173278809, 18.505495071411133, 63.56044006347656, 40.35165023803711, 31.337326049804688 ]  |  2.566667  |  77  |  0  |  77  |  0  |  
|  [ -23.02717399597168, 15.82509994506836, 13.738765716552734, 63.578548431396484, 41.87036895751953, 31.94818687438965 ]  |  [ -23.736263275146484, 15.648351669311523, 18.41758155822754, 63.56044006347656, 40.52747344970703, 31.60346031188965 ]  |  2.6  |  78  |  0  |  78  |  0  |  
|  [ -22.782278060913086, 16.87955093383789, 12.736515045166016, 63.5378303527832, 42.18948745727539, 31.72342300415039 ]  |  [ -23.736263275146484, 15.912087440490723, 18.241758346557617, 63.56044006347656, 40.96703338623047, 31.736526489257812 ]  |  2.633333  |  79  |  0  |  79  |  0  |  
|  [ -22.420940399169922, 16.500385284423828, 13.6494140625, 63.31955337524414, 42.486900329589844, 32.263771057128906 ]  |  [ -23.648351669311523, 16.439559936523438, 17.9780216217041, 63.56044006347656, 40.61538314819336, 31.736526489257812 ]  |  2.666667  |  80  |  0  |  80  |  0  |  
|  [ -22.37036895751953, 17.368610382080078, 12.866889953613281, 63.2377815246582, 42.553810119628906, 31.99169921875 ]  |  [ -23.736263275146484, 17.230770111083984, 17.538461685180664, 63.56044006347656, 41.230770111083984, 31.736526489257812 ]  |  2.7  |  81  |  0  |  81  |  0  |  
|  [ -22.06131362915039, 16.573135375976562, 12.687126159667969, 63.052276611328125, 43.093746185302734, 32.13390350341797 ]  |  [ -23.648351669311523, 17.670330047607422, 17.36263656616211, 63.56044006347656, 41.758243560791016, 31.736526489257812 ]  |  2.733333  |  82  |  0  |  82  |  0  |  
|  [ -22.385456085205078, 17.74917984008789, 12.322639465332031, 63.289180755615234, 42.830780029296875, 31.52545166015625 ]  |  [ -23.296703338623047, 17.846153259277344, 17.36263656616211, 63.56044006347656, 41.846153259277344, 31.736526489257812 ]  |  2.766667  |  83  |  0  |  83  |  0  |  
|  [ -21.898948669433594, 17.802074432373047, 12.497598648071289, 63.07012939453125, 43.051292419433594, 31.314191818237305 ]  |  [ -23.03296661376953, 17.934066772460938, 17.186813354492188, 63.56044006347656, 41.93406677246094, 31.736526489257812 ]  |  2.8  |  84  |  0  |  84  |  0  |  
|  [ -22.177154541015625, 18.463970184326172, 12.02808952331543, 63.15828323364258, 43.03634262084961, 30.879919052124023 ]  |  [ -22.769229888916016, 18.10988998413086, 17.010988235473633, 63.56044006347656, 42.10988998413086, 31.736526489257812 ]  |  2.833333  |  85  |  0  |  85  |  0  |  
|  [ -21.78738784790039, 17.844398498535156, 12.970048904418945, 63.178443908691406, 43.081565856933594, 31.753210067749023 ]  |  [ -22.41758155822754, 18.461538314819336, 16.83516502380371, 63.56044006347656, 42.28571319580078, 31.736526489257812 ]  |  2.866667  |  86  |  0  |  86  |  0  |  
|  [ -21.961402893066406, 18.614517211914062, 11.639020919799805, 62.880191802978516, 43.199310302734375, 29.97894287109375 ]  |  [ -22.329669952392578, 18.989011764526367, 16.395605087280273, 63.56044006347656, 42.373626708984375, 31.669992446899414 ]  |  2.9  |  87  |  0  |  87  |  0  |  
|  [ -21.657323837280273, 17.85409927368164, 12.24429702758789, 62.858619689941406, 43.27726364135742, 30.547487258911133 ]  |  [ -22.329669952392578, 19.25274658203125, 16.395605087280273, 63.56044006347656, 42.46154022216797, 31.60346031188965 ]  |  2.933333  |  88  |  0  |  88  |  0  |  
|  [ -21.635107040405273, 18.40591812133789, 11.937997817993164, 62.91606140136719, 43.510955810546875, 30.824491500854492 ]  |  [ -22.329669952392578, 19.25274658203125, 16.30769157409668, 63.56044006347656, 42.989009857177734, 31.53692626953125 ]  |  2.966667  |  89  |  0  |  89  |  0  |  
|  [ -21.876277923583984, 18.718517303466797, 11.269281387329102, 62.68397521972656, 43.5070686340332, 29.33953285217285 ]  |  [ -22.329669952392578, 19.25274658203125, 16.131868362426758, 63.56044006347656, 42.81318664550781, 31.071191787719727 ]  |  3  |  90  |  0  |  90  |  0  |  
|  [ -21.641109466552734, 19.48666000366211, 11.76222038269043, 62.81147766113281, 43.45753479003906, 29.022966384887695 ]  |  [ -22.505495071411133, 19.428571701049805, 16.043956756591797, 63.56044006347656, 42.72527313232422, 31.004657745361328 ]  |  3.033333  |  91  |  0  |  91  |  0  |  
|  [ -21.527097702026367, 19.367733001708984, 11.404321670532227, 62.77633285522461, 43.59197235107422, 29.014522552490234 ]  |  [ -22.593406677246094, 19.604394912719727, 15.868131637573242, 63.56044006347656, 43.07692337036133, 31.004657745361328 ]  |  3.066667  |  92  |  0  |  92  |  0  |  
|  [ -21.202878952026367, 19.549728393554688, 11.318082809448242, 62.44987869262695, 43.79768753051758, 27.39031410217285 ]  |  [ -22.593406677246094, 19.868131637573242, 15.780220031738281, 63.56044006347656, 43.07692337036133, 30.405855178833008 ]  |  3.1  |  93  |  0  |  93  |  0  |  
|  [ -21.271738052368164, 19.904521942138672, 11.269638061523438, 62.94227981567383, 43.7359619140625, 27.15762710571289 ]  |  [ -22.593406677246094, 20.21977996826172, 15.780220031738281, 63.56044006347656, 43.07692337036133, 29.940120697021484 ]  |  3.133333  |  94  |  0  |  94  |  0  |  
|  [ -20.980621337890625, 19.71249008178711, 10.761499404907227, 62.37788772583008, 43.68357467651367, 26.91143226623535 ]  |  [ -22.41758155822754, 20.483516693115234, 15.780220031738281, 63.56044006347656, 43.16483688354492, 29.40785026550293 ]  |  3.166667  |  95  |  0  |  95  |  0  |  
|  [ -20.988325119018555, 20.33755874633789, 10.993402481079102, 62.54322814941406, 43.704830169677734, 25.39938735961914 ]  |  [ -22.065933227539062, 20.74725341796875, 15.604395866394043, 63.56044006347656, 43.16483688354492, 28.675981521606445 ]  |  3.2  |  96  |  0  |  96  |  0  |  
|  [ -21.11195945739746, 19.88526153564453, 10.632173538208008, 62.87762451171875, 43.834861755371094, 25.308300018310547 ]  |  [ -21.80219841003418, 20.923076629638672, 15.252747535705566, 63.38461685180664, 43.16483688354492, 28.143712997436523 ]  |  3.233333  |  97  |  0  |  97  |  0  |  
|  [ -20.991567611694336, 20.036128997802734, 10.74587631225586, 62.7082633972168, 43.964420318603516, 26.32863998413086 ]  |  [ -21.538461685180664, 21.186813354492188, 15.252747535705566, 63.20878982543945, 43.16483688354492, 27.478376388549805 ]  |  3.266667  |  98  |  0  |  98  |  0  |  
|  [ -20.626062393188477, 19.930465698242188, 10.68458366394043, 62.496829986572266, 43.57940673828125, 23.500892639160156 ]  |  [ -21.450550079345703, 21.27472496032715, 15.076923370361328, 63.20878982543945, 43.07692337036133, 26.813039779663086 ]  |  3.3  |  99  |  0  |  99  |  0  |  
End of preview. Expand in Data Studio⟨45⟩
* * *
  *  Previous⟨29⟩
  * 1⟨46⟩
  * 2⟨47⟩
  * 3⟨48⟩
  * ...⟨49⟩
  * 18⟨50⟩
  * Next ⟨47⟩


  * Dataset Structure⟨51⟩
  * Citation⟨52⟩


This dataset was created using LeRobot⟨53⟩.
 ![](https://huggingface.co/datasets/huggingface/badges/resolve/main/visualize-this-dataset-xl.svg) ![](https://huggingface.co/datasets/huggingface/badges/resolve/main/visualize-this-dataset-xl-dark.svg) ⟨54⟩
##   ⟨51⟩ Dataset Structure 
meta/info.json⟨55⟩:

```
{
    "codebase_version": "v3.0",
    "fps": 30,
    "features": {
        "action": {
            "dtype": "float32",
            "names": [
                "shoulder_pan.pos",
                "shoulder_lift.pos",
                "elbow_flex.pos",
                "wrist_flex.pos",
                "wrist_roll.pos",
                "gripper.pos"
            ],
            "shape": [
                6
            ]
        },
        "observation.state": {
            "dtype": "float32",
            "names": [
                "shoulder_pan.pos",
                "shoulder_lift.pos",
                "elbow_flex.pos",
                "wrist_flex.pos",
                "wrist_roll.pos",
                "gripper.pos"
            ],
            "shape": [
                6
            ]
        },
        "observation.images.tuy": {
            "dtype": "video",
            "shape": [
                480,
                640,
                3
            ],
            "names": [
                "height",
                "width",
                "channels"
            ],
            "info": {
                "video.height": 480,
                "video.width": 640,
                "video.codec": "av1",
                "video.pix_fmt": "yuv420p",
                "video.is_depth_map": false,
                "video.fps": 30,
                "video.channels": 3,
                "has_audio": false
            }
        },
        "timestamp": {
            "dtype": "float32",
            "shape": [
                1
            ],
            "names": null
        },
        "frame_index": {
            "dtype": "int64",
            "shape": [
                1
            ],
            "names": null
        },
        "episode_index": {
            "dtype": "int64",
            "shape": [
                1
            ],
            "names": null
        },
        "index": {
            "dtype": "int64",
            "shape": [
                1
            ],
            "names": null
        },
        "task_index": {
            "dtype": "int64",
            "shape": [
                1
            ],
            "names": null
        }
    },
    "total_episodes": 1,
    "total_frames": 1787,
    "total_tasks": 1,
    "chunks_size": 1000,
    "data_files_size_in_mb": 100,
    "video_files_size_in_mb": 200,
    "data_path": "data/chunk-{chunk_index:03d}/file-{file_index:03d}.parquet",
    "video_path": "videos/{video_key}/chunk-{chunk_index:03d}/file-{file_index:03d}.mp4",
    "robot_type": "so_follower",
    "splits": {
        "train": "0:1"
    }
}

```

##   ⟨52⟩ Citation 
**BibTeX:**

```
[More Information Needed]

```

Copy to bucket new
Use this dataset 

Downloads last month
    73
License: apache-2.0 Number of rows: 1,787 Total file size: 23.8 MB
##  Collection including Jasonstephane/Cube_bottom_V10
#### Cube Bottom Collection 10 items • Updated 19 days ago ⟨56⟩
System theme
Company
TOS⟨57⟩ Privacy⟨58⟩ About⟨59⟩ Careers⟨60⟩ ⟨1⟩
Website
Models⟨2⟩ Datasets⟨3⟩ Spaces⟨4⟩ Pricing⟨8⟩ Docs⟨6⟩
