![Hugging Face's logo](https://huggingface.co/front/assets/huggingface_logo-noborder.svg) Hugging Face⟨1⟩
  *  Models ⟨2⟩
  *  Datasets ⟨3⟩
  *  Spaces ⟨4⟩
  *  Buckets new⟨5⟩
  *  Docs ⟨6⟩
  *  Enterprise ⟨7⟩
  * Pricing⟨8⟩
  *     * Website
      *  Tasks⟨9⟩
      *  HuggingChat⟨10⟩
      *  Collections⟨11⟩
      *  Languages⟨12⟩
      *  Organizations⟨13⟩
    * Community
      *  Blog⟨14⟩
      *  Posts⟨15⟩
      *  Daily Papers⟨16⟩
      *  Hardware⟨17⟩
      *  Learn⟨18⟩
      *  Discord⟨19⟩
      *  Forum⟨20⟩
      *  GitHub⟨21⟩
    * Solutions
      *  Team & Enterprise⟨7⟩
      *  Hugging Face PRO⟨22⟩
      *  Enterprise Support⟨23⟩
      *  Inference Providers⟨24⟩
      *  Inference Endpoints⟨25⟩
      *  Storage Buckets⟨5⟩
  * * * *
  * Log In⟨26⟩
  * Sign Up⟨27⟩


#   Datasets:⟨3⟩
* * *
 ![](https://huggingface.co/avatars/218868fcd037fde161221f88a2ce071a.svg) ⟨28⟩
Bigenlight⟨28⟩
/
banana_in_pot_lerobot_v3⟨29⟩
like 0
Tasks:  Robotics ⟨30⟩
Modalities:  Video ⟨31⟩
Size:  < 1K ⟨32⟩
Tags:  lerobot ⟨33⟩ LeRobot ⟨34⟩ imitation-learning ⟨35⟩ ur7e ⟨36⟩ manipulation ⟨37⟩ act ⟨38⟩
Libraries:  Datasets ⟨39⟩
Croissant
 lerobot ⟨40⟩
License:
apache-2.0
 Dataset card ⟨29⟩ Data Studio ⟨41⟩ Files Files and versions xet ⟨42⟩ Community ⟨43⟩
Dataset Viewer
 Auto-converted to Parquet⟨44⟩ API Embed  Duplicate⟨45⟩ Data Studio
Subset (1)
default · 4 rows
default (4 rows)
Split (1)
train · 4 rows
train (4 rows)
Search is not available for this dataset
SQL
Console  
|  video video 74.9 643  |  
| --- |  
|   |  
|   |  
|   |  
|   |  
  * Setup⟨46⟩
  * Task⟨47⟩
  * Schema⟨48⟩
  * Hardware & Collection⟨49⟩
    * Source stream rates (native, before resampling)⟨50⟩
    * Known quirks (data characteristics, not conversion bugs)⟨51⟩
  * Usage⟨52⟩
  * Related repositories (this family)⟨53⟩
  * Limitations & intended use⟨54⟩
  * Citation⟨55⟩


#   ⟨56⟩ banana_in_pot — UR7e teleop, "put the right banana in the pot" (LeRobot v3.0) 
Joint-space imitation-learning dataset: **51 human teleoperation demos** of a UR7e arm picking a target banana out of a cluttered scene and dropping it into a pot, with two 720p camera views. Ready to train ACT (or any LeRobot policy) out of the box.
  * **51 episodes · 21,524 frames · 30 fps · ~11.96 min · ~483 MB**
  * Format: **LeRobot v3.0** (`lerobot` 0.6.1)
  * Action / state space: **7-D absolute joint** (6 UR joints + gripper)
  * Every demo is a **success**.


##   ⟨46⟩ Setup 
Collected on a **Universal Robots UR7e** — a 6-DOF collaborative arm (joint values in **radians**) — driven by a **GELLO** low-cost 3D-printed **leader arm** for kinesthetic teleoperation. The operator moves the GELLO leader; its joint positions are mapped to UR7e joint commands. Two Intel RealSense cameras record the scene as **RGB video only** :
  * **Camera 1 — Intel RealSense D435**
  * **Camera 2 — Intel RealSense D435if** (a D435 variant)


Both stream **1280×720 (720p) @ 30 fps** , color format `yuv420p`. One camera is on a **tripod** (scene / third-person view), the other views the workspace. **No depth or IR streams were recorded** — despite the RealSense depth capability, only the RGB color stream was saved (no point cloud, no depth map in this release). The two physical viewpoints must be preserved at deploy time — **cam1 ↔ cam2 order matters**. An ArUco/AprilTag fiducial is present on the table.
![setup](https://huggingface.co/datasets/Bigenlight/banana_in_pot_lerobot_v3/resolve/main/assets/setup_01.jpg)⟨57⟩ ![setup](https://huggingface.co/datasets/Bigenlight/banana_in_pot_lerobot_v3/resolve/main/assets/setup_02.jpg)⟨58⟩
##   ⟨47⟩ Task 
**"put the right banana in the pot."** The tabletop holds several distractor objects — **two bananas, an apple, carrots/peppers, and a slice of watermelon** — plus a **silver pot**. The operator must grasp the **RIGHT banana** (the target; the left banana and all other produce are distractors) and place it inside the pot.
  * **Success criterion:** the right banana ends up inside the silver pot.
  * **Distractors:** left banana, apple, carrots/peppers, watermelon slice.


##   ⟨48⟩ Schema   
| feature  | dtype  | shape  | meaning  |  
| --- | --- | --- | --- |  
| `observation.state`  | float32  | (7,)  | UR7e measured joints `ur_q1..ur_q6` (rad) + `grip_pos` (gripper opening)  |  
| `action`  | float32  | (7,)  | commanded absolute joint targets `cmd1..cmd6` (rad) + `grip_cmd`  |  
| `observation.images.cam1`  | video (AV1)  | (720, 1280, 3)  | viewpoint 1 (RGB, HWC uint8)  |  
| `observation.images.cam2`  | video (AV1)  | (720, 1280, 3)  | viewpoint 2 (RGB, HWC uint8)  |  
Plus the standard LeRobot bookkeeping columns (`timestamp`, `frame_index`, `episode_index`, `index`, `task_index`). `action` is an **absolute** joint-target command (not a delta); the gripper command `grip_cmd` is effectively binary (open/close).
> Note: the LeRobot metadata records `robot_type: "ur5e_gello"` — a legacy label kept for reproducibility. The physical robot is a **UR7e**.
##   ⟨49⟩ Hardware & Collection 
  * **Robot:** Universal Robots **UR7e** , 6-DOF, joints in radians. Inference uses the UR7e follower only.
  * **Teleoperation:** **GELLO** leader arm (kinesthetic). The `gello_*` leader streams are **intentionally excluded** from this LeRobot dataset — the robot cannot observe the leader at inference time.
  * **Cameras:** Intel RealSense **D435** (cam1) + **D435if** (cam2), **RGB only** , 1280×720 @ 30 fps, `yuv420p`; raw `cam1.mp4`/`cam2.mp4` were MPEG-4, **re-encoded to AV1 (crf 30)** here. No depth/IR.


###   ⟨50⟩ Source stream rates (native, before resampling)   
| stream  | native rate  | in this dataset  |  
| --- | --- | --- |  
| cameras (cam1, cam2)  | 30 Hz  | kept as the master 30 fps clock  |  
|  `command` (UR joint targets)  | ~56 Hz  | → `action[0:6]`, resampled to 30 fps  |  
| `ur_joint_states`  | ~56 Hz  | → `observation.state[0:6]`, resampled to 30 fps  |  
| `tcp_pose`  | ~56 Hz  | _(not in this dataset — see EE variant)_  |  
|  `wrench` (6-axis F/T)  | ~56 Hz  | _(not in this dataset — see EE variant)_  |  
| `gripper`  | ~37 Hz  | → `grip_pos` / `grip_cmd`, resampled to 30 fps  |  
| `gello_joint_states`  | ~30 Hz  | excluded (leader-only)  |  
All included robot streams are **resampled onto the 30 fps camera grid** by nearest-timestamp lookup on the cam1 frame timeline. cam2 is aligned to cam1 by nearest camera timestamp (handles the ±1–2 frame count mismatch seen in some takes).
  * **Scale:** 51 episodes / 21,524 frames / ~~718 s (~~ 12 min) @ 30 fps.
  * **Episode set:** raw take numbers 1–36 with gaps `{9, 23, 30, 35}` _by design_ ; re-takes fill the count back to 51 folders. All 51 episodes are successful demonstrations.


###   ⟨51⟩ Known quirks (data characteristics, not conversion bugs) 
  * **1 take** originally had `NaN` in `grip_cmd` (333 frames) — **repaired** by forward/back-fill during conversion.
  * **~7 takes** contain raw robot-stream dropouts (75–280 ms gaps), giving a cam↔robot nearest-match error up to ~40 ms (≈2 control periods) at those frames. Mostly harmless for ACT.
  * `grip_pos` peaks at 0.898 (~6.3% of frames > 0.6) = fully-open gripper — physical, not an artifact.


QA: the conversion was independently validated (schema/v3.0 compliance, 4-way frame-count reconciliation, per-frame alignment re-derived to 1e-7, 0 NaN/Inf in stored arrays, video integrity corr 0.9995 vs raw, and a real `lerobot-train` smoke test).
##   ⟨52⟩ Usage 
Load with the LeRobot API:

```
from lerobot.datasets.lerobot_dataset import LeRobotDataset

ds = LeRobotDataset("Bigenlight/banana_in_pot_lerobot_v3")
print(ds.meta.total_episodes, ds.meta.total_frames)   # 51, 21524

sample = ds[0]
sample["observation.state"]          # (7,) float32
sample["action"]                     # (7,) float32
sample["observation.images.cam1"]    # (3, 720, 1280) float32 CHW

```

Train ACT (RTX 3060 12 GB reference; 720p resized on-the-fly to 360×640):

```
lerobot-train \
  --dataset.repo_id=Bigenlight/banana_in_pot_lerobot_v3 \
  --policy.type=act --policy.device=cuda \
  --batch_size=8 --steps=50000 \
  --output_dir=outputs/act_banana

```

A pretrained ACT checkpoint for this dataset is published at **Bigenlight/act_banana_in_pot**⟨59⟩ (chunk_size 100, ResNet18 + VAE). Reported open-loop held-out L1 ≈ **0.0235 rad (~1.34°)** , gripper accuracy **99.2%** , with no train/held-out gap (no overfitting).
##   ⟨53⟩ Related repositories (this family)   
| repo  | contents  |  
| --- | --- |  
| **Bigenlight/banana_in_pot_lerobot_v3**⟨29⟩  |  **this** — main LeRobot joint-space dataset  |  
| Bigenlight/banana_in_pot_ee_lerobot_v3⟨60⟩  | EE variant: adds `observation.tcp_pose` (7) + `observation.wrench` (6)  |  
| Bigenlight/banana_in_pot_raw⟨61⟩  | raw HDF5 + MP4 (all original signals, incl. GELLO leader)  |  
| Bigenlight/act_banana_in_pot⟨59⟩  | trained ACT policy  |  
The EE variant additionally supports **HIL-SERL** -style end-effector-delta training (base-frame TCP displacement + gripper).
##   ⟨54⟩ Limitations & intended use 
  * **Single task, single scene layout, single operator** — expect limited generalization across novel object arrangements or lighting.
  * **All demonstrations are successes** — no failure/recovery data; not suited as-is for methods that need negative examples.
  * Offline metrics are strong, but **closed-loop performance on a real UR7e is not guaranteed** and should be validated on hardware.
  * Intended for research in imitation learning and robot manipulation (ACT and related LeRobot policies).


##   ⟨55⟩ Citation 

```
@misc{theo2026bananainpot,
  title        = {banana_in_pot: UR7e teleoperation demonstrations for
                  "put the right banana in the pot"},
  author       = {Theo and {Bigenlight}},
  year         = {2026},
  howpublished = {\url{https://huggingface.co/datasets/Bigenlight/banana_in_pot_lerobot_v3}},
  note         = {LeRobot v3.0 dataset, 51 episodes}
}

```

License: **Apache-2.0**.
Copy to bucket new
Use this dataset 

Downloads last month
    110
Number of rows: 4 Total file size: 506 MB
##  Models trained or fine-tuned on Bigenlight/banana_in_pot_lerobot_v3
 ![](https://huggingface.co/avatars/218868fcd037fde161221f88a2ce071a.svg) Bigenlight/act_banana_in_pot Robotics • 51.7M • Updated 17 days ago • 26 ⟨59⟩
 ![](https://huggingface.co/avatars/218868fcd037fde161221f88a2ce071a.svg) Bigenlight/diffusion_banana_in_pot_joint Robotics • 0.3B • Updated 16 days ago • 23 ⟨62⟩
 ![](https://huggingface.co/avatars/218868fcd037fde161221f88a2ce071a.svg) Bigenlight/flow_matching_banana_in_pot_joint Robotics • 0.2B • Updated 9 days ago • 20 ⟨63⟩
 ![](https://huggingface.co/avatars/218868fcd037fde161221f88a2ce071a.svg) Bigenlight/diffusion_banana_in_pot_ee Robotics • 0.3B • Updated 15 days ago • 17 ⟨64⟩
 ![](https://huggingface.co/avatars/218868fcd037fde161221f88a2ce071a.svg) Bigenlight/banana_in_pot_hilserl Robotics • Updated 17 days ago ⟨65⟩
System theme
Company
TOS⟨66⟩ Privacy⟨67⟩ About⟨68⟩ Careers⟨69⟩ ⟨1⟩
Website
Models⟨2⟩ Datasets⟨3⟩ Spaces⟨4⟩ Pricing⟨8⟩ Docs⟨6⟩
