![Hugging Face's logo](https://huggingface.co/front/assets/huggingface_logo-noborder.svg) Hugging Face⟨1⟩
  *  Models ⟨2⟩
  *  Datasets ⟨3⟩
  *  Spaces ⟨4⟩
  *  Buckets new⟨5⟩
  *  Docs ⟨6⟩
  *  Enterprise ⟨7⟩
  * Pricing⟨8⟩
  *     * Website
      *  Tasks⟨9⟩
      *  HuggingChat⟨10⟩
      *  Collections⟨11⟩
      *  Languages⟨12⟩
      *  Organizations⟨13⟩
    * Community
      *  Blog⟨14⟩
      *  Posts⟨15⟩
      *  Daily Papers⟨16⟩
      *  Hardware⟨17⟩
      *  Learn⟨18⟩
      *  Discord⟨19⟩
      *  Forum⟨20⟩
      *  GitHub⟨21⟩
    * Solutions
      *  Team & Enterprise⟨7⟩
      *  Hugging Face PRO⟨22⟩
      *  Enterprise Support⟨23⟩
      *  Inference Providers⟨24⟩
      *  Inference Endpoints⟨25⟩
      *  Storage Buckets⟨5⟩
  * * * *
  * Log In⟨26⟩
  * Sign Up⟨27⟩


#   Datasets:⟨3⟩
* * *
Duplicated from markov-ai/gaming-500-hours⟨28⟩
![⟨29⟩]
 ![](https://huggingface.co/avatars/4ce5515d165e4a2873d3dbf0fbf5a16f.svg) ⟨30⟩
Naya2004⟨30⟩
/
gaming-500-hours⟨31⟩
like 0
Modalities:  Tabular ⟨32⟩ Text ⟨33⟩ Video ⟨34⟩
Formats:  json ⟨35⟩
Size:  < 1K ⟨36⟩
Libraries:  Datasets ⟨37⟩ pandas ⟨38⟩ Polars ⟨39⟩ + 1
 Dataset card ⟨31⟩ Data Studio ⟨40⟩ Files Files and versions xet ⟨41⟩ Community 1 ⟨42⟩
Dataset Viewer
 Auto-converted to Parquet⟨43⟩ API Embed  Duplicate⟨44⟩ Data Studio
Subset (1)
default · 776 rows
default (776 rows)
Split (1)
train · 776 rows
train (776 rows)
SQL
Console  
|  workflow_id stringlengths 36 36  |  game stringlengths 3 29  |  category stringclasses 1 value  |  platform stringclasses 2 values  |  title stringlengths 21 84  |  description stringlengths 136 411  |  tags listlengths 5 10  |  duration_min float64 3.17 458  |  duration_ms int64 190k 27.5M  |  event_count int64 10 1.76M  |  clip stringlengths 49 75  |  events stringlengths 52 78  |  frame_events stringlengths 58 84  |  metadata stringlengths 54 80  |  
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |  
|  770970bc-9bf1-4275-90f7-74081578ae46  |  Age of Empires  |  gaming  |  windows  |  Age of Empires II: Definitive Edition — Extended Multiplayer Sessions  |  User plays multiple ranked multiplayer matches of Age of Empires II: Definitive Edition over an extended session, performing sustained RTS gameplay including base building, resource management, unit control, and combat across Dark Age through Imperial Age progression. Includes matchmaking queues, lobby waits, and brief...  |  [ "age-of-empires", "rts", "multiplayer", "ranked", "strategy", "risk:game_simulator", "conf:0.72" ]  |  457.74  |  27,464,400  |  1,534,183  |  age-of-empires/770970bc-9bf1-4275-90f7-74081578ae46/clip.mp4  |  age-of-empires/770970bc-9bf1-4275-90f7-74081578ae46/events.json  |  age-of-empires/770970bc-9bf1-4275-90f7-74081578ae46/frame_events.json  |  age-of-empires/770970bc-9bf1-4275-90f7-74081578ae46/metadata.json  |  
|  bf36f8b7-8843-4e13-b13e-5a26ad367a1e  |  Valorant  |  gaming  |  windows  |  VALORANT Competitive Gameplay Sessions  |  Extended VALORANT competitive and casual gameplay across multiple matches, including buy phases, combat rounds, agent selection, post-match reviews, and rank progression. The user plays primarily as Chamber across maps including Pearl, Haven, Breeze, Lotus, Ascent, and Split.  |  [ "valorant", "fps", "competitive", "chamber", "platinum", "risk:game_simulator", "conf:0.82" ]  |  343.47  |  20,608,300  |  905,940  |  valorant/bf36f8b7-8843-4e13-b13e-5a26ad367a1e/clip.mp4  |  valorant/bf36f8b7-8843-4e13-b13e-5a26ad367a1e/events.json  |  valorant/bf36f8b7-8843-4e13-b13e-5a26ad367a1e/frame_events.json  |  valorant/bf36f8b7-8843-4e13-b13e-5a26ad367a1e/metadata.json  |  
|  996a51da-7fe7-4830-8982-0b9a850bd281  |  Hitman 3  |  gaming  |  windows  |  Hitman 3 — Dartmoor and Berlin missions gameplay  |  User plays Hitman 3 across the Dartmoor 'Death in the Family' and Berlin 'Apex Predator' missions, with extended idle/paused segments, occasional ChatGPT lookups for in-game codes and hints, and sustained stealth gameplay including eliminations, exploration, and mission completion.  |  [ "hitman3", "stealth", "gaming", "dartmoor", "berlin", "apex-predator", "risk:game_simulator", "risk:passive_low_active", "conf:0.72" ]  |  335.5  |  20,130,067  |  6,111  |  hitman-3/996a51da-7fe7-4830-8982-0b9a850bd281/clip.mp4  |  hitman-3/996a51da-7fe7-4830-8982-0b9a850bd281/events.json  |  hitman-3/996a51da-7fe7-4830-8982-0b9a850bd281/frame_events.json  |  hitman-3/996a51da-7fe7-4830-8982-0b9a850bd281/metadata.json  |  
|  69eac841-958e-4367-882c-02dbee56cccb  |  Age of Empires  |  gaming  |  windows  |  Age of Empires II DE — Custom AI Lobby Matches  |  User sets up and plays custom 4v4 AI (Extreme difficulty) matches in Age of Empires II: Definitive Edition, configuring lobbies, selecting civilizations (Cumans, Khmer, Italians, Portuguese), and engaging in extended gameplay with base building, military management, and combat against AI opponents.  |  [ "aoe2", "rts", "custom-lobby", "ai-match", "strategy", "risk:game_simulator", "conf:0.81" ]  |  281.44  |  16,886,233  |  985,267  |  age-of-empires/69eac841-958e-4367-882c-02dbee56cccb/clip.mp4  |  age-of-empires/69eac841-958e-4367-882c-02dbee56cccb/events.json  |  age-of-empires/69eac841-958e-4367-882c-02dbee56cccb/frame_events.json  |  age-of-empires/69eac841-958e-4367-882c-02dbee56cccb/metadata.json  |  
|  703edcce-1038-4fd7-9a43-3a10adc31f50  |  Road 96  |  gaming  |  windows  |  Road 96 Narrative Adventure Playthrough  |  Extended playthrough of the narrative adventure game Road 96, spanning multiple episodes with exploration, dialogue choices, puzzle-solving, and cutscene viewing. Includes frequent lookups of walkthroughs and safe codes via Chrome and ChatGPT.  |  [ "road-96", "narrative-game", "adventure", "walkthrough", "risk:game_simulator", "risk:passive_low_active", "conf:0.88" ]  |  252.11  |  15,126,400  |  245,093  |  road-96/703edcce-1038-4fd7-9a43-3a10adc31f50/clip.mp4  |  road-96/703edcce-1038-4fd7-9a43-3a10adc31f50/events.json  |  road-96/703edcce-1038-4fd7-9a43-3a10adc31f50/frame_events.json  |  road-96/703edcce-1038-4fd7-9a43-3a10adc31f50/metadata.json  |  
|  f1cdb36f-524b-4020-b427-29852dbe6276  |  Valorant  |  gaming  |  windows  |  VALORANT Competitive Gaming Session  |  Extended VALORANT competitive multiplayer session spanning multiple matches, including launcher navigation, agent selection, active gameplay rounds with combat and ability usage, and post-match review screens. All activity is recreational gaming with no productive output.  |  [ "valorant", "fps", "competitive", "riot-games", "chamber", "iso", "risk:game_simulator", "conf:0.92" ]  |  249.92  |  14,995,267  |  677,646  |  valorant/f1cdb36f-524b-4020-b427-29852dbe6276/clip.mp4  |  valorant/f1cdb36f-524b-4020-b427-29852dbe6276/events.json  |  valorant/f1cdb36f-524b-4020-b427-29852dbe6276/frame_events.json  |  valorant/f1cdb36f-524b-4020-b427-29852dbe6276/metadata.json  |  
|  7775bf68-534c-48dd-aab2-9d8d509ec55c  |  Assassins Creed  |  gaming  |  windows  |  Assassin's Creed IV Black Flag Extended Play Session  |  User plays through a long session of Assassin's Creed IV: Black Flag, progressing through multiple story missions including stealth, naval combat, ship boarding, and exploration sequences. The session includes many passive cutscene segments and idle post-mission screens alongside active gameplay.  |  [ "assassins-creed", "ac4", "black-flag", "gaming", "naval-combat", "stealth", "risk:game_simulator", "risk:kuro_self_reference", "risk:passive_low_active", "conf:0.21" ]  |  246.86  |  14,811,467  |  660,937  |  assassins-creed/7775bf68-534c-48dd-aab2-9d8d509ec55c/clip.mp4  |  assassins-creed/7775bf68-534c-48dd-aab2-9d8d509ec55c/events.json  |  assassins-creed/7775bf68-534c-48dd-aab2-9d8d509ec55c/frame_events.json  |  assassins-creed/7775bf68-534c-48dd-aab2-9d8d509ec55c/metadata.json  |  
|  8e1005e9-6fcc-4709-ad15-66ffe756c623  |  Valorant  |  gaming  |  windows  |  Extended VALORANT competitive multiplayer session  |  User plays multiple competitive VALORANT matches over an extended session, including agent selection, active gameplay rounds with combat and ability usage, post-match reviews, and lobby navigation.  |  [ "valorant", "fps", "competitive", "multiplayer", "chamber", "risk:game_simulator", "conf:0.82" ]  |  245.69  |  14,741,533  |  699,422  |  valorant/8e1005e9-6fcc-4709-ad15-66ffe756c623/clip.mp4  |  valorant/8e1005e9-6fcc-4709-ad15-66ffe756c623/events.json  |  valorant/8e1005e9-6fcc-4709-ad15-66ffe756c623/frame_events.json  |  valorant/8e1005e9-6fcc-4709-ad15-66ffe756c623/metadata.json  |  
|  0cb05921-9fa3-4d0c-b3f6-8a379aa10470  |  Valorant  |  gaming  |  windows  |  VALORANT gaming session – competitive and casual matches  |  User plays multiple VALORANT sessions including competitive ranked matches, skirmish modes, and practice range. Activity spans agent selection, active gameplay, post-match review, and lobby management across many segments.  |  [ "valorant", "fps", "competitive", "gaming", "practice-range", "risk:game_simulator", "conf:0.93" ]  |  241.94  |  14,516,500  |  339,543  |  valorant/0cb05921-9fa3-4d0c-b3f6-8a379aa10470/clip.mp4  |  valorant/0cb05921-9fa3-4d0c-b3f6-8a379aa10470/events.json  |  valorant/0cb05921-9fa3-4d0c-b3f6-8a379aa10470/frame_events.json  |  valorant/0cb05921-9fa3-4d0c-b3f6-8a379aa10470/metadata.json  |  
|  6b6919d5-25fa-44d2-9584-bd87c082dda7  |  Valorant  |  gaming  |  windows  |  Extended VALORANT Competitive Gameplay Session  |  User plays multiple extended sessions of VALORANT, a competitive tactical FPS game, across numerous rounds and matches. Activity includes buy phases, combat, ability usage, map navigation, and post-match lobbying.  |  [ "valorant", "fps", "competitive", "multiplayer", "risk:game_simulator", "conf:0.82" ]  |  228.78  |  13,727,100  |  316,861  |  valorant/6b6919d5-25fa-44d2-9584-bd87c082dda7/clip.mp4  |  valorant/6b6919d5-25fa-44d2-9584-bd87c082dda7/events.json  |  valorant/6b6919d5-25fa-44d2-9584-bd87c082dda7/frame_events.json  |  valorant/6b6919d5-25fa-44d2-9584-bd87c082dda7/metadata.json  |  
|  a70ab21c-8fb0-4166-a94e-4edd4caca30c  |  Assassins Creed Syndicate  |  gaming  |  windows  |  Assassin's Creed Syndicate Extended Gameplay Session  |  User plays through multiple missions and sequences of Assassin's Creed Syndicate, including stealth infiltrations, combat, parkour traversal, carriage driving, and story cutscenes across Victorian London. Activity spans the majority of the session with sustained active gameplay inputs.  |  [ "assassins-creed-syndicate", "action-adventure", "gaming", "open-world", "risk:game_simulator", "conf:0.82" ]  |  212.05  |  12,723,133  |  464,239  |  assassins-creed-syndicate/a70ab21c-8fb0-4166-a94e-4edd4caca30c/clip.mp4  |  assassins-creed-syndicate/a70ab21c-8fb0-4166-a94e-4edd4caca30c/events.json  |  assassins-creed-syndicate/a70ab21c-8fb0-4166-a94e-4edd4caca30c/frame_events.json  |  assassins-creed-syndicate/a70ab21c-8fb0-4166-a94e-4edd4caca30c/metadata.json  |  
|  463137e5-0b1f-4288-a48f-642254b055fa  |  Assassins Creed  |  gaming  |  windows  |  Assassin's Creed IV Black Flag – Extended Gameplay Session  |  User plays a long session of Assassin's Creed IV: Black Flag covering land-based missions in Havana and Nassau (combat, stealth, parkour, assassination contracts), naval combat and sailing, ship boarding, wildlife hunting, and story cutscenes. Sustained recreational gaming throughout.  |  [ "assassins-creed", "ac4", "black-flag", "open-world", "naval-combat", "stealth", "risk:game_simulator", "conf:0.82" ]  |  199.46  |  11,967,667  |  586,573  |  assassins-creed/463137e5-0b1f-4288-a48f-642254b055fa/clip.mp4  |  assassins-creed/463137e5-0b1f-4288-a48f-642254b055fa/events.json  |  assassins-creed/463137e5-0b1f-4288-a48f-642254b055fa/frame_events.json  |  assassins-creed/463137e5-0b1f-4288-a48f-642254b055fa/metadata.json  |  
|  88ef8af3-ccf7-4687-ac81-940207f8dbb6  |  Minecraft  |  gaming  |  windows  |  Minecraft Singleplayer — Session Launch & Extended Survival Gameplay  |  User browses YouTube briefly then launches Minecraft via TLauncher and plays an extended singleplayer survival session involving resource gathering (tree chopping, sugar cane farming), villager trading, crafting, base building, and inventory management across many segments.  |  [ "minecraft", "survival", "farming", "trading", "crafting", "resource-gathering", "risk:game_simulator", "conf:0.85" ]  |  194.64  |  11,678,500  |  416,983  |  minecraft/88ef8af3-ccf7-4687-ac81-940207f8dbb6/clip.mp4  |  minecraft/88ef8af3-ccf7-4687-ac81-940207f8dbb6/events.json  |  minecraft/88ef8af3-ccf7-4687-ac81-940207f8dbb6/frame_events.json  |  minecraft/88ef8af3-ccf7-4687-ac81-940207f8dbb6/metadata.json  |  
|  6fbf61a9-3d19-4262-933b-e053f3815fca  |  Forza Horizon  |  gaming  |  windows  |  Forza Horizon 6 extended gameplay session  |  User plays Forza Horizon 6 across an extended session covering character creation, car selection, story missions, street races, convoy multiplayer, open-world exploration, and social features including Xbox friend invites.  |  [ "forza-horizon-6", "racing", "open-world", "multiplayer", "convoy", "risk:game_simulator", "conf:0.90" ]  |  194.31  |  11,658,867  |  98,608  |  forza-horizon/6fbf61a9-3d19-4262-933b-e053f3815fca/clip.mp4  |  forza-horizon/6fbf61a9-3d19-4262-933b-e053f3815fca/events.json  |  forza-horizon/6fbf61a9-3d19-4262-933b-e053f3815fca/frame_events.json  |  forza-horizon/6fbf61a9-3d19-4262-933b-e053f3815fca/metadata.json  |  
|  575fc52b-a9cc-4725-a66b-434aeb64011c  |  007 First Light  |  gaming  |  windows  |  007 First Light — full playthrough session  |  User launches and plays through an extended session of 007 First Light, a stealth-action James Bond game, progressing through multiple missions including office infiltration, museum escape, corporate building stealth, penthouse break-in, and data center combat. Session includes active gameplay, cutscenes, menus, loadin...  |  [ "007-first-light", "stealth", "action", "james-bond", "mission-progression", "risk:game_simulator", "conf:0.82" ]  |  182.73  |  10,963,867  |  284,924  |  007-first-light/575fc52b-a9cc-4725-a66b-434aeb64011c/clip.mp4  |  007-first-light/575fc52b-a9cc-4725-a66b-434aeb64011c/events.json  |  007-first-light/575fc52b-a9cc-4725-a66b-434aeb64011c/frame_events.json  |  007-first-light/575fc52b-a9cc-4725-a66b-434aeb64011c/metadata.json  |  
|  a49b86d9-343d-4f08-9862-47917dd4303c  |  Grand Theft Auto V  |  gaming  |  windows  |  GTA V Extended Free-Roam and Racing Session  |  User spends the entire session playing Grand Theft Auto V, engaging in free-roam driving, street races, combat with NPCs, cheat code usage, and open-world exploration across desert, rural, and urban environments. No productive output or external task is being performed.  |  [ "gta-v", "free-roam", "driving", "racing", "cheat-codes", "open-world", "risk:game_simulator", "conf:0.95" ]  |  179.73  |  10,784,000  |  215,361  |  grand-theft-auto-v/a49b86d9-343d-4f08-9862-47917dd4303c/clip.mp4  |  grand-theft-auto-v/a49b86d9-343d-4f08-9862-47917dd4303c/events.json  |  grand-theft-auto-v/a49b86d9-343d-4f08-9862-47917dd4303c/frame_events.json  |  grand-theft-auto-v/a49b86d9-343d-4f08-9862-47917dd4303c/metadata.json  |  
|  f3d4bdf5-7234-4a11-b41a-139f35df64b5  |  Assassins Creed Syndicate  |  gaming  |  windows  |  Assassin's Creed Syndicate gameplay recording session (first block)  |  Extended gameplay session of Assassin's Creed Syndicate recorded via VidLog, covering missions including killing the Master Spy, dockside combat, borough conquest, and various story missions through Victorian London. Interspersed with brief VidLog dashboard checks.  |  [ "assassins-creed-syndicate", "gameplay", "vidlog", "recording", "risk:game_simulator", "risk:kuro_self_reference", "conf:0.82" ]  |  178.47  |  10,708,467  |  402,292  |  assassins-creed-syndicate/f3d4bdf5-7234-4a11-b41a-139f35df64b5/clip.mp4  |  assassins-creed-syndicate/f3d4bdf5-7234-4a11-b41a-139f35df64b5/events.json  |  assassins-creed-syndicate/f3d4bdf5-7234-4a11-b41a-139f35df64b5/frame_events.json  |  assassins-creed-syndicate/f3d4bdf5-7234-4a11-b41a-139f35df64b5/metadata.json  |  
|  0fd632fd-290d-405c-9b8b-74621a2fa255  |  Valorant  |  gaming  |  windows  |  VALORANT Competitive Gaming Session  |  Extended VALORANT competitive multiplayer session spanning multiple matches, including active gameplay rounds, buy phases, agent selection, lobby navigation, queue waiting, and brief practice range use. The user plays as Jett across several competitive matches at Silver rank.  |  [ "valorant", "fps", "competitive", "jett", "silver-rank", "risk:game_simulator", "conf:0.82" ]  |  168.22  |  10,093,033  |  394,968  |  valorant/0fd632fd-290d-405c-9b8b-74621a2fa255/clip.mp4  |  valorant/0fd632fd-290d-405c-9b8b-74621a2fa255/events.json  |  valorant/0fd632fd-290d-405c-9b8b-74621a2fa255/frame_events.json  |  valorant/0fd632fd-290d-405c-9b8b-74621a2fa255/metadata.json  |  
|  7bde55b3-9b07-4d39-867d-d21f183a2f10  |  Ac4  |  gaming  |  windows  |  Assassin's Creed IV Black Flag Extended Play Session  |  User plays Assassin's Creed IV Black Flag for an extended session covering naval combat, island exploration, stealth missions, ship boarding, harpooning, and story progression. Includes launching the game, completing side activities, and navigating menus.  |  [ "ac4", "assassins-creed", "gaming", "naval-combat", "open-world", "risk:game_simulator", "risk:kuro_self_reference", "conf:0.82" ]  |  164.67  |  9,880,133  |  469,226  |  ac4/7bde55b3-9b07-4d39-867d-d21f183a2f10/clip.mp4  |  ac4/7bde55b3-9b07-4d39-867d-d21f183a2f10/events.json  |  ac4/7bde55b3-9b07-4d39-867d-d21f183a2f10/frame_events.json  |  ac4/7bde55b3-9b07-4d39-867d-d21f183a2f10/metadata.json  |  
|  98efb7b4-02a8-40ad-8906-f08abf67703b  |  Grand Theft Auto V  |  gaming  |  windows  |  Grand Theft Auto V — Open-World Exploration and Story Missions  |  Extended GTA V gameplay session covering open-world driving, combat, cheat code use, weapon browsing, strip club visits, darts minigame, motorcycle riding, and various story/side missions across desert and urban environments. Recreational gaming with no productive output.  |  [ "gta-v", "open-world", "driving", "combat", "missions", "risk:game_simulator", "conf:0.15" ]  |  162.49  |  9,749,300  |  195,783  |  grand-theft-auto-v/98efb7b4-02a8-40ad-8906-f08abf67703b/clip.mp4  |  grand-theft-auto-v/98efb7b4-02a8-40ad-8906-f08abf67703b/events.json  |  grand-theft-auto-v/98efb7b4-02a8-40ad-8906-f08abf67703b/frame_events.json  |  grand-theft-auto-v/98efb7b4-02a8-40ad-8906-f08abf67703b/metadata.json  |  
|  6b8dca9e-190c-49e8-a4b9-bc67354bc35e  |  Assassins Creed Syndicate  |  gaming  |  windows  |  Assassin's Creed Syndicate Gameplay Session 2  |  Second extended gameplay session in Assassin's Creed Syndicate covering bounty hunts, anarchist intervention missions, Marx-related story missions, Bank of England heist, and open-world traversal through Victorian London.  |  [ "assassins-creed-syndicate", "action-adventure", "gaming", "risk:game_simulator", "conf:0.80" ]  |  161.58  |  9,694,700  |  341,057  |  assassins-creed-syndicate/6b8dca9e-190c-49e8-a4b9-bc67354bc35e/clip.mp4  |  assassins-creed-syndicate/6b8dca9e-190c-49e8-a4b9-bc67354bc35e/events.json  |  assassins-creed-syndicate/6b8dca9e-190c-49e8-a4b9-bc67354bc35e/frame_events.json  |  assassins-creed-syndicate/6b8dca9e-190c-49e8-a4b9-bc67354bc35e/metadata.json  |  
|  f6aee1f9-e37f-4e14-8bee-546f239a1dec  |  Minecraft  |  gaming  |  windows  |  Minecraft Multiplayer PvP Combat Session  |  Extended Minecraft PvP gaming session on practice servers (GamerTee.net, OPHCRACK.NET, OPPractice.net) using Lunar Client, involving sustained combat with other players, inventory management, potion use, and active multiplayer interaction across many rounds.  |  [ "minecraft", "pvp", "multiplayer", "lunar-client", "combat", "risk:game_simulator", "conf:0.78" ]  |  160.22  |  9,613,433  |  263,997  |  minecraft/f6aee1f9-e37f-4e14-8bee-546f239a1dec/clip.mp4  |  minecraft/f6aee1f9-e37f-4e14-8bee-546f239a1dec/events.json  |  minecraft/f6aee1f9-e37f-4e14-8bee-546f239a1dec/frame_events.json  |  minecraft/f6aee1f9-e37f-4e14-8bee-546f239a1dec/metadata.json  |  
|  909651ff-65e9-4ca0-aa38-d756f26fd753  |  Assassins Creed  |  gaming  |  windows  |  Assassin's Creed IV: Black Flag Extended Play Session  |  Extended gameplay session of Assassin's Creed IV: Black Flag covering land missions, naval combat, fort assaults, stealth missions, ship upgrades, and underwater exploration. Includes ReShade graphics configuration and passive cutscene viewing throughout.  |  [ "assassins-creed", "ac4", "naval-combat", "stealth", "reshade", "open-world", "risk:game_simulator", "risk:passive_low_active", "conf:0.82" ]  |  159.56  |  9,573,500  |  431,224  |  assassins-creed/909651ff-65e9-4ca0-aa38-d756f26fd753/clip.mp4  |  assassins-creed/909651ff-65e9-4ca0-aa38-d756f26fd753/events.json  |  assassins-creed/909651ff-65e9-4ca0-aa38-d756f26fd753/frame_events.json  |  assassins-creed/909651ff-65e9-4ca0-aa38-d756f26fd753/metadata.json  |  
|  a3c49489-7512-4398-af78-cffa5ada989e  |  Valorant  |  gaming  |  windows  |  VALORANT session — setup, matchmaking, and extended competitive play  |  User sets up for gaming (Spotify, wallpaper change), launches VALORANT, queues for competitive matches, and plays multiple extended ranked matches across maps including Breeze, Fracture, and Split, ending with a Silver 3 rank result.  |  [ "valorant", "fps", "competitive", "ranked", "reyna", "gekko", "risk:game_simulator", "conf:0.82" ]  |  147.88  |  8,872,700  |  472,779  |  valorant/a3c49489-7512-4398-af78-cffa5ada989e/clip.mp4  |  valorant/a3c49489-7512-4398-af78-cffa5ada989e/events.json  |  valorant/a3c49489-7512-4398-af78-cffa5ada989e/frame_events.json  |  valorant/a3c49489-7512-4398-af78-cffa5ada989e/metadata.json  |  
|  935921a1-632c-4a77-a356-98af2fbe62d5  |  Valorant  |  gaming  |  windows  |  VALORANT session — login, lobby, and extended competitive gameplay  |  User logs into the Riot Games client, queues for competitive VALORANT matches, and plays multiple full matches across several maps. Activity includes agent selection, buy phases, active combat rounds, post-match lobby management, and use of the Overwolf VALORANT Tracker overlay.  |  [ "valorant", "fps", "competitive", "riot-games", "overwolf", "risk:game_simulator", "conf:0.72" ]  |  145.26  |  8,715,400  |  344,194  |  valorant/935921a1-632c-4a77-a356-98af2fbe62d5/clip.mp4  |  valorant/935921a1-632c-4a77-a356-98af2fbe62d5/events.json  |  valorant/935921a1-632c-4a77-a356-98af2fbe62d5/frame_events.json  |  valorant/935921a1-632c-4a77-a356-98af2fbe62d5/metadata.json  |  
|  8c3d3861-b472-46d4-8b33-f48b81b66df8  |  Palworld  |  gaming  |  windows  |  Palworld Extended Gameplay Session  |  User plays Palworld across an extended session covering open-world exploration, combat, creature capture and management, base building, crafting, inventory management, and technology progression. Activity is sustained and varied but constitutes recreational gaming with no productive software work.  |  [ "palworld", "survival-game", "creature-collection", "base-building", "crafting", "risk:game_simulator", "risk:passive_low_active", "conf:0.82" ]  |  142.76  |  8,565,500  |  382,151  |  palworld/8c3d3861-b472-46d4-8b33-f48b81b66df8/clip.mp4  |  palworld/8c3d3861-b472-46d4-8b33-f48b81b66df8/events.json  |  palworld/8c3d3861-b472-46d4-8b33-f48b81b66df8/frame_events.json  |  palworld/8c3d3861-b472-46d4-8b33-f48b81b66df8/metadata.json  |  
|  a8a99a7a-c89c-47b6-be74-205f8e95e2fa  |  007 First Light  |  gaming  |  windows  |  007 First Light — full gameplay session  |  Extended gaming session playing 007 First Light (James Bond action/stealth game) across multiple missions including industrial combat, tropical resort infiltration, snowy quarry stealth, and MI6 facility exploration. Includes active gameplay, cutscenes, menus, and brief task-switching interruptions.  |  [ "007-first-light", "james-bond", "stealth", "action", "shooter", "risk:game_simulator", "conf:0.78" ]  |  140.97  |  8,458,200  |  191,115  |  007-first-light/a8a99a7a-c89c-47b6-be74-205f8e95e2fa/clip.mp4  |  007-first-light/a8a99a7a-c89c-47b6-be74-205f8e95e2fa/events.json  |  007-first-light/a8a99a7a-c89c-47b6-be74-205f8e95e2fa/frame_events.json  |  007-first-light/a8a99a7a-c89c-47b6-be74-205f8e95e2fa/metadata.json  |  
|  23958359-97a9-4198-bca3-a6f05181e65f  |  Valorant  |  gaming  |  windows  |  VALORANT Competitive Multiplayer Session  |  Extended VALORANT competitive play session spanning multiple matches, including agent selection, buy phases, active combat rounds, and post-game screens. The user plays as Brimstone and Sova across maps including Lotus and Ascent, engaging in sustained FPS gameplay.  |  [ "valorant", "fps", "competitive", "multiplayer", "risk:game_simulator", "conf:0.92" ]  |  134.11  |  8,046,700  |  321,898  |  valorant/23958359-97a9-4198-bca3-a6f05181e65f/clip.mp4  |  valorant/23958359-97a9-4198-bca3-a6f05181e65f/events.json  |  valorant/23958359-97a9-4198-bca3-a6f05181e65f/frame_events.json  |  valorant/23958359-97a9-4198-bca3-a6f05181e65f/metadata.json  |  
|  6df2898c-a58b-4176-a390-561dd153eb77  |  Minecraft  |  gaming  |  windows  |  Minecraft Multiplayer Survival Session  |  Extended Minecraft Java Edition multiplayer survival gameplay on an Aternos-hosted server, covering exploration, combat, fishing, trading, mining, and resource gathering across numerous segments. Activity is recreational gaming with no productive software artifact being created.  |  [ "minecraft", "multiplayer", "survival", "aternos", "java-edition", "risk:game_simulator", "conf:0.82" ]  |  134.03  |  8,041,533  |  233,427  |  minecraft/6df2898c-a58b-4176-a390-561dd153eb77/clip.mp4  |  minecraft/6df2898c-a58b-4176-a390-561dd153eb77/events.json  |  minecraft/6df2898c-a58b-4176-a390-561dd153eb77/frame_events.json  |  minecraft/6df2898c-a58b-4176-a390-561dd153eb77/metadata.json  |  
|  148aa769-09ba-4b8a-9815-85939693ba36  |  Grand Theft Auto V  |  gaming  |  windows  |  Grand Theft Auto V extended gameplay session  |  User plays Grand Theft Auto V across an extended session covering free-roam driving, story missions, heist setup, police chases, and character customization. The session includes both active gameplay and passive cutscene/TV watching segments.  |  [ "gta-v", "open-world", "driving", "missions", "heist", "police-chase", "risk:game_simulator", "risk:passive_low_active", "conf:0.88" ]  |  130.93  |  7,855,800  |  153,061  |  grand-theft-auto-v/148aa769-09ba-4b8a-9815-85939693ba36/clip.mp4  |  grand-theft-auto-v/148aa769-09ba-4b8a-9815-85939693ba36/events.json  |  grand-theft-auto-v/148aa769-09ba-4b8a-9815-85939693ba36/frame_events.json  |  grand-theft-auto-v/148aa769-09ba-4b8a-9815-85939693ba36/metadata.json  |  
|  d51f001e-f472-4478-a36a-c4dc5b691936  |  Valorant  |  gaming  |  windows  |  VALORANT Competitive & Custom Match Sessions  |  Extended VALORANT gaming session spanning competitive ranked matches, custom skirmishes, and practice range activity. The user plays multiple full matches across several maps (Haven, Pearl, Lotus, Fracture, Breeze, Split), selecting agents (Reyna, Clove, Jett, Sova, Breach), purchasing weapons, and engaging in active F...  |  [ "valorant", "fps", "competitive", "gaming", "ranked", "risk:game_simulator", "conf:0.85" ]  |  130.53  |  7,831,933  |  418,924  |  valorant/d51f001e-f472-4478-a36a-c4dc5b691936/clip.mp4  |  valorant/d51f001e-f472-4478-a36a-c4dc5b691936/events.json  |  valorant/d51f001e-f472-4478-a36a-c4dc5b691936/frame_events.json  |  valorant/d51f001e-f472-4478-a36a-c4dc5b691936/metadata.json  |  
|  83d3c8d0-64c4-4f71-9f3c-6fef6bcbc57a  |  Assassins Creed Syndicate  |  gaming  |  windows  |  Assassin's Creed Syndicate extended gameplay session  |  User plays through multiple hours of Assassin's Creed Syndicate, completing missions including boat defense, gang strongholds, child liberation, train rooftop sequences, and WWI-era London missions. Sustained active gameplay with combat, parkour, stealth, and mission progression throughout.  |  [ "assassins-creed-syndicate", "action-adventure", "gameplay", "missions", "risk:game_simulator", "conf:0.92" ]  |  126.92  |  7,615,200  |  330,826  |  assassins-creed-syndicate/83d3c8d0-64c4-4f71-9f3c-6fef6bcbc57a/clip.mp4  |  assassins-creed-syndicate/83d3c8d0-64c4-4f71-9f3c-6fef6bcbc57a/events.json  |  assassins-creed-syndicate/83d3c8d0-64c4-4f71-9f3c-6fef6bcbc57a/frame_events.json  |  assassins-creed-syndicate/83d3c8d0-64c4-4f71-9f3c-6fef6bcbc57a/metadata.json  |  
|  1561aa44-4d3a-4499-b326-07674623c13d  |  Assassins Creed Syndicate  |  gaming  |  windows  |  Assassin's Creed Syndicate Gameplay Session  |  Extended gameplay session in Assassin's Creed Syndicate covering multiple missions across Victorian London, including stealth infiltrations, combat, parkour traversal, carriage driving, and story cutscenes. Recorded as part of a VidLog footage collection task, but the activity itself is recreational gaming with no prod...  |  [ "assassins-creed-syndicate", "gaming", "open-world", "stealth", "action-adventure", "risk:game_simulator", "risk:passive_low_active", "conf:0.82" ]  |  126.72  |  7,603,467  |  259,551  |  assassins-creed-syndicate/1561aa44-4d3a-4499-b326-07674623c13d/clip.mp4  |  assassins-creed-syndicate/1561aa44-4d3a-4499-b326-07674623c13d/events.json  |  assassins-creed-syndicate/1561aa44-4d3a-4499-b326-07674623c13d/frame_events.json  |  assassins-creed-syndicate/1561aa44-4d3a-4499-b326-07674623c13d/metadata.json  |  
|  340f1ab1-f40a-429b-a605-6b8bc71519e8  |  Minecraft  |  gaming  |  windows  |  Minecraft PvP Combat — Multiplayer Practice Server  |  User engages in sustained Minecraft PvP combat on a multiplayer practice server using Lunar Client, fighting other players with swords, potions, and golden apples across multiple extended sessions.  |  [ "minecraft", "pvp", "combat", "lunar-client", "multiplayer", "risk:game_simulator", "conf:0.72" ]  |  125.06  |  7,503,900  |  214,703  |  minecraft/340f1ab1-f40a-429b-a605-6b8bc71519e8/clip.mp4  |  minecraft/340f1ab1-f40a-429b-a605-6b8bc71519e8/events.json  |  minecraft/340f1ab1-f40a-429b-a605-6b8bc71519e8/frame_events.json  |  minecraft/340f1ab1-f40a-429b-a605-6b8bc71519e8/metadata.json  |  
|  6a63ae3b-8967-4524-9b0a-f34be1a98d2e  |  Age of Empires  |  gaming  |  windows  |  Age of Empires II DE — Ranked Multiplayer Sessions  |  User plays multiple ranked 4v4 multiplayer matches in Age of Empires II: Definitive Edition, managing civilizations (Huns, Mongols), building bases, gathering resources, and engaging in combat. Includes matchmaking, lobby browsing, queue waiting, and brief Reddit/ChatGPT lookups about game mechanics between matches.  |  [ "aoe2", "rts", "ranked", "multiplayer", "strategy", "risk:game_simulator", "conf:0.82" ]  |  123.27  |  7,396,467  |  385,713  |  age-of-empires/6a63ae3b-8967-4524-9b0a-f34be1a98d2e/clip.mp4  |  age-of-empires/6a63ae3b-8967-4524-9b0a-f34be1a98d2e/events.json  |  age-of-empires/6a63ae3b-8967-4524-9b0a-f34be1a98d2e/frame_events.json  |  age-of-empires/6a63ae3b-8967-4524-9b0a-f34be1a98d2e/metadata.json  |  
|  45ec1f7e-5b76-4248-996f-3ea63f0af687  |  Valorant  |  gaming  |  windows  |  VALORANT Team Deathmatch and Competitive Matches  |  Extended VALORANT gaming session spanning team deathmatch warmup and multiple competitive matches across maps including Kasbah, Breeze, Lotus, and Pearl. The user actively plays as various agents (Jett, Reyna, Chamber), engaging in combat, purchasing weapons, using abilities, and progressing through ranked matches.  |  [ "valorant", "fps", "competitive", "gaming", "risk:game_simulator", "conf:0.92" ]  |  122.34  |  7,340,300  |  387,916  |  valorant/45ec1f7e-5b76-4248-996f-3ea63f0af687/clip.mp4  |  valorant/45ec1f7e-5b76-4248-996f-3ea63f0af687/events.json  |  valorant/45ec1f7e-5b76-4248-996f-3ea63f0af687/frame_events.json  |  valorant/45ec1f7e-5b76-4248-996f-3ea63f0af687/metadata.json  |  
|  6ea9b106-a420-44f6-80c7-87d1e9646fc0  |  Wolfenstein  |  gaming  |  windows  |  Wolfenstein: The Old Blood — Extended Play Session  |  User plays through multiple chapters of Wolfenstein: The Old Blood, an FPS game, including menu navigation, cutscene viewing, and sustained active combat and exploration gameplay. No productive software work is involved.  |  [ "wolfenstein", "fps", "gaming", "action", "risk:game_simulator", "conf:0.95" ]  |  121.81  |  7,308,633  |  219,027  |  wolfenstein/6ea9b106-a420-44f6-80c7-87d1e9646fc0/clip.mp4  |  wolfenstein/6ea9b106-a420-44f6-80c7-87d1e9646fc0/events.json  |  wolfenstein/6ea9b106-a420-44f6-80c7-87d1e9646fc0/frame_events.json  |  wolfenstein/6ea9b106-a420-44f6-80c7-87d1e9646fc0/metadata.json  |  
|  671d731f-7466-47ad-97c7-3ed8080be768  |  007 First Light  |  gaming  |  windows  |  007 First Light — Extended Gameplay Session  |  User plays through a substantial portion of the James Bond game '007 First Light,' progressing through MI6 facility exploration, hotel infiltration stealth missions, combat sequences, driving missions, and narrative cutscenes. Gameplay spans multiple mission areas with active character control, puzzle-solving, and stor...  |  [ "007-first-light", "james-bond", "stealth", "action", "driving", "risk:game_simulator", "conf:0.82" ]  |  121.8  |  7,308,033  |  152,373  |  007-first-light/671d731f-7466-47ad-97c7-3ed8080be768/clip.mp4  |  007-first-light/671d731f-7466-47ad-97c7-3ed8080be768/events.json  |  007-first-light/671d731f-7466-47ad-97c7-3ed8080be768/frame_events.json  |  007-first-light/671d731f-7466-47ad-97c7-3ed8080be768/metadata.json  |  
|  9972c944-dd16-47b9-b9f5-06db7921ce11  |  007 First Light  |  gaming  |  windows  |  007 First Light — Game Launch, Setup, and Extended Gameplay  |  User launches the James Bond game '007 First Light', configures graphics and audio settings, and plays through multiple missions including stealth sequences, combat training, driving, and narrative cutscenes. The session spans initial setup through several story missions with sustained WASD/mouse gameplay input.  |  [ "007-first-light", "james-bond", "stealth", "action", "gaming", "risk:game_simulator", "risk:passive_low_active", "conf:0.85" ]  |  121.09  |  7,265,567  |  155,019  |  007-first-light/9972c944-dd16-47b9-b9f5-06db7921ce11/clip.mp4  |  007-first-light/9972c944-dd16-47b9-b9f5-06db7921ce11/events.json  |  007-first-light/9972c944-dd16-47b9-b9f5-06db7921ce11/frame_events.json  |  007-first-light/9972c944-dd16-47b9-b9f5-06db7921ce11/metadata.json  |  
|  aee9bc67-f56a-4e87-98df-5b76841f7c7e  |  Valorant  |  gaming  |  windows  |  VALORANT session — launcher, lobbies, menus, and competitive matches  |  Extended VALORANT gaming session covering launcher update, lobby navigation, agent selection, settings adjustments, and multiple competitive matches across Lotus and Breeze maps including overtime play and post-match review.  |  [ "valorant", "fps", "competitive", "ranked", "riot-games", "risk:game_simulator", "conf:0.88" ]  |  120.07  |  7,204,133  |  405,231  |  valorant/aee9bc67-f56a-4e87-98df-5b76841f7c7e/clip.mp4  |  valorant/aee9bc67-f56a-4e87-98df-5b76841f7c7e/events.json  |  valorant/aee9bc67-f56a-4e87-98df-5b76841f7c7e/frame_events.json  |  valorant/aee9bc67-f56a-4e87-98df-5b76841f7c7e/metadata.json  |  
|  97a4326d-1fcc-4573-9b2e-437a39bef368  |  Need for Speed  |  gaming  |  windows  |  Need for Speed Most Wanted — Extended Gameplay Session  |  User launches and plays Need for Speed Most Wanted for an extended session covering police pursuits, sprint and circuit races, car customization, and free-roam driving across multiple environments.  |  [ "nfs", "need-for-speed", "most-wanted", "racing", "gameplay", "risk:game_simulator", "conf:0.85" ]  |  119.97  |  7,198,233  |  48,218  |  need-for-speed/97a4326d-1fcc-4573-9b2e-437a39bef368/clip.mp4  |  need-for-speed/97a4326d-1fcc-4573-9b2e-437a39bef368/events.json  |  need-for-speed/97a4326d-1fcc-4573-9b2e-437a39bef368/frame_events.json  |  need-for-speed/97a4326d-1fcc-4573-9b2e-437a39bef368/metadata.json  |  
|  7ccbbd71-0bbc-4c41-9727-0dc0889fc4a6  |  007 First Light  |  gaming  |  windows  |  007 First Light gameplay session  |  Extended gameplay session of the James Bond action-adventure game '007 First Light', covering mission exploration, stealth, combat, driving, and story cutscenes across a marketplace, dockyard, industrial facility, and desert environments.  |  [ "007-first-light", "james-bond", "stealth", "action", "third-person-shooter", "risk:game_simulator", "conf:0.92" ]  |  118.65  |  7,119,233  |  169,900  |  007-first-light/7ccbbd71-0bbc-4c41-9727-0dc0889fc4a6/clip.mp4  |  007-first-light/7ccbbd71-0bbc-4c41-9727-0dc0889fc4a6/events.json  |  007-first-light/7ccbbd71-0bbc-4c41-9727-0dc0889fc4a6/frame_events.json  |  007-first-light/7ccbbd71-0bbc-4c41-9727-0dc0889fc4a6/metadata.json  |  
|  867c6d0d-2d66-4e40-9fb4-bdf916fd9ec4  |  Palworld  |  gaming  |  windows  |  Palworld Base Management, Crafting & Inventory  |  Extended Palworld gameplay focused on base building, production line management, inventory organization, resource crafting, and Pal assignment. Covers routine survival-game maintenance loops across many segments.  |  [ "palworld", "base-building", "crafting", "inventory-management", "survival", "risk:game_simulator", "conf:0.83" ]  |  118.18  |  7,090,633  |  326,784  |  palworld/867c6d0d-2d66-4e40-9fb4-bdf916fd9ec4/clip.mp4  |  palworld/867c6d0d-2d66-4e40-9fb4-bdf916fd9ec4/events.json  |  palworld/867c6d0d-2d66-4e40-9fb4-bdf916fd9ec4/frame_events.json  |  palworld/867c6d0d-2d66-4e40-9fb4-bdf916fd9ec4/metadata.json  |  
|  37d71edd-6614-4eba-b220-3440f71e3ad3  |  Forza Horizon  |  gaming  |  windows  |  Forza Horizon 6 Extended Gameplay Session  |  User plays Forza Horizon 6 across an extended session involving open-world driving, racing events, treasure hunting, car collection, tuning menu browsing, car customization, and settings adjustments across Japanese-themed environments.  |  [ "forza-horizon-6", "racing", "open-world", "car-customization", "treasure-hunt", "risk:game_simulator", "risk:passive_low_active", "conf:0.82" ]  |  117.77  |  7,066,267  |  82,406  |  forza-horizon/37d71edd-6614-4eba-b220-3440f71e3ad3/clip.mp4  |  forza-horizon/37d71edd-6614-4eba-b220-3440f71e3ad3/events.json  |  forza-horizon/37d71edd-6614-4eba-b220-3440f71e3ad3/frame_events.json  |  forza-horizon/37d71edd-6614-4eba-b220-3440f71e3ad3/metadata.json  |  
|  cd050431-6fda-483a-9f54-5cdb187e9c88  |  Grand Theft Auto V  |  gaming  |  windows  |  Grand Theft Auto V Extended Gameplay Session  |  User plays through a lengthy GTA V session covering story missions (Daddy's Little Girl, Friend Request, The Long Stretch), free-roam exploration, driving, combat, and open-world activities. Gameplay spans beach exploration, yacht missions, Lifeinvader office infiltration, police chases, weapon shopping, and helicopter...  |  [ "gta-v", "open-world", "story-missions", "free-roam", "driving", "risk:game_simulator", "conf:0.92" ]  |  116.6  |  6,996,200  |  124,990  |  grand-theft-auto-v/cd050431-6fda-483a-9f54-5cdb187e9c88/clip.mp4  |  grand-theft-auto-v/cd050431-6fda-483a-9f54-5cdb187e9c88/events.json  |  grand-theft-auto-v/cd050431-6fda-483a-9f54-5cdb187e9c88/frame_events.json  |  grand-theft-auto-v/cd050431-6fda-483a-9f54-5cdb187e9c88/metadata.json  |  
|  f3396741-a553-452a-adec-2d6580bd5376  |  Grand Theft Auto V  |  gaming  |  windows  |  Grand Theft Auto V Extended Gameplay Session  |  User plays Grand Theft Auto V for an extended session covering free-roam driving, open-world exploration, story missions, combat sequences, and map navigation. Activity spans rural and urban environments with vehicle operation, shooting mechanics, and mission progression.  |  [ "gta-v", "open-world", "driving", "combat", "free-roam", "risk:game_simulator", "risk:passive_low_active", "conf:0.95" ]  |  115.49  |  6,929,300  |  150,816  |  grand-theft-auto-v/f3396741-a553-452a-adec-2d6580bd5376/clip.mp4  |  grand-theft-auto-v/f3396741-a553-452a-adec-2d6580bd5376/events.json  |  grand-theft-auto-v/f3396741-a553-452a-adec-2d6580bd5376/frame_events.json  |  grand-theft-auto-v/f3396741-a553-452a-adec-2d6580bd5376/metadata.json  |  
|  508402e4-6ecf-4e36-8e64-1d851d2fee61  |  Just Cause 2  |  gaming  |  windows  |  Just Cause 2 Extended Gameplay Session  |  User plays Just Cause 2 across a long session, completing missions, destroying objectives, driving vehicles, and free-roaming. Includes a brief YouTube browse for Just Cause 3/4 content and file explorer navigation to launch the game.  |  [ "just-cause-2", "open-world", "action", "gaming", "risk:game_simulator", "risk:passive_low_active", "conf:0.82" ]  |  115.1  |  6,906,267  |  172,850  |  just-cause-2/508402e4-6ecf-4e36-8e64-1d851d2fee61/clip.mp4  |  just-cause-2/508402e4-6ecf-4e36-8e64-1d851d2fee61/events.json  |  just-cause-2/508402e4-6ecf-4e36-8e64-1d851d2fee61/frame_events.json  |  just-cause-2/508402e4-6ecf-4e36-8e64-1d851d2fee61/metadata.json  |  
|  ab385609-a422-40ac-90f1-3f7cde079a68  |  Hitman 3  |  gaming  |  windows  |  HITMAN 3 Gameplay Session  |  Extended HITMAN 3 gameplay session covering the 'The Farewell' mission in Mendoza and the 'Untouchable' mission in the Carpathian Mountains, including stealth mechanics, combat, cutscenes, and mission completion. Predominantly passive with very low input density.  |  [ "hitman3", "stealth", "gaming", "recreational", "risk:game_simulator", "risk:passive_low_active", "conf:0.88" ]  |  114.82  |  6,889,300  |  213  |  hitman-3/ab385609-a422-40ac-90f1-3f7cde079a68/clip.mp4  |  hitman-3/ab385609-a422-40ac-90f1-3f7cde079a68/events.json  |  hitman-3/ab385609-a422-40ac-90f1-3f7cde079a68/frame_events.json  |  hitman-3/ab385609-a422-40ac-90f1-3f7cde079a68/metadata.json  |  
|  9257baf1-fcce-4e6b-b9cb-f80b6ccb9cab  |  Arc Raiders  |  gaming  |  windows  |  ARC Raiders Extended Play Session  |  User plays ARC Raiders across an extended session covering game launch, multiple raid runs, inventory management, crafting, combat, and menu navigation. The session is dominated by routine extraction shooter gameplay with repeated looting, inventory organization, and combat loops.  |  [ "arc-raiders", "extraction-shooter", "inventory-management", "combat", "crafting", "risk:game_simulator", "risk:kuro_self_reference", "conf:0.82" ]  |  113.32  |  6,799,433  |  178,715  |  arc-raiders/9257baf1-fcce-4e6b-b9cb-f80b6ccb9cab/clip.mp4  |  arc-raiders/9257baf1-fcce-4e6b-b9cb-f80b6ccb9cab/events.json  |  arc-raiders/9257baf1-fcce-4e6b-b9cb-f80b6ccb9cab/frame_events.json  |  arc-raiders/9257baf1-fcce-4e6b-b9cb-f80b6ccb9cab/metadata.json  |  
|  0df52d77-ecd4-4f90-b2ae-14dcc91bb38c  |  Valorant  |  gaming  |  windows  |  VALORANT Extended Gaming Session  |  User spends the majority of the session playing VALORANT across multiple game modes including Deathmatch, competitive matches, and Skirmish. Activity includes launcher navigation, agent selection, sustained match gameplay, and post-match lobby interactions.  |  [ "valorant", "fps", "competitive", "deathmatch", "riot-games", "risk:game_simulator", "conf:0.82" ]  |  113.15  |  6,789,000  |  289,231  |  valorant/0df52d77-ecd4-4f90-b2ae-14dcc91bb38c/clip.mp4  |  valorant/0df52d77-ecd4-4f90-b2ae-14dcc91bb38c/events.json  |  valorant/0df52d77-ecd4-4f90-b2ae-14dcc91bb38c/frame_events.json  |  valorant/0df52d77-ecd4-4f90-b2ae-14dcc91bb38c/metadata.json  |  
|  e33327bd-6b8f-49c9-a871-f9ae819b2160  |  Valorant  |  gaming  |  windows  |  Extended VALORANT Gaming Session  |  User launches and plays VALORANT across a long competitive gaming session spanning multiple ranked and skirmish matches. Activity includes sustained FPS gameplay with movement, combat, ability usage, buy phases, and scoreboard reviews across numerous rounds.  |  [ "valorant", "fps", "competitive", "ranked", "skirmish", "risk:game_simulator", "conf:0.92" ]  |  112.97  |  6,778,300  |  336,060  |  valorant/e33327bd-6b8f-49c9-a871-f9ae819b2160/clip.mp4  |  valorant/e33327bd-6b8f-49c9-a871-f9ae819b2160/events.json  |  valorant/e33327bd-6b8f-49c9-a871-f9ae819b2160/frame_events.json  |  valorant/e33327bd-6b8f-49c9-a871-f9ae819b2160/metadata.json  |  
|  17b680bf-7418-4955-9b94-4281402d8e7a  |  Cod Mw2  |  gaming  |  windows  |  Call of Duty: Modern Warfare II Campaign Playthrough  |  User launches and plays through the Call of Duty: Modern Warfare II single-player campaign across multiple missions including Strike, Kill or Capture, Wetwork, Tradecraft, Borderline, and Cartel Protection. Session spans game launch, menu navigation, and sustained FPS gameplay across varied environments.  |  [ "cod-mw2", "fps", "campaign", "single-player", "gaming", "risk:game_simulator", "conf:0.82" ]  |  110.67  |  6,640,367  |  186,805  |  cod-mw2/17b680bf-7418-4955-9b94-4281402d8e7a/clip.mp4  |  cod-mw2/17b680bf-7418-4955-9b94-4281402d8e7a/events.json  |  cod-mw2/17b680bf-7418-4955-9b94-4281402d8e7a/frame_events.json  |  cod-mw2/17b680bf-7418-4955-9b94-4281402d8e7a/metadata.json  |  
|  c18187bb-53c8-435a-bb53-c43dd81d4d03  |  Palworld  |  gaming  |  windows  |  Palworld Extended Gameplay Session  |  User plays Palworld across an extended session involving open-world exploration, combat with bosses and wild Pals, dungeon runs, crafting, inventory management, base building, and occasional browser research to look up game information. Activity spans multiple biomes and game systems with sustained active engagement.  |  [ "palworld", "survival", "creature-collection", "crafting", "exploration", "combat", "boss-fights", "risk:game_simulator", "conf:0.78" ]  |  109.83  |  6,590,000  |  310,166  |  palworld/c18187bb-53c8-435a-bb53-c43dd81d4d03/clip.mp4  |  palworld/c18187bb-53c8-435a-bb53-c43dd81d4d03/events.json  |  palworld/c18187bb-53c8-435a-bb53-c43dd81d4d03/frame_events.json  |  palworld/c18187bb-53c8-435a-bb53-c43dd81d4d03/metadata.json  |  
|  018b5d9e-9860-45c8-a750-6e0a70f6c992  |  Palworld  |  gaming  |  windows  |  Palworld Extended Gameplay Session  |  User plays Palworld across a full session covering exploration, base building, crafting, inventory management, boss battles, and creature collection. Activity spans multiple game systems including technology trees, fast travel, Pal party management, and progressive base upgrades.  |  [ "palworld", "survival", "creature-collection", "base-building", "boss-battles", "exploration", "risk:game_simulator", "conf:0.82" ]  |  109.82  |  6,589,033  |  287,221  |  palworld/018b5d9e-9860-45c8-a750-6e0a70f6c992/clip.mp4  |  palworld/018b5d9e-9860-45c8-a750-6e0a70f6c992/events.json  |  palworld/018b5d9e-9860-45c8-a750-6e0a70f6c992/frame_events.json  |  palworld/018b5d9e-9860-45c8-a750-6e0a70f6c992/metadata.json  |  
|  3bebd238-0f55-4265-9853-df5db7f38a72  |  Valorant  |  gaming  |  windows  |  VALORANT competitive and deathmatch gameplay  |  User plays multiple rounds of VALORANT across competitive ranked matches and a deathmatch session, including agent selection, buy phases, combat, and post-match screens. Active FPS gameplay with sustained movement, aiming, and ability usage throughout.  |  [ "valorant", "fps", "competitive", "ranked", "deathmatch", "risk:game_simulator", "conf:0.75" ]  |  108.62  |  6,517,400  |  216,983  |  valorant/3bebd238-0f55-4265-9853-df5db7f38a72/clip.mp4  |  valorant/3bebd238-0f55-4265-9853-df5db7f38a72/events.json  |  valorant/3bebd238-0f55-4265-9853-df5db7f38a72/frame_events.json  |  valorant/3bebd238-0f55-4265-9853-df5db7f38a72/metadata.json  |  
|  9b42164b-9575-4b2d-b07a-550da39f32b8  |  Palworld  |  gaming  |  windows  |  Palworld Extended Gameplay Session  |  User plays Palworld across an extended session involving combat, boss battles, exploration, inventory management, creature collection, and base building. Activity is sustained but primarily recreational gaming with no productive software work.  |  [ "palworld", "gaming", "survival", "creature-collection", "boss-battles", "risk:game_simulator", "risk:kuro_self_reference", "conf:0.82" ]  |  105.73  |  6,344,067  |  278,852  |  palworld/9b42164b-9575-4b2d-b07a-550da39f32b8/clip.mp4  |  palworld/9b42164b-9575-4b2d-b07a-550da39f32b8/events.json  |  palworld/9b42164b-9575-4b2d-b07a-550da39f32b8/frame_events.json  |  palworld/9b42164b-9575-4b2d-b07a-550da39f32b8/metadata.json  |  
|  17ee57ca-56d6-4bd3-b985-428bca7b3a16  |  Grand Theft Auto V  |  gaming  |  windows  |  Grand Theft Auto V Extended Play Session  |  User plays Grand Theft Auto V for an extended session covering story missions, open-world driving, combat sequences, and idle map viewing. Activity includes yoga minigames, assassination missions, surreal combat sequences, and general open-world exploration with cheat codes.  |  [ "gta-v", "open-world", "driving", "combat", "missions", "risk:game_simulator", "risk:passive_low_active", "conf:0.92" ]  |  105.4  |  6,323,833  |  142,574  |  grand-theft-auto-v/17ee57ca-56d6-4bd3-b985-428bca7b3a16/clip.mp4  |  grand-theft-auto-v/17ee57ca-56d6-4bd3-b985-428bca7b3a16/events.json  |  grand-theft-auto-v/17ee57ca-56d6-4bd3-b985-428bca7b3a16/frame_events.json  |  grand-theft-auto-v/17ee57ca-56d6-4bd3-b985-428bca7b3a16/metadata.json  |  
|  1ce8c902-d4e5-4de0-a848-9b5669dd1812  |  Palworld  |  gaming  |  windows  |  Palworld Extended Gameplay Session  |  Extended Palworld gaming session covering exploration, combat, base management, crafting, inventory organization, creature capture, and boss fights. Includes brief browser research on game mechanics and breeding combinations as supporting context.  |  [ "palworld", "survival", "creature-collection", "base-management", "combat", "risk:game_simulator", "conf:0.82" ]  |  104.85  |  6,291,033  |  274,604  |  palworld/1ce8c902-d4e5-4de0-a848-9b5669dd1812/clip.mp4  |  palworld/1ce8c902-d4e5-4de0-a848-9b5669dd1812/events.json  |  palworld/1ce8c902-d4e5-4de0-a848-9b5669dd1812/frame_events.json  |  palworld/1ce8c902-d4e5-4de0-a848-9b5669dd1812/metadata.json  |  
|  80761419-d3a1-406b-99ef-ab51829e81ed  |  Grand Theft Auto V  |  gaming  |  windows  |  Grand Theft Auto V Session — Launch, Exploration, and Missions  |  User launches GTA V via Steam and spends the entire session in open-world gameplay including driving, combat, cheat code usage, weapon shopping, and story missions. Activity is recreational gaming with no productive output.  |  [ "gta-v", "steam", "open-world", "driving", "missions", "cheats", "risk:game_simulator", "risk:passive_low_active", "conf:0.92" ]  |  104.67  |  6,280,133  |  116,510  |  grand-theft-auto-v/80761419-d3a1-406b-99ef-ab51829e81ed/clip.mp4  |  grand-theft-auto-v/80761419-d3a1-406b-99ef-ab51829e81ed/events.json  |  grand-theft-auto-v/80761419-d3a1-406b-99ef-ab51829e81ed/frame_events.json  |  grand-theft-auto-v/80761419-d3a1-406b-99ef-ab51829e81ed/metadata.json  |  
|  c7cd7174-ebab-431e-b0b2-38c592bf1bdf  |  Need for Speed  |  gaming  |  windows  |  Need for Speed Payback Extended Gameplay Session  |  User plays Need for Speed Payback for an extended session spanning approximately 90 minutes, completing races, drift challenges, police chases, open-world driving, and menu navigation across desert, city, and mountain environments. No productive software work is present.  |  [ "need-for-speed", "racing", "nfs-payback", "gaming", "risk:game_simulator", "conf:0.25" ]  |  104.05  |  6,242,767  |  34,199  |  need-for-speed/c7cd7174-ebab-431e-b0b2-38c592bf1bdf/clip.mp4  |  need-for-speed/c7cd7174-ebab-431e-b0b2-38c592bf1bdf/events.json  |  need-for-speed/c7cd7174-ebab-431e-b0b2-38c592bf1bdf/frame_events.json  |  need-for-speed/c7cd7174-ebab-431e-b0b2-38c592bf1bdf/metadata.json  |  
|  91edc0e4-4406-46d4-9678-9a471613533f  |  Minecraft  |  gaming  |  windows  |  Minecraft Multiplayer Survival Gameplay  |  Extended Minecraft Java Edition multiplayer session involving exploration, resource gathering, combat, farming, trading with villagers, and base management across a third-party server. Gameplay is sustained but routine survival activities without a focused construction or redstone goal.  |  [ "minecraft", "multiplayer", "survival", "farming", "combat", "exploration", "risk:game_simulator", "conf:0.82" ]  |  102.86  |  6,171,500  |  188,940  |  minecraft/91edc0e4-4406-46d4-9678-9a471613533f/clip.mp4  |  minecraft/91edc0e4-4406-46d4-9678-9a471613533f/events.json  |  minecraft/91edc0e4-4406-46d4-9678-9a471613533f/frame_events.json  |  minecraft/91edc0e4-4406-46d4-9678-9a471613533f/metadata.json  |  
|  1fc6679e-39bb-45e2-8b3f-35e47259c1bd  |  Valorant  |  gaming  |  windows  |  VALORANT Competitive Multiplayer Sessions  |  Extended VALORANT competitive gameplay across multiple matches including agent selection, buy phases, active combat rounds, and match transitions. Covers two full match sessions on Split and Lotus/Fracture/Ascent maps with no productive work output.  |  [ "valorant", "fps", "competitive", "gaming", "risk:game_simulator", "risk:kuro_self_reference", "conf:0.92" ]  |  102.26  |  6,135,500  |  243,789  |  valorant/1fc6679e-39bb-45e2-8b3f-35e47259c1bd/clip.mp4  |  valorant/1fc6679e-39bb-45e2-8b3f-35e47259c1bd/events.json  |  valorant/1fc6679e-39bb-45e2-8b3f-35e47259c1bd/frame_events.json  |  valorant/1fc6679e-39bb-45e2-8b3f-35e47259c1bd/metadata.json  |  
|  293aced1-901d-4dad-b3de-2002dff5a8b6  |  Valorant  |  gaming  |  windows  |  VALORANT competitive and deathmatch gameplay sessions  |  User plays sustained VALORANT matches including deathmatch and competitive modes, demonstrating active FPS gameplay with movement, shooting, ability usage, weapon purchasing, and round progression across multiple maps including Haven and Breeze.  |  [ "valorant", "fps", "competitive", "deathmatch", "risk:game_simulator", "conf:0.82" ]  |  101.46  |  6,087,433  |  318,273  |  valorant/293aced1-901d-4dad-b3de-2002dff5a8b6/clip.mp4  |  valorant/293aced1-901d-4dad-b3de-2002dff5a8b6/events.json  |  valorant/293aced1-901d-4dad-b3de-2002dff5a8b6/frame_events.json  |  valorant/293aced1-901d-4dad-b3de-2002dff5a8b6/metadata.json  |  
|  7fb1515e-fdd9-4f5b-9e72-769fc40cd46e  |  Minecraft  |  gaming  |  windows  |  Minecraft PvP multiplayer session (main block)  |  Extended Minecraft PvP combat session on a multiplayer server using Lunar Client, featuring FFA duels, practice arena fights, sword combat, inventory management, and team chat interactions across many rounds.  |  [ "minecraft", "pvp", "lunar-client", "multiplayer", "combat", "ffa", "risk:game_simulator", "conf:0.83" ]  |  100.63  |  6,037,800  |  181,591  |  minecraft/7fb1515e-fdd9-4f5b-9e72-769fc40cd46e/clip.mp4  |  minecraft/7fb1515e-fdd9-4f5b-9e72-769fc40cd46e/events.json  |  minecraft/7fb1515e-fdd9-4f5b-9e72-769fc40cd46e/frame_events.json  |  minecraft/7fb1515e-fdd9-4f5b-9e72-769fc40cd46e/metadata.json  |  
|  b8f79af4-6736-4e69-9259-406f748111af  |  Grand Theft Auto V  |  gaming  |  windows  |  GTA V Open-World Free Roam and Gameplay  |  Extended recreational GTA V gameplay session covering open-world free roam, driving, combat, vehicle customization at Los Santos Customs, heist missions, and map navigation with no productive output or artifact creation.  |  [ "gta-v", "free-roam", "driving", "combat", "vehicle-customization", "heist", "risk:game_simulator", "risk:passive_low_active", "risk:no_clear_goal", "conf:0.82" ]  |  99.8  |  5,988,167  |  86,323  |  grand-theft-auto-v/b8f79af4-6736-4e69-9259-406f748111af/clip.mp4  |  grand-theft-auto-v/b8f79af4-6736-4e69-9259-406f748111af/events.json  |  grand-theft-auto-v/b8f79af4-6736-4e69-9259-406f748111af/frame_events.json  |  grand-theft-auto-v/b8f79af4-6736-4e69-9259-406f748111af/metadata.json  |  
|  380f1654-e4f7-4221-9bdd-cac924a555da  |  Nfs Underground 2  |  gaming  |  windows  |  Need for Speed Underground 2 Free-Roam Session  |  Extended session of playing Need for Speed Underground 2, with the player free-roaming through a nighttime city environment using keyboard controls for steering, acceleration, and braking. No productive work output; purely entertainment gaming activity.  |  [ "nfs-underground-2", "racing", "open-world", "gaming", "risk:game_simulator", "risk:kuro_self_reference", "conf:0.82" ]  |  99.78  |  5,986,967  |  18,950  |  nfs-underground-2/380f1654-e4f7-4221-9bdd-cac924a555da/clip.mp4  |  nfs-underground-2/380f1654-e4f7-4221-9bdd-cac924a555da/events.json  |  nfs-underground-2/380f1654-e4f7-4221-9bdd-cac924a555da/frame_events.json  |  nfs-underground-2/380f1654-e4f7-4221-9bdd-cac924a555da/metadata.json  |  
|  2f7c0d7f-1538-4c3f-84e6-67c4982c13d5  |  Call Of Duty  |  gaming  |  windows  |  Call of Duty Black Ops 6 Zombies Extended Session  |  User plays an extended session of Call of Duty Black Ops 6 Zombies mode on the Nuketown map, progressing through rounds 1–48+ with active combat, weapon upgrades, and in-game objective completion. Purely recreational gaming activity.  |  [ "call-of-duty", "black-ops-6", "zombies", "nuketown", "fps", "risk:game_simulator", "conf:0.25" ]  |  99.26  |  5,955,833  |  324,507  |  call-of-duty/2f7c0d7f-1538-4c3f-84e6-67c4982c13d5/clip.mp4  |  call-of-duty/2f7c0d7f-1538-4c3f-84e6-67c4982c13d5/events.json  |  call-of-duty/2f7c0d7f-1538-4c3f-84e6-67c4982c13d5/frame_events.json  |  call-of-duty/2f7c0d7f-1538-4c3f-84e6-67c4982c13d5/metadata.json  |  
|  e510c466-c041-4835-a94e-b01d40b8cef7  |  Palworld  |  gaming  |  windows  |  Palworld Session — Exploration, Combat, and Base Management  |  Extended Palworld gameplay session covering open-world exploration, boss combat, creature collection, base building, crafting, and inventory/Pal management across multiple in-game locations. Recreational gaming with no productive output.  |  [ "palworld", "survival", "creature-collection", "base-building", "crafting", "combat", "risk:game_simulator", "conf:0.82" ]  |  99.07  |  5,944,433  |  243,060  |  palworld/e510c466-c041-4835-a94e-b01d40b8cef7/clip.mp4  |  palworld/e510c466-c041-4835-a94e-b01d40b8cef7/events.json  |  palworld/e510c466-c041-4835-a94e-b01d40b8cef7/frame_events.json  |  palworld/e510c466-c041-4835-a94e-b01d40b8cef7/metadata.json  |  
|  754a2d9d-81ee-47a2-9ef8-90ca40256232  |  Grand Theft Auto V  |  gaming  |  windows  |  Grand Theft Auto V Open-World Gameplay Session  |  Extended GTA V session covering free-roam driving, tennis mini-game, character customization, mission completion (Paparazzo), cheat code use, and mod browsing. Predominantly recreational open-world play with no meaningful productive output.  |  [ "gta-v", "open-world", "driving", "cheats", "mods", "risk:game_simulator", "risk:passive_low_active", "conf:0.82" ]  |  98.97  |  5,937,900  |  94,358  |  grand-theft-auto-v/754a2d9d-81ee-47a2-9ef8-90ca40256232/clip.mp4  |  grand-theft-auto-v/754a2d9d-81ee-47a2-9ef8-90ca40256232/events.json  |  grand-theft-auto-v/754a2d9d-81ee-47a2-9ef8-90ca40256232/frame_events.json  |  grand-theft-auto-v/754a2d9d-81ee-47a2-9ef8-90ca40256232/metadata.json  |  
|  fcd9cd2a-cf2e-40a7-9230-1d32242b9035  |  Valorant  |  gaming  |  windows  |  VALORANT Competitive Match Sessions  |  User plays multiple competitive VALORANT matches across two maps (Lotus and Fracture/Pearl), including agent selection, buy phases, combat, and post-match navigation. Entirely recreational gaming with no productive output.  |  [ "valorant", "fps", "competitive", "chamber", "risk:game_simulator", "conf:0.15" ]  |  95.72  |  5,743,233  |  271,515  |  valorant/fcd9cd2a-cf2e-40a7-9230-1d32242b9035/clip.mp4  |  valorant/fcd9cd2a-cf2e-40a7-9230-1d32242b9035/events.json  |  valorant/fcd9cd2a-cf2e-40a7-9230-1d32242b9035/frame_events.json  |  valorant/fcd9cd2a-cf2e-40a7-9230-1d32242b9035/metadata.json  |  
|  3296894b-3394-420a-acc9-7ea633f26e3a  |  Valorant  |  gaming  |  windows  |  VALORANT Gaming Session  |  Extended VALORANT gaming session including lobby management, agent selection, custom skirmish matches, competitive play, and cosmetic customization. User plays multiple rounds across various maps with teammates.  |  [ "valorant", "fps", "gaming", "multiplayer", "risk:game_simulator", "conf:0.88" ]  |  95.65  |  5,738,900  |  129,753  |  valorant/3296894b-3394-420a-acc9-7ea633f26e3a/clip.mp4  |  valorant/3296894b-3394-420a-acc9-7ea633f26e3a/events.json  |  valorant/3296894b-3394-420a-acc9-7ea633f26e3a/frame_events.json  |  valorant/3296894b-3394-420a-acc9-7ea633f26e3a/metadata.json  |  
|  a285f0be-5266-4412-ac3d-35933d8198ac  |  The Finals  |  gaming  |  windows  |  Playing The Finals (FPS) — Full Session  |  User launches and plays the first-person shooter game 'The Finals' across an extended session including Quick Cash matches, Team Deathmatch rounds, private lobbies, and in-game store browsing. Activity spans game launch through exit, with sustained but routine FPS gameplay.  |  [ "the-finals", "fps", "team-deathmatch", "quick-cash", "steam", "risk:game_simulator", "risk:passive_low_active", "conf:0.82" ]  |  95.17  |  5,710,467  |  1,755,224  |  the-finals/a285f0be-5266-4412-ac3d-35933d8198ac/clip.mp4  |  the-finals/a285f0be-5266-4412-ac3d-35933d8198ac/events.json  |  the-finals/a285f0be-5266-4412-ac3d-35933d8198ac/frame_events.json  |  the-finals/a285f0be-5266-4412-ac3d-35933d8198ac/metadata.json  |  
|  10a41ad2-97e1-4958-aac5-3758f1382719  |  Avatar Frontiers Of Pandora  |  gaming  |  windows  |  Avatar: Frontiers of Pandora – Setup, Loading, and Gameplay  |  User launches Avatar: Frontiers of Pandora, configures settings, watches extended loading screens and cutscenes, creates a character, and does minimal gameplay exploration. The session is dominated by idle menu time, loading screens, and passive cutscene viewing with virtually no active input.  |  [ "avatar-frontiers-of-pandora", "ubisoft-connect", "gaming", "idle", "character-creation", "risk:game_simulator", "risk:passive_low_active", "risk:no_clear_goal", "conf:0.20" ]  |  93.67  |  5,619,900  |  807  |  avatar-frontiers-of-pandora/10a41ad2-97e1-4958-aac5-3758f1382719/clip.mp4  |  avatar-frontiers-of-pandora/10a41ad2-97e1-4958-aac5-3758f1382719/events.json  |  avatar-frontiers-of-pandora/10a41ad2-97e1-4958-aac5-3758f1382719/frame_events.json  |  avatar-frontiers-of-pandora/10a41ad2-97e1-4958-aac5-3758f1382719/metadata.json  |  
|  3e263e39-8ff1-4a4a-b2bc-5dcca6c352ba  |  Far Cry 5  |  gaming  |  windows  |  Far Cry 5 Open-World Gameplay Session  |  Extended Far Cry 5 gaming session covering open-world exploration, combat missions, vehicle driving, plane piloting, stealth encounters, and story progression through John Seed's region. Includes active gameplay segments, cutscenes, and mission completion across the full session.  |  [ "far-cry-5", "fps", "open-world", "ubisoft", "gaming", "risk:game_simulator", "conf:0.92" ]  |  92.92  |  5,575,467  |  237,776  |  far-cry-5/3e263e39-8ff1-4a4a-b2bc-5dcca6c352ba/clip.mp4  |  far-cry-5/3e263e39-8ff1-4a4a-b2bc-5dcca6c352ba/events.json  |  far-cry-5/3e263e39-8ff1-4a4a-b2bc-5dcca6c352ba/frame_events.json  |  far-cry-5/3e263e39-8ff1-4a4a-b2bc-5dcca6c352ba/metadata.json  |  
|  4ef0ed03-0352-4a6e-87d9-ad5fefb06448  |  Grand Theft Auto V  |  gaming  |  windows  |  Grand Theft Auto V Story Mode Playthrough  |  Extended GTA V story mode session covering game launch, open-world exploration, driving, combat, heist planning, and mission progression across Los Santos and Sandy Shores. Includes the Jewel Store Job heist arc from reconnaissance through completion, followed by Trevor's introduction missions.  |  [ "gta-v", "story-mode", "heist", "open-world", "missions", "risk:game_simulator", "conf:0.82" ]  |  92.07  |  5,524,200  |  97,613  |  grand-theft-auto-v/4ef0ed03-0352-4a6e-87d9-ad5fefb06448/clip.mp4  |  grand-theft-auto-v/4ef0ed03-0352-4a6e-87d9-ad5fefb06448/events.json  |  grand-theft-auto-v/4ef0ed03-0352-4a6e-87d9-ad5fefb06448/frame_events.json  |  grand-theft-auto-v/4ef0ed03-0352-4a6e-87d9-ad5fefb06448/metadata.json  |  
|  2509ee4d-84c2-4f4a-8b63-5d6c1e70f3af  |  The Finals  |  gaming  |  windows  |  The Finals FPS Multiplayer Sessions  |  User launches and plays multiple sessions of The Finals, a competitive first-person shooter, across Quick Cash and Team Deathmatch modes. Activity includes game launch, menu navigation, character customization, matchmaking, and sustained active gameplay across numerous matches.  |  [ "the-finals", "fps", "multiplayer", "quick-cash", "team-deathmatch", "risk:game_simulator", "conf:0.82" ]  |  91.28  |  5,476,933  |  1,638,408  |  the-finals/2509ee4d-84c2-4f4a-8b63-5d6c1e70f3af/clip.mp4  |  the-finals/2509ee4d-84c2-4f4a-8b63-5d6c1e70f3af/events.json  |  the-finals/2509ee4d-84c2-4f4a-8b63-5d6c1e70f3af/frame_events.json  |  the-finals/2509ee4d-84c2-4f4a-8b63-5d6c1e70f3af/metadata.json  |  
|  a606c8da-c65d-4443-8811-6d8da5208e4a  |  Farming Simulator  |  gaming  |  windows  |  Farming Simulator 18 Extended Gameplay Session  |  User plays Farming Simulator 18 for an extended session, driving tractors, harvesters, and trucks around a farm environment, performing tasks like plowing, harvesting, and deliveries. Activity is entirely recreational gaming with no productive software work output.  |  [ "farming-simulator", "gaming", "simulation", "recreational", "risk:game_simulator", "conf:0.92" ]  |  91.01  |  5,460,333  |  102,006  |  farming-simulator/a606c8da-c65d-4443-8811-6d8da5208e4a/clip.mp4  |  farming-simulator/a606c8da-c65d-4443-8811-6d8da5208e4a/events.json  |  farming-simulator/a606c8da-c65d-4443-8811-6d8da5208e4a/frame_events.json  |  farming-simulator/a606c8da-c65d-4443-8811-6d8da5208e4a/metadata.json  |  
|  68db38db-9041-4bd4-8902-b570fec90c14  |  Assassins Creed Odyssey  |  gaming  |  windows  |  Assassin's Creed Odyssey – Launcher, Menu, and Gameplay  |  User launches Assassin's Creed Odyssey via Xbox app and Ubisoft Connect, navigates menus, and plays through the Penelope's Shroud quest with extended idle periods on title screens and menus. Session is overwhelmingly idle (99%) with very low input density throughout.  |  [ "assassins-creed-odyssey", "ubisoft-connect", "xbox-app", "gaming", "idle", "risk:game_simulator", "risk:passive_low_active", "risk:no_clear_goal", "conf:0.20" ]  |  90.91  |  5,454,767  |  522  |  assassins-creed-odyssey/68db38db-9041-4bd4-8902-b570fec90c14/clip.mp4  |  assassins-creed-odyssey/68db38db-9041-4bd4-8902-b570fec90c14/events.json  |  assassins-creed-odyssey/68db38db-9041-4bd4-8902-b570fec90c14/frame_events.json  |  assassins-creed-odyssey/68db38db-9041-4bd4-8902-b570fec90c14/metadata.json  |  
|  0b08ff9b-b568-4be2-b3a3-e2363f903b81  |  Counter-Strike 2  |  gaming  |  windows  |  Counter-Strike 2 Competitive Match Session  |  Extended CS2 competitive gameplay session on Dust II, spanning match preparation, multiple rounds of active FPS gameplay including weapon purchasing, combat, bomb planting, and post-match review. Includes two full matches ending in a 7-13 defeat and a 13-11 victory.  |  [ "cs2", "counter-strike", "fps", "competitive", "dust2", "risk:game_simulator", "conf:0.85" ]  |  90.66  |  5,439,833  |  185,547  |  counter-strike-2/0b08ff9b-b568-4be2-b3a3-e2363f903b81/clip.mp4  |  counter-strike-2/0b08ff9b-b568-4be2-b3a3-e2363f903b81/events.json  |  counter-strike-2/0b08ff9b-b568-4be2-b3a3-e2363f903b81/frame_events.json  |  counter-strike-2/0b08ff9b-b568-4be2-b3a3-e2363f903b81/metadata.json  |  
|  90bc562f-213a-4a84-9265-d3878c8e49f3  |  Asphalt 9  |  gaming  |  windows  |  Extended Asphalt 9: Legends racing session  |  User plays Asphalt 9: Legends across many races and events, including multiplayer races, Star Hunt and Prototype Racing events, car upgrades, shop browsing, and ad-watching to refill car timers. Sustained entertainment gaming with no productive output.  |  [ "asphalt9", "racing", "gaming", "multiplayer", "risk:game_simulator", "conf:0.82" ]  |  89.7  |  5,382,167  |  67,307  |  asphalt-9/90bc562f-213a-4a84-9265-d3878c8e49f3/clip.mp4  |  asphalt-9/90bc562f-213a-4a84-9265-d3878c8e49f3/events.json  |  asphalt-9/90bc562f-213a-4a84-9265-d3878c8e49f3/frame_events.json  |  asphalt-9/90bc562f-213a-4a84-9265-d3878c8e49f3/metadata.json  |  
|  c70a8646-5d9d-4bd6-bd6b-d581224b1435  |  Fears To Fathom  |  gaming  |  windows  |  Fears to Fathom: Ironbark Lookout Playthrough  |  User launches and plays through the horror game 'Fears to Fathom: Ironbark Lookout' via Steam, progressing through driving sequences, diner interactions, forest exploration, lookout tower puzzles, retro computer terminals, and narrative horror events. Includes sustained engagement with game mechanics and story progress...  |  [ "fears-to-fathom", "horror", "narrative", "steam", "risk:game_simulator", "conf:0.85" ]  |  88.62  |  5,316,933  |  157,583  |  fears-to-fathom/c70a8646-5d9d-4bd6-bd6b-d581224b1435/clip.mp4  |  fears-to-fathom/c70a8646-5d9d-4bd6-bd6b-d581224b1435/events.json  |  fears-to-fathom/c70a8646-5d9d-4bd6-bd6b-d581224b1435/frame_events.json  |  fears-to-fathom/c70a8646-5d9d-4bd6-bd6b-d581224b1435/metadata.json  |  
|  9bde066f-3d40-4c4f-b9f9-ae2dfabc4630  |  Grand Theft Auto San Andreas  |  gaming  |  windows  |  GTA SA-MP Roleplay Session  |  Extended GTA San Andreas Multiplayer roleplay session spanning combat, driving, flying, social chat, and idle standing across a roleplay server. Activity ranges from active combat and vehicle control to passive standing and text chat with other players.  |  [ "gta-sa", "sa-mp", "roleplay", "multiplayer", "combat", "driving", "risk:game_simulator", "conf:0.82" ]  |  88.09  |  5,285,267  |  92,231  |  grand-theft-auto-san-andreas/9bde066f-3d40-4c4f-b9f9-ae2dfabc4630/clip.mp4  |  grand-theft-auto-san-andreas/9bde066f-3d40-4c4f-b9f9-ae2dfabc4630/events.json  |  grand-theft-auto-san-andreas/9bde066f-3d40-4c4f-b9f9-ae2dfabc4630/frame_events.json  |  grand-theft-auto-san-andreas/9bde066f-3d40-4c4f-b9f9-ae2dfabc4630/metadata.json  |  
|  ca992fbf-dd7a-4a7c-b1a1-e5159ef8bfc3  |  Valorant  |  gaming  |  windows  |  VALORANT Session – Lobbying, Queuing, and Gameplay  |  Extended VALORANT gaming session covering party setup, queue waiting, agent selection, and multiple rounds of competitive and casual gameplay across several maps. Activity is recreational FPS gaming with no productive output.  |  [ "valorant", "fps", "competitive", "omen", "spike-rush", "risk:game_simulator", "conf:0.82" ]  |  87.92  |  5,275,267  |  115,711  |  valorant/ca992fbf-dd7a-4a7c-b1a1-e5159ef8bfc3/clip.mp4  |  valorant/ca992fbf-dd7a-4a7c-b1a1-e5159ef8bfc3/events.json  |  valorant/ca992fbf-dd7a-4a7c-b1a1-e5159ef8bfc3/frame_events.json  |  valorant/ca992fbf-dd7a-4a7c-b1a1-e5159ef8bfc3/metadata.json  |  
|  a26cad9c-6714-42c8-980e-2f76886747fb  |  Minecraft  |  gaming  |  windows  |  Minecraft PvP Multiplayer Gameplay  |  User plays Minecraft PvP combat on a multiplayer server using Lunar Client, engaging in sword fights, using potions and items, managing inventory, and chatting with other players across multiple sessions.  |  [ "minecraft", "pvp", "lunar-client", "multiplayer", "risk:game_simulator", "conf:0.82" ]  |  87.52  |  5,251,167  |  134,594  |  minecraft/a26cad9c-6714-42c8-980e-2f76886747fb/clip.mp4  |  minecraft/a26cad9c-6714-42c8-980e-2f76886747fb/events.json  |  minecraft/a26cad9c-6714-42c8-980e-2f76886747fb/frame_events.json  |  minecraft/a26cad9c-6714-42c8-980e-2f76886747fb/metadata.json  |  
|  e83ec540-d75c-4b9a-8bbb-5e45c1ff60bd  |  The Finals  |  gaming  |  windows  |  The Finals — Active Gameplay Sessions  |  User plays multiple matches of The Finals, a competitive first-person shooter, across extended sessions. Activity includes lobby setup, loadout customization, party management, and sustained in-game combat with movement, aiming, shooting, and objective play.  |  [ "the-finals", "fps", "competitive", "steam", "quick-cash", "team-deathmatch", "risk:game_simulator", "conf:0.75" ]  |  86.98  |  5,218,900  |  1,526,450  |  the-finals/e83ec540-d75c-4b9a-8bbb-5e45c1ff60bd/clip.mp4  |  the-finals/e83ec540-d75c-4b9a-8bbb-5e45c1ff60bd/events.json  |  the-finals/e83ec540-d75c-4b9a-8bbb-5e45c1ff60bd/frame_events.json  |  the-finals/e83ec540-d75c-4b9a-8bbb-5e45c1ff60bd/metadata.json  |  
|  a707b859-96b8-48ca-a37f-c0f132d86607  |  Pokemon  |  gaming  |  windows  |  Pokemon Z Fan Game Playthrough  |  Extended session playing Pokemon Z, a fan-made Pokemon RPG built on mkxp-z. Activity spans overworld exploration, turn-based battles, party management, item collection, NPC dialogue, and gym progression across multiple routes and towns.  |  [ "pokemon", "rpg", "fan-game", "mkxp-z", "turn-based", "risk:game_simulator", "conf:0.82" ]  |  86.9  |  5,214,000  |  27,545  |  pokemon/a707b859-96b8-48ca-a37f-c0f132d86607/clip.mp4  |  pokemon/a707b859-96b8-48ca-a37f-c0f132d86607/events.json  |  pokemon/a707b859-96b8-48ca-a37f-c0f132d86607/frame_events.json  |  pokemon/a707b859-96b8-48ca-a37f-c0f132d86607/metadata.json  |  
|  4c795de1-bc77-41fe-9a58-fe5996468ee7  |  Assassins Creed Syndicate  |  gaming  |  windows  |  Assassin's Creed Syndicate Gameplay Session 1  |  Extended gameplay session in Assassin's Creed Syndicate covering multiple missions including child liberation, kidnapping targets, escorting Henry, and Charles Dickens side missions through Victorian London environments.  |  [ "assassins-creed-syndicate", "action-adventure", "gaming", "risk:game_simulator", "conf:0.82" ]  |  86.01  |  5,160,333  |  216,752  |  assassins-creed-syndicate/4c795de1-bc77-41fe-9a58-fe5996468ee7/clip.mp4  |  assassins-creed-syndicate/4c795de1-bc77-41fe-9a58-fe5996468ee7/events.json  |  assassins-creed-syndicate/4c795de1-bc77-41fe-9a58-fe5996468ee7/frame_events.json  |  assassins-creed-syndicate/4c795de1-bc77-41fe-9a58-fe5996468ee7/metadata.json  |  
|  b860f766-4b91-446c-b333-c99456ae2d50  |  Assassins Creed  |  gaming  |  windows  |  Assassin's Creed IV Black Flag Playthrough  |  Extended gameplay session of Assassin's Creed IV Black Flag covering multiple missions including jungle combat, naval battles, stealth assassinations, and story progression through to end credits. Includes active gameplay, cutscenes, and mission completion sequences.  |  [ "assassins-creed", "ac4", "black-flag", "ubisoft", "action-adventure", "risk:game_simulator", "conf:0.82" ]  |  85.77  |  5,146,333  |  224,556  |  assassins-creed/b860f766-4b91-446c-b333-c99456ae2d50/clip.mp4  |  assassins-creed/b860f766-4b91-446c-b333-c99456ae2d50/events.json  |  assassins-creed/b860f766-4b91-446c-b333-c99456ae2d50/frame_events.json  |  assassins-creed/b860f766-4b91-446c-b333-c99456ae2d50/metadata.json  |  
|  b79d3019-7449-41c3-8aa8-57fe08509860  |  007 First Light  |  gaming  |  windows  |  007 First Light Extended Gameplay Session  |  User plays through an extended session of 007 First Light, progressing through stealth missions, combat sequences, vehicle sections, and story cutscenes across multiple levels of the James Bond game.  |  [ "007-first-light", "james-bond", "stealth", "action", "shooter", "gameplay", "risk:game_simulator", "conf:0.87" ]  |  85.66  |  5,139,333  |  146,485  |  007-first-light/b79d3019-7449-41c3-8aa8-57fe08509860/clip.mp4  |  007-first-light/b79d3019-7449-41c3-8aa8-57fe08509860/events.json  |  007-first-light/b79d3019-7449-41c3-8aa8-57fe08509860/frame_events.json  |  007-first-light/b79d3019-7449-41c3-8aa8-57fe08509860/metadata.json  |  
|  0fb789e6-cd07-4e43-a2f1-3bed77b8d6ae  |  The Last Of Us  |  gaming  |  windows  |  The Last of Us Part I gameplay and story progression  |  User plays through The Last of Us Part I, engaging in combat, exploration, stealth, horseback riding, and story cutscenes across multiple chapters. Gameplay is a mix of active combat segments and passive narrative viewing.  |  [ "the-last-of-us", "action-adventure", "single-player", "story", "risk:game_simulator", "risk:passive_low_active", "conf:0.85" ]  |  84.87  |  5,092,033  |  1,323  |  the-last-of-us/0fb789e6-cd07-4e43-a2f1-3bed77b8d6ae/clip.mp4  |  the-last-of-us/0fb789e6-cd07-4e43-a2f1-3bed77b8d6ae/events.json  |  the-last-of-us/0fb789e6-cd07-4e43-a2f1-3bed77b8d6ae/frame_events.json  |  the-last-of-us/0fb789e6-cd07-4e43-a2f1-3bed77b8d6ae/metadata.json  |  
|  ced1e31e-54e0-4313-93db-4f828a3c6912  |  Farming Simulator  |  gaming  |  windows  |  Farming Simulator 18 Extended Gameplay Session  |  User plays Farming Simulator 18 for an extended session (~75 minutes), performing farming tasks including tilling, seeding, harvesting, equipment management, field purchases, and delivery quests. This is recreational gaming with no productive output.  |  [ "farming-simulator", "gaming", "simulation", "android-emulator", "risk:game_simulator", "conf:0.15" ]  |  84.78  |  5,086,800  |  158,361  |  farming-simulator/ced1e31e-54e0-4313-93db-4f828a3c6912/clip.mp4  |  farming-simulator/ced1e31e-54e0-4313-93db-4f828a3c6912/events.json  |  farming-simulator/ced1e31e-54e0-4313-93db-4f828a3c6912/frame_events.json  |  farming-simulator/ced1e31e-54e0-4313-93db-4f828a3c6912/metadata.json  |  
|  f5494902-25a1-4c21-9582-42e4abb3d984  |  Valorant  |  gaming  |  windows  |  Extended VALORANT Competitive Session  |  User plays multiple VALORANT competitive and unrated matches over an extended session, including agent selection, active combat rounds, buy phases, post-match lobbies, and matchmaking. Activity is sustained FPS gaming with high input density throughout.  |  [ "valorant", "fps", "competitive", "multiplayer", "risk:game_simulator", "conf:0.82" ]  |  84.53  |  5,071,500  |  239,520  |  valorant/f5494902-25a1-4c21-9582-42e4abb3d984/clip.mp4  |  valorant/f5494902-25a1-4c21-9582-42e4abb3d984/events.json  |  valorant/f5494902-25a1-4c21-9582-42e4abb3d984/frame_events.json  |  valorant/f5494902-25a1-4c21-9582-42e4abb3d984/metadata.json  |  
|  f12a0f63-1cf7-42d3-a4d0-fb4905a6223d  |  Valorant  |  gaming  |  windows  |  VALORANT Competitive Match Session  |  Extended VALORANT gaming session spanning multiple competitive matches, including launcher startup, agent selection, active gameplay rounds with combat and weapon purchasing, and post-match screens. Pure entertainment gaming with no productive software work.  |  [ "valorant", "fps", "competitive", "riot-games", "risk:game_simulator", "risk:kuro_self_reference", "conf:0.92" ]  |  82.97  |  4,978,433  |  152,864  |  valorant/f12a0f63-1cf7-42d3-a4d0-fb4905a6223d/clip.mp4  |  valorant/f12a0f63-1cf7-42d3-a4d0-fb4905a6223d/events.json  |  valorant/f12a0f63-1cf7-42d3-a4d0-fb4905a6223d/frame_events.json  |  valorant/f12a0f63-1cf7-42d3-a4d0-fb4905a6223d/metadata.json  |  
|  012842c1-1c30-4c03-b99a-f5d6fa30cda6  |  Valorant  |  gaming  |  windows  |  Extended VALORANT competitive gameplay session  |  User plays multiple rounds of VALORANT competitive matches over an extended session, including match queuing, agent selection, active combat, and post-match review. Sustained FPS gameplay with consistent WASD movement, aiming, shooting, and ability usage throughout.  |  [ "valorant", "fps", "competitive", "multiplayer", "risk:game_simulator", "conf:0.95" ]  |  82.54  |  4,952,433  |  249,804  |  valorant/012842c1-1c30-4c03-b99a-f5d6fa30cda6/clip.mp4  |  valorant/012842c1-1c30-4c03-b99a-f5d6fa30cda6/events.json  |  valorant/012842c1-1c30-4c03-b99a-f5d6fa30cda6/frame_events.json  |  valorant/012842c1-1c30-4c03-b99a-f5d6fa30cda6/metadata.json  |  
|  48ba81a7-9f5c-48fd-be60-94323674694b  |  Road 96  |  gaming  |  windows  |  Road 96 narrative adventure gameplay  |  User launches and plays the narrative adventure game Road 96 across an extended session, progressing through story sequences, dialogue choices, minigames, and environmental exploration. Occasional switches to YouTube ASMR and Reddit for game strategy occur throughout.  |  [ "road-96", "narrative-game", "adventure", "steam", "story", "risk:game_simulator", "risk:passive_low_active", "conf:0.78" ]  |  82.38  |  4,942,600  |  73,658  |  road-96/48ba81a7-9f5c-48fd-be60-94323674694b/clip.mp4  |  road-96/48ba81a7-9f5c-48fd-be60-94323674694b/events.json  |  road-96/48ba81a7-9f5c-48fd-be60-94323674694b/frame_events.json  |  road-96/48ba81a7-9f5c-48fd-be60-94323674694b/metadata.json  |  
|  bcc3e79a-4b78-454f-a48b-26b4dd8c585b  |  Forza Horizon  |  gaming  |  windows  |  Forza Horizon 6 Extended Play Session  |  User plays Forza Horizon 6 across an extended session involving open-world driving, racing events, car collection management, menu navigation, and exploration. Activity is predominantly entertainment gaming with no productive or educational value.  |  [ "forza-horizon", "racing", "open-world", "gaming", "risk:game_simulator", "risk:kuro_self_reference", "conf:0.82" ]  |  81.07  |  4,864,200  |  46,033  |  forza-horizon/bcc3e79a-4b78-454f-a48b-26b4dd8c585b/clip.mp4  |  forza-horizon/bcc3e79a-4b78-454f-a48b-26b4dd8c585b/events.json  |  forza-horizon/bcc3e79a-4b78-454f-a48b-26b4dd8c585b/frame_events.json  |  forza-horizon/bcc3e79a-4b78-454f-a48b-26b4dd8c585b/metadata.json  |  
|  600278d5-2944-4c6b-af75-4afdd79c9953  |  Minecraft  |  gaming  |  windows  |  Minecraft PvP Combat on FlowPvP Server  |  User engages in sustained Minecraft PvP gameplay on the FlowPvP server using Lunar Client, participating in duels, FFA arenas, and ranked matches with active combat, inventory management, and kit configuration. Session spans multiple combat rounds with consistent high input activity.  |  [ "minecraft", "pvp", "lunar-client", "flowpvp", "multiplayer", "combat", "risk:game_simulator", "conf:0.82" ]  |  79.48  |  4,768,933  |  159,712  |  minecraft/600278d5-2944-4c6b-af75-4afdd79c9953/clip.mp4  |  minecraft/600278d5-2944-4c6b-af75-4afdd79c9953/events.json  |  minecraft/600278d5-2944-4c6b-af75-4afdd79c9953/frame_events.json  |  minecraft/600278d5-2944-4c6b-af75-4afdd79c9953/metadata.json  |  
|  05f12848-dd5d-4fd0-807b-a8a411311ad4  |  007 First Light  |  gaming  |  windows  |  007 First Light — Extended Facility Mission with Pause Breaks  |  User resumes playing 007 First Light through extended facility missions including corridor navigation, combat, stealth sequences, and cutscenes, interspersed with long idle periods on the game's pause menu. Active gameplay segments are mixed with significant idle/paused time.  |  [ "007-first-light", "james-bond", "stealth", "combat", "gameplay", "pause-menu", "risk:game_simulator", "risk:passive_low_active", "conf:0.88" ]  |  79.31  |  4,758,533  |  127,526  |  007-first-light/05f12848-dd5d-4fd0-807b-a8a411311ad4/clip.mp4  |  007-first-light/05f12848-dd5d-4fd0-807b-a8a411311ad4/events.json  |  007-first-light/05f12848-dd5d-4fd0-807b-a8a411311ad4/frame_events.json  |  007-first-light/05f12848-dd5d-4fd0-807b-a8a411311ad4/metadata.json  |  
|  3cbfba29-84c6-48d2-bc09-d67a46f6d699  |  Counter-Strike 2  |  gaming  |  macos  |  Counter-Strike: Source Multiplayer Sessions  |  Multiple sustained Counter-Strike: Source multiplayer gameplay sessions on the Italy and other maps, with active combat, weapon purchasing, and team objectives. Includes game setup and configuration research.  |  [ "counter-strike", "fps", "multiplayer", "gaming", "risk:game_simulator", "conf:0.85" ]  |  78.77  |  4,726,433  |  185,416  |  counter-strike-2/3cbfba29-84c6-48d2-bc09-d67a46f6d699/clip.mp4  |  counter-strike-2/3cbfba29-84c6-48d2-bc09-d67a46f6d699/events.json  |  counter-strike-2/3cbfba29-84c6-48d2-bc09-d67a46f6d699/frame_events.json  |  counter-strike-2/3cbfba29-84c6-48d2-bc09-d67a46f6d699/metadata.json  |  
|  fe5d579a-1c39-4038-86ab-ac95ccb4bb7a  |  Forza Horizon 3  |  gaming  |  windows  |  Forza Horizon 3 Extended Gameplay Session  |  User launches and plays Forza Horizon 3 across an extended session including racing, open-world driving, car browsing, and photo mode. Interspersed with YouTube entertainment viewing, OMEN Gaming Hub checks, and brief WhatsApp use.  |  [ "forza-horizon-3", "racing", "open-world", "gaming", "risk:game_simulator", "risk:passive_low_active", "conf:0.78" ]  |  78.45  |  4,707,200  |  42,947  |  forza-horizon-3/fe5d579a-1c39-4038-86ab-ac95ccb4bb7a/clip.mp4  |  forza-horizon-3/fe5d579a-1c39-4038-86ab-ac95ccb4bb7a/events.json  |  forza-horizon-3/fe5d579a-1c39-4038-86ab-ac95ccb4bb7a/frame_events.json  |  forza-horizon-3/fe5d579a-1c39-4038-86ab-ac95ccb4bb7a/metadata.json  |  
End of preview. Expand in Data Studio⟨45⟩
* * *
  *  Previous⟨31⟩
  * 1⟨46⟩
  * 2⟨47⟩
  * 3⟨48⟩
  * ...⟨49⟩
  * 8⟨50⟩
  * Next ⟨47⟩


  * Layout⟨51⟩
  * Top games by hours⟨52⟩


#   ⟨53⟩ Gaming Dataset (gaming-1) — 494.7 Hours 
Native PC/console gameplay screen-recordings, organized **by game**. Each workflow is one play session, trimmed to **pure gameplay** — login screens, launchers, desktop, collection-app references, and any watching/streaming are removed. In-game menus, lobbies, loading, and cutscenes are retained as part of the session.
  * **Workflows:** 776
  * **Total gameplay:** 494.7 hours
  * **Distinct games:** 168
  * **Clip duration (min):** median 24.0, p90 90.9, max 457.7
  * **Platforms:** windows (489.3h), macos (5.3h)
  * **Video:** 30fps CFR H.264.


##   ⟨51⟩ Layout 

```
{game-slug}/{workflow_id}/
  clip.mp4           # gameplay-only, 30fps CFR
  events.json        # input/app events, rebased to the clip timeline (NDJSON)
  frame_events.json  # per-frame event view (NDJSON)
  metadata.json      # workflow_id, game, category, platform, title, description, tags, total_duration_ms, event_count

```

##   ⟨52⟩ Top games by hours   
| Game  | Workflows  | Hours  | Share  |  
| --- | --- | --- | --- |  
| Valorant  | 117  | 102.2  | 20.7%  |  
| Minecraft  | 75  | 41.3  | 8.3%  |  
| Grand Theft Auto V  | 42  | 34.7  | 7.0%  |  
| Palworld  | 30  | 28.7  | 5.8%  |  
| Assassins Creed Syndicate  | 10  | 17.9  | 3.6%  |  
| 007 First Light  | 13  | 17.5  | 3.5%  |  
| Age of Empires  | 7  | 15.5  | 3.1%  |  
| Assassins Creed  | 11  | 15.2  | 3.1%  |  
| Forza Horizon  | 36  | 15.1  | 3.1%  |  
| Counter-Strike 2  | 20  | 12.2  | 2.5%  |  
| Asphalt 9  | 20  | 11.2  | 2.3%  |  
| Hitman 3  | 7  | 9.9  | 2.0%  |  
| Rocket League  | 14  | 7.7  | 1.6%  |  
| Need for Speed  | 11  | 6.9  | 1.4%  |  
| The Finals  | 8  | 6.3  | 1.3%  |  
| Road 96  | 2  | 5.6  | 1.1%  |  
| Pragmata  | 11  | 5.3  | 1.1%  |  
| Candy Crush  | 13  | 5.2  | 1.1%  |  
| Dota 2  | 13  | 4.8  | 1.0%  |  
| Farming Simulator  | 5  | 4.7  | 0.9%  |  
| Forza Horizon 3  | 5  | 3.8  | 0.8%  |  
| Wolfenstein  | 4  | 3.8  | 0.8%  |  
| Ghost of Tsushima  | 9  | 3.5  | 0.7%  |  
| PUBG/BGMI  | 7  | 3.3  | 0.7%  |  
| Hogwarts Legacy  | 4  | 2.8  | 0.6%  |  
Copy to bucket new
Use this dataset 

Downloads last month
    1,967
Number of rows: 776 Total file size: 1.6 TB
System theme
Company
TOS⟨54⟩ Privacy⟨55⟩ About⟨56⟩ Careers⟨57⟩ ⟨1⟩
Website
Models⟨2⟩ Datasets⟨3⟩ Spaces⟨4⟩ Pricing⟨8⟩ Docs⟨6⟩
