![Hugging Face's logo](https://huggingface.co/front/assets/huggingface_logo-noborder.svg) Hugging Face⟨1⟩
  *  Models ⟨2⟩
  *  Datasets ⟨3⟩
  *  Spaces ⟨4⟩
  *  Buckets new⟨5⟩
  *  Docs ⟨6⟩
  *  Enterprise ⟨7⟩
  * Pricing⟨8⟩
  *     * Website
      *  Tasks⟨9⟩
      *  HuggingChat⟨10⟩
      *  Collections⟨11⟩
      *  Languages⟨12⟩
      *  Organizations⟨13⟩
    * Community
      *  Blog⟨14⟩
      *  Posts⟨15⟩
      *  Daily Papers⟨16⟩
      *  Hardware⟨17⟩
      *  Learn⟨18⟩
      *  Discord⟨19⟩
      *  Forum⟨20⟩
      *  GitHub⟨21⟩
    * Solutions
      *  Team & Enterprise⟨7⟩
      *  Hugging Face PRO⟨22⟩
      *  Enterprise Support⟨23⟩
      *  Inference Providers⟨24⟩
      *  Inference Endpoints⟨25⟩
      *  Storage Buckets⟨5⟩
  * * * *
  * Log In⟨26⟩
  * Sign Up⟨27⟩


#   Datasets:⟨3⟩
* * *
Duplicated from DilushaChandrasiri/SriLanka-Bird-Diversity-Dataset⟨28⟩
![⟨29⟩]
 ![](https://cdn-avatars.huggingface.co/v1/production/uploads/6a44a021d23d3c61c9d627a8/oG9-UXKfNVbEhE0cTjxjF.png) ⟨30⟩
Bird-Diversity⟨30⟩
/
Diversity⟨31⟩
like 0
Follow
![⟨32⟩] Bird Diversity 2
Tasks:  Tabular Classification ⟨33⟩ Tabular Regression ⟨34⟩ Other ⟨35⟩
Modalities:  Tabular ⟨36⟩ Text ⟨37⟩ Geospatial ⟨38⟩
Formats:  csv ⟨39⟩
Languages:  English ⟨40⟩
Size:  1M - 10M ⟨41⟩
ArXiv:
arxiv: 2607.00582
Tags:  biology ⟨42⟩ ecology ⟨43⟩ ornithology ⟨44⟩ birds ⟨45⟩ biodiversity ⟨46⟩ sri-lanka ⟨47⟩ + 6
Libraries:  Datasets ⟨48⟩ pandas ⟨49⟩ Polars ⟨50⟩ + 1
License:
cc-by-4.0
 Dataset card ⟨31⟩ Data Studio ⟨51⟩ Files Files and versions xet ⟨52⟩ Community 1 ⟨53⟩
Dataset Viewer
 Auto-converted to Parquet⟨54⟩ API Embed  Duplicate⟨55⟩ Data Studio
Subset (1)
default · 1.55M rows
default (1.55M rows)
Split (1)
train · 1.55M rows
train (1.55M rows)
SQL
Console  
|  index int64 0 2.38M  |  verbatimScientificName stringclasses 429 values  |  stateProvince stringclasses 25 values  |  individualCount float64 1 100k  |  decimalLatitude float64 5.93 9.83  |  decimalLongitude float64 79.7 81.9  |  eventDate stringdate 2014-01-01 00:00:00 2024-12-31 00:00:00  |  avg_rad float64 -0.3 117  |  NDVI_raw float64 -1,909 9.98k  |  LandCover_Class int64 2 17  |  elevation_meters int64 -10 2.52k  |  Carbon_Mass float64 0 0  |  Dust_Mass float64 0 0  |  SO2_Mass float64 0 0  |  Sulfate_Mass float64 0 0  |  Sea_Salt_Mass float64 0 0  |  Total_Aerosol_Extinction float64 0.07 0.45  |  temp_mean float64 18.1 32.5  |  rainfall float64 0 114  |  wind_mean float64 0.35 9.35  |  humid_mean float64 49.7 96.9  |  shortwave_radiation float64 1.55 27.6  |  lka_general_2020 float64 0 5.2k  |  NDVI float64 -0.19 1  |  
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |  
|  0  |  Anarhynchus alexandrinus  |  Mannar  |  8  |  9.058512  |  79.85502  |  2021-01-06  |  0.66  |  3,792  |  10  |  0  |  0  |  0  |  0  |  0  |  0  |  0.175115  |  26.58  |  15.17  |  1.31  |  85.53  |  17.65  |  2.805795  |  0.3792  |  
|  2  |  Hirundo rustica  |  Colombo  |  10  |  6.866285  |  79.93144  |  2024-12-23  |  10.16  |  7,045  |  13  |  5  |  0  |  0  |  0  |  0  |  0  |  0.198127  |  26.21  |  0.25  |  2.51  |  84.3  |  20.49  |  8.91733  |  0.7045  |  
|  6  |  Corvus macrorhynchos  |  Matara  |  2  |  5.983496  |  80.52548  |  2024-10-12  |  1.26  |  6,989  |  10  |  5  |  0  |  0  |  0  |  0  |  0  |  0.131458  |  26.91  |  14.47  |  5.18  |  83.81  |  15.67  |  2.768103  |  0.6989  |  
|  7  |  Dicrurus caerulescens  |  Matale  |  1  |  7.969125  |  80.75477  |  2021-11-20  |  0.37  |  8,543  |  8  |  194  |  0  |  0  |  0  |  0  |  0  |  0.123156  |  25.3  |  2.54  |  2.98  |  89.54  |  21.99  |  3.33974  |  0.8543  |  
|  8  |  Threskiornis melanocephalus  |  Jaffna  |  30  |  9.637712  |  79.9519  |  2019-03-25  |  0.52  |  4,000  |  10  |  2  |  0  |  0  |  0  |  0  |  0  |  0.220155  |  29.67  |  0  |  4.65  |  63.33  |  24.53  |  3.209018  |  0.4  |  
|  9  |  Pavo cristatus  |  Puttalam  |  1  |  7.356422  |  79.87173  |  2023-06-15  |  1.78  |  7,655  |  14  |  12  |  0  |  0  |  0  |  0  |  0  |  0.243836  |  27.83  |  0.8  |  4.04  |  88.33  |  23.17  |  2.901542  |  0.7655  |  
|  10  |  Corvus macrorhynchos  |  Colombo  |  2  |  6.921539  |  80.013664  |  2020-04-07  |  5.87  |  6,497  |  14  |  18  |  0  |  0  |  0  |  0  |  0  |  0.218812  |  28.1  |  1.45  |  2.47  |  77.74  |  23.93  |  4.427688  |  0.6497  |  
|  11  |  Ocyceros gingalensis  |  Kegalla  |  1  |  6.995203  |  80.40633  |  2024-10-30  |  0.88  |  8,285  |  2  |  67  |  0  |  0  |  0  |  0  |  0  |  0.112732  |  23.63  |  0.26  |  1.34  |  90.27  |  19.14  |  3.48004  |  0.8285  |  
|  12  |  Lalage melanoptera  |  Badulla  |  2  |  6.846334  |  81.05875  |  2020-08-09  |  0.5  |  7,232  |  8  |  606  |  0  |  0  |  0  |  0  |  0  |  0.124867  |  24.73  |  2.44  |  3.39  |  80.05  |  15.62  |  5.263761  |  0.7232  |  
|  13  |  Rhipidura aureola  |  Ratnapura  |  1  |  6.676661  |  80.69981  |  2022-04-18  |  0.59  |  8,962  |  8  |  542  |  0  |  0  |  0  |  0  |  0  |  0.14498  |  25.34  |  4.27  |  1.89  |  91.12  |  19.9  |  8.189035  |  0.8962  |  
|  14  |  Microcarbo niger  |  Colombo  |  1  |  6.830337  |  79.93607  |  2020-06-08  |  5.34  |  5,963  |  9  |  24  |  0  |  0  |  0  |  0  |  0  |  0.180944  |  27.21  |  6.22  |  4.23  |  86.21  |  16.26  |  10.325916  |  0.5963  |  
|  15  |  Egretta garzetta  |  Matara  |  34  |  5.983496  |  80.52548  |  2021-04-30  |  1.79  |  6,078  |  8  |  5  |  0  |  0  |  0  |  0  |  0  |  0.28155  |  28.39  |  6.52  |  2.53  |  80.13  |  20.14  |  2.768103  |  0.6078  |  
|  16  |  Copsychus saularis  |  Colombo  |  1  |  6.840681  |  79.87928  |  2022-05-15  |  14.44  |  3,867  |  13  |  9  |  0  |  0  |  0  |  0  |  0  |  0.331033  |  26.97  |  13.02  |  5.21  |  85.9  |  17.25  |  13.384609  |  0.3867  |  
|  17  |  Columba livia  |  Kalutara  |  6  |  6.584886  |  79.95885  |  2021-04-07  |  3.63  |  240  |  9  |  7  |  0  |  0  |  0  |  0  |  0  |  0.301166  |  27.09  |  3.48  |  1.8  |  83.58  |  23.18  |  10.596757  |  0.024  |  
|  20  |  Pelecanus philippensis  |  Monaragala  |  1  |  6.687563  |  81.08508  |  2021-07-03  |  0.25  |  7,006  |  8  |  180  |  0  |  0  |  0  |  0  |  0  |  0.156583  |  26.24  |  3.98  |  3.75  |  90.26  |  19.73  |  2.681323  |  0.7006  |  
|  21  |  Pycnonotus cafer  |  Colombo  |  3  |  6.879435  |  79.92904  |  2018-10-04  |  11.46  |  6,663  |  13  |  3  |  0  |  0  |  0  |  0  |  0  |  0.222476  |  25.98  |  13.41  |  3.19  |  90.98  |  21.87  |  10.476233  |  0.6663  |  
|  23  |  Hirundo rustica  |  Colombo  |  3  |  6.879259  |  79.930664  |  2021-01-05  |  7.72  |  7,697  |  13  |  3  |  0  |  0  |  0  |  0  |  0  |  0.13798  |  25.98  |  7.17  |  2.1  |  84.23  |  21.11  |  10.476233  |  0.7697  |  
|  24  |  Psilopogon rubricapillus  |  Colombo  |  1  |  6.830337  |  79.93607  |  2021-04-05  |  7.17  |  5,368  |  9  |  24  |  0  |  0  |  0  |  0  |  0  |  0.325238  |  27.94  |  0.42  |  2  |  79.18  |  23.5  |  10.325916  |  0.5368  |  
|  25  |  Hypsipetes ganeesa  |  Ratnapura  |  20  |  6.40896  |  80.44533  |  2018-02-01  |  0.12  |  8,696  |  2  |  745  |  0  |  0  |  0  |  0  |  0  |  0.13205  |  24.79  |  3.99  |  1.52  |  86  |  19.02  |  1.963569  |  0.8696  |  
|  27  |  Acridotheres tristis  |  Colombo  |  7  |  6.879259  |  79.930664  |  2019-03-20  |  11.96  |  6,714  |  13  |  3  |  0  |  0  |  0  |  0  |  0  |  0.24523  |  28.09  |  0.18  |  1.42  |  70.35  |  26.74  |  10.476233  |  0.6714  |  
|  28  |  Chloropsis jerdoni  |  Ratnapura  |  1  |  6.40896  |  80.44533  |  2017-09-17  |  0.389559  |  8,760  |  2  |  745  |  0  |  0  |  0  |  0  |  0  |  0.138059  |  24.75  |  3.13  |  3.55  |  86.72  |  15.71  |  1.963569  |  0.876  |  
|  29  |  Pomatorhinus melanurus  |  Ratnapura  |  2  |  6.428428  |  80.438736  |  2018-01-25  |  0.14  |  8,498  |  2  |  338  |  0  |  0  |  0  |  0  |  0  |  0.235743  |  23.49  |  0.06  |  1.14  |  77.57  |  22.38  |  1.752394  |  0.8498  |  
|  30  |  Argya affinis  |  Mannar  |  7  |  9.024707  |  79.86775  |  2022-01-17  |  1.84  |  7,787  |  10  |  12  |  0  |  0  |  0  |  0  |  0  |  0.191505  |  26.54  |  10.46  |  4.89  |  82.22  |  18.33  |  6.447099  |  0.7787  |  
|  32  |  Ardea cinerea  |  Colombo  |  4  |  6.933077  |  79.8556  |  2022-12-01  |  29.129999  |  3,674  |  13  |  7  |  0  |  0  |  0  |  0  |  0  |  0.180907  |  27.3  |  1.66  |  1.72  |  75.04  |  20.59  |  31.16661  |  0.3674  |  
|  33  |  Vanellus indicus  |  Anuradhapura  |  2  |  8.352865  |  80.40179  |  2016-01-06  |  37.111393  |  7,010  |  9  |  84  |  0  |  0  |  0  |  0  |  0  |  0.222079  |  25.32  |  21.26  |  2.97  |  91.82  |  9.79  |  1.621537  |  0.701  |  
|  34  |  Corvus macrorhynchos  |  Nuwara  |  10  |  6.793745  |  80.80122  |  2019-03-14  |  0.31  |  6,020  |  8  |  2,115  |  0  |  0  |  0  |  0  |  0  |  0.168793  |  23.16  |  0.02  |  1.63  |  74.61  |  25.66  |  4.914375  |  0.602  |  
|  35  |  Corvus macrorhynchos  |  Gampaha  |  9  |  7.167305  |  79.915245  |  2024-01-24  |  3.02  |  7,662  |  14  |  6  |  0  |  0  |  0  |  0  |  0  |  0.159481  |  24.64  |  0  |  3.18  |  76.95  |  23.91  |  3.491359  |  0.7662  |  
|  36  |  Eudynamys scolopaceus  |  Galle  |  3  |  6.048434  |  80.19695  |  2024-04-28  |  3.04  |  6,687  |  8  |  5  |  0  |  0  |  0  |  0  |  0  |  0.196698  |  29.51  |  5.84  |  1.25  |  78.33  |  20.11  |  2.73933  |  0.6687  |  
|  39  |  Sitta frontalis  |  Matale  |  2  |  7.517829  |  80.731575  |  2023-02-14  |  0.27  |  8,289  |  2  |  1,157  |  0  |  0  |  0  |  0  |  0  |  0.133129  |  21.85  |  0.04  |  2.14  |  88.16  |  23.94  |  11.161503  |  0.8289  |  
|  40  |  Vanellus indicus  |  Matara  |  2  |  5.975843  |  80.52221  |  2023-12-29  |  2.05  |  7,426  |  11  |  5  |  0  |  0  |  0  |  0  |  0  |  0.110802  |  26.95  |  25.82  |  4.16  |  89.97  |  9.86  |  2.768103  |  0.7426  |  
|  41  |  Cypsiurus balasiensis  |  Matara  |  1  |  5.94295  |  80.56059  |  2020-05-19  |  2.75  |  4,635  |  9  |  26  |  0  |  0  |  0  |  0  |  0  |  0.211204  |  28.01  |  9.47  |  7.28  |  82.93  |  10.95  |  4.601256  |  0.4635  |  
|  43  |  Ardea cinerea  |  Monaragala  |  2  |  6.4891  |  80.8658  |  2021-12-18  |  0.2  |  8,525  |  9  |  103  |  0  |  0  |  0  |  0  |  0  |  0.126004  |  24.47  |  19.51  |  1.19  |  85.72  |  17.72  |  4.117622  |  0.8525  |  
|  44  |  Apus affinis  |  Hambantota  |  35  |  6.058703  |  80.82833  |  2021-02-04  |  0.73  |  7,349  |  10  |  8  |  0  |  0  |  0  |  0  |  0  |  0.187394  |  26.68  |  0.58  |  4.19  |  79.42  |  18.42  |  6.206602  |  0.7349  |  
|  50  |  Acridotheres tristis  |  Ampara  |  2  |  6.794739  |  81.81482  |  2020-02-26  |  0.27  |  6,995  |  10  |  3  |  0  |  0  |  0  |  0  |  0  |  0.181756  |  27.34  |  0.03  |  2.64  |  78.19  |  22.75  |  1.566867  |  0.6995  |  
|  51  |  Copsychus saularis  |  Anuradhapura  |  3  |  8.037133  |  80.746506  |  2024-03-24  |  0.98  |  5,663  |  9  |  171  |  0  |  0  |  0  |  0  |  0  |  0.242401  |  27.41  |  2.03  |  2.34  |  79.52  |  23.46  |  6.653724  |  0.5663  |  
|  52  |  Ardeola grayii  |  Colombo  |  3  |  6.912505  |  79.8703  |  2022-11-24  |  19.99  |  4,590  |  13  |  11  |  0  |  0  |  0  |  0  |  0  |  0.212888  |  26.31  |  0.04  |  2.12  |  80.03  |  21.7  |  3.302017  |  0.459  |  
|  53  |  Spilornis cheela  |  Colombo  |  1  |  6.892344  |  80.172554  |  2023-08-04  |  0.7  |  8,096  |  8  |  102  |  0  |  0  |  0  |  0  |  0  |  0.188183  |  26.65  |  0.35  |  3.74  |  88.66  |  20.45  |  27.765616  |  0.8096  |  
|  56  |  Ardea coromanda  |  Kegalla  |  120  |  6.987599  |  80.42288  |  2014-03-01  |  0.38923  |  7,790  |  8  |  97  |  0  |  0  |  0  |  0  |  0  |  0.195021  |  22.98  |  0.01  |  1.36  |  77.95  |  20.61  |  2.851636  |  0.779  |  
|  58  |  Cecropis hyperythra  |  Ratnapura  |  12  |  6.407421  |  80.64273  |  2021-12-11  |  0.33  |  8,926  |  2  |  809  |  0  |  0  |  0  |  0  |  0  |  0.126004  |  24.74  |  2.56  |  2.57  |  87.76  |  20.54  |  17.498741  |  0.8926  |  
|  60  |  Icthyophaga leucogaster  |  Kalutara  |  1  |  6.676849  |  79.920425  |  2021-04-20  |  1.78  |  8,565  |  13  |  10  |  0  |  0  |  0  |  0  |  0  |  0.301166  |  27.68  |  5.7  |  3.5  |  83.68  |  23.18  |  9.319591  |  0.8565  |  
|  61  |  Ardea alba  |  Mannar  |  20  |  8.930852  |  79.93026  |  2022-01-04  |  0.15  |  5,557  |  10  |  3  |  0  |  0  |  0  |  0  |  0  |  0.191505  |  25.71  |  0.74  |  5.35  |  82.16  |  19.29  |  1.200532  |  0.5557  |  
|  62  |  Oriolus xanthornus  |  Colombo  |  1  |  6.830337  |  79.93607  |  2021-09-30  |  4.41  |  5,852  |  9  |  24  |  0  |  0  |  0  |  0  |  0  |  0.209652  |  26.39  |  7.1  |  2.95  |  86.4  |  17.45  |  10.325916  |  0.5852  |  
|  63  |  Oriolus xanthornus  |  Gampaha  |  2  |  6.988058  |  79.980774  |  2021-12-24  |  4.72  |  6,877  |  14  |  26  |  0  |  0  |  0  |  0  |  0  |  0.147139  |  24.59  |  0.13  |  3.2  |  78.58  |  23.01  |  9.957386  |  0.6877  |  
|  65  |  Acridotheres tristis  |  Mannar  |  16  |  8.945312  |  79.92311  |  2022-01-14  |  0.59  |  4,075  |  16  |  4  |  0  |  0  |  0  |  0  |  0  |  0.191505  |  26.64  |  0  |  2.45  |  83.91  |  22.5  |  1.200532  |  0.4075  |  
|  67  |  Lonchura malacca  |  Hambantota  |  1  |  6.232749  |  81.159645  |  2021-05-27  |  0.75  |  5,148  |  14  |  23  |  0  |  0  |  0  |  0  |  0  |  0.14604  |  28.05  |  1.59  |  8.1  |  83.65  |  16.57  |  11.042163  |  0.5148  |  
|  68  |  Prinia socialis  |  Batticaloa  |  1  |  7.742025  |  81.66617  |  2016-02-27  |  0.996346  |  5,559  |  9  |  7  |  0  |  0  |  0  |  0  |  0  |  0.213007  |  27.88  |  0.93  |  4.22  |  78.97  |  20.03  |  2.952391  |  0.5559  |  
|  70  |  Anastomus oscitans  |  Anuradhapura  |  2  |  8.35832  |  80.45929  |  2023-04-11  |  1.06  |  6,867  |  9  |  96  |  0  |  0  |  0  |  0  |  0  |  0.231277  |  27.45  |  0.39  |  2.19  |  79.53  |  23.53  |  1.853566  |  0.6867  |  
|  72  |  Columba livia  |  Matara  |  2  |  5.975843  |  80.52221  |  2021-02-14  |  4.57  |  6,513  |  10  |  5  |  0  |  0  |  0  |  0  |  0  |  0.187394  |  27.15  |  0.78  |  1.23  |  79.02  |  24.37  |  2.768103  |  0.6513  |  
|  73  |  Oriolus xanthornus  |  Colombo  |  1  |  6.921542  |  80.01369  |  2021-05-16  |  4.38  |  6,342  |  14  |  18  |  0  |  0  |  0  |  0  |  0  |  0.184111  |  26.76  |  1.17  |  3  |  87.29  |  18.59  |  4.427688  |  0.6342  |  
|  75  |  Lanius cristatus  |  Colombo  |  1  |  6.901168  |  79.883  |  2021-02-28  |  14.24  |  6,386  |  13  |  3  |  0  |  0  |  0  |  0  |  0  |  0.176356  |  26.71  |  0.04  |  1.41  |  73.05  |  25.63  |  5.942243  |  0.6386  |  
|  77  |  Acrocephalus stentoreus  |  Mannar  |  3  |  8.95014  |  79.96343  |  2024-02-21  |  0.75  |  3,917  |  9  |  5  |  0  |  0  |  0  |  0  |  0  |  0.296243  |  26.89  |  0  |  2.53  |  79.56  |  23.9  |  1.04491  |  0.3917  |  
|  78  |  Spilopelia chinensis  |  Gampaha  |  3  |  7.012445  |  79.9039  |  2020-11-08  |  6.83  |  5,307  |  13  |  14  |  0  |  0  |  0  |  0  |  0  |  0.183319  |  27.32  |  15.92  |  2.38  |  81.2  |  19.88  |  13.359376  |  0.5307  |  
|  80  |  Anhinga melanogaster  |  Hambantota  |  1  |  6.188598  |  81.22004  |  2023-08-25  |  0.39  |  3,063  |  12  |  4  |  0  |  0  |  0  |  0  |  0  |  0.176639  |  28.09  |  1.57  |  5.25  |  82.81  |  25.02  |  4.196543  |  0.3063  |  
|  81  |  Copsychus fulicatus  |  Nuwara  |  1  |  7.130149  |  80.84357  |  2017-02-22  |  0.232381  |  7,879  |  8  |  717  |  0  |  0  |  0  |  0  |  0  |  0.157714  |  23.88  |  0.01  |  0.82  |  74.15  |  25.26  |  8.361939  |  0.7879  |  
|  82  |  Haliastur indus  |  Colombo  |  2  |  6.903542  |  80.033165  |  2023-04-17  |  2.76  |  8,075  |  14  |  10  |  0  |  0  |  0  |  0  |  0  |  0.248073  |  27.93  |  0.31  |  1.63  |  79.66  |  23.51  |  4.671355  |  0.8075  |  
|  83  |  Gelochelidon nilotica  |  Hambantota  |  3  |  6.188598  |  81.22004  |  2021-12-21  |  0.2  |  7,482  |  14  |  4  |  0  |  0  |  0  |  0  |  0  |  0.139011  |  27.08  |  1.82  |  4.08  |  83.21  |  19.61  |  4.196543  |  0.7482  |  
|  84  |  Corvus splendens  |  Matara  |  274  |  5.94295  |  80.56059  |  2020-05-25  |  2.75  |  4,635  |  9  |  26  |  0  |  0  |  0  |  0  |  0  |  0.211204  |  28.07  |  7.18  |  4.74  |  87.2  |  16.91  |  4.601256  |  0.4635  |  
|  85  |  Tachyspiza badia  |  Colombo  |  1  |  6.924184  |  79.91887  |  2021-07-13  |  4.27  |  5,823  |  13  |  25  |  0  |  0  |  0  |  0  |  0  |  0.190623  |  25.98  |  3.49  |  4.74  |  88.14  |  22.45  |  5.739982  |  0.5823  |  
|  86  |  Cypsiurus balasiensis  |  Hambantota  |  2  |  6.1964  |  81.210915  |  2023-05-04  |  0.5  |  6,626  |  17  |  2  |  0  |  0  |  0  |  0  |  0  |  0.193386  |  27.83  |  24.97  |  4.81  |  85.86  |  18.03  |  4.196543  |  0.6626  |  
|  88  |  Copsychus saularis  |  Matale  |  4  |  7.575104  |  80.62861  |  2022-06-11  |  0.74  |  6,592  |  8  |  355  |  0  |  0  |  0  |  0  |  0  |  0.183022  |  24.65  |  1.8  |  3.67  |  88.93  |  16.43  |  5.977915  |  0.6592  |  
|  89  |  Tachyspiza virgata  |  Ratnapura  |  1  |  6.40896  |  80.44533  |  2018-01-31  |  0.11  |  8,635  |  2  |  745  |  0  |  0  |  0  |  0  |  0  |  0.235743  |  24.52  |  7.47  |  2.04  |  87.54  |  11.69  |  1.963569  |  0.8635  |  
|  90  |  Cisticola juncidis  |  Gampaha  |  3  |  7.025558  |  79.88532  |  2022-11-12  |  4.2  |  7,267  |  14  |  3  |  0  |  0  |  0  |  0  |  0  |  0.212888  |  25.36  |  3.97  |  2.54  |  87.86  |  16.19  |  3.205106  |  0.7267  |  
|  91  |  Acridotheres tristis  |  Puttalam  |  7  |  7.705803  |  79.8119  |  2022-11-12  |  0.53  |  7,985  |  9  |  3  |  0  |  0  |  0  |  0  |  0  |  0.227135  |  25.8  |  3.97  |  3.21  |  87.45  |  16.19  |  1.714285  |  0.7985  |  
|  92  |  Halcyon smyrnensis  |  Ratnapura  |  1  |  6.431646  |  80.41547  |  2024-12-04  |  0.31  |  8,491  |  2  |  433  |  0  |  0  |  0  |  0  |  0  |  0.162129  |  25.05  |  0.14  |  1  |  84.82  |  19.67  |  1.766349  |  0.8491  |  
|  93  |  Vanellus indicus  |  Gampaha  |  22  |  7.024795  |  79.88228  |  2022-12-07  |  5.19  |  5,455  |  9  |  6  |  0  |  0  |  0  |  0  |  0  |  0.180907  |  24.74  |  0.35  |  4.17  |  84.3  |  9.21  |  3.205106  |  0.5455  |  
|  94  |  Psilopogon zeylanicus  |  Kalutara  |  1  |  6.724506  |  80.15604  |  2016-11-01  |  0.48989  |  8,354  |  2  |  25  |  0  |  0  |  0  |  0  |  0  |  0.257068  |  25.57  |  18.05  |  2.53  |  89.53  |  16.78  |  3.946051  |  0.8354  |  
|  95  |  Argya affinis  |  Gampaha  |  7  |  6.988723  |  79.981026  |  2021-09-22  |  3.38  |  6,853  |  14  |  30  |  0  |  0  |  0  |  0  |  0  |  0.209652  |  26.74  |  2.94  |  3.12  |  88.08  |  24.59  |  9.957386  |  0.6853  |  
|  96  |  Leptocoma zeylonica  |  Gampaha  |  2  |  7.09855  |  79.985725  |  2023-05-03  |  2.63  |  8,067  |  14  |  24  |  0  |  0  |  0  |  0  |  0  |  0.228888  |  27.29  |  13.94  |  3.51  |  85.12  |  8.71  |  5.832619  |  0.8067  |  
|  97  |  Eremopterix griseus  |  Gampaha  |  12  |  7.024743  |  79.88276  |  2021-12-08  |  5.08  |  4,946  |  9  |  4  |  0  |  0  |  0  |  0  |  0  |  0.147139  |  26.32  |  2.08  |  2.45  |  83.34  |  21.87  |  3.205106  |  0.4946  |  
|  98  |  Phalacrocorax fuscicollis  |  Colombo  |  1  |  6.863201  |  79.9009  |  2024-10-12  |  12.68  |  4,266  |  13  |  12  |  0  |  0  |  0  |  0  |  0  |  0.139566  |  25.8  |  19.69  |  3.45  |  86.42  |  11.82  |  8.31633  |  0.4266  |  
|  100  |  Centropus sinensis  |  Colombo  |  1  |  6.797  |  79.9  |  2024-08-13  |  7.25  |  5,232  |  9  |  29  |  0  |  0  |  0  |  0  |  0  |  0.188473  |  26.24  |  15.2  |  4.09  |  91.44  |  15.48  |  6.697522  |  0.5232  |  
|  101  |  Ardea alba  |  Puttalam  |  2  |  8.064328  |  79.82228  |  2021-10-14  |  1.63  |  2,284  |  9  |  4  |  0  |  0  |  0  |  0  |  0  |  0.194741  |  27.75  |  0.4  |  5.7  |  83.91  |  22.96  |  3.221645  |  0.2284  |  
|  102  |  Leptocoma zeylonica  |  Gampaha  |  4  |  7.012474  |  79.90404  |  2023-03-14  |  11.52  |  6,791  |  13  |  12  |  0  |  0  |  0  |  0  |  0  |  0.23936  |  27.33  |  2.59  |  1.36  |  76.98  |  24.61  |  13.359376  |  0.6791  |  
|  103  |  Psittacula krameri  |  Nuwara  |  4  |  6.967494  |  80.76754  |  2024-12-18  |  6.92  |  6,940  |  9  |  1,883  |  0  |  0  |  0  |  0  |  0  |  0.139092  |  22.52  |  1.13  |  1.51  |  92.01  |  17.72  |  3.353881  |  0.694  |  
|  104  |  Dicrurus caerulescens  |  Gampaha  |  2  |  7.031971  |  79.96317  |  2021-04-14  |  4.36  |  6,427  |  14  |  39  |  0  |  0  |  0  |  0  |  0  |  0.325238  |  27.39  |  17.11  |  1.68  |  82  |  25.1  |  9.118636  |  0.6427  |  
|  105  |  Dicaeum erythrorhynchos  |  Matale  |  6  |  7.575104  |  80.62861  |  2022-06-12  |  0.74  |  6,592  |  8  |  355  |  0  |  0  |  0  |  0  |  0  |  0.183022  |  25.15  |  0.93  |  3.25  |  85.49  |  17.83  |  5.977915  |  0.6592  |  
|  106  |  Oriolus xanthornus  |  Colombo  |  1  |  6.878049  |  79.93749  |  2020-06-23  |  12.5  |  5,374  |  13  |  21  |  0  |  0  |  0  |  0  |  0  |  0.180944  |  27.14  |  0.82  |  3.42  |  80.83  |  18.22  |  10.939944  |  0.5374  |  
|  107  |  Dendrocygna javanica  |  Puttalam  |  2  |  7.95986  |  79.809204  |  2022-12-18  |  1.13  |  6,925  |  12  |  2  |  0  |  0  |  0  |  0  |  0  |  0.191658  |  25.55  |  3.17  |  5  |  84.63  |  13.38  |  5.463104  |  0.6925  |  
|  109  |  Dicrurus leucophaeus  |  Galle  |  2  |  6.071811  |  80.34308  |  2018-03-18  |  0.43  |  7,921  |  8  |  93  |  0  |  0  |  0  |  0  |  0  |  0.204558  |  27.62  |  0.64  |  4.36  |  82.31  |  24.55  |  7.827464  |  0.7921  |  
|  110  |  Psilopogon flavifrons  |  Kalutara  |  1  |  6.377266  |  80.136116  |  2023-04-07  |  0.64  |  8,695  |  8  |  11  |  0  |  0  |  0  |  0  |  0  |  0.230458  |  28.7  |  5.23  |  1.42  |  70.98  |  22.77  |  16.79167  |  0.8695  |  
|  112  |  Ardea coromanda  |  Mannar  |  20  |  9.000365  |  79.89113  |  2015-12-19  |  0.171793  |  7,185  |  10  |  3  |  0  |  0  |  0  |  0  |  0  |  0.132053  |  26.55  |  13.04  |  4.32  |  87.05  |  14.78  |  2.685908  |  0.7185  |  
|  113  |  Centropus sinensis  |  Gampaha  |  2  |  7.012474  |  79.90404  |  2023-06-19  |  7.54  |  6,038  |  13  |  12  |  0  |  0  |  0  |  0  |  0  |  0.232264  |  26.98  |  1.74  |  4.1  |  88.23  |  22.36  |  13.359376  |  0.6038  |  
|  117  |  Acridotheres tristis  |  Gampaha  |  1  |  6.998735  |  79.919395  |  2021-11-03  |  4.72  |  5,957  |  9  |  25  |  0  |  0  |  0  |  0  |  0  |  0.130587  |  25.86  |  14.79  |  2.55  |  87.62  |  10.58  |  19.084203  |  0.5957  |  
|  118  |  Ardea alba  |  Galle  |  3  |  6.02112  |  80.34088  |  2020-08-08  |  0.98  |  8,342  |  8  |  36  |  0  |  0  |  0  |  0  |  0  |  0.167707  |  26.7  |  3.29  |  5.57  |  86.52  |  16.99  |  4.961723  |  0.8342  |  
|  119  |  Columba livia  |  Kalutara  |  6  |  6.721401  |  79.90663  |  2021-12-08  |  7.22  |  4,720  |  13  |  10  |  0  |  0  |  0  |  0  |  0  |  0.165283  |  26.71  |  3.17  |  1.58  |  81.36  |  22.18  |  5.500665  |  0.472  |  
|  126  |  Leptocoma zeylonica  |  Kurunegala  |  1  |  7.618708  |  80.23146  |  2023-10-25  |  1.3  |  7,140  |  14  |  103  |  0  |  0  |  0  |  0  |  0  |  0.234282  |  26.69  |  9.3  |  0.97  |  82.01  |  18.41  |  1.863179  |  0.714  |  
|  127  |  Spilopelia chinensis  |  Colombo  |  12  |  6.87978  |  79.92924  |  2024-12-05  |  9.66  |  7,281  |  13  |  3  |  0  |  0  |  0  |  0  |  0  |  0.198127  |  26.69  |  3.98  |  2.17  |  84.58  |  20.62  |  10.476233  |  0.7281  |  
|  130  |  Orthotomus sutorius  |  Kandy  |  2  |  7.200713  |  80.562096  |  2021-02-26  |  0.62  |  7,902  |  8  |  572  |  0  |  0  |  0  |  0  |  0  |  0.139845  |  23.2  |  0.05  |  1.09  |  85.04  |  24.76  |  14.606029  |  0.7902  |  
|  131  |  Hirundo rustica  |  Mannar  |  4  |  8.949303  |  79.92343  |  2024-02-22  |  0.3  |  920  |  17  |  0  |  0  |  0  |  0  |  0  |  0  |  0.296243  |  27.33  |  0  |  1.93  |  81.44  |  22.78  |  1.200532  |  0.092  |  
|  133  |  Dicrurus caerulescens  |  Matale  |  3  |  7.540686  |  80.735  |  2023-02-21  |  0.37  |  8,232  |  2  |  1,069  |  0  |  0  |  0  |  0  |  0  |  0.133129  |  23.15  |  1.66  |  2.38  |  89.61  |  24.33  |  7.626007  |  0.8232  |  
|  135  |  Copsychus saularis  |  Colombo  |  2  |  6.840681  |  79.87928  |  2023-05-26  |  14.61  |  6,550  |  13  |  9  |  0  |  0  |  0  |  0  |  0  |  0.228888  |  27.75  |  0.69  |  3.91  |  86.63  |  24.57  |  13.384609  |  0.655  |  
|  136  |  Orthotomus sutorius  |  Colombo  |  4  |  6.889166  |  79.94686  |  2020-01-20  |  8.58  |  6,277  |  13  |  7  |  0  |  0  |  0  |  0  |  0  |  0.137738  |  26.5  |  2.6  |  3.86  |  83.29  |  20.68  |  6.585009  |  0.6277  |  
|  137  |  Anhinga melanogaster  |  Hambantota  |  15  |  6.193845  |  81.25768  |  2022-02-06  |  0.46  |  4,890  |  9  |  3  |  0  |  0  |  0  |  0  |  0  |  0.183054  |  26.95  |  0.05  |  4.28  |  78.52  |  21.69  |  3.069176  |  0.489  |  
|  139  |  Copsychus saularis  |  Colombo  |  3  |  6.889166  |  79.94686  |  2022-12-11  |  6.61  |  6,746  |  13  |  7  |  0  |  0  |  0  |  0  |  0  |  0.180907  |  26.06  |  15.46  |  3.56  |  84.25  |  16.66  |  6.585009  |  0.6746  |  
|  140  |  Threskiornis melanocephalus  |  Colombo  |  124  |  6.91245  |  79.90943  |  2024-08-10  |  9.24  |  4,405  |  13  |  7  |  0  |  0  |  0  |  0  |  0  |  0.188473  |  26.81  |  1.75  |  4.29  |  84.42  |  18.87  |  16.163552  |  0.4405  |  
|  141  |  Vanellus indicus  |  Hambantota  |  1  |  6.390747  |  81.412186  |  2019-01-24  |  0.01  |  8,053  |  9  |  33  |  0  |  0  |  0  |  0  |  0  |  0.152445  |  25.31  |  0.14  |  2.16  |  83.88  |  20.61  |  1.377294  |  0.8053  |  
|  142  |  Plocealauda affinis  |  Hambantota  |  1  |  6.188598  |  81.22004  |  2016-12-08  |  -0.045748  |  7,106  |  14  |  4  |  0  |  0  |  0  |  0  |  0  |  0.189238  |  27.1  |  8.58  |  2.15  |  84.74  |  16.79  |  4.196543  |  0.7106  |  
|  145  |  Lonchura punctulata  |  Matara  |  5  |  5.98644  |  80.42406  |  2018-01-14  |  0.72  |  7,963  |  13  |  5  |  0  |  0  |  0  |  0  |  0  |  0.278389  |  26.36  |  1.56  |  3.2  |  84.17  |  21.65  |  4.553882  |  0.7963  |  
|  146  |  Argya affinis  |  Nuwara  |  6  |  6.988039  |  80.4334  |  2015-04-10  |  0.295037  |  8,076  |  2  |  128  |  0  |  0  |  0  |  0  |  0  |  0.141756  |  24.5  |  7.38  |  0.61  |  83.98  |  21.53  |  10.404107  |  0.8076  |  
|  148  |  Argya cinereifrons  |  Ratnapura  |  25  |  6.40896  |  80.44533  |  2017-01-19  |  -0.012363  |  8,616  |  2  |  745  |  0  |  0  |  0  |  0  |  0  |  0.143545  |  24.33  |  0.25  |  1.57  |  72.93  |  21.3  |  1.963569  |  0.8616  |  
End of preview. Expand in Data Studio⟨56⟩
* * *
  *  Previous⟨31⟩
  * 1⟨57⟩
  * 2⟨58⟩
  * 3⟨59⟩
  * ...⟨60⟩
  * 15,521⟨61⟩
  * Next ⟨58⟩


  * Dataset Summary⟨62⟩
  * Dataset Description⟨63⟩
  * Dataset Creators⟨64⟩
    * Bird Occurrence Data⟨65⟩
    * Environmental Variables⟨66⟩
  * Ecological Applications⟨67⟩
  * Machine Learning Applications⟨68⟩
  * Sampling Bias⟨69⟩
  * Environmental Resolution⟨70⟩
  * Taxonomic Limitations⟨71⟩
  * Recommended Use⟨72⟩
  * Related Paper⟨73⟩


#   ⟨74⟩ Sri Lanka Bird Diversity Dataset 
##   ⟨62⟩ Dataset Summary 
The **Sri Lanka Bird Diversity Dataset with Environmental and Climate Features** is a large-scale biodiversity dataset containing **1,552,048 bird occurrence records** covering **429 bird species** across all **25 provinces of Sri Lanka**.
The dataset integrates bird observation records with spatial, climatic, environmental, and land-cover variables extracted at each observation location. It provides a comprehensive resource for machine learning, ecological modeling, and biodiversity research.
The dataset spans observations collected between **2014 and 2024** , enabling studies on:
  * Species distribution modeling (SDM)
  * Climate–biodiversity relationships
  * Habitat suitability prediction
  * Bird species classification
  * Environmental impact analysis
  * Ecological machine learning applications


* * *
#   ⟨75⟩ Dataset Details 
##   ⟨63⟩ Dataset Description 
Each record represents a bird observation associated with geographic coordinates, observation metadata, and environmental conditions at the observation location and time.
The dataset contains:
  * **1,552,048 observation records**
  * **429 unique bird species**
  * **25 provinces of Sri Lanka**
  * **10 years of observations (2014–2024)**
  * **24 feature variables**


The dataset combines biodiversity observations with environmental variables derived from satellite imagery, climate models, and atmospheric datasets.
* * *
##   ⟨64⟩ Dataset Creators 
Developed by:
  * Dilusha Chandrasiri
  * Maneesha Herath
  * Muditha Herath
  * Yasith Hewarathna
  * Gishan Bandara


* * *
#   ⟨76⟩ Data Sources 
The dataset integrates information from multiple publicly available sources:
###   ⟨65⟩ Bird Occurrence Data 
  * **Global Biodiversity Information Facility (GBIF)**  
Bird observation records with species taxonomy and geographic information.


###   ⟨66⟩ Environmental Variables   
| Variable Group  | Source  |  
| --- | --- |  
| Vegetation indices  | Satellite remote sensing data (MODIS/Sentinel-derived products)  |  
| Land cover  | ESA WorldCover / land-use datasets  |  
| Elevation  | SRTM Digital Elevation Model  |  
| Climate variables  | ERA5 climate reanalysis  |  
| Atmospheric variables  | NASA MERRA-2 aerosol reanalysis  |  
| Geographic information  | Sri Lankan administrative boundaries  |  
Users should acknowledge and cite the original data providers when using this dataset.
* * *
#   ⟨77⟩ Dataset Structure 
The dataset is provided as:
The file contains **24 columns**.
* * *
#   ⟨78⟩ Features   
| Feature  | Type  | Description  |  
| --- | --- | --- |  
| `index`  | Integer  | Unique row identifier  |  
| `verbatimScientificName`  | String  | Scientific name of observed bird species  |  
| `stateProvince`  | String  | Province where observation occurred  |  
| `individualCount`  | Float  | Number of observed individuals  |  
| `decimalLatitude`  | Float  | Latitude coordinate (WGS84)  |  
| `decimalLongitude`  | Float  | Longitude coordinate (WGS84)  |  
| `eventDate`  | Date  | Observation date  |  
| `avg_rad`  | Float  | Average surface radiation  |  
| `NDVI_raw`  | Float  | Raw vegetation index  |  
| `NDVI`  | Float  | Normalized vegetation index  |  
| `LandCover_Class`  | Integer  | Land cover category identifier  |  
| `elevation_meters`  | Integer  | Elevation above sea level  |  
| `Carbon_Mass`  | Float  | Atmospheric carbon aerosol mass  |  
| `Dust_Mass`  | Float  | Atmospheric dust aerosol mass  |  
| `SO2_Mass`  | Float  | Sulfur dioxide aerosol concentration  |  
| `Sulfate_Mass`  | Float  | Sulfate aerosol concentration  |  
| `Sea_Salt_Mass`  | Float  | Sea salt aerosol concentration  |  
| `Total_Aerosol_Extinction`  | Float  | Aerosol optical extinction  |  
| `temp_mean`  | Float  | Mean temperature  |  
| `rainfall`  | Float  | Rainfall measurement  |  
| `wind_mean`  | Float  | Average wind speed  |  
| `humid_mean`  | Float  | Relative humidity  |  
| `shortwave_radiation`  | Float  | Solar shortwave radiation  |  
| `lka_general_2020`  | Float  | Sri Lankan environmental baseline indicator  |  
* * *
#   ⟨79⟩ Dataset Statistics   
| Statistic  | Value  |  
| --- | --- |  
| Total records  | 1,552,048  |  
| Bird species  | 429  |  
| Geographic coverage  | Sri Lanka  |  
| Provinces covered  | 25  |  
| Observation period  | 2014–2024  |  
| Features  | 24  |  
| Missing values  | None after preprocessing  |  
* * *
#   ⟨80⟩ Geographic Coverage 
The dataset covers all provinces of Sri Lanka:
  * Ampara
  * Anuradhapura
  * Badulla
  * Batticaloa
  * Colombo
  * Galle
  * Gampaha
  * Hambantota
  * Jaffna
  * Kalutara
  * Kandy
  * Kegalle
  * Kilinochchi
  * Kurunegala
  * Mannar
  * Matale
  * Matara
  * Monaragala
  * Mullaittivu
  * Nuwara Eliya
  * Polonnaruwa
  * Puttalam
  * Ratnapura
  * Trincomalee
  * Vavuniya


* * *
#   ⟨81⟩ Data Processing Pipeline 
The dataset was generated through the following processing workflow:
  1. Bird occurrence records were collected and filtered for Sri Lanka.
  2. Records with invalid geographic coordinates were removed.
  3. Species names were standardized using taxonomic information.
  4. Environmental raster datasets were spatially sampled at each observation location.
  5. Climate variables were matched based on observation date and location.
  6. Land-cover and elevation information were extracted.
  7. Environmental features were normalized where required.
  8. Missing records were removed.
  9. Final feature vectors were generated for machine learning applications.


* * *
#   ⟨82⟩ Intended Uses 
This dataset is suitable for:
##   ⟨67⟩ Ecological Applications 
  * Species distribution modeling
  * Habitat suitability analysis
  * Biodiversity assessment
  * Environmental impact studies
  * Climate change research


##   ⟨68⟩ Machine Learning Applications 
  * Multi-class species classification
  * Regression-based abundance prediction
  * Geospatial prediction models
  * Feature importance analysis
  * Explainable AI studies in ecology


* * *
#   ⟨83⟩ Example Machine Learning Tasks   
| Task  | Target Variable  | Input Features  |  
| --- | --- | --- |  
| Species Classification  | `verbatimScientificName`  | Environmental + geographic features  |  
| Bird Abundance Prediction  | `individualCount`  | Climate + habitat variables  |  
| Habitat Modeling  | Species presence  | Location + environmental variables  |  
| Regional Biodiversity Analysis  | Province/species distribution  | Full feature set  |  
* * *
#   ⟨84⟩ Dataset Limitations and Biases 
##   ⟨69⟩ Sampling Bias 
Bird occurrence datasets collected from citizen science platforms may contain:
  * Uneven geographic coverage
  * Higher observation density near accessible locations
  * Seasonal observation biases


##   ⟨70⟩ Environmental Resolution 
Environmental variables are derived from remote sensing and climate products. Their spatial resolution may not perfectly represent local habitat conditions.
##   ⟨71⟩ Taxonomic Limitations 
Species identification accuracy depends on the quality of original observation records.
##   ⟨72⟩ Recommended Use 
Researchers should consider sampling bias correction and ecological validation before deploying models for conservation decision-making.
* * *
#   ⟨85⟩ Ethical Considerations 
This dataset is intended for scientific research and educational purposes.
Users should avoid:
  * Using predictions without ecological validation
  * Drawing conservation conclusions from biased samples
  * Misinterpreting correlations as causal relationships


* * *
#   ⟨86⟩ License 
This dataset is released under the:
**Creative Commons Attribution 4.0 International (CC BY 4.0)**
Users are free to share and adapt the dataset with appropriate attribution.
* * *
##   ⟨73⟩ Related Paper 
This dataset accompanies the following research paper:
**How Environment and Urbanization Shape Bird Diversity in Sri Lanka**
**arXiv:** <https://arxiv.org/abs/2607.00582>
The paper describes the methodology for constructing this dataset, including data collection, environmental feature extraction, preprocessing, and the machine learning analyses performed using the dataset. Readers interested in the complete methodology and experimental results are encouraged to refer to the paper.
If you use this dataset in your research, please consider citing both the dataset and the accompanying paper.
#   ⟨87⟩ Citation 
If you use this dataset, please cite:

```
@dataset{sri_lanka_bird_diversity_2026,
  title        = {Sri Lanka Bird Diversity Dataset with Environmental and Climate Features},
  author       = {Chandrasiri, Dilusha and Herath, Maneesha and Herath, Muditha and Hewarathna, Yasith and Bandara, Gishan},
  year         = {2026},
  publisher    = {Hugging Face},
  version      = {1.0},
  license      = {CC-BY-4.0}
}

```

Copy to bucket new
Use this dataset 

Downloads last month
    51
Number of rows: 1,552,048 Total file size: 423 MB
##  Paper for Bird-Diversity/Diversity
#### How Environment and Urbanization Shape Bird Diversity in Sri Lanka Paper • 2607.00582 • Published 25 days ago ⟨88⟩
System theme
Company
TOS⟨89⟩ Privacy⟨90⟩ About⟨91⟩ Careers⟨92⟩ ⟨1⟩
Website
Models⟨2⟩ Datasets⟨3⟩ Spaces⟨4⟩ Pricing⟨8⟩ Docs⟨6⟩
