![Hugging Face's logo](https://huggingface.co/front/assets/huggingface_logo-noborder.svg) Hugging Face⟨1⟩
  *  Models ⟨2⟩
  *  Datasets ⟨3⟩
  *  Spaces ⟨4⟩
  *  Buckets new⟨5⟩
  *  Docs ⟨6⟩
  *  Enterprise ⟨7⟩
  * Pricing⟨8⟩
  *     * Website
      *  Tasks⟨9⟩
      *  HuggingChat⟨10⟩
      *  Collections⟨11⟩
      *  Languages⟨12⟩
      *  Organizations⟨13⟩
    * Community
      *  Blog⟨14⟩
      *  Posts⟨15⟩
      *  Daily Papers⟨16⟩
      *  Hardware⟨17⟩
      *  Learn⟨18⟩
      *  Discord⟨19⟩
      *  Forum⟨20⟩
      *  GitHub⟨21⟩
    * Solutions
      *  Team & Enterprise⟨7⟩
      *  Hugging Face PRO⟨22⟩
      *  Enterprise Support⟨23⟩
      *  Inference Providers⟨24⟩
      *  Inference Endpoints⟨25⟩
      *  Storage Buckets⟨5⟩
  * * * *
  * Log In⟨26⟩
  * Sign Up⟨27⟩


#   Datasets:⟨3⟩
* * *
 ![](https://huggingface.co/avatars/a20318492906e6048d345a09a426564b.svg) ⟨28⟩
Jasonstephane⟨28⟩
/
Cube_bottom_V7⟨29⟩
like 0
Tasks:  Robotics ⟨30⟩
Modalities:  Tabular ⟨31⟩ Time-series ⟨32⟩ Video ⟨33⟩
Formats:  parquet ⟨34⟩
Size:  1K - 10K ⟨35⟩
Tags:  LeRobot ⟨36⟩
Libraries:  Datasets ⟨37⟩ pandas ⟨38⟩ Polars ⟨39⟩ + 2
License:
apache-2.0
 Dataset card ⟨29⟩ Data Studio ⟨40⟩ Files Files and versions xet ⟨41⟩ Community ⟨42⟩
Dataset Viewer
 Auto-converted to Parquet⟨43⟩ API Embed  Duplicate⟨44⟩ Data Studio
Subset (1)
default · 1.79k rows
default (1.79k rows)
Split (1)
train · 1.79k rows
train (1.79k rows)
Search is not available for this dataset
SQL
Console  
|  action list  |  observation.state list  |  timestamp float32 0 59.6  |  frame_index int64 0 1.79k  |  episode_index int64 0 0  |  index int64 0 1.79k  |  task_index int64 0 0  |  
| --- | --- | --- | --- | --- | --- | --- |  
|  [ -6.683761119842529, -111.93910217285156, 101.83136749267578, 70.542724609375, 20.055973052978516, 1.9353036880493164 ]  |  [ -10.021978378295898, -104.79120635986328, 98.4175796508789, 73.14286041259766, 23.47252655029297, 17.69793701171875 ]  |  0  |  0  |  0  |  0  |  0  |  
|  [ -6.801967144012451, -111.76628112792969, 102.27241516113281, 70.41047668457031, 19.93171501159668, 1.9661369323730469 ]  |  [ -10.021978378295898, -104.79120635986328, 98.4175796508789, 73.14286041259766, 23.47252655029297, 17.69793701171875 ]  |  0.033333  |  1  |  0  |  1  |  0  |  
|  [ -4.711369514465332, -111.57066345214844, 101.41687774658203, 68.29215240478516, 21.19551658630371, 2.168105125427246 ]  |  [ -9.670330047607422, -105.05494689941406, 98.32967376708984, 72.87911987304688, 23.03296661376953, 17.564870834350586 ]  |  0.066667  |  2  |  0  |  2  |  0  |  
|  [ -7.061278820037842, -112.18385314941406, 102.74104309082031, 70.19440460205078, 20.023494720458984, 1.9938068389892578 ]  |  [ -8.615385055541992, -105.67032623291016, 97.80220031738281, 72.26373291015625, 22.153846740722656, 16.034597396850586 ]  |  0.1  |  3  |  0  |  3  |  0  |  
|  [ -6.247570991516113, -112.45405578613281, 102.7861557006836, 69.77693939208984, 20.622814178466797, 2.014434814453125 ]  |  [ -7.560439586639404, -106.37362670898438, 97.53845977783203, 71.82417297363281, 21.538461685180664, 13.838988304138184 ]  |  0.133333  |  4  |  0  |  4  |  0  |  
|  [ -5.867042064666748, -112.56077575683594, 102.35499572753906, 69.23662567138672, 20.624216079711914, 2.0464229583740234 ]  |  [ -7.296703338623047, -106.54945373535156, 97.53845977783203, 71.47252655029297, 21.186813354492188, 11.177644729614258 ]  |  0.166667  |  5  |  0  |  5  |  0  |  
|  [ -6.220022678375244, -112.28973388671875, 102.50995635986328, 69.00261688232422, 20.48647689819336, 1.9678077697753906 ]  |  [ -7.472527503967285, -106.54945373535156, 97.53845977783203, 71.20879364013672, 21.098901748657227, 8.582834243774414 ]  |  0.2  |  6  |  0  |  6  |  0  |  
|  [ -5.4890289306640625, -111.78732299804688, 102.17529296875, 68.71478271484375, 21.059574127197266, 1.8570146560668945 ]  |  [ -7.384615421295166, -106.54945373535156, 97.53845977783203, 70.76923370361328, 21.098901748657227, 6.52029275894165 ]  |  0.233333  |  7  |  0  |  7  |  0  |  
|  [ -6.492091655731201, -112.48719787597656, 102.74922943115234, 69.28630065917969, 20.754104614257812, 1.9610919952392578 ]  |  [ -6.769230842590332, -106.54945373535156, 97.53845977783203, 70.4175796508789, 21.098901748657227, 5.056553363800049 ]  |  0.266667  |  8  |  0  |  8  |  0  |  
|  [ -6.254897594451904, -111.8692626953125, 102.45062255859375, 68.81481170654297, 21.028568267822266, 1.9432640075683594 ]  |  [ -6.241758346557617, -106.54945373535156, 97.53845977783203, 70.15384674072266, 21.098901748657227, 4.058549404144287 ]  |  0.3  |  9  |  0  |  9  |  0  |  
|  [ -6.232811450958252, -111.89540100097656, 101.78514099121094, 68.84351348876953, 21.012619018554688, 1.8429670333862305 ]  |  [ -6.241758346557617, -106.54945373535156, 97.53845977783203, 70.15384674072266, 21.098901748657227, 3.459747076034546 ]  |  0.333333  |  10  |  0  |  10  |  0  |  
|  [ -6.367153167724609, -111.83953857421875, 102.710693359375, 68.45037078857422, 20.84168815612793, 1.7972192764282227 ]  |  [ -6.681318759918213, -106.54945373535156, 97.53845977783203, 69.97801971435547, 21.098901748657227, 3.1270792484283447 ]  |  0.366667  |  11  |  0  |  11  |  0  |  
|  [ -6.297198295593262, -111.77880859375, 103.08882141113281, 68.49458312988281, 20.794281005859375, 1.7504215240478516 ]  |  [ -6.681318759918213, -106.54945373535156, 97.53845977783203, 69.97801971435547, 21.098901748657227, 2.7944111824035645 ]  |  0.4  |  12  |  0  |  12  |  0  |  
|  [ -6.949549198150635, -111.65231323242188, 102.79472351074219, 68.54338073730469, 20.739120483398438, 1.5623350143432617 ]  |  [ -6.505494594573975, -106.54945373535156, 97.53845977783203, 69.89010620117188, 21.098901748657227, 2.5948104858398438 ]  |  0.433333  |  13  |  0  |  13  |  0  |  
|  [ -6.554165363311768, -111.49635314941406, 102.70047760009766, 68.42051696777344, 20.795188903808594, 1.648965835571289 ]  |  [ -6.241758346557617, -106.54945373535156, 97.53845977783203, 69.71428680419922, 21.098901748657227, 2.461743116378784 ]  |  0.466667  |  14  |  0  |  14  |  0  |  
|  [ -6.750063896179199, -111.54762268066406, 102.11314392089844, 68.30500793457031, 20.760452270507812, 1.6291704177856445 ]  |  [ -6.241758346557617, -106.54945373535156, 97.53845977783203, 69.62637329101562, 21.098901748657227, 2.3286759853363037 ]  |  0.5  |  15  |  0  |  15  |  0  |  
|  [ -6.603545188903809, -111.74205017089844, 102.54026794433594, 68.16352081298828, 20.435941696166992, 1.583409309387207 ]  |  [ -6.329670429229736, -106.54945373535156, 97.53845977783203, 69.62637329101562, 21.098901748657227, 2.3286759853363037 ]  |  0.533333  |  16  |  0  |  16  |  0  |  
|  [ -6.990126609802246, -111.73896789550781, 102.87176513671875, 68.46820831298828, 20.45311737060547, 1.5282011032104492 ]  |  [ -6.593406677246094, -106.54945373535156, 97.53845977783203, 69.45054626464844, 21.098901748657227, 2.2621424198150635 ]  |  0.566667  |  17  |  0  |  17  |  0  |  
|  [ -7.240838050842285, -111.51431274414062, 102.18177795410156, 68.45269012451172, 20.200458526611328, 1.5918865203857422 ]  |  [ -6.769230842590332, -106.54945373535156, 97.53845977783203, 69.36264038085938, 21.098901748657227, 2.1956088542938232 ]  |  0.6  |  18  |  0  |  18  |  0  |  
|  [ -6.689830303192139, -111.377685546875, 101.97587585449219, 68.36007690429688, 20.487024307250977, 1.6892518997192383 ]  |  [ -6.857142925262451, -106.54945373535156, 97.53845977783203, 69.36264038085938, 21.098901748657227, 2.1956088542938232 ]  |  0.633333  |  19  |  0  |  19  |  0  |  
|  [ -6.64105224609375, -111.323486328125, 102.22439575195312, 67.84812927246094, 20.6397705078125, 1.5897188186645508 ]  |  [ -6.857142925262451, -106.54945373535156, 97.53845977783203, 69.36264038085938, 21.098901748657227, 2.1956088542938232 ]  |  0.666667  |  20  |  0  |  20  |  0  |  
|  [ -6.942091464996338, -111.52914428710938, 101.88533020019531, 68.01982116699219, 20.444026947021484, 1.7940282821655273 ]  |  [ -6.857142925262451, -106.54945373535156, 97.53845977783203, 69.27472686767578, 21.098901748657227, 2.1956088542938232 ]  |  0.7  |  21  |  0  |  21  |  0  |  
|  [ -6.8027663230896, -111.32962036132812, 102.12580871582031, 67.66073608398438, 20.541166305541992, 1.6859779357910156 ]  |  [ -6.857142925262451, -106.54945373535156, 97.53845977783203, 69.0988998413086, 21.098901748657227, 2.1956088542938232 ]  |  0.733333  |  22  |  0  |  22  |  0  |  
|  [ -6.85558557510376, -111.14617919921875, 101.36845397949219, 67.94141387939453, 20.4641170501709, 1.6653919219970703 ]  |  [ -6.857142925262451, -106.54945373535156, 97.53845977783203, 69.010986328125, 21.098901748657227, 2.1956088542938232 ]  |  0.766667  |  23  |  0  |  23  |  0  |  
|  [ -7.004848957061768, -111.36100769042969, 101.35785675048828, 67.6505355834961, 20.22793960571289, 1.6534738540649414 ]  |  [ -6.857142925262451, -106.54945373535156, 97.53845977783203, 68.92308044433594, 21.098901748657227, 2.1956088542938232 ]  |  0.8  |  24  |  0  |  24  |  0  |  
|  [ -7.019255638122559, -110.94805908203125, 101.36329650878906, 67.60182189941406, 20.56072235107422, 1.9058866500854492 ]  |  [ -6.857142925262451, -106.54945373535156, 97.53845977783203, 68.92308044433594, 21.098901748657227, 2.1956088542938232 ]  |  0.833333  |  25  |  0  |  25  |  0  |  
|  [ -6.513035774230957, -111.34260559082031, 100.53152465820312, 67.03424835205078, 20.57756805419922, 2.0184268951416016 ]  |  [ -6.857142925262451, -106.54945373535156, 97.53845977783203, 68.92308044433594, 21.098901748657227, 2.1956088542938232 ]  |  0.866667  |  26  |  0  |  26  |  0  |  
|  [ -7.298219680786133, -111.53738403320312, 101.00808715820312, 67.7309341430664, 20.446937561035156, 1.9800357818603516 ]  |  [ -6.857142925262451, -106.54945373535156, 97.53845977783203, 68.92308044433594, 21.098901748657227, 2.1956088542938232 ]  |  0.9  |  27  |  0  |  27  |  0  |  
|  [ -7.012305736541748, -110.81272888183594, 100.31863403320312, 67.41670989990234, 20.68049430847168, 2.1620140075683594 ]  |  [ -6.857142925262451, -106.54945373535156, 97.53845977783203, 68.74725341796875, 21.098901748657227, 2.1956088542938232 ]  |  0.933333  |  28  |  0  |  28  |  0  |  
|  [ -6.2719831466674805, -111.46397399902344, 99.56938171386719, 66.54873657226562, 20.855731964111328, 2.6407365798950195 ]  |  [ -6.857142925262451, -106.54945373535156, 97.53845977783203, 68.74725341796875, 21.098901748657227, 2.1956088542938232 ]  |  0.966667  |  29  |  0  |  29  |  0  |  
|  [ -6.250013828277588, -111.35472106933594, 99.90706634521484, 66.80579376220703, 20.94991683959961, 2.839344024658203 ]  |  [ -6.857142925262451, -106.54945373535156, 97.53845977783203, 68.74725341796875, 21.098901748657227, 2.1956088542938232 ]  |  1  |  30  |  0  |  30  |  0  |  
|  [ -6.514794826507568, -111.68983459472656, 100.31561279296875, 66.7398681640625, 20.709835052490234, 2.8845157623291016 ]  |  [ -6.94505500793457, -106.54945373535156, 97.53845977783203, 68.3956069946289, 21.098901748657227, 2.1956088542938232 ]  |  1.033333  |  31  |  0  |  31  |  0  |  
|  [ -6.091972351074219, -110.85066223144531, 98.87913513183594, 66.12933349609375, 21.012413024902344, 3.039745330810547 ]  |  [ -6.94505500793457, -106.54945373535156, 97.53845977783203, 68.21977996826172, 21.098901748657227, 2.3286759853363037 ]  |  1.066667  |  32  |  0  |  32  |  0  |  
|  [ -6.384948253631592, -110.77362060546875, 98.10310363769531, 66.29116821289062, 21.161094665527344, 3.4034204483032227 ]  |  [ -6.769230842590332, -106.54945373535156, 97.53845977783203, 67.95604705810547, 21.098901748657227, 2.461743116378784 ]  |  1.1  |  33  |  0  |  33  |  0  |  
|  [ -6.260306358337402, -110.56752014160156, 98.5745849609375, 66.38036346435547, 21.57179069519043, 3.7127113342285156 ]  |  [ -6.681318759918213, -106.54945373535156, 97.53845977783203, 67.69230651855469, 21.098901748657227, 2.661344051361084 ]  |  1.133333  |  34  |  0  |  34  |  0  |  
|  [ -6.062241554260254, -110.17880249023438, 97.92923736572266, 66.17459106445312, 21.818439483642578, 4.140736103057861 ]  |  [ -6.681318759918213, -106.54945373535156, 97.53845977783203, 67.51648712158203, 21.098901748657227, 2.8609447479248047 ]  |  1.166667  |  35  |  0  |  35  |  0  |  
|  [ -6.116880416870117, -109.355712890625, 96.05516052246094, 65.61534118652344, 22.25255584716797, 5.274962902069092 ]  |  [ -6.681318759918213, -106.54945373535156, 97.53845977783203, 67.51648712158203, 21.098901748657227, 2.994011878967285 ]  |  1.2  |  36  |  0  |  36  |  0  |  
|  [ -5.310323238372803, -109.52153015136719, 95.08963012695312, 65.34759521484375, 22.450719833374023, 5.38028621673584 ]  |  [ -6.681318759918213, -106.54945373535156, 97.53845977783203, 67.51648712158203, 21.098901748657227, 3.193612813949585 ]  |  1.233333  |  37  |  0  |  37  |  0  |  
|  [ -5.678827285766602, -107.64308166503906, 92.75289916992188, 64.94161224365234, 23.06113052368164, 6.490041732788086 ]  |  [ -6.681318759918213, -106.54945373535156, 97.53845977783203, 67.25274658203125, 21.36263656616211, 3.725881576538086 ]  |  1.266667  |  38  |  0  |  38  |  0  |  
|  [ -5.241286277770996, -108.57505798339844, 92.89320373535156, 64.8660888671875, 23.447704315185547, 6.750927448272705 ]  |  [ -6.505494594573975, -106.54945373535156, 97.53845977783203, 66.9011001586914, 21.626373291015625, 4.258150577545166 ]  |  1.3  |  39  |  0  |  39  |  0  |  
|  [ -4.891990661621094, -107.78385925292969, 92.80953979492188, 64.88751220703125, 23.44137191772461, 6.811290740966797 ]  |  [ -6.241758346557617, -106.54945373535156, 97.53845977783203, 66.54945373535156, 21.9780216217041, 4.790419101715088 ]  |  1.333333  |  40  |  0  |  40  |  0  |  
|  [ -5.8519287109375, -104.84149169921875, 89.2486572265625, 64.94589233398438, 23.596500396728516, 8.251545906066895 ]  |  [ -5.890110015869141, -106.54945373535156, 97.27472686767578, 66.28571319580078, 22.329669952392578, 5.389221668243408 ]  |  1.366667  |  41  |  0  |  41  |  0  |  
|  [ -5.41480016708374, -103.70169067382812, 88.45867156982422, 64.7826919555664, 23.997480392456055, 8.214456558227539 ]  |  [ -5.626373767852783, -106.54945373535156, 97.18681335449219, 66.19779968261719, 22.593406677246094, 5.721889495849609 ]  |  1.4  |  42  |  0  |  42  |  0  |  
|  [ -6.249433994293213, -100.71441650390625, 85.64874267578125, 64.31983947753906, 24.583311080932617, 9.373380661010742 ]  |  [ -5.538461685180664, -106.19779968261719, 96.74725341796875, 66.10989379882812, 22.769229888916016, 6.32069206237793 ]  |  1.433333  |  43  |  0  |  43  |  0  |  
|  [ -6.979061126708984, -98.86738586425781, 84.16119384765625, 64.67938995361328, 24.924701690673828, 10.29238224029541 ]  |  [ -5.450549602508545, -105.4065933227539, 95.6043930053711, 66.10989379882812, 22.94505500793457, 6.852960586547852 ]  |  1.466667  |  44  |  0  |  44  |  0  |  
|  [ -6.9702606201171875, -97.3883056640625, 82.45367431640625, 64.62025451660156, 24.85738182067871, 10.54765796661377 ]  |  [ -5.714285850524902, -105.14286041259766, 94.46154022216797, 66.10989379882812, 23.296703338623047, 7.318696022033691 ]  |  1.5  |  45  |  0  |  45  |  0  |  
|  [ -7.300567626953125, -94.85679626464844, 80.31734466552734, 64.21369934082031, 25.523632049560547, 11.4680814743042 ]  |  [ -5.890110015869141, -103.56044006347656, 92.87911987304688, 65.93406677246094, 23.736263275146484, 8.183632850646973 ]  |  1.533333  |  46  |  0  |  46  |  0  |  
|  [ -8.668935775756836, -89.27827453613281, 75.12100219726562, 64.418212890625, 25.847827911376953, 13.360840797424316 ]  |  [ -6.329670429229736, -101.62637329101562, 90.94505310058594, 65.93406677246094, 24, 8.915502548217773 ]  |  1.566667  |  47  |  0  |  47  |  0  |  
|  [ -8.518379211425781, -88.98102569580078, 75.71998596191406, 64.2605209350586, 25.812990188598633, 13.094379425048828 ]  |  [ -6.769230842590332, -99.78022003173828, 89.010986328125, 65.84615325927734, 24.351648330688477, 9.580838203430176 ]  |  1.6  |  48  |  0  |  48  |  0  |  
|  [ -8.367938995361328, -89.94935607910156, 75.99287414550781, 64.24168395996094, 25.912660598754883, 12.835685729980469 ]  |  [ -7.120879173278809, -97.5824203491211, 86.72527313232422, 65.67032623291016, 24.703296661376953, 10.512309074401855 ]  |  1.633333  |  49  |  0  |  49  |  0  |  
|  [ -9.396251678466797, -83.16869354248047, 70.86048889160156, 64.24243927001953, 26.526552200317383, 14.559012413024902 ]  |  [ -7.560439586639404, -95.03296661376953, 84.35164642333984, 65.67032623291016, 24.96703338623047, 11.377245903015137 ]  |  1.666667  |  50  |  0  |  50  |  0  |  
|  [ -10.378671646118164, -79.25996398925781, 67.68305969238281, 64.21126556396484, 26.694190979003906, 15.721351623535156 ]  |  [ -8.087912559509277, -93.27472686767578, 82.76923370361328, 65.4945068359375, 25.14285659790039, 11.776447296142578 ]  |  1.7  |  51  |  0  |  51  |  0  |  
|  [ -11.464990615844727, -72.56022644042969, 63.47392272949219, 64.71852111816406, 27.49673843383789, 16.993900299072266 ]  |  [ -8.615385055541992, -92.21977996826172, 81.71428680419922, 65.4065933227539, 25.494504928588867, 12.242182731628418 ]  |  1.733333  |  52  |  0  |  52  |  0  |  
|  [ -12.050155639648438, -68.41970825195312, 60.087242126464844, 64.21514892578125, 27.858625411987305, 17.80955696105957 ]  |  [ -9.142857551574707, -90.63735961914062, 80.30769348144531, 65.4065933227539, 25.758241653442383, 13.24018669128418 ]  |  1.766667  |  53  |  0  |  53  |  0  |  
|  [ -11.624820709228516, -72.22695922851562, 62.865360260009766, 64.57758331298828, 27.531583786010742, 17.11669158935547 ]  |  [ -9.582417488098145, -87.82417297363281, 77.84615325927734, 65.4065933227539, 26.19780158996582, 14.304723739624023 ]  |  1.8  |  54  |  0  |  54  |  0  |  
|  [ -12.118037223815918, -68.99803924560547, 61.184200286865234, 64.46351623535156, 27.82278060913086, 17.552331924438477 ]  |  [ -10.285714149475098, -83.95604705810547, 74.5934066772461, 65.4065933227539, 26.549449920654297, 15.369261741638184 ]  |  1.833333  |  55  |  0  |  55  |  0  |  
|  [ -12.529424667358398, -62.489315032958984, 56.414363861083984, 64.62781524658203, 28.14165496826172, 17.68121910095215 ]  |  [ -10.98901081085205, -79.56044006347656, 71.42857360839844, 65.4065933227539, 26.72527503967285, 15.834996223449707 ]  |  1.866667  |  56  |  0  |  56  |  0  |  
|  [ -14.008162498474121, -56.83863830566406, 52.54539108276367, 64.76469421386719, 28.898250579833984, 19.40947914123535 ]  |  [ -11.692307472229004, -75.86813354492188, 68.96703338623047, 65.4065933227539, 26.989011764526367, 16.300731658935547 ]  |  1.9  |  57  |  0  |  57  |  0  |  
|  [ -14.597375869750977, -54.28290939331055, 51.281333923339844, 64.98828125, 29.055660247802734, 20.04177474975586 ]  |  [ -12.04395580291748, -73.14286041259766, 67.47252655029297, 65.4065933227539, 27.340660095214844, 16.699934005737305 ]  |  1.933333  |  58  |  0  |  58  |  0  |  
|  [ -14.832235336303711, -50.23551559448242, 48.223541259765625, 64.87982177734375, 29.442867279052734, 19.964866638183594 ]  |  [ -12.219779968261719, -69.80220031738281, 65.71428680419922, 65.4065933227539, 27.604394912719727, 17.232202529907227 ]  |  1.966667  |  59  |  0  |  59  |  0  |  
|  [ -15.447240829467773, -46.890228271484375, 46.41795349121094, 65.3893051147461, 29.853111267089844, 20.671871185302734 ]  |  [ -12.747252464294434, -65.5824203491211, 63.25274658203125, 65.4065933227539, 28.043956756591797, 18.03060531616211 ]  |  2  |  60  |  0  |  60  |  0  |  
|  [ -16.103389739990234, -46.69775390625, 45.02988815307617, 65.45506286621094, 30.06515884399414, 21.66762924194336 ]  |  [ -13.538461685180664, -60.92307662963867, 60.35165023803711, 65.4065933227539, 28.30769157409668, 18.62940788269043 ]  |  2.033333  |  61  |  0  |  61  |  0  |  
|  [ -16.823949813842773, -41.04102325439453, 42.553585052490234, 65.81385040283203, 31.039995193481445, 22.85613250732422 ]  |  [ -14.505494117736816, -56.96703338623047, 57.53845977783203, 65.4065933227539, 28.74725341796875, 19.16167640686035 ]  |  2.066667  |  62  |  0  |  62  |  0  |  
|  [ -16.86798667907715, -39.736942291259766, 41.430419921875, 65.68310546875, 30.475570678710938, 22.107255935668945 ]  |  [ -15.20879077911377, -53.53845977783203, 55.07692337036133, 65.4065933227539, 29.010988235473633, 19.89354705810547 ]  |  2.1  |  63  |  0  |  63  |  0  |  
|  [ -17.945180892944336, -34.111209869384766, 38.083221435546875, 65.96279907226562, 31.282920837402344, 23.31365203857422 ]  |  [ -15.736263275146484, -50.81318664550781, 52.79121017456055, 65.4065933227539, 29.538461685180664, 20.69194984436035 ]  |  2.133333  |  64  |  0  |  64  |  0  |  
|  [ -18.429977416992188, -31.6804141998291, 36.21104049682617, 66.29541778564453, 31.712974548339844, 23.98515510559082 ]  |  [ -16.08791160583496, -48, 50.68132019042969, 65.4065933227539, 29.714284896850586, 21.224218368530273 ]  |  2.166667  |  65  |  0  |  65  |  0  |  
|  [ -19.165178298950195, -28.398418426513672, 34.401729583740234, 66.18437957763672, 32.06740188598633, 23.915321350097656 ]  |  [ -16.439559936523438, -45.010990142822266, 48.83516311645508, 65.4065933227539, 29.89011001586914, 21.423818588256836 ]  |  2.2  |  66  |  0  |  66  |  0  |  
|  [ -19.193889617919922, -26.82309913635254, 34.57270050048828, 66.48651885986328, 32.227081298828125, 24.06621551513672 ]  |  [ -16.879121780395508, -41.406593322753906, 46.901100158691406, 65.5824203491211, 30.41758155822754, 22.022621154785156 ]  |  2.233333  |  67  |  0  |  67  |  0  |  
|  [ -19.03583526611328, -26.946048736572266, 34.565940856933594, 66.60738372802734, 32.065040588378906, 23.777008056640625 ]  |  [ -17.318681716918945, -37.626373291015625, 44.61538314819336, 65.84615325927734, 30.85714340209961, 22.621423721313477 ]  |  2.266667  |  68  |  0  |  68  |  0  |  
|  [ -19.555892944335938, -22.660388946533203, 31.94878387451172, 66.79437255859375, 33.00112533569336, 24.89578628540039 ]  |  [ -17.934066772460938, -34.021976470947266, 42.68132019042969, 66.02198028564453, 31.120878219604492, 22.954092025756836 ]  |  2.3  |  69  |  0  |  69  |  0  |  
|  [ -20.45745849609375, -18.769670486450195, 28.715654373168945, 66.98442840576172, 33.57831954956055, 25.31103515625 ]  |  [ -18.63736343383789, -31.208791732788086, 41.4505500793457, 66.19779968261719, 31.296703338623047, 23.1536922454834 ]  |  2.333333  |  70  |  0  |  70  |  0  |  
|  [ -21.123916625976562, -13.948780059814453, 25.645793914794922, 66.88397216796875, 33.85990524291992, 25.401317596435547 ]  |  [ -19.16483497619629, -29.186813354492188, 40.39560317993164, 66.46154022216797, 31.736263275146484, 23.552894592285156 ]  |  2.366667  |  71  |  0  |  71  |  0  |  
|  [ -21.637617111206055, -12.51523208618164, 25.08915138244629, 67.14954376220703, 34.272159576416016, 26.205930709838867 ]  |  [ -19.604394912719727, -26.813186645507812, 38.63736343383789, 66.63735961914062, 32.17582321166992, 24.085163116455078 ]  |  2.4  |  72  |  0  |  72  |  0  |  
|  [ -21.129608154296875, -13.353126525878906, 25.94002914428711, 66.9241943359375, 34.28178787231445, 25.636219024658203 ]  |  [ -20.131868362426758, -23.560440063476562, 36.17582321166992, 66.63735961914062, 32.70329666137695, 24.417831420898438 ]  |  2.433333  |  73  |  0  |  73  |  0  |  
|  [ -21.511899948120117, -10.884206771850586, 24.86576271057129, 67.53752136230469, 34.70203399658203, 25.661535263061523 ]  |  [ -20.659339904785156, -19.868131637573242, 33.89011001586914, 66.63735961914062, 33.05494689941406, 24.88356590270996 ]  |  2.466667  |  74  |  0  |  74  |  0  |  
|  [ -21.26344108581543, -9.577827453613281, 24.427204132080078, 67.28913879394531, 34.729637145996094, 25.94530487060547 ]  |  [ -20.83516502380371, -16.879121780395508, 32.483516693115234, 66.54945373535156, 33.31867980957031, 25.016633987426758 ]  |  2.5  |  75  |  0  |  75  |  0  |  
|  [ -21.797517776489258, -7.5517730712890625, 22.545684814453125, 67.28763580322266, 35.494842529296875, 26.697439193725586 ]  |  [ -21.010988235473633, -14.505494117736816, 31.604394912719727, 66.72527313232422, 33.67033004760742, 25.016633987426758 ]  |  2.533333  |  76  |  0  |  76  |  0  |  
|  [ -22.369462966918945, -6.222740173339844, 21.629791259765625, 67.55937194824219, 35.40028381347656, 26.77962875366211 ]  |  [ -21.010988235473633, -12.219779968261719, 30.72527503967285, 66.81318664550781, 33.93406677246094, 25.28276824951172 ]  |  2.566667  |  77  |  0  |  77  |  0  |  
|  [ -22.701251983642578, -4.598979949951172, 20.146530151367188, 67.13812255859375, 35.71644592285156, 26.06037139892578 ]  |  [ -21.010988235473633, -10.373626708984375, 29.670330047607422, 66.989013671875, 34.28571319580078, 25.615436553955078 ]  |  2.6  |  78  |  0  |  78  |  0  |  
|  [ -22.41645050048828, -5.218757629394531, 20.880163192749023, 67.50748443603516, 35.80070495605469, 26.215892791748047 ]  |  [ -21.186813354492188, -8.351648330688477, 28.439559936523438, 67.07691955566406, 34.5494499206543, 25.948102951049805 ]  |  2.633333  |  79  |  0  |  79  |  0  |  
|  [ -22.89636993408203, -0.06782150268554688, 18.461780548095703, 67.45313262939453, 36.83208465576172, 27.124881744384766 ]  |  [ -21.626373291015625, -6.505494594573975, 27.296703338623047, 67.16483306884766, 34.63736343383789, 25.948102951049805 ]  |  2.666667  |  80  |  0  |  80  |  0  |  
|  [ -22.49338722229004, -2.2445106506347656, 19.546751022338867, 67.72455596923828, 36.46742630004883, 26.759685516357422 ]  |  [ -22.153846740722656, -5.450549602508545, 26.41758155822754, 67.16483306884766, 34.901100158691406, 25.948102951049805 ]  |  2.7  |  81  |  0  |  81  |  0  |  
|  [ -22.923736572265625, 0.8964195251464844, 17.339458465576172, 67.54585266113281, 37.62615966796875, 27.19638442993164 ]  |  [ -22.505495071411133, -4.835165023803711, 25.89011001586914, 67.25274658203125, 35.60439682006836, 26.147705078125 ]  |  2.733333  |  82  |  0  |  82  |  0  |  
|  [ -22.88347625732422, -0.4326057434082031, 17.581186294555664, 67.43882751464844, 37.05147171020508, 26.937366485595703 ]  |  [ -22.681318283081055, -3.692307710647583, 25.098901748657227, 67.25274658203125, 35.69230651855469, 26.347305297851562 ]  |  2.766667  |  83  |  0  |  83  |  0  |  
|  [ -22.985380172729492, 1.5586891174316406, 16.894126892089844, 67.66551208496094, 37.784889221191406, 27.302017211914062 ]  |  [ -22.769229888916016, -2.0219781398773193, 24.043956756591797, 67.25274658203125, 35.9560432434082, 26.48037338256836 ]  |  2.8  |  84  |  0  |  84  |  0  |  
|  [ -23.012981414794922, 1.8542556762695312, 16.71640968322754, 67.81500244140625, 37.31630325317383, 26.635725021362305 ]  |  [ -22.769229888916016, -0.17582418024539948, 23.076923370361328, 67.25274658203125, 36.21977996826172, 26.546905517578125 ]  |  2.833333  |  85  |  0  |  85  |  0  |  
|  [ -22.921222686767578, 4.502803802490234, 16.611299514770508, 67.74673461914062, 37.8968620300293, 27.241764068603516 ]  |  [ -22.593406677246094, 1.1428571939468384, 22.549449920654297, 67.25274658203125, 36.483516693115234, 26.679973602294922 ]  |  2.866667  |  86  |  0  |  86  |  0  |  
|  [ -22.962949752807617, 1.4962539672851562, 16.2580623626709, 67.05572509765625, 37.45283508300781, 26.278305053710938 ]  |  [ -22.505495071411133, 1.9340659379959106, 22.0219783782959, 67.25274658203125, 36.659339904785156, 26.679973602294922 ]  |  2.9  |  87  |  0  |  87  |  0  |  
|  [ -22.912019729614258, 2.802978515625, 16.117145538330078, 67.27202606201172, 37.870567321777344, 27.29534149169922 ]  |  [ -22.41758155822754, 2.373626470565796, 21.670330047607422, 67.25274658203125, 36.74725341796875, 26.74650764465332 ]  |  2.933333  |  88  |  0  |  88  |  0  |  
|  [ -23.077861785888672, 4.621391296386719, 15.52199935913086, 67.3515396118164, 38.29845428466797, 27.076873779296875 ]  |  [ -22.41758155822754, 2.6373627185821533, 21.406593322753906, 67.25274658203125, 36.74725341796875, 26.74650764465332 ]  |  2.966667  |  89  |  0  |  89  |  0  |  
|  [ -22.687599182128906, 0.6267738342285156, 16.689105987548828, 67.09696197509766, 37.78679275512695, 26.001235961914062 ]  |  [ -22.41758155822754, 2.6373627185821533, 21.05494499206543, 67.25274658203125, 37.010990142822266, 26.74650764465332 ]  |  3  |  90  |  0  |  90  |  0  |  
|  [ -22.752527236938477, 5.227329254150391, 15.302249908447266, 67.16487884521484, 38.510929107666016, 26.64849090576172 ]  |  [ -22.505495071411133, 3.4285714626312256, 20.52747344970703, 67.25274658203125, 37.27472686767578, 26.679973602294922 ]  |  3.033333  |  91  |  0  |  91  |  0  |  
|  [ -22.760351181030273, 4.928489685058594, 14.658124923706055, 67.23904418945312, 38.46552276611328, 26.589237213134766 ]  |  [ -22.769229888916016, 4.307692527770996, 20.351648330688477, 67.25274658203125, 37.18681335449219, 26.679973602294922 ]  |  3.066667  |  92  |  0  |  92  |  0  |  
|  [ -22.540790557861328, 5.913791656494141, 14.490484237670898, 66.7390365600586, 39.01219177246094, 26.62777328491211 ]  |  [ -22.85714340209961, 5.098901271820068, 20.263736724853516, 67.25274658203125, 37.626373291015625, 26.613439559936523 ]  |  3.1  |  93  |  0  |  93  |  0  |  
|  [ -22.797922134399414, 6.585205078125, 14.090709686279297, 67.29086303710938, 38.94975280761719, 26.027740478515625 ]  |  [ -22.85714340209961, 5.714285850524902, 19.824174880981445, 67.25274658203125, 37.80219650268555, 26.613439559936523 ]  |  3.133333  |  94  |  0  |  94  |  0  |  
|  [ -22.243486404418945, 7.1279754638671875, 13.270986557006836, 66.60911560058594, 39.262237548828125, 26.3914794921875 ]  |  [ -22.769229888916016, 6.241758346557617, 19.384614944458008, 67.25274658203125, 37.89011001586914, 26.613439559936523 ]  |  3.166667  |  95  |  0  |  95  |  0  |  
|  [ -22.410215377807617, 9.42343521118164, 12.743799209594727, 66.68964385986328, 39.45800018310547, 26.16375732421875 ]  |  [ -22.769229888916016, 6.681318759918213, 18.94505500793457, 67.25274658203125, 38.06593322753906, 26.613439559936523 ]  |  3.2  |  96  |  0  |  96  |  0  |  
|  [ -22.310840606689453, 6.307621002197266, 13.52206039428711, 66.94722747802734, 39.02532196044922, 25.361988067626953 ]  |  [ -22.769229888916016, 7.472527503967285, 18.505495071411133, 67.25274658203125, 38.41758346557617, 26.546905517578125 ]  |  3.233333  |  97  |  0  |  97  |  0  |  
|  [ -22.36200523376465, 7.881614685058594, 13.756359100341797, 66.995361328125, 39.44486999511719, 26.046640396118164 ]  |  [ -22.769229888916016, 8.351648330688477, 17.89011001586914, 67.25274658203125, 38.769229888916016, 26.48037338256836 ]  |  3.266667  |  98  |  0  |  98  |  0  |  
|  [ -21.950469970703125, 6.4490203857421875, 13.677019119262695, 66.88155364990234, 39.02570343017578, 25.343326568603516 ]  |  [ -22.769229888916016, 9.230769157409668, 17.626373291015625, 67.25274658203125, 38.769229888916016, 26.280771255493164 ]  |  3.3  |  99  |  0  |  99  |  0  |  
End of preview. Expand in Data Studio⟨45⟩
* * *
  *  Previous⟨29⟩
  * 1⟨46⟩
  * 2⟨47⟩
  * 3⟨48⟩
  * ...⟨49⟩
  * 18⟨50⟩
  * Next ⟨47⟩


  * Dataset Structure⟨51⟩
  * Citation⟨52⟩


This dataset was created using LeRobot⟨53⟩.
 ![](https://huggingface.co/datasets/huggingface/badges/resolve/main/visualize-this-dataset-xl.svg) ![](https://huggingface.co/datasets/huggingface/badges/resolve/main/visualize-this-dataset-xl-dark.svg) ⟨54⟩
##   ⟨51⟩ Dataset Structure 
meta/info.json⟨55⟩:

```
{
    "codebase_version": "v3.0",
    "fps": 30,
    "features": {
        "action": {
            "dtype": "float32",
            "names": [
                "shoulder_pan.pos",
                "shoulder_lift.pos",
                "elbow_flex.pos",
                "wrist_flex.pos",
                "wrist_roll.pos",
                "gripper.pos"
            ],
            "shape": [
                6
            ]
        },
        "observation.state": {
            "dtype": "float32",
            "names": [
                "shoulder_pan.pos",
                "shoulder_lift.pos",
                "elbow_flex.pos",
                "wrist_flex.pos",
                "wrist_roll.pos",
                "gripper.pos"
            ],
            "shape": [
                6
            ]
        },
        "observation.images.tuy": {
            "dtype": "video",
            "shape": [
                480,
                640,
                3
            ],
            "names": [
                "height",
                "width",
                "channels"
            ],
            "info": {
                "video.height": 480,
                "video.width": 640,
                "video.codec": "av1",
                "video.pix_fmt": "yuv420p",
                "video.is_depth_map": false,
                "video.fps": 30,
                "video.channels": 3,
                "has_audio": false
            }
        },
        "timestamp": {
            "dtype": "float32",
            "shape": [
                1
            ],
            "names": null
        },
        "frame_index": {
            "dtype": "int64",
            "shape": [
                1
            ],
            "names": null
        },
        "episode_index": {
            "dtype": "int64",
            "shape": [
                1
            ],
            "names": null
        },
        "index": {
            "dtype": "int64",
            "shape": [
                1
            ],
            "names": null
        },
        "task_index": {
            "dtype": "int64",
            "shape": [
                1
            ],
            "names": null
        }
    },
    "total_episodes": 1,
    "total_frames": 1789,
    "total_tasks": 1,
    "chunks_size": 1000,
    "data_files_size_in_mb": 100,
    "video_files_size_in_mb": 200,
    "data_path": "data/chunk-{chunk_index:03d}/file-{file_index:03d}.parquet",
    "video_path": "videos/{video_key}/chunk-{chunk_index:03d}/file-{file_index:03d}.mp4",
    "robot_type": "so_follower",
    "splits": {
        "train": "0:1"
    }
}

```

##   ⟨52⟩ Citation 
**BibTeX:**

```
[More Information Needed]

```

Copy to bucket new
Use this dataset 

Downloads last month
    66
License: apache-2.0 Number of rows: 1,789 Total file size: 23.7 MB
##  Collection including Jasonstephane/Cube_bottom_V7
#### Cube Bottom Collection 10 items • Updated 19 days ago ⟨56⟩
System theme
Company
TOS⟨57⟩ Privacy⟨58⟩ About⟨59⟩ Careers⟨60⟩ ⟨1⟩
Website
Models⟨2⟩ Datasets⟨3⟩ Spaces⟨4⟩ Pricing⟨8⟩ Docs⟨6⟩
